### ISSUE TITLE
$Revision$ tag is not updated

### ISSUE THREAD

**Issue by acaranta** [postfixadmin/postfixadmin#1]
Hi !
I just stumbled upon this Git repo of Postfixadmin ...

It's great, but I've must have failed to see any warnings about the fact that the $Revision$ in the files is not updated on the git Repo .... compared to the SVN sourceforge repo ...

Therefore ... install / upgrade fails miserably, without much warnings :(
Just to be sure the infos gets somewhere here ;)

The real trouble is everything seems to run fine ... even the upgrade.php ... which does nothing at all ... therefore postfixadmin fails :(

**Comment by palepurple** [comment]
Hi -- Thanks -- should be fixed now. I've changed how the upgrade.php script works.

**Comment by acaranta** [comment]
thx ;)
