### ISSUE TITLE
Forgot your password clear

### ISSUE THREAD

**Issue by MisterM74** [postfixadmin/postfixadmin#10]
Hello
Is it possible to disable the clear password function in PostfixAdmin and other ...
Yours
Mz

**Comment by palepurple** [comment]
Can you explain what you mean by "disable the clear password function"?

PostfixAdmin doesn't require that passwords are stored in clear/plain text within the database - it's assumed they'll be hashed using something like sha1/sha256 or dovecot's password tool ...
