### ISSUE TITLE
fetchmail.pl

### ISSUE THREAD

**Issue by piccardi** [postfixadmin/postfixadmin#100]
The script search for a configuration file in /etc/mail/postfixadmin/fetchmail.conf, it should be useful, for Debian installations, to make it search (like is done for vacation.pl) also in /etc/postfixadmin/fetchmail.conf.

**Comment by pedromorgan** [comment]
So this is a config path issue right ?

which do u prefer, or is it context ?

**Comment by piccardi** [comment]
Yes, it is a config path issue. In the vacation.pl script (used for the vacation feature) there is the code:
`
if (-f "/etc/mail/postfixadmin/vacation.conf") {
    require "/etc/mail/postfixadmin/vacation.conf";
} elsif (-f "/etc/postfixadmin/vacation.conf") {
    require "/etc/postfixadmin/vacation.conf";
}
`
just having something similar for fetchmail.conf should be sufficient
