### ISSUE TITLE
fetchmail.pl create a lock file inside /var/run instead of /var/lock

### ISSUE THREAD

**Issue by piccardi** [postfixadmin/postfixadmin#101]
The fetchmail.pl script try to create a lock file in /var/run/fetchmail, but this is removed at every reboot, and to create that directory you need root permission. Using just the canonical /var/lock directory should be preferred, and no privileged user will be needed to create the lock file

**Comment by cboltz** [comment]
I understand your problem, but don't like your solution - and at least on my system, it wouldn't work ;-)

My /var/lock is a symlink to /run/lock, and that is `root:lock 775` (openSUSE Tumbleweed, and I'm quite sure that I didn't do anything to change these permissions). So the user running fetchmail.pl would need to be in the `lock` group.

The better solution would be to ship a tmpfiles.d sniplet that creates /run/fetchmail/ on boot with the correct permissions.

**Comment by piccardi** [comment]
Sorry, I did'nt know about that suse choice and I agree:  your solution is better.

**Comment by DavidGoodwin** [comment]
feel free to add in a tmpfiles.d snippet, but in the meantime, I think 8f20c96278a694a7e0bb570f1d56c208105e5a14 is a reasonable solution.
