### ISSUE TITLE
vacation.pl: insert row in db only if notification is sent

### ISSUE THREAD

**Issue by grubshka** [postfixadmin/postfixadmin#103]
When an error occurs while sending the vacation notification message, the script should not insert or update the vacation_notification table.

**Comment by pedromorgan** [comment]
@grubshka what kind of error ?
thats a vacation.pl issue right ?
https://github.com/postfixadmin/postfixadmin/blob/master/VIRTUAL_VACATION/vacation.pl#L245

**Comment by grubshka** [comment]
Yes, that's a vacation.pl issues.

Any kind of error while sending email : I had different problems after upgrading to debian stretch, first because of perl modules, then an error in my SSL configuration, so the emails were not sent, but the vacation_notification table was updated as if the emails were sent.

**Comment by pedromorgan** [comment]
umm, can i ask the muppet question of what made the "email being sent" fail ?

**Comment by grubshka** [comment]
It was only installation nd configuration errors : as I said, firstly the perl mail sender modules was throwing errors, I don't remember what fixed it but I think it was a dependency problem. The second one was the SSL configuration that I was missing to overload in my configuration file.

I know this is not very important, but if it's easy to change the order of things, it would be more logical not to update the table in that cases.

**Comment by pedromorgan** [comment]
So just had a look at the code, and the email is send after checking if the target address has already been notified. 

So it could be done, but would need to check the status of the sent email, and make things more complex.

https://github.com/postfixadmin/postfixadmin/blob/master/VIRTUAL_VACATION/vacation.pl#L439
