### ISSUE TITLE
vacation.pl - Mail::Sender is depreceated

### ISSUE THREAD

**Issue by pedromorgan** [postfixadmin/postfixadmin#104]
Get this message with a fresh install

```
Mail::Sender is deprecated and 
you should look to Email::Sender instead 
at /var/spool/vacation/vacation.pl
```

**Comment by DavidGoodwin** [comment]
I think that's all fixed ...

https://github.com/postfixadmin/postfixadmin/commit/b781195526bf8ff0d4907e308b0fe16294827140#diff-90722adf6d049c1a5ae39e550413c693

https://github.com/postfixadmin/postfixadmin/commits/master/VIRTUAL_VACATION/vacation.pl

It's not been bundled into an  official release yet.
