### ISSUE TITLE
Failed login error log

### ISSUE THREAD

**Issue by pztop** [postfixadmin/postfixadmin#105]
My system is CentOS7/Nginx/PHP7.1/Postfix3/PostfixAdmin 3.1

Today I tried to setup fail2ban and I found out that PA wrote login error to /var/log/php-fpm/www-error.log like these:
```
[13-Dec-2017 12:07:21 America/Vancouver] PostfixAdmin login failed (username: test@grhmail.com)
[13-Dec-2017 13:52:18 America/Vancouver] PostfixAdmin login failed (username: someuser@gmail.com)
```
First, the log line does not contain the IP address, which is a "must have" for fail2ban. How to enable PA to log the IP as well? The nginx access log (/var/log/nginx/pa-access.log) does record the access of login.php with IP address, timestamp.,etc. 

Second, I don't understand that why the error not writing into nginx's error log like other web application does. I do configured to use /var/log/nginx/pa-error.log as the error log for nginx. 

Thanks for help in advance.

**Comment by pedromorgan** [comment]
This is a log formatting issue right ?

**Comment by pztop** [comment]
Yes it is. I do need the error log contain the IP address information. Something like:
```
[13-Dec-2017 12:07:21 America/Vancouver] PostfixAdmin login failed. Client IP: 1.2.3. 4 (username: test@grhmail.com)
```

**Comment by pedromorgan** [comment]
ok a idiot question, does that cormat conform to mail.log format ?

**Comment by pztop** [comment]
I am not sure what your question mean. I think the ideal way is PostfixAdmin should log all fail login attempts to web server error log, (in my case it should be /var/log/nginx/pa-error.log), and the log should have time stamp, client IP, and a message described the error. 

I don't think this is related to maillog. The maillog only need to deal with IMAP-login , POP3-login or submission authentication.,etc.  I also have roundcube and mailwatch on the same server, they correctlly send failed login to nginx log file, so fail2ban cak pick up from there.

**Comment by pedromorgan** [comment]
um ok.. sorry for  `cormat` meant `Format` above oops

this is an issue we need to figure out,.. ie its a postixadmin www.error and alike

So the question is..
- where do u want the errors to goto ?

**Comment by pztop** [comment]
The error log should go to the log file defined in the web server. In my case of nginx, I have nginx conf file:
```
# cat /etc/nginx/conf.d/postfixadmin.mydomain.com.conf 
.....

server {
    server_name     postfixadmin.mxdomain.com;
    root            /var/www/html/postfixadmin;
    charset         utf-8;
    index           index.php index.htm;
    access_log      /var/log/nginx/pa-access.log;
    error_log       /var/log/nginx/pa-error.log;
.....
}
```
So the failed login error should be put in _pa-error.log_ or _pa-error.log_.

**Comment by pedromorgan** [comment]
ok so I get the nginx,,
so what happens, is "pa", "pfa" writing out the error in wrong format right ?

Sorry these are muppet question, new kid on the brick.. ;-)

**Comment by pztop** [comment]
For my understanding, it is the wrong format (missing IP address) with wrong place (should use nginx log instead of php log).

I have limited knowledge of PHP and I looked the login.php and I see this line 80:
```
    } else { # $h->login failed
        error_log("PostfixAdmin login failed (username: $fUsername)");
       	flash_error($PALANG['pLogin_failed']);
```
I guess that error_log does not write out IP address.

**Comment by pztop** [comment]
If we can send the error log to nginx access_log, then nginx may just insert the IP automatically.

**Comment by pedromorgan** [comment]
sorry a muppet here, but wanta common config dont we..
re ngins.x

i wrie web apps, and behind nginx so curious

**Comment by DavidGoodwin** [comment]
That might log the IP address as well (via the error_log(...) call in login.php).

**Comment by pztop** [comment]
Thank you David.

I realized that my issue it that PHP-FPM by default setting it doesn't send error log to Nginx. Once it been configured properly, then the error_log start to write to the error log I defined in my nginx site configuration file.  The beauty of Nginx logging it it automatically record the IP address so you don't need to send and IP address from your PHP code. 

Here is my configuration:
in /etc/php-fpm.conf, disable error_log:
```
;error_log = /var/log/php-fpm/error.log
```
In /etc/php-fpm.d/www.conf
```
catch_workers_output = yes
;php_admin_value[error_log] = /var/log/php-fpm/www-error.log
```
Now the nginx error log:
```
2017/12/14 21:51:14 [error] 28387#28387: *33 FastCGI sent in stderr: "PHP message: PostfixAdmin login failed (username: fakeuser@gmail.com)" while reading response header from upstream, client: 10.11.22.33, server: postfixadmin.mxdomain.com, request: "POST /login.php HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "postfixadmin.mydoamin.com", referrer: "https://postfixadmin.mydomain.com/login.php"
```

**Comment by rpv-tomsk** [comment]
Hi,

We need same update for `users/login.php` too. 
Can anybody please add PR?

**Comment by DavidGoodwin** [comment]
see ^

**Comment by rpv-tomsk** [comment]
Thanks a lot!
