### ISSUE TITLE
"Next" branch

### ISSUE THREAD

**Issue by pedromorgan** [postfixadmin/postfixadmin#107]
Can i suggest we have a "next" or "develop" branch,

this would be the target branch, and where all PR's should be merged into..
this will change often and means we can cook things, and revert if it boils over..

We then merge to "master" (locked to admins), and blow release.

**Comment by pedromorgan** [comment]
Oh also also main thing, we can add reviewers, so master is locked, and to get anything into next/develop would require 1+ approval

This would be cool I think to move forward, and I can setup the "play-server"...

**Comment by DavidGoodwin** [comment]
so, a year or so later ... i think if there were more developers contributing to the project then yeah - having some sort of gitflow based development would be good .... but as it is, there isn't .... and I'm not sure there's any need to have a 'merge-to' branch. 

Development is taking place on 'master' and there are release branches (e.g. postfixadmin_3.2) and tags (E.g. postfixadmin-3.2.2).
