### ISSUE TITLE
vacation.pl

### ISSUE THREAD

**Issue by a1d3s** [postfixadmin/postfixadmin#111]
Hi there , 
we are using postfixadmin 3.1 and vacattion.pl 5.0
# Virtual Vacation 5.0
#
# $Revision: 1 $
#
# Updates:
# 2017/06/13  Gianluca Giacometti <php at gianlucagiacometti dot it>
#             Updated the usage syntax implementing GetOpt::Long
#             Removed deprecated Mail::Sender and implemented Email::Sender

The utf8 encoding didnt work right, but i cant figure out why.
einschlieÃlich = einschließlich
the problem exist on german umlauts ÄÖÜ and ß

**Comment by a1d3s** [comment]
The erros is only in body of mail , subject works

**Comment by DavidGoodwin** [comment]
Hmm... 

I'm not sure we've had a 'Virtual Vacation 5.0' in master. and I can't see anything mentioning getopt::long.

Where did you get your vacation.pl from ? :)

**Comment by DavidGoodwin** [comment]
(inactive)

**Comment by Liberasys** [comment]
Please see issue 288: https://github.com/postfixadmin/postfixadmin/issues/288
BR
