### ISSUE TITLE
Vacation diary is not displayed correctly in Chrome

### ISSUE THREAD

**Issue by zsebacsi** [postfixadmin/postfixadmin#115]
I'm using Chrome latest version and the diary is displayed in the lower left corner, also not all the 100% is displayed, so I must scroll down to see the whole table
diary displays correctly under FF on the same machine.
any guess?
![image](https://user-images.githubusercontent.com/34830620/34336700-939c5d82-e959-11e7-8863-22e65c6c6fad.png)

**Comment by DavidGoodwin** [comment]
It works for me; from what's in master. 

Can you confirm if this is still a problem and what version of Postfixadmin you're using please?
