### ISSUE TITLE
Undefined index v_active in list-virtual.php

### ISSUE THREAD

**Issue by orlitzky** [postfixadmin/postfixadmin#118]
I'm seeing these in our logs:

```
Jan 12 23:06:16 mail2 apache2: PHP Notice:  Undefined index: v_active in /var/www/example.com/postfixadmin/public/list-virtual.php on line 246
```

The code in question looks like,

```php
if($row['v_active'] == NULL) {
    $row['v_active'] = 'f';
 }
$row['v_active']=('t'==$row['v_active']) ? 1 : 0;
```

Basically, it's fudging the value in the row array when the database is postgres, so that from then on, you don't have to care that the database is postgres.

However, the access of `$row['v_active'] ` is unconditional, and if we look at where that value comes from...

```php
if (Config::bool('vacation_control_admin')) {
    $table_vacation = table_by_key('vacation');
    $sql_select .= ", $table_vacation.active AS v_active ";
    $sql_join   .= " LEFT JOIN $table_vacation ON $table_mailbox.username=$table_vacation.email ";
}
```

then we see that `$row['v_active'] ` will only be defined if `Config::bool('vacation_control_admin')` is true. Therefore, the fix is to wrap the row-fudging code in the same test; something like,

```php
if (Config::bool('vacation_control_admin')) {
    if($row['v_active'] == NULL) {
        $row['v_active'] = 'f';
     }
    $row['v_active']=('t'==$row['v_active']) ? 1 : 0;
}
```

**Comment by cboltz** [comment]
Thanks for the report!

Fixed.
