### ISSUE TITLE
inaccurate instructions in UPGRADE.TXT?

### ISSUE THREAD

**Issue by LTIOfficial** [postfixadmin/postfixadmin#119]
This line in the UPGRADE.TXT file seems inaccurate:
https://github.com/postfixadmin/postfixadmin/blob/9982783481cefe9b45333f613d0366741ce7d8d5/DOCUMENTS/UPGRADE.txt#L65

The middle directive specifies the 'templates' directory, which does exist, rather than the templaces_c directory that we are attempting to set up at this stage of the instructions.
Also, the perms provided in that same middle directive appear to be specific to a file (640), rather than a directory (750?).

On a very related note, the INSTALL.TXT file fails to mention that the installer (sysadmin) must manually create the templates_c directory.  It only mentions adjusting its permissions.  A web search for "ERROR: the templates_c directory doesn't exist or isn't writeable for the webserver" reveals that this omission has a good number of people confused when trying to get pfadmin working:
https://github.com/postfixadmin/postfixadmin/blob/9982783481cefe9b45333f613d0366741ce7d8d5/INSTALL.TXT#L110-L111

**Comment by LTIOfficial** [comment]
For those running SELinux, and only because pfadmin requires full write perms to the directory, your manually created templates_c dir will also need the following SELinux permission set.  Be sure to first adjust **the path** shown below to that of your own install location.  The first command sets a permanent policy, while the second one then recursively applies that new policy (and all existing others) to the directory tree shown.

$ sudo semanage fcontext -a -t httpd_sys_rw_content_t "**/var/www/utils/pfadmin/public/templates_c**(/.*)?"
$ sudo restorecon -Rv /var/www/utils/pfadmin/

**Comment by cboltz** [comment]
Thanks for the report and the SELinux instructions!

I just commited the updated UPGRADE.txt.

**Comment by xpunkt** [comment]
# $ mkdir templates_c && chmod 640 templates && chown -R www-data templates_c

$ mkdir templates_c && chmod 640 templates_c && chown -R www-data templates_c

in gentoo its in ebuild fix needed

$ mkdir templates_c && chmod 660 templates_c && chown -R root templates_c && chgrp -R apache templates_c

but still why is templates_c in webroot :(

**Comment by LTIOfficial** [comment]
Good, but the UPGRADE.TXT instructions are still not telling anyone that they have to create the templates_c directory themselves.  They still give the impression that the directory should already be there when they go to set its owner/permissions.

The INSTALL.TXT file also still needs to be updated with the same information.

It might also be very helpful to me and others for you to add INSTALL & UPGRADE instructions for using SQLite.  In the new build that I am currently attempting, I have not yet been able to work out why I am seeing the following error in setup.php:

```
Error: Can't connect to database
Please edit the $CONF['database_*'] parameters in config.local.php.

DEBUG INFORMATION
Connect: given database path does not exist, is not writable, or $CONF['database_name'] is empty.
```

I have spent two days now confirming/reconfirming that none of the above debug info is pointing me to the correct solution.
The sqlite path/file does exist, and
apache has full rw access to it
```-rw-rw----. 1 apache vmail 0 Jan 13 04:00 /var/mail/vmail/postfixadmin.db```

And the full path is provided in the config.local.php file
```$CONF['database_name'] = '/var/mail/vmail/postfixadmin.db';```

Any pointers from you folks could prove very helpful here.

**Comment by DavidGoodwin** [comment]
tried something like 

```
su - apache -s /bin/bash 
sqlite3 /var/mail/vmail/postfixadmin.db 
```

Is it possible selinux is stopping apache from reading/writing to there?

Running the upgrade.php should populate the schema etc of the sqlite db.

**Comment by LTIOfficial** [comment]
Thanks for the reply, David.  I appreciate the input.

I found no issue with directly using sqlite3 to create a db file in that location, but if such a file is not populated by 'something', I found that it is removed upon exiting sqlite3 (disclaimer: this is my first time playing with sqlite).  The only tutorial I've found on using sqlite with pfadmin tell its readers to 'touch' and set owner/perms on the file, so that it simply exists in writable form for the web server (apache in my case) when pfadmin goes looking to populate it.  Of course, there is always a chance that I could be missing or misunderstanding something there, but no setup tutorial has indicated that anything else is needed for setting the sqlite db file before visiting the setup.php browser page (other than directing config.local.php to its full path, of course).  Over the last few days, I have tried many combinations of ownership (including with full rwx perms, to try to discover if it's something else that actually needs that access (mail, vmail, root, etc..  hell, I've even tried giving postfix access, although I don't see that connection this early in the install  lol ).

I'm working up this build in a VM, and currently have SELinux in Permissive mode (setenforce 0) in order to keep it out of the way while troubleshooting this mystery issue.

This is an initial install of pfadmin.  Given its name, I would expect 'upgrade.php' to be specific to upgrading the app from a previous version.  Please correct me if you know that to be inaccurate.

**Comment by DavidGoodwin** [comment]
upgrade.php will create / populate your database if it's empty, and apply whatever outstanding updates there are otherwise.

I'm fairly sure you need to : 

 1. Populate config.local.php with ```$CONF['database_type'] = 'sqlite';``` and ```$CONF['database_name'] = '/path/to/whatever/sqlite.db'; ``` 
 2. Run upgrade.php (either through your browser, or on the command line ( ``` php upgrade.php ``` ) )
