### ISSUE TITLE
Undefined index: sendmail_all_admins

### ISSUE THREAD

**Issue by pogott** [postfixadmin/postfixadmin#120]
PHP Notice:  Undefined index: sendmail_all_admins in /usr/share/postfixadmin/templates_c/5dff9b6bde917a46a79a527ab46d311db2b61baf_0.file.menu.tpl.php on line 90

Probably similar to https://github.com/postfixadmin/postfixadmin/issues/118

**Comment by DavidGoodwin** [comment]
your config.inc.php is missing 

```php
$CONF['sendmail_all_admins'] = 'NO';
```

**Comment by DavidGoodwin** [comment]
aad433eceb18cb0c7b39a0abb53e5572dce06c3a should stop it anyway.
