### ISSUE TITLE
Consider to change to InnoDB DB engine at Mysql

### ISSUE THREAD

**Issue by KissPeter** [postfixadmin/postfixadmin#123]
I'm using Galera where there is only experimental support for MyISAM and isntalling postfixadmin caused outage. 
My idea is either change to InnoDB or select and use the configured default DB engine.
Thank you

**Comment by DavidGoodwin** [comment]
I'm inclined to agree; I don't think we use any specific MyISAM settings, and we shouldn't be using it still in 2018....

**Comment by DavidGoodwin** [comment]
works fine with MariaDB, defaulting to InnoDB.

**Comment by DavidGoodwin** [comment]
see 2bb583a86a748a5c571989aa9d2b6db6eeda7ef4
