### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by gwaewion** [postfixadmin/postfixadmin#125]
Everything seems fine... attempting to create/update database structure

CREATE TABLE IF NOT EXISTS `config` ( `id` int(11) not null auto_increment primary key, `name` VARCHAR(20) /*!40100 CHARACTER SET latin1 */ NOT NULL DEFAULT '', `value` VARCHAR(20) /*!40100 CHARACTER SET latin1 */ NOT NULL DEFAULT '', UNIQUE name ( `name` ) ) ENGINE = MYISAM COMMENT = 'PostfixAdmin settings'

Updating database:

- old version: 438; target version: 1840

  (If the update doesn't work, run setup.php?debug=1 to see the detailed error messages and SQL queries.)
updating to version 439 (MySQL)...

DEBUG INFORMATION:
Invalid query: Table '/tmp/#sql_9e_0.MAI' is read only

Check your error_log for the failed query.

**Comment by DavidGoodwin** [comment]
Hi -
a. Check MySQL's error logs ...
b. Run setup.php with ?debug=1 on the end
c. Try running ```mysqlrepair --defaults-extra-file=/etc/mysql/debian.cnf -A --auto-repair```
 (this assumes Debian).
d. If you have nothing in the postfixadmin database, try dropping and recreating it.

If none of that helps, can you let me know what version/variant of MySQL/MariaDB etc you're running.

**Comment by gwaewion** [comment]
i have use clean mariadb install with virgin 'mail' database. maria's log - https://pastebin.com/Y4NqW7GP . here is two runs og setup.php with enabled debug - https://pastebin.com/bpq36ezU . 

running mariadb docker container. mysqld  Ver 10.1.28-MariaDB for Linux on x86_64 (MariaDB Server)

**Comment by DavidGoodwin** [comment]
```updating to version 438 (MySQL)...
 
CREATE TABLE IF NOT EXISTS `alias_domain` ( `alias_domain` varchar(255) /*!40100 CHARACTER SET latin1 */ NOT NULL default '', `target_domain` varchar(255) /*!40100 CHARACTER SET latin1 */ NOT NULL default '', `created` datetime NOT NULL default '2000-01-01 00:00:00', `modified` datetime NOT NULL default '2000-01-01 00:00:00', `active` tinyint(1) NOT NULL default '1', PRIMARY KEY (`alias_domain`), KEY `active` (`active`), KEY `target_domain` (`target_domain`) ) ENGINE=MyISAM COMMENT='Postfix Admin - Domain Aliases'
 
  done
updating to version 439 (MySQL)...```

**Comment by DavidGoodwin** [comment]
presumably therefore failing on ```function upgrade_373_mysql() { # MySQL only
    $table_domain = table_by_key ('domain');
    $table_mailbox = table_by_key('mailbox');

    $all_sql = explode("\n", trim("
        ALTER TABLE $table_domain  CHANGE `description`  `description` VARCHAR( 255 ) {UTF-8}  NOT NULL
        ALTER TABLE $table_mailbox CHANGE `name`         `name`        VARCHAR( 255 ) {UTF-8}  NOT NULL
    "));

    foreach ($all_sql as $sql) {
        $result = db_query_parsed($sql);
    }
}
```

**Comment by DavidGoodwin** [comment]
I can't replicate the problem on MariaDB 10.1.26-0+deb9u1     (Debian Stretch). I'll see if I can with a docker image ....

**Comment by DavidGoodwin** [comment]
I can't replicate with a docker image of 10.1.28 either.
What version of PostfixAdmin are you using?

**Comment by gwaewion** [comment]
Latest from master branch.

**Comment by gwaewion** [comment]
2018/02/01 17:59:25 [error] 10#10: *1 FastCGI sent in stderr: "PHP message: Invalid query: Table '/tmp/#sql_a1_0.MAI' is read only
PHP message: caused by query: SHOW COLUMNS FROM fetchmail LIKE 'ssl'" while reading response header from upstream,

**Comment by gwaewion** [comment]
i using my own docker image - https://github.com/gwaewion/hole-mariadb 
with official mariadb image no such problem.

**Comment by DavidGoodwin** [comment]
I don't know what's wrong with your docker image; does it work with other projects/apps/things?

**Comment by DavidGoodwin** [comment]
I'm assuming you've found the problem and it's some sort of image based on your docker image....
