### ISSUE TITLE
You are not allowed to edit

### ISSUE THREAD

**Issue by Olvikolvi** [postfixadmin/postfixadmin#128]
After upgrading from 2.3.4 to latest 3.2 I can't edit admin users anymore. I'am logged in as Super admin. After saving I got error "You are not allowed to edit".

**Comment by DavidGoodwin** [comment]
I can't replicate this. By 'latest 3.2' I take you mean what's here on github in 'master' - e.g https://github.com/postfixadmin/postfixadmin/commit/220f8289c788a37116e859af1a71e44ed76fe748

**Comment by DavidGoodwin** [comment]
```select * from domain_admins``` -> is your user listed as Domain 'ALL' or something else?

**Comment by Olvikolvi** [comment]
Yes it is.. All i have is 'ALL'.

**Comment by DavidGoodwin** [comment]
and ```select * From admin``` -> your user is listed as a superadmin ?

**Comment by Olvikolvi** [comment]
Yes superadmin = 1

**Comment by DavidGoodwin** [comment]
Can't replicate; inactive. 
Closing
