### ISSUE TITLE
mail location not in sync in DOCUMENTS/ ?

### ISSUE THREAD

**Issue by AndreBer** [postfixadmin/postfixadmin#129]
Hi,

### 1.  DOVECOT.txt line 33

I was wondering why my IMAP client didn't see an inbox. 

Looks like  `mail_location = maildir:/var/mail/vmail/%u/ `)is not in sync with the value of the column MAILDIR in table MAILBOX in the MySQL database.   (DOVECOT.txt line 133)

I've changed to: 
`mail_location = maildir:/var/mail/vmail/%d/%n
`
Or maybe it can be read from database? Did not check that. 

### 2.  DOVECOT.txt:133

`SELECT CONCAT('/var/vmail/mail/', maildir) 
`should probably be:
`SELECT CONCAT('/var/mail/vmail/', maildir)
`to be in sync with POSTFIX_CONF.txt:24:
`virtual_mailbox_base = /var/mail/vmail
`

**Comment by DavidGoodwin** [comment]
What your mail location is will depend on $CONF['domain_path'] and $CONF['domain_in_mailbox']. So e.g. you might need dovecot to use maildir:/var/mail/vmail/%d/%u or maildir:/var/mail/vmail/%d/%u

(See https://wiki.dovecot.org/MailLocation under 'Variables' )
