### ISSUE TITLE
domain qoutas, not just qoutas

### ISSUE THREAD

**Issue by xpunkt** [postfixadmin/postfixadmin#13]
as super admin its possible to set max qoutas pr mailbox, this works, but is imho not very flexible pr domain :(

i like to change to be super admin assign say 5GB to one domain, and then domain owner can use this size in total for all mailboxes in total, so it can be 5 mailboxes as 1GB or 1 mailbox with 2GB and one last with 3GB, the old system it would be max mailbox with max quotas, its from super admin point of view to restrictive

sorry if domain based quotas is solved

**Comment by cboltz** [comment]
This is already possible - set both $CONF['quota'] and $CONF['domain_quota'] to 'YES'.

You can set the default values (used when adding a new domain) with $CONF['maxquota'] and $CONF['domain_quota_default'].

**Comment by xpunkt** [comment]
adding this to postfixadmin 2.3.8 makes webui with no qoutas :/

so is it in trunk ?

**Comment by cboltz** [comment]
Right, you'll need to use 3.0 beta3 or trunk for this.

Don't worry about the "beta" label too much - it probably has less bugs than 2.3.x ever had ;-)
