### ISSUE TITLE
broadcast messages maybe tagged as spam

### ISSUE THREAD

**Issue by schudi** [postfixadmin/postfixadmin#132]
Hi there,

i just used the broadcast function and the messages were close to the spam limit.
After digging into it, i found three issues:
no date header
no message id
wrong formatted body

Please apply these changes to broadcast-message.php.

change line 81 to (add new line after every 76 characters, to be rfc compliant):
$b_message = chunk_split(base64_encode($_POST['message']));

add after line 88 (add date and message id header):
$fHeaders .= 'Date: ' . date('r', time()) . "\n";
$fHeaders .= 'Message-ID: <' . time() .'-' . md5($smtp_from_email . $fTo) . '@' . $_SERVER['SERVER_NAME'] . '>' . "\n";

change line 91 (93 respectively) to (add a second newline before the body):
$fHeaders .= 'Content-Transfer-Encoding: base64' . "\n\n";

Kind regards,
Michael

**Comment by DavidGoodwin** [comment]
I've not tested the above; but it's possible it'll work.
