### ISSUE TITLE
Error while updating password of a mailbox using PostgreSQL as a backend database

### ISSUE THREAD

**Issue by jackdeguest** [postfixadmin/postfixadmin#133]
Context:
I have a mailbox of type jacques.deguest@example.com created, existing and set with some password.
I went to PostfixAdmin interface, edited the mailbox and changed the password:
https://www.example.com/postfixadmin/edit-mailbox.php?username=jacques.deguest%40example.com&domain=example.com
This produced the following web error:

```
DEBUG INFORMATION:
Invalid query: ERROR: column "t" does not exist LINE 1: UPDATE alias SET active=t WHERE address='jacques.deguest@ang... ^

Please check the documentation and website for more information.

Postfix Admin
Forums 
```

In file `edit-mailbox.php` at line 165 there is the sql query: `UPDATE $table_alias SET active=$sqlActive WHERE address='$fUsername' AND domain='$fDomain'`

This produce the following query in the PostgreSQL: `UPDATE alias SET active=t WHERE address='jacques.deguest@example.com' AND domain='example.com'`

This sql query is slightly wrong. The variable $sqlActive should be surrounded by single quotes: `UPDATE $table_alias SET active='$sqlActive' WHERE address='$fUsername' AND domain='$fDomain'`

This now becomes: `UPDATE alias SET active='t' WHERE address='jacques.deguest@example.com' AND domain='example.com'`, which works.

And with MySQL if one uses 0 or 1, this would work as well.

**Comment by DavidGoodwin** [comment]
An easy fix would be to upgrade your PostfixAdmin version - edit-mailbox.php hasn't existed for a couple of releases now.
(the last time I can find it is https://github.com/postfixadmin/postfixadmin/blob/postfixadmin-2.3.7/edit-mailbox.php#L165 ).

**Comment by jackdeguest** [comment]
This is the version I got on Ubuntu 16.04.3x64 LTS when doing apt-get install postfixadmin
I already changed the code, but it would be nice to be able to install an up to date version indeed.

**Comment by DavidGoodwin** [comment]
Try downloading a .deb from https://sourceforge.net/projects/postfixadmin/files/postfixadmin/postfixadmin-3.1/
