### ISSUE TITLE
Feature request: Usage of SSH-Wrapper for doveadm to have splitted web and mail system

### ISSUE THREAD

**Issue by linuxmail** [postfixadmin/postfixadmin#135]
Hello,

I prefer always a splitted system for web and mail. In case a webserver was "hacked", then only the webserver is down, but not the mail system.
A webserver has always more weak points, so it would be great to have a better solution, than I use at the moment.
My "doveadm" is a plain one liner,

```
#!/bin/sh
ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /var/www/foo/ssh/doveadm-ecdsa doveadm@192.168.1.2 doveadm pw $@
```
 that use SSH to execute the command on the remote mailserver. The bad thing is, that any ($SSH_ORIGINAL_COMMAND) command can be executed. I tried to restrict it a bit, but than it isn't possible to login via the web, because the verfication fails. The first command is OK (doveadm pw -s SSHA512 -t {SSHA512}......=) but I assume that it then fails to submit the password for verification.

May some others here have a better solution :-)

cu denny

**Comment by DavidGoodwin** [comment]
I think I'm missing something - why do you need the ssh 'stuff' - why can't you just execute doveadm locally on the web server to generate the hashes?

**Comment by linuxmail** [comment]
Hello @DavidGoodwin,

because, doveadm isn't available on that hosts. I use Debian and no Dovecot related things are installed on any webhosts. So that is the reason to use SSH from webhost -> mailhost to execute doveadm pw.

**Comment by DavidGoodwin** [comment]
Ah, OK. But when you do the SSH command="" thing, you get the SSH_ORIGINAL_COMMAND in an env var - so could filter/escape/check that before executing it?

Alternatively use a hashing format that's not dependent on doveadm?
