### ISSUE TITLE
Postgresql support

### ISSUE THREAD

**Issue by vazir** [postfixadmin/postfixadmin#136]
Can you please include WORKING PostgreSQL .cf files for postfix as you do for mysql? I understand postfix should do it, but it don't! And that's make your users to have a pain in the butt. There zillions examples for different everything version in different sources, which just do not work, and makes us to hate a really good software.

**Comment by DavidGoodwin** [comment]
I'll add a full example of postfix, dovecot and postgresql to git this evening (I hope).

**Comment by DavidGoodwin** [comment]
Hope the document is readable.
