### ISSUE TITLE
Postfixadmin-CLI create mailbox failure.

### ISSUE THREAD

**Issue by greenaar** [postfixadmin/postfixadmin#137]
When attempting to create a test account via cli.

Invalid query: Incorrect datetime value: '' for column 'token_validity' at row 1
caused by query: INSERT INTO mailbox (username,local_part,domain,maildir,password,name,quota,active,phone,email_other,token,token_validity,created,modified) VALUES ('admin@home.local','admin','home.local','home.local/admin/','$1$078826fe$9p0Riq5MIQAbLblw9xJXF0','Test','0','1','','','','',now(),now())
<p />DEBUG INFORMATION:<br />Invalid query: Incorrect datetime value: '' for column 'token_validity' at row 1 <p>Check your error_log for the failed query. 

The last empty value set '' obviously needs to contain .. something. (Perhaps now() ?)

**Comment by greenaar** [comment]
Actually, I'm seeing this when trying to create users in the UI as well, v3.1, fresh install.

**Comment by greenaar** [comment]
Setting a default in model/MailboxHandler.php (line 45) makes the issue go away.

**Comment by greenaar** [comment]
Which i now see is present in master, but not in the last tagged release..

**Comment by DavidGoodwin** [comment]
Hi - yeah .... we're not great at making regular releases. Thanks for reporting the issue and figuring out the fix though :)

**Comment by greenaar** [comment]
Looking forward to the next tagged release - I did notice the output when building a .deb doesn't seem to match the install instructions (ie there are folders present at the webroot level that a checkout doesn't have) -- it'd be a good thing to have that sorted - ditto the upgrade instructions are obviously still only applicable to the last tagged release (which given the issue i mentioned above, is broken.. a point release fix might be appreciated).
