### ISSUE TITLE
postfix or dovecot

### ISSUE THREAD

**Issue by gurussia** [postfixadmin/postfixadmin#138]
HI guys.

It is unknown where this post has to be. So i have two computers on the same internal network. I one of them has email server, but other don't have, go users comment they can't send e-mail from the other. So it want to know, is it possible to install on the two servers and use on of them like apache2 use second server like internal ip proxy. So if computer A has 192.168.1.74 and computer B has 192.168.1.75 and computer B want to send e-mail he need to send use computer A and computer A will send e-mail. Server use postfix and dovecot. And i want only this computer B to communicate to computer A. Example: external ip 35.32.555.222 try to use computer B, she automatically be denied, include this has to be impossible becouse computer A and computer B will be on internal ip. So what i want is. Computer B only to communicate " send, recive and etc " with Computer A and Computer A will send all e-mail, recive all e-mails to Computer A and Computer B. This is second question: I have fear enable proxy in apache2, maybe someone can breach and enter. So if user enable proxy apache2 to communicate only with other apache2 server on lan address, only lan. If someone try breach second apache2 proxy server she be jail. Please guys help

**Comment by DavidGoodwin** [comment]
Postfix (or any other SMTP server) can relay mail - so in your case, you'd run postfix on computer B and A. A is configured to accept mail from the other (using 'mynetworks = ip.of.B') and the B is told to have a 'relayhost = ip.of.A'...).

By default postfix will reject mail from any unknown IP addresses.

Apache proxy wise - I think the default configuration is to deny all proxy requests, and you as an administrator need to enable it when it's necessary.

**Comment by gurussia** [comment]
Feb 19 21:51:06 user postfix/smtps/smtpd[696]: connect from unknown[192.168.23.3]
Feb 19 21:51:06 user postfix/smtps/smtpd[696]: Anonymous TLS connection established from unknown[192.168.23.3]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Feb 19 21:51:06 user postfix/smtps/smtpd[696]: lost connection after CONNECT from unknown[192.168.23.3]
Feb 19 21:51:06 user postfix/smtps/smtpd[696]: disconnect from unknown[192.168.23.23] commands=0/0
When i try recover from gitlab it connect to e-mail server and it log it comment tls... but why don't it continue and send email.
