### ISSUE TITLE
Invalid query: Table 'mail.admin' doesn't exist

### ISSUE THREAD

**Issue by wtrdk** [postfixadmin/postfixadmin#14]
I try to upgrade an existing posfixadmin install to the most recent GIT version, but when executing setup.php?debug=1 I keep getting this error:

```
Everything seems fine... attempting to create/update database structure

CREATE TABLE IF NOT EXISTS config ( `id` int(11) not null auto_increment primary key, `name` VARCHAR(20) /*!40100 CHARACTER SET latin1 */ NOT NULL DEFAULT '', `value` VARCHAR(20) /*!40100 CHARACTER SET latin1 */ NOT NULL DEFAULT '', UNIQUE name ( `name` ) ) ENGINE = MYISAM COMMENT = 'PostfixAdmin settings'

Updating database:

- old version: 1282; target version: 1835

  (If the update doesn't work, run setup.php?debug=1 to see the detailed error messages and SQL queries.)
updating to version 1283 (MySQL and PgSQL)...

DEBUG INFORMATION:
Invalid query: Table 'mail.admin' doesn't exist

Check your error_log for the failed query.
```

My mailserver is working perfectly, but I can't get postfixadmin to work. Can you help me?

I use PHP7, MySQL 5.7.12-0ubuntu1 on Ubuntu 16.04

**Comment by DavidGoodwin** [comment]
```
function upgrade_1283_mysql_pgsql() {
    _db_add_field('admin', 'superadmin', '{BOOLEAN}', 'password');
}
````
So that's adding the field 'superadmin' to the 'admin' table. 

You should have had more SQL generated from the above debug=1 thing.

**Comment by cboltz** [comment]
Wild guess: you forgot to migrate your config when doing the update _and_ you use use custom table names or a table prefix.

Please run `use mail; show tables;` in a mysql shell and show the output.

**Comment by cboltz** [comment]
No feedback since months, therefore I assume you were able to fix it yourself.

If the problem still exists, feel free to reopen with more details.
