### ISSUE TITLE
Array to string conversion in functions.inc.php on line 1737

### ISSUE THREAD

**Issue by dennisvj** [postfixadmin/postfixadmin#140]
Hi.

Installed Postfixadim 3.1 on a debian 9 server with php 7.0.27 and apache 2.4. When editing a mailbox or alias, the mailbox gets disabled and the text is ' array' In the error log I see:

[Tue Feb 20 15:43:33.876396 2018] [:error] [pid 1479] [client  PHP Notice:  Array to string conversion in /opt/postfixadmin/functions.inc.php on line 1737, referer: http://192.168.66.151/postfixadmin/edit.php?table=alias&edit=postmaster%40example.com

Running:

    PHP version 7.0.27-0+deb9u1
    Apache/2.4.25 (Debian)

Never encountered that one before. Running Postfixadmin on a pre-PHP 7 environment and that one is running fine. Any ideas?

**Comment by DavidGoodwin** [comment]
Can you paste in what you have on line 1737 of your functions.inc.php file (and a few lines before and after for context) please?

I can't see what could be causing that on the tagged version 3.1. Perhaps your file has some local modifications (or the packager modified it?)

**Comment by dennisvj** [comment]
Sure: 
   1724  * db_update_q
   1725  * Action: Updates a specified table
   1726  * Call: db_update_q (string table, string where, array values [, array timestamp])
   1727  * @param string $table - table name
   1728  * @param string $where - WHERE condition (as SQL)
   1729  * @param array $values - key/value map of data to insert into the table.
   1730  * @param array $timestamp (optional) - array of fields to set to now() - default: array('modified')
   1731  * @return int - number of updated rows
   1732  */
   1733 function db_update_q($table, $where, $values, $timestamp = array('modified')) {
   1734     $table = table_by_key($table);
   1735 
   1736     foreach ($values as $key => $value) {
   1737         $sql_values[$key] = $key . "='" . escape_string($values) . "'";
   1738     }
   1739 
   1740     foreach ($timestamp as $key) {
   1741         if (db_sqlite()) {
   1742             $sql_values[$key] = escape_string($key) . "=datetime('now')";
   1743         } else {
   1744             $sql_values[$key] = escape_string($key) . "=now()";
   1745         }
   1746     }
   1747 
   1748     $sql="UPDATE $table SET " . implode(",", $sql_values) . " WHERE $where";
   1749 
   1750     $result = db_query($sql);
   1751     return $result['rows'];
   1752 }

**Comment by DavidGoodwin** [comment]
Ah hah. That's fixed with the pull request #142

**Comment by DavidGoodwin** [comment]
(You wouldn't see the error in pre v7 PHP, as it didn't emit a warning if someone tried to cast an array into a string ... it'd just silently put in 'Array'. From PHP 7 onwards it emits an notice warning - which is what you saw.
