### ISSUE TITLE
Sourceforge link broken

### ISSUE THREAD

**Issue by hringriin** [postfixadmin/postfixadmin#146]
The [link][link] on the [website][website] does not work.

I don't have a SF account to report it there. Sorry for the inconvenience.

[link]: https://sourceforge.net/projects/postfixadmin/files/
[website]: http://postfixadmin.sourceforge.net/

**Comment by DavidGoodwin** [comment]
https://sourceforge.net/projects/postfixadmin/files/ works for me. Perhaps SourceForge had a temporary problem?

**Comment by hringriin** [comment]
Certainly ...
