### ISSUE TITLE
'succes' typo in db_connect function

### ISSUE THREAD

**Issue by tfarina** [postfixadmin/postfixadmin#15]
https://github.com/postfixadmin/postfixadmin/blob/master/functions.inc.php#L1253

**Comment by DavidGoodwin** [comment]
Nicely spotted - although that variable looks unused (at least from an initial 'find' point of view)

**Comment by cboltz** [comment]
Fixed in SVN trunk r1858 (by dropping the unused variables). The next sync to github will bring the fix to git.
