### ISSUE TITLE
Strange apache2 error log when logging into postfixadamin 

### ISSUE THREAD

**Issue by mariobig** [postfixadmin/postfixadmin#151]
Hi,

I have just upgraded postfixadmin from 3.0.1 to 3.1. It runs in the following  environment:

Debian 9 stretch
PHP7.0
10.1.23-MariaDB-9+deb9u1
Postfix 3.1.8
Dovecot 2.2.27 (c0f36b0)

When I log in to Postfixadmin the system records the following errors in /var/www/apache2/error.log
I haven't noticed any malfunctions or failures. It seems the everything works correctly but I am concern about the error.log.

Can anybody explain me what is the reason of theese strange records? 

[Sat Mar 17 13:12:07.451027 2018] [:error] [pid 29667] [client 83.28.182.23:1025] Config::read(): attempt to read undefined config option "admin_struct_hook", returning null, referer: https://waw.homeip.net/postfixadmin/login.php
[Sat Mar 17 13:12:07.476175 2018] [:error] [pid 29667] [client 83.28.182.23:1025] PHP Notice:  Undefined index: theme_custom_css in /var/www/postfixadmin/templates_c/d9ec88a593bae50c481f6d7daa9770a4b570dfc8_0.file.header.tpl.php on line 33, referer: https://waw.homeip.net/postfixadmin/login.php
[Sat Mar 17 13:12:07.478384 2018] [:error] [pid 29667] [client 83.28.182.23:1025] PHP Notice:  Undefined index: motd_superadmin in /var/www/postfixadmin/templates_c/892c9ffbe3bbd92e32cca36f360535595f742036_0.file.index.tpl.php on line 40, referer: https://waw.homeip.net/postfixadmin/login.php
[Sat Mar 17 13:12:07.478521 2018] [:error] [pid 29667] [client 83.28.182.23:1025] PHP Notice:  Undefined index: motd_admin in /var/www/postfixadmin/templates_c/892c9ffbe3bbd92e32cca36f360535595f742036_0.file.index.tpl.php on line 41, referer: https://waw.homeip.net/postfixadmin/login.php
[Sat Mar 17 13:12:21.112830 2018] [:error] [pid 4204] [client 83.28.182.23:1027] Config::read(): attempt to read undefined config option "alias_domain_struct_hook", returning null, referer: https://waw.homeip.net/postfixadmin/main.php
[Sat Mar 17 13:12:21.115611 2018] [:error] [pid 4204] [client 83.28.182.23:1027] Config::read(): attempt to read undefined config option "alias_struct_hook", returning null, referer: https://waw.homeip.net/postfixadmin/main.php
[Sat Mar 17 13:12:21.120573 2018] [:error] [pid 4204] [client 83.28.182.23:1027] Config::read(): attempt to read undefined config option "domain_quota_default", returning null, referer: https://waw.homeip.net/postfixadmin/main.php
[Sat Mar 17 13:12:21.121011 2018] [:error] [pid 4204] [client 83.28.182.23:1027] Config::read(): attempt to read undefined config option "domain_struct_hook", returning null, referer: https://waw.homeip.net/postfixadmin/main.php
[Sat Mar 17 13:12:21.132771 2018] [:error] [pid 4204] [client 83.28.182.23:1027] PHP Notice:  Undefined index: theme_custom_css in /var/www/postfixadmin/templates_c/d9ec88a593bae50c481f6d7daa9770a4b570dfc8_0.file.header.tpl.php on line 33, referer: https://waw.homeip.net/postfixadmin/main.php
[Sat Mar 17 13:12:21.134848 2018] [:error] [pid 4204] [client 83.28.182.23:1027] PHP Notice:  Undefined index: motd_superadmin in /var/www/postfixadmin/templates_c/892c9ffbe3bbd92e32cca36f360535595f742036_0.file.index.tpl.php on line 40, referer: https://waw.homeip.net/postfixadmin/main.php
[Sat Mar 17 13:12:21.134967 2018] [:error] [pid 4204] [client 83.28.182.23:1027] PHP Notice:  Undefined index: motd_admin in /var/www/postfixadmin/templates_c/892c9ffbe3bbd92e32cca36f360535595f742036_0.file.index.tpl.php on line 41, referer: https://waw.homeip.net/postfixadmin/main.php

**Comment by cboltz** [comment]
It looks like you have an old config.inc.php (from PostfixAdmin 2.x) which misses some new config options like `$CONF[*_struct_hook]`.

I'd recommend to move your local settings to config.local.php (create it if it doesn't exist yet), and to take config.inc.php from the PostfixAdmin tarball / package without changing it. 

If you still see this warnings after switching to config.inc.php from 3.1, feel free to reopen ;-)
