### ISSUE TITLE
disallow catchall addresses (or other "special" characters) as a configuration option?

### ISSUE THREAD

**Issue by benjyamon** [postfixadmin/postfixadmin#152]
We hacked on our instance (quick-n-dirty functions.inc.php and model/AliasHandler.php) to definitely not allow catch-all addresses (as well as barring other certain characters that may technically be legitimate in email addresses, but with our mdir storage, where homedir name equals email address, quite a few "special" characters become clumsy (to hazardous!)) 

Obviously a more elegant solution might be to add a configuration setting to allow catch-all, or not... And the more complex part: a set of additional characters that one might want to configure as disallowed, basically affecting that regex in function check_email(). . .

**Comment by DavidGoodwin** [comment]
What's the problem with a sysadmin type being able to create a catch all address? If you're giving someone permission to create mailboxes and aliases for a domain, presumably you need to trust them?

Is the problem that e.g. boss@megacorp.com could have their email intercepted by someone who has creates the mailbox boss*%?@megacorp.com ?

**Comment by benjyamon** [comment]
Catch-all addresses mean accepting and scanning lots more spam, sent to infinitely more addresses @domain.org, rather than being able to reject much of it at the "RCPT TO:"  because it's not To: a valid address. 
(I'm not saying nobody should be able to use postfixadmin to create them, but we banned catch-all's long ago and would love to configure rather than hack our postfixadmin instance to enforce this policy ;)

**Comment by DavidGoodwin** [comment]
Oh yes - I agree they're a pain in that regard. I seem to remember implementing a catch-all once by changing the SQL query ( .... union 'catch-all@doman' limit 1 ... ). In which case PostfixAdmin wouldn't help :)
