### ISSUE TITLE
Feature Request: Hash algorithm migration

### ISSUE THREAD

**Issue by thabbs** [postfixadmin/postfixadmin#156]
Giving the fact that an email administrator has been using postfixadmin for a very long time (s)he might got stuck in using a weak hash algorithm.

The current implementation makes it difficult to migrate from,  i.e. md5, to, i.e. sha256.
Please help a wider audience to prepare an easy migration.

I suggest to indroduce:

- a second password field in the Mailbox table reserved for the hash algorithm to migrate to (called "password_hash_future" or appropriate)
- a configuration option called "encrypt_future" or appropriate containing of the algorithm to use in future (\$CONF['encrypt_future'])

Required code changes:

- when changing a password the second password field should be updated with the password hash created using "encrpyt_future" if the encrypt_future option is set and its value is different from the "encrypt" option
- when creating users both old and new algorithms should be set if the "encrypt_future" option is set and its value is different from the "encrypt" option

Optional UI enhancement:
- migrate "encrypt_future" to "encrypt": bulk copy existing values from the new password field to the old password field and adjust \$CONF['encrypt']. Though, this feature might be overhead and easily can be fulfilled manually by e-mail administrators editing config.local.php and manipulating the database.

**Comment by DavidGoodwin** [comment]
The password reset changes that landed not too long ago may help with moving to a new password format? (alternative email to send a new password to; phone number etc).

**Comment by snuggeman** [comment]
If you just change the "encrypt" setting, all new or changed passwords will be generated with this algorithm?

Will this not accomplish what you are after?  Or does your backends not support multiple algorithms simultaneously?
