### ISSUE TITLE
Postfix Admin can't create admin table

### ISSUE THREAD

**Issue by Raghnarok** [postfixadmin/postfixadmin#159]
Hello,

Sorry if it's the wrong place to ask for this.
I'm trying to setup my server with postfixadmin over mysql and I got a problem when trying to do the first update :
> Postfix Admin Setup Checker
> 
> Running software:
> 
>     PHP version 7.0.27-0+deb9u1
>     Apache/2.4.25 (Debian)
> 
> Checking for dependencies:
> 
>     Magic Quotes: Disabled - OK
>     Depends on: presence config.inc.php - OK
>     Checking $CONF['configured'] - OK
>     Smarty template compile directory is writable - OK
>     Depends on: MySQL 4.1 - OK
>     Testing database connection - OK - mysqli://postfixadmin:xxxxx@localhost/postfixadmin
>     Depends on: session - OK
>     Depends on: pcre - OK
>     Depends on: multibyte string - OK
>     Depends on: IMAP functions - OK
> 
> Everything seems fine... attempting to create/update database structure
> 
> CREATE TABLE IF NOT EXISTS config ( `id` int(11) not null auto_increment primary key, `name` VARCHAR(20) /*!40100 CHARACTER SET latin1 */ NOT NULL DEFAULT '', `value` VARCHAR(20) /*!40100 CHARACTER SET latin1 */ NOT NULL DEFAULT '', UNIQUE name ( `name` ) ) ENGINE = MYISAM COMMENT = 'PostfixAdmin settings'
> 
> Updating database:
> 
> - old version: 0; target version: 1835
>   (If the update doesn't work, run setup.php?debug=1 to see the detailed error messages and SQL queries.)
> 
> updating to version 1 (MySQL)...
> 
> CREATE TABLE IF NOT EXISTS admin ( `username` varchar(255) NOT NULL default '', `password` varchar(255) NOT NULL default '', `created` datetime NOT NULL default '2000-01-01 00:00:00', `modified` datetime NOT NULL default '2000-01-01 00:00:00', `active` tinyint(1) NOT NULL default '1', PRIMARY KEY (`username`) ) ENGINE=MyISAM COMMENT='Postfix Admin - Virtual Admins';
> 
> DEBUG INFORMATION:
> Invalid query: Specified key was too long; max key length is 1000 bytes
> 
> Check your error_log for the failed query. 

It seems that the problem is the length of the key 'username', if I set it to 250 or less it's working fine.
What should I do?

**Comment by gnanet** [comment]
It may be related to the default collation, an index limit of 1000 may be reached if the varchar(255) is defaulting to utf8mb4, read more about this in #76

**Comment by Raghnarok** [comment]
Yes I understand that. But what should I do for my own setup? I mean, is there a problem only on my server or is it something everybody is having?

**Comment by DavidGoodwin** [comment]
I think it might work if you change the table's Engine to be InnoDB.

**Comment by Raghnarok** [comment]
Oh, found the solution. I just had to change the default collation to utf8_generai_ci instead of the utf8mb4_general_ci.

Sorry for that, thanks for your help.

**Comment by locvfx** [comment]
Great, it works!
Thank you @Raghnarok

**Comment by VladimirKazantsev** [comment]
Tell me what to fix
