### ISSUE TITLE
sqlite version

### ISSUE THREAD

**Issue by LynxChaus** [postfixadmin/postfixadmin#16]
In commit b6453c8 sqlite need strict version >= 3.12.0 - with older slqite versions postfixadmin not show any virtual mailboxes.

**Comment by DavidGoodwin** [comment]
Where do you find an sqlite package that's version >=3.12.0?

On Jessie I only see sqlite 2.8.17-12 or sqlite3 3.8.7.1-1+deb8u2 0

**Comment by LynxChaus** [comment]
Self back-ported.

**Comment by dennisschuerholz** [comment]
Up to today the sqlite-version on debian 8 is still set to `3.8.7.1`. I don't know what @phyrog's (who implemented the sqlite support) server setup is like, but my local client (arch linux) uses sqlite version `3.16.2-1` so I don't think it's that uncommon to use newer versions if not running debianish systems. Hence I can understand how he probably didn't expect this not to work on standard debian.

**Comment by LynxChaus** [comment]
Debian stretch carry sqlite-3.16.2-2. jessie is dead.

**Comment by cboltz** [comment]
I just added `SQLite 3.12 (or higher)` as requirement to INSTALL.TXT.

I'm not familiar with the `debian/control` syntax, but I'll happily change it if you tell me what needs to be changed (ideally as pull request ;-)

Also, If you want a version check in setup.php, feel free to open a pull request ;-)
