### ISSUE TITLE
Cross-Site Request Forgery vulnerability in users/login.php Error using Master

### ISSUE THREAD

**Issue by jameslbrown** [postfixadmin/postfixadmin#162]
To fix the Cross-site Request Forgery vulnerability in the current version, I replaced /users/login.php with https://github.com/postfixadmin/postfixadmin/blob/master/public/users/login.php#L35 - unfortunately I get:

`James Brown
James Brown - 6 days ago   
Hi GingerDog
I'm getting:
Fatal error: Uncaught Error: Call to undefined function init_session() in /Library/WebServer/Documents/postfixadmin-3.1/users/login.php:51 Stack trace: #0 {main} thrown in /Library/WebServer/Documents/postfixadmin-3.1/users/login.php on line 51`

Anyone know to fix this?

Thanks,

James.

**Comment by jameslbrown** [comment]
Thanks David. I downloaded the functions.inc.php file and replaced the old one with it. Now I get:

`Notice: Undefined index: database_use_ssl in /Library/Webserver/Documents/postfixadmin-3.1/functions.inc.php on line 1349
ERROR: The PostfixAdmin database layout is outdated (you have r1836, but r1837 is expected). Please run setup.php to upgrade the database.`

Running setup.php give this:

`Depends on: MySQL 4.1 - OK
Depends on: SQLite - OK 
(change the database_type to 'sqlite' in config.local.php if you want to use SQLite)

Notice: Undefined index: database_use_ssl in /Library/Webserver/Documents/postfixadmin-3.1/functions.inc.php on line 1349
Testing database connection (using mysqli) - OK
Depends on: session - OK
Depends on: pcre - OK
Depends on: multibyte string - OK
Warning: Depends on: IMAP functions - NOT FOUND
To install IMAP support, install php5-imap
Without IMAP support, you won't be able to create subfolders when creating mailboxes.
Everything seems fine... attempting to create/update database structure

Database is up to date`

And I set get the undefined index error.

**Comment by DavidGoodwin** [comment]
You're trying to mix code from one version/branch with another, so I'm not surprised there are problems.
If you'd just pasted in the function above into your local (unmodified) functions.inc.php it might have worked.

Given you're happy to modify/update the files, you might as well just ```git clone git@github.com:postfixadmin/postfixadmin.git whatever``` and use that?

**Comment by jameslbrown** [comment]
Thanks David. Downloaded master as a zip file. Moved the files and folders into my 3.1 folder. Setup.php now gives me:

```
Notice: Undefined variable: incpath in /Library/WebServer/Documents/postfixadmin-3.1/setup.php on line 32

Warning: require(/templates/header.php): failed to open stream: No such file or directory in /Library/WebServer/Documents/postfixadmin-3.1/setup.php on line 32

Fatal error: require(): Failed opening required '/templates/header.php' (include_path='.:') in /Library/WebServer/Documents/postfixadmin-3.1/setup.php on line 32
```

**Comment by DavidGoodwin** [comment]
I don't know what you've downloaded; but master doesn't do that.

For a start setup.php is in public/ ....

**Comment by jameslbrown** [comment]
Ah, that's where everything went!

Running that setup.php worked, after copying the templates_c folder across from 3.1. 

All good now. 

Thanks heaps for your help David - I really appreciate it.
