### ISSUE TITLE
tls problem in postfix

### ISSUE THREAD

**Issue by measwel** [postfixadmin/postfixadmin#163]
I keep getting this error when connecting to postfix from nodemailer:
Error: Error upgrading connection with STARTTLS: 454 4.7.0 TLS not available due to local problem

However, there is no problem connecting and sending email with email client. Also diagnostic tools show no tls errors - all seems fine. The only thing I notice is that diagnostics report tls v 1.2 while the error mentiones 4.7.0 TLS. Is this a version number?

I would appreciate someone to help me with this issue.

**Comment by DavidGoodwin** [comment]
I'm afraid this a project for a web interface to manage mailboxes/aliases etc for Postfix; while there may be some people reading this who can help, you may have a long wait. Try e.g. https://reddit.com/r/postfix or something instead?
