### ISSUE TITLE
add tag for 3.2

### ISSUE THREAD

**Issue by volker-raschek** [postfixadmin/postfixadmin#164]
Hello, 
please add a new release.tar and git tag for version 3.2.

Volker

**Comment by DavidGoodwin** [comment]
Yes, it's coming; I've just updated smarty so I'll do it in a couple of days assuming no one notices anything broken.

**Comment by DavidGoodwin** [comment]
finally done - https://github.com/postfixadmin/postfixadmin/releases/tag/postfixadmin-3.2

3.2 is live/done.
