### ISSUE TITLE
Question to POSTFIX_CONF.txt

### ISSUE THREAD

**Issue by n3vu0r** [postfixadmin/postfixadmin#165]
What is the sense of `mysql_virtual_alias_domain_mailbox_maps.cf`? Aliases addresses are mapped by `$virtual_alias_maps` to mailbox addresses. And these are then mapped to mailbox paths (or their existence is just confirmed) by `mysql_virtual_mailbox_maps.cf`. Which case then does `mysql_virtual_alias_domain_mailbox_maps.cf` cover?

`main.cf`:
```
virtual_mailbox_domains = proxy:mysql:/etc/postfix/sql/mysql_virtual_domains_maps.cf
virtual_alias_maps =
   proxy:mysql:/etc/postfix/sql/mysql_virtual_alias_maps.cf,
   proxy:mysql:/etc/postfix/sql/mysql_virtual_alias_domain_maps.cf,
   proxy:mysql:/etc/postfix/sql/mysql_virtual_alias_domain_catchall_maps.cf
virtual_mailbox_maps =
   proxy:mysql:/etc/postfix/sql/mysql_virtual_mailbox_maps.cf,
   proxy:mysql:/etc/postfix/sql/mysql_virtual_alias_domain_mailbox_maps.cf
```

`mysql_virtual_alias_domain_mailbox_maps.cf`:
```
user = postfix
password = password
hosts = localhost
dbname = postfix
query = SELECT maildir FROM mailbox,alias_domain WHERE alias_domain.alias_domain = '%d' and mailbox.username = CONCAT('%u', '@', alias_domain.target_domain) AND mailbox.active = 1 AND alias_domain.active='1'
```

**Comment by gnanet** [comment]
lets break up the name of the CF the right way:  virtual / alias_domain / mailbox_maps
so if you have alias-domains , you dont need to replicate every mailbox config data for the alias domain, just simply make a smart SQL query that matches the domain part to the alias-domains list, but  matches the userpart to the parent-domain of your alias domain.

at least that was my understanding the last 9-10 years

**Comment by n3vu0r** [comment]
Thanks!

This itself makes sense to me, but I think that this query will never be executed because `mysql_virtual_alias_domain_maps.cf` performs the alias translation already, and then `mysql_virtual_mailbox_maps.cf` translates the mailbox address to its path, so `mysql_virtual_alias_domain_mailbox_maps.cf` will only be triggered if an alias domain is not covered by the previous two queries. Is there a use case that it is not covered by these two queries?

Example: In postfixadmin we create the domain `domain.tld` and an alias domain `alias.tld` to `domain.tld` and the mailbox `user@domain.tld`. Then the essential parts of the `alias`, `alias_domain`, and `mailbox` tables look like this:

Table `alias`:
```text
# address goto domain
user@domain.tld user@domain.tld domain.tld # Identity to avoid catchall matches.
```

Table `alias_domain`:
```text
# alias_domain target_domain
alias.tld domain.tld
```

Table `mailbox`:
```text
# username maildir
user@domain.tld domain.tld/user/
```

Querying `mysql_virtual_alias_domain_maps.cf` for `user@alias.tld` returns:
`user@domain.tld`

Then querying `mysql_virtual_mailbox_maps.cf` for `user@domain.tld` returns:
`domain.tld/user` # Or at least something non-empty

And since we have matches, `mysql_virtual_alias_domain_mailbox_maps.cf` is not queried for `user@alias.tld`, which would return `domain.tld/user/`, and thus not required?! Or do I miss something?
