### ISSUE TITLE
Update fr language

### ISSUE THREAD

**Issue by abonanni** [postfixadmin/postfixadmin#168]
The following term is not translated correctly :
`$PALANG['pEdit_alias_forward_and_store'] = 'Transférer une copie.';`

A better translation would be :
`$PALANG['pEdit_alias_forward_and_store'] = 'Conserver une copie.';`

**Comment by cboltz** [comment]
The english text is `Deliver to the local mailbox.`

Google translate says the current text means `Transfer a copy` and your proposed text means `Keep a copy`. While your text is better, it still differs a lot from the english text and doesn't make it clear where the copy is kept (hint: in the mailbox).

Can you please provide a translation that matches the english text more closely?

**Comment by abonanni** [comment]
Hello,
`'Conserver une copie des messages dans la boite aux lettres' ` could be a better translation.

I have reviewed the all file 'fr.lang'. Is it possible to publish it ?
`remote: Permission to postfixadmin/postfixadmin.git denied to abonanni.`
`fatal: unable to access 'https://github.com/postfixadmin/postfixadmin.git/': The requested URL returned error: 403`

**Comment by abonanni** [comment]
Made a pull request #169

**Comment by cboltz** [comment]
Thanks!
