### ISSUE TITLE
using postfixadmin-cli to create mailboxes

### ISSUE THREAD

**Issue by zeigerpuppy** [postfixadmin/postfixadmin#17]
I am trying to link postfixadmin-cli (v0.2 from debian unstable) to WHMCS hooks.  In which case, I'll be using the
command:
```
postfixadmin-cli mailbox add 
```
This should execute unattended, but when I run
```
postfixadmin-cli mailbox add test@mydomain.net --name 'testname' --password 'testpW01' --quota 10000
```
the command returns:

Error: The passwords that you supplied don't match!

Am I missing an option?

**Comment by zeigerpuppy** [comment]
My apologies, I should have read the help docs in more detail, there is a field called --password2

and for reference:
```
postfixadmin-cli mailbox add help
```

**Comment by cboltz** [comment]
I have to admit that --password2 is not the best thing we have ;-) but it makes some implementation details easier.

I'm closing this ticket since things work as expected.
