### ISSUE TITLE
Remove doveadm warning

### ISSUE THREAD

**Issue by snuggeman** [postfixadmin/postfixadmin#171]
I get tons of logs like:
`PHP Warning:  file_exists(): open_basedir restriction in effect. File(/usr/bin/doveadm) is not within the allowed path(s)`

I silenced it with:
```
--- config.inc.php      2018-04-29 16:08:28.260238755 +0200
+++ config.inc.php.new  2018-04-29 16:03:19.772123293 +0200
@@ -193,7 +193,7 @@
 // $CONF['dovecotpw'] = "/usr/sbin/dovecotpw";
 // for dovecot 2.x (dovecot 2.0.0 - 2.0.7 is not supported!)
 $CONF['dovecotpw'] = "/usr/sbin/doveadm pw";
-if(file_exists('/usr/bin/doveadm')) {
+if(@file_exists('/usr/bin/doveadm')) {
     $CONF['dovecotpw'] = "/usr/bin/doveadm pw"; # debian
 }
```

**Comment by DavidGoodwin** [comment]
Using the @ operator is normally frowned upon ... https://stackoverflow.com/questions/21427211/check-if-open-basedir-restriction-is-in-effect implies there isn't a better option though :-/

**Comment by DavidGoodwin** [comment]
see b9f0f5bec9c1fc374d2585dabbfd75f7f13b6c35 when I eventually push it.
