### ISSUE TITLE
Can't access login page with /postfixadmin

### ISSUE THREAD

**Issue by Moonman147** [postfixadmin/postfixadmin#173]
Hey,

so since version 3.2 I've got an Issue with Postfix Admin.
When I'm trying to access the login page with domain.tld/postfixadmin I get the following report:

> The Postfix Admin directory layout changed.
Please update your webserver config so that the DocumentRoot or Alias points to the directory "public".

But I'm able to access Postfix Admin with domain.tld/postfixadmin/public.
Anyway I'd prefer to access the login page with the regular path again.
If someone could tell me how to fix this exactly, that would be great. :)

**Comment by DavidGoodwin** [comment]
You need to reconfigure your webserver so it maps /path/to/postfixadmin/public to domain.tld/postfixadmin .... that's all.

So - it's probably a case of changing an Alias definition within Apache.

**Comment by Moonman147** [comment]
Thanks for replying!
So yeah after some research I actually got it.
For those having this problem too, here's the solution:

1. Open your apache2.conf (/etc/apache2/apache2.conf)

2. Search for
```
<Directory /var/www/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride None
        Require all granted
</Directory>
```

3. Put this code below (Maybe you need to adjust the path)
```
Alias /postfixadmin/ "/var/www/html/postfixadmin/public/"
<Directory "/var/www/html/postfixadmin/public/">
        Options FollowSymLinks
        AllowOverride None
        Allow from all
        Order allow,deny
</Directory>
```

4. Restart Apache `/etc/init.d/apache2 restart` and done.

Some things can be so easy if you know how to do it. :D

**Comment by DavidGoodwin** [comment]
Quite! If you're installing Postfixadmin through the .deb package, then you probably want to edit /etc/apache2/conf-available/postfixadmin.conf (perhaps) or /etc/postfixadmin/apache.conf (perhaps).... it just depends on your circumstances.

**Comment by supersophie** [comment]
I've got a better idea. Downgrade to the earlier version I was on, because it worked before with this.  Is there a downgrade set of instructions available?
