### ISSUE TITLE
Database Version 1837 not working for sqlite

### ISSUE THREAD

**Issue by Lem** [postfixadmin/postfixadmin#176]
I'm trying to create a new sqlite-file, but getting an error on version 1837:
```
updating to version 1837 (all databases)...

DEBUG INFORMATION:
Invalid query: near "SHOW": syntax error 
```

It seems that public/upgrade.php is executing **upgrade_1837**, and than wants to use **upgrade_1837_sqlite** afterwards. Shouldn't it go straight to **upgrade_1837_sqlite**?

**Comment by DavidGoodwin** [comment]
hmm, perhaps.
As a quick fix, edit upgrade.php and add in a check on $CONF['database_type'] like the below patch :  

```
diff --git a/public/upgrade.php b/public/upgrade.php
index 6904455a..33df8cba 100644
--- a/public/upgrade.php
+++ b/public/upgrade.php
@@ -1679,6 +1679,11 @@ function upgrade_1836_mysql() {
 }
 
 function upgrade_1837() {
+    global $CONF;
+
+    if ($CONF['database_type'] == 'sqlite') {
+        return;
+    }
     # alternative contact means to reset a forgotten password
     foreach (array('admin', 'mailbox') as $table) {
         _db_add_field($table, 'phone', "varchar(30) {UTF-8} NOT NULL DEFAULT ''", 'active');
```

**Comment by DavidGoodwin** [comment]
(That'll just skip upgrade_1837() ... alternatively just stick 'return;' as the first line within function_1837() )

**Comment by Lem** [comment]
I've tried again now. This time setup using sqlite ended successfuly.
But I didn't check if everything is working as it should.
