### ISSUE TITLE
upgrade_1839 not working for sqlite

### ISSUE THREAD

**Issue by Lem** [postfixadmin/postfixadmin#177]
Creating a new database with sqlite fails on in function **upgrade_1839**:
```
Invalid query: near "SHOW": syntax error
```

**Comment by DavidGoodwin** [comment]
hmm, we don't have a db_field_exists() variant for sqlite.
```
function _db_field_exists($table, $field) {
    global $CONF;
    if ($CONF['database_type'] == 'pgsql') {
        return _pgsql_field_exists($table, $field);
    } else {
        return _mysql_field_exists($table, $field);
    }
}```

**Comment by DavidGoodwin** [comment]
Thanks .... I get to the end of public/setup.php now on a test server; but I don't have time to properly test my hacky fix.

I'm not sure if it's acceptable to drop the 'log' table and recreate it either; but sqlite doesn't seem to like the attempt at adding in the 'id' pkey field.

**Comment by Degress** [comment]
Hello, I pulled the latest changes and now I am able to pass through the database upgrade. However, when creating the admin user, another error appeared:

```
DEBUG INFORMATION:
Invalid query: table admin has no column named token 
```
```
Invalid query: table admin has no column named token, referer: http://10.10.0.1/postfixadmin/setup.php
[:error] caused by query: INSERT INTO admin (username,password,superadmin,active,phone,email_other,token,token_validity,created,modified) VALUES ('ab@cd','xxxxx','1','1','','','','2018-05-25 05:11:53',datetime('now'),datetime('now')), referer: http://postfixadmin/setup.php)

```
