### ISSUE TITLE
ERROR: manifest length read was ...

### ISSUE THREAD

**Issue by qcybb** [postfixadmin/postfixadmin#178]
I just upgraded to Postfixadmin v3.2 and I am receiving this message when trying to access it.

``ERROR: manifest length read was "41556" should be "655360"``

**Comment by DavidGoodwin** [comment]
That doesn't feel like an error postfixadmin/php would spit out. Where are you seeing this?

**Comment by qcybb** [comment]
I see this error on login.php page. I've not been able to use it since upgrading.

**Comment by DavidGoodwin** [comment]
How did you upgrade? (rpm/deb/manually?)
Is there anything logged in the Apache error log?

**Comment by qcybb** [comment]
I upgraded manually. Nothing in the Nginx or Apache error logs.

Does this update version have any new PHP extension requirements?

**Comment by DavidGoodwin** [comment]
the document root has changed to include /public on the end...

**Comment by qcybb** [comment]
Yes, I followed the instructions and changed my alias to point to the new "public" folder.

> The Postfix Admin directory layout changed.
> Please update your webserver config so that the DocumentRoot or Alias points to the directory "public".

**Comment by qcybb** [comment]
I managed to get it to work by editing **common.php** and commenting out the following line :

> require_once("$incpath/lib/random_compat.phar");

**Comment by DavidGoodwin** [comment]
What variant of PHP are you running? 

I've added an if(extension_loaded('Phar')) { .... } around that line now.

**Comment by DavidGoodwin** [comment]
https://github.com/postfixadmin/postfixadmin/commit/1c4a6080d7459d220845fd201a8d15bf57aa0a1b

Thank you for figuring out the problem

**Comment by qcybb** [comment]
You bet, everything is running great now. 

I'm using PHP 7.1 on Apache 2.4 running on FreeBSD.
