### ISSUE TITLE
postfixadmin-cli mailbox add gets error

### ISSUE THREAD

**Issue by hfukui-at-earthview-jp** [postfixadmin/postfixadmin#179]
I run `postfixadmin-cli mailbox add aaa@example.com --password aaa --password2 aaa,
and I get errors below.
Error: invalid parameter --0 => postfixadmin-cli.php

Error: invalid parameter --1 => mailbox

Error: invalid parameter --2 => add

Error: invalid parameter --3 => aaa@example.com

Error: invalid parameter --4 => --password

Error: invalid parameter --5 => aaa

Error: invalid parameter --6 => --password2

Error: invalid parameter --7 => aaa

I removed the code below in function parseParams, and now i can add mailbox correctly.
$this->params = array_merge($this->params, $params);

Regards

**Comment by DavidGoodwin** [comment]
see : 6d328795cbff4948f9d4ed84c1b3b3d147299aea

thanks for reporting it :)

**Comment by hfukui-at-earthview-jp** [comment]
Thanks.
I'll use the code updated.
