### ISSUE TITLE
php5-imap comes up as a missing depend while it is installed on (raspbian-jessie-armv7/php5.6.33)

### ISSUE THREAD

**Issue by marxenegls** [postfixadmin/postfixadmin#180]
Warning: Depends on: IMAP functions - NOT FOUND
To install IMAP support, install php5-imap
Without IMAP support, you won't be able to create subfolders when creating mailboxes.

stumbled upon an old blog mentioning the same **issue (http://data.agaric.com/installing-imap-functions-php-debian-agaric-saga) 
"Fatal error: Call to undefined function imap_open() ..." only diff is that it mentions libc-client 2002d - i have 2007d installed .
It goes on to "o get these functions to work, you have to compile PHP with --with-imap[=DIR], where DIR is the c-client install prefix. From our example above, you would use --with-imap=/usr/local/imap-2000b"

I'm gonna try compiling php5.6.33 's imap module myself .
thought I'd mention it

**Comment by marxenegls** [comment]
Oops sorry jumped the gun : ( 
php5enmod imap did the trick 
this'll look very bad on my git resume

**Comment by DavidGoodwin** [comment]
No one saw it .. don't worry :)

You probably don't need the imap functions anyway.
