### ISSUE TITLE
Invalid token 

### ISSUE THREAD

**Issue by cfcolaco** [postfixadmin/postfixadmin#183]
Hi, 

After successful PostfixAdmin setup, when I try to log in, I keep getting an "Invalid Token" message, Unfortunately, I don't see any logs anywhere to provide more detail and I am getting clueless of what might be causing this. 

anywhere I could start looking to find the root cause of this and solve it? 

Using CentOS, Nginx, php-fpm, mariadb. 

Tried Different browsers, different computers. 

thanks in advance and really sorry for the "vague" issue, tough i don't really have much more details to provide.

**Comment by gnanet** [comment]
To assist others in helping you, could you write down the version of PFA you are running, also the PHP version. This error message is presented on many parts of the code, but on  login this may be caused by a different value presented in the POST data, versus  the PHP session value of PFA_token.

You could check the POST data from the login with chrome dev-tools network tab, and check if a value named token was sent, also you may try to clean your cookies.

my 2 cents

**Comment by DavidGoodwin** [comment]
It's possible https://github.com/postfixadmin/postfixadmin/commit/1f643a052f34948f615119a82a0b027c200d6d19 will fix it for you....

**Comment by cfcolaco** [comment]
@gnanet @DavidGoodwin Thanks a lot for your replies and I am really sorry for my late reply, tough found out the issue is NGINX related. Switched to Apache and is working thus I am closing this issue and will troubleshoot the nginx part when I have the time to check what might be causing it. in the meanwhile, apache is just fine. 

Once  again, thank you a lot.

**Comment by JunMatsumoto1118** [comment]
I also experienced the same problem
Cause that the session management directory of php-fpm does not exist

Execution 
mkdir /var/lib/php/session
chown nginx:nginx /var/lib/php/session

**Comment by DavidGoodwin** [comment]
Thank you @JunMatsumoto1118

**Comment by tchangth1** [comment]
> I also experienced the same problem
> Cause that the session management directory of php-fpm does not exist
> 
> Execution
> mkdir /var/lib/php/session
> chown nginx:nginx /var/lib/php/session

sudo setfacl -R -m u:nginx:rwx /var/lib/php/opcache/ /var/lib/php/session/ /var/lib/php/wsdlcache/

bcos that 3 directories are under apache (and NOT nginx). by switching the owner to nginx, the problem went away
