### ISSUE TITLE
# not usable in passwords

### ISSUE THREAD

**Issue by TallGuy74** [postfixadmin/postfixadmin#186]
I tried to add a user with a password like go#orgob4st and postfixadmin complained about my password needing to be longer than three characters. It looks like everything after the # is seen as a comment and not used. This is on postfixadmin 3.1, not 3.2.

**Comment by DavidGoodwin** [comment]
the regexp being used is in config.inc.php - ```'/([a-zA-Z].*){3}/'```
It probably needs changing to be something simpler like : ```/.{3}/``` (match any 3 characters).
