### ISSUE TITLE
vacation never runs

### ISSUE THREAD

**Issue by corrilan** [postfixadmin/postfixadmin#187]
Hello all

I have configured vacation on several servers in the past without issue.  This latest one is not working as expected.

The following is from my /var/log/messages, you can see the "unknown user" error 6 lines down.
The inbound email arrives at my jason@mydomain.com account fine.
The relay on line 6 states "relay=virtual" whereas the working servers show "relay=vacation".
It seems vacation is not being called, instead, virtual is being called.
vacation is listed in my /etc/postfix/master.cf file.
After weeks on and off trying to get this going, I am stumped.

Any ideas?

Jason

From /var/log/messages:

Jun 20 17:26:51 mailserver postfix/smtpd[27233]: connect from mail-lf0-f52.google.com[209.85.215.52]
Jun 20 17:26:51 mailserver postfix/smtpd[27233]: Anonymous TLS connection established from mail-lf0-f52.google.com[209.85.215.52]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Jun 20 17:26:52 mailserver postfix/smtpd[27233]: 578D23C061E: client=mail-lf0-f52.google.com[209.85.215.52]
Jun 20 17:26:52 mailserver postfix/cleanup[27403]: 578D23C061E: message-id=<CAD-X0s8BhAo7_tH0VeKCPp73MEw+LVc+_8qz6dSbnG50LpGbsQ@mail.gmail.com>
Jun 20 17:26:52 mailserver postfix/qmgr[27195]: 578D23C061E: from=<myemail@googlemail.com>, size=2747, nrcpt=2 (queue active)
Jun 20 17:26:52 mailserver postfix/virtual[27406]: 578D23C061E: to=<jason@auto-reply.mydomain.com>, relay=virtual, delay=0.63, delays=0.53/0.03/0/0.06, dsn=5.1.1, status=bounced (unknown user: "jason@auto-reply.mydomain.com")
Jun 20 17:26:52 mailserver postfix/virtual[27407]: 578D23C061E: to=<jason@mydomain.com>, relay=virtual, delay=0.64, delays=0.53/0.06/0/0.06, dsn=2.0.0, status=sent (delivered to maildir)
Jun 20 17:26:52 mailserver postfix/smtpd[27233]: disconnect from mail-lf0-f52.google.com[209.85.215.52] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
Jun 20 17:26:52 mailserver postfix/qmgr[27195]: 578D23C061E: removed

Vacation as listed in /etc/postfix/master.cf:

vacation  unix  -       n       n       -       -       pipe
        flags=Rhu user=vacation argv=/var/spool/vacation/vacation.pl -f ${sender} -- ${recipient}

**Comment by DavidGoodwin** [comment]
Do you have transport entry for auto-reply.mydomain.com?

**Comment by gnanet** [comment]
Just a hint...

You need the vacation as a transport mapped to your auto-reply domain for example in **/etc/postfix/vmail_transport**: 
`auto-reply.mydomain.com    vacation:`

which should be referred in **main.cf**:
`transport_maps=[POSSIBLE OTHER TRANSPORT MAPS],hash:/etc/postfix/vmail_transport`

**Comment by corrilan** [comment]
Hello

Yes I have my transports in a mysql database, along with various virtual: transports I have auto-reply.mydomain.com vacation:

In fact, my other servers which work fine have auto-reply.mydomain.com vacation (without the colon).

I have tried both methods on this troublesome server.

Regards

Jason

**Comment by gnanet** [comment]
some extracts from your main.cf would maybe help

My example setup:
`postconf -n | grep transport`

```
transport_maps = mysql:/etc/postfix/mysql_virtual_transport_maps.cf
virtual_transport = dovecot
```

/etc/postfix/mysql_virtual_transport_maps.cf
```
...
query = SELECT domain_transport FROM postfix_domains WHERE domain_domain='%s' and domain_active = 1
...
```

relevant part of master.cf
```
responder    unix  -       n       n       -       -       pipe
    flags=RO user=nobody argv=/var/spool/autoresponder/responder.php ${sender} ${recipient}

```

A short query anyonimized, gave me, i have the colon in my database:
```
domain_domain | domain_trasport | domain_active
autoreply.mydomain.org    responder:       1
```

**Comment by DavidGoodwin** [comment]
What output do you see from your version of : 

```postmap -q whatever@auto.reply.com mysql:/etc/postfix/mysql_virtual_transport_maps.cf``` 

?

**Comment by gnanet** [comment]
But most important, your logs show, that the **vacation** transport does not kick in, instead it uses the **virtual**:

> Jun 20 17:26:52 mailserver postfix/virtual[27406]: 578D23C061E: to=jason@**auto-reply.mydomain.com**, **relay=virtual**, delay=0.63, delays=0.53/0.03/0/0.06, dsn=5.1.1, status=bounced (unknown user: "jason@auto-reply.mydomain.com")

**Comment by corrilan** [comment]
I found an issue in my transport maps mysql configuration file.  I have amended file and now the vacation service is at least firing when I receive an email.  Still have an issue with the email not actually being sent but as least i'm a step closer.

Thanks for your advice folks, it was of help and led me to the culprit.
