### ISSUE TITLE
wget comannd faulty

### ISSUE THREAD

**Issue by muhlemmer** [postfixadmin/postfixadmin#188]
The wget command in INSTALL.txt does not work like this. The `-O` flag is passed before the web address, which results in a fail. (Location not found)

Furthermore, `-O` can be omitted altogether, and the file will be saved under it's original name. (postfixadmin-3.1.tar.gz)

**Comment by DavidGoodwin** [comment]
Thank you! You're quite right. Hopefully fixed in 00877885cfe5b9cf92174c89d3b16adfdf370e97
