### ISSUE TITLE
templates_c needs to be created before chmod

### ISSUE THREAD

**Issue by muhlemmer** [postfixadmin/postfixadmin#189]
INSTALL.txt says `chown -R www-data /srv/postfixadmin/templates_c` to be run. However, the directory does not exists yet. `mkdir -p /srv/postfixadmin/templates_c` should be run first.

**Comment by DavidGoodwin** [comment]
Thank you. 

I almost merged your patch, but then noticed you had a typo (src vs srv) and thought I might as well add git clone + check what is downloaded in the tar.gz release...

**Comment by DavidGoodwin** [comment]
00877885cfe5b9cf92174c89d3b16adfdf370e97
