### ISSUE TITLE
vacation works from command line but not when called via Postfix

### ISSUE THREAD

**Issue by corrilan** [postfixadmin/postfixadmin#190]
Hello all

When I pipe a test email into the vacation service from the command line, all works fine and I receive the out of office reply at my Google email account.

The problem occurs when Postfix receives an email for me.  The vacation message is not sent.

/etc/postfix/master.cf contains:
vacation  unix  -       n       n       -       -       pipe
        flags=Rq user=vacation  argv=/var/spool/vacation/vacation.pl -f ${sender} -- ${recipient}

In the log file below, you will see the line that calls vacation, it states "me@auto-reply.mydomain.com".  To me, this appears to be incorrect, surely it should state "me#mydomain.com@auto-reply.mydomain.com"?

Snippet from /var/log/mail.log showing inbound email from my Google email account to my me@mydomain.com email account:

Jul  4 13:57:36 mailserver postfix/smtpd[24508]: connect from mail-lj1-f177.google.com[209.85.208.177]
Jul  4 13:57:37 mailserver postfix/smtpd[24508]: Anonymous TLS connection established from mail-lj1-f177.google.com[209.85.208.177]: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
Jul  4 13:57:37 mailserver postfix/smtpd[24508]: C643B3C0649: client=mail-lj1-f177.google.com[209.85.208.177]
Jul  4 13:57:38 mailserver postfix/cleanup[24514]: C643B3C0649: message-id=<CAD-X0s_6-BZTDzuExSJUuNkhU7m-pFe5P=4Z-s4qn_BgA263Ew@mail.gmail.com>
Jul  4 13:57:38 mailserver postfix/qmgr[24192]: C643B3C0649: from=<me@googlemail.com>, size=2737, nrcpt=2 (queue active)
Jul  4 13:57:38 mailserver postfix/virtual[24517]: C643B3C0649: to=<me@mydomain.com>, relay=virtual, delay=0.41, delays=0.36/0.01/0/0.04, dsn=2.0.0, status=sent (delivered to maildir)
Jul  4 13:57:38 mailserver postfix/smtpd[24508]: disconnect from mail-lj1-f177.google.com[209.85.208.177] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
Jul  4 13:57:39 mailserver postfix/pipe[24556]: C643B3C0649: to=<me@auto-reply.mydomain.com>, relay=vacation, delay=1.4, delays=0.36/0.04/0/1, dsn=2.0.0, status=sent (delivered via vacation service)
Jul  4 13:57:39 mailserver postfix/qmgr[24192]: C643B3C0649: removed

Regards

Jason

**Comment by DavidGoodwin** [comment]
can you copy+paste your postfix transports file and the output from ```postconf | grep transport_maps``` ?

does the vacation system user have access to run /var/spool/vacation/vacation.pl ? can you pipe a test mail to vacation.pl as the vacation user?

**Comment by corrilan** [comment]
Hello DavidGoodwin

Thanks for any insight you can provide.

Postfix transports file:

domain | description | aliases | mailboxes | maxquota | quota | transport | backupmx | created | modified | active
ALL | | 0 | 0 | 0 | 0 | | 0 | 2018-07-03 17:22:20 | 2018-07-03 17:22:20 | 1
mydomain.com | | 0 | 0 | 0 | 0 | virtual: | 0 | 2018-02-28 14:10:00 | 2018-02-28 14:10:00 | 1
mail.mydomain.com | | 0 | 0 | 0 | 0 | virtual: | 0 | 2018-02-28 14:10:00 | 2018-02-28 14:10:00 | 1
auto-reply.mydomain.com | | 0 | 0 | 0 | 0 | vacation: | 0 | 2018-02-28 14:10:00 | 2018-02-28 14:10:00 | 1

Output of postconf | grep transport_maps:

address_verify_sender_dependent_default_transport_maps = $sender_dependent_default_transport_maps
address_verify_transport_maps = $transport_maps
empty_address_default_transport_maps_lookup_key = <>
fallback_transport_maps =
mailbox_transport_maps =
proxy_read_maps = $local_recipient_maps $mydestination $virtual_alias_maps $virtual_alias_domains $virtual_mailbox_maps $virtual_mailbox_domains $relay_recipient_maps $relay_domains $canonical_maps $sender_canonical_maps $recipient_canonical_maps $relocated_maps $transport_maps $mynetworks $smtpd_sender_login_maps $sender_bcc_maps $recipient_bcc_maps $smtp_generic_maps $lmtp_generic_maps $alias_maps $smtpd_client_restrictions $smtpd_helo_restrictions $smtpd_sender_restrictions $smtpd_relay_restrictions $smtpd_recipient_restrictions
sender_dependent_default_transport_maps =
transport_maps = mysql:/etc/postfix/mysql_transport.cf
postconf: warning: /etc/postfix/main.cf: unused parameter: virtual_overquota_bounce=yes
postconf: warning: /etc/postfix/main.cf: unused parameter: virtual_mailbox_limit_maps=mysql:/etc/postfix/mysql_virtual_mailbox_limit_maps.cf
postconf: warning: /etc/postfix/main.cf: unused parameter: virtual_maildir_limit_message=Sorry, the your maildir has overdrawn your diskspace quota, please free up some of spaces of your mailbox try again.
postconf: warning: /etc/postfix/main.cf: unused parameter: virtual_create_maildirsize=yes
postconf: warning: /etc/postfix/main.cf: unused parameter: virtual_mailbox_extended=yes
postconf: warning: /etc/postfix/main.cf: unused parameter: virtual_mailbox_limit_override=yes

/var/spool/vacation/vacation.pl is owned by the vacation user:

-rwxr-xr-x 1 vacation vacation 25K Jul  6 10:31 /var/spool/vacation/vacation.pl
root@mailserver:~#
root@mailserver:~# ls -lah /var/spool/vacation/vacation.pl
-rwxr-xr-x 1 vacation vacation 25K Jul  6 10:31 /var/spool/vacation/vacation.pl

The script does fire when email received  and attempts to convert the email to normal style, as shown in vaction log file:

"Converted autoreply mailbox back to normal style - from me@auto-reply.mydomain.com to me"

This is not working though and resulting in just "me" rather than "me@mydomain.com" because the initial # symbol which the script uses to revert the email address is not present.

The manual testing of the script works and is run as vacation user as follows, out of office message is sent and received as expected:

sudo -u vacation cat ./test-email | perl /var/spool/vacation/vacation.pl -f me@googlemail.com -- me@mydomain.com

**Comment by DavidGoodwin** [comment]
What does ```postmap -q me@mydomain.com mysql:/etc/postfix/something/alias_maps.cf ``` return ?

(I'd expect that to give me@mydomain.com and me#autoreply@auto-reply.mydomain.com )


What does 

```postmap -q me#autoreply@auto-reply.mydomain.com mysql:/etc/postfix/mysql_transport.cf``` show ?
(Hopefully vacation: )
