### ISSUE TITLE
link on home page to gentoo wiki page is broken

### ISSUE THREAD

**Issue by thejoelinux** [postfixadmin/postfixadmin#191]
On the home page of Postfix, there is a link to a page on Gentoo Wiki :

http://gentoo-wiki.com/HOWTO_Setup_a_Virtual_Postfix/Courier_Mail_System_with_PostfixAdmin

This page does not exists anymore.

**Comment by DavidGoodwin** [comment]
thanks; hopefully fixed.

**Comment by munagala05** [comment]
not comming
