### ISSUE TITLE
When setting up a forward email address, it doesn't forward the mail there

### ISSUE THREAD

**Issue by barrychapman** [postfixadmin/postfixadmin#193]
I have created a mailbox user, and set up their email forwarding to forward the mail to my gmail account.

However, when I send them an email, it just ends up in their mailbox. What do i do?

Thanks!

**Comment by DavidGoodwin** [comment]
Check the output from ```postmap -q user@address mysql:/etc/postfix/sql/whatever.cf```

that'll give you some idea as to whether the alias expansion is taking place.

and what's in ```/var/log/mail.log``` - perhaps the email is being sent to gmail and the mailbox, but gmail is marking it as spam ?

**Comment by barrychapman** [comment]
When I use:

`[root@localhost ~]# postmap -q info@floordetective.com mysql:/etc/postfix/mysql-virtual-mailbox-maps.cf`

it gives me:

`floordetective.com/info/`

Not quite sure how to interpret these results.

**Comment by DavidGoodwin** [comment]
whatever - should be your alias maps file - so 

```postmap -q info@floordetective.com mysql:/etc/postfix/mysql-virtual-alias-maps.cf``` 

for instance

**Comment by DavidGoodwin** [comment]
For me, on one system : 
```postmap -q dg@example.co.uk pgsql:/etc/postfix/pgsql/virtual-alias-maps.cf```

gives : 

```dg#example.co.uk@autoreply.example.co.uk,dg@example.co.uk```

I suspect your lookup is only returning one address and not both.

**Comment by AnastaZIuk** [comment]
so what was the solution?

**Comment by AnastaZIuk** [comment]
@barrychapman  @DavidGoodwin

**Comment by AnastaZIuk** [comment]
> so what was the solution?

https://sourceforge.net/p/postfixadmin/discussion/676076/thread/6c7c7ce29a/ I've had similar issue probably

**Comment by DavidGoodwin** [comment]
@AnastaZIuk suggest you check what is in the database table for the mailbox/alias, and figure out if the virtual_alias_maps.cf file is correct or not.

**Comment by barrychapman** [comment]
In my case, I enabled debug on postfix/dovecot and tail -f /var/log/maillog

I was able to look at the behavior of each action being taken when a request came in:


```
Sep 12 22:58:26 ip-172-31-6-128 dovecot: auth: Debug: client passdb out: CONT#01119#011UGFzc3dvcmQ6
Sep 12 22:58:32 ip-172-31-6-128 dovecot: auth: Debug: client in: CONT#01119#011YnV5dGVycGVuZXNvbmxpbmU= (previous base64 data may contain sensitive data)
Sep 12 22:58:32 ip-172-31-6-128 dovecot: auth-worker(22433): Debug: sql(st2@examplesite.net,212.70.22.12): query: SELECT username, domain, password, CONCAT('/var/spool/mail/', maildir) AS home, '1002' AS uid, '1002' AS gid FROM mailbox WHERE local_part = 'st2' AND domain = 'examplesite.net'
Sep 12 22:58:32 ip-172-31-6-128 dovecot: auth-worker(22433): sql(st2@examplesite.net,212.70.22.12): unknown user
Sep 12 22:58:34 ip-172-31-6-128 postfix/smtps/smtpd[22229]: warning: unknown[212.70.22.12]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
Sep 12 22:58:34 ip-172-31-6-128 dovecot: auth: Debug: client passdb out: FAIL#01119#011user=st2@examplesite.net
```

**Comment by DavidGoodwin** [comment]
@barrychapman for those log messages, they're only showing that someone can login using dovecot. I thought the problem was postfix not delivering mail as expected.

**Comment by AnastaZIuk** [comment]
thank you guys! generally problem found and solved! :D

**Comment by barrychapman** [comment]
> @barrychapman for those log messages, they're only showing that someone can login using dovecot. I thought the problem was postfix not delivering mail as expected.

All I did was show him log messages available when he enables debug. That is what the log looks like.

It is the output of /var/log/maillog available to users with access. It tells you problems that may occur with your configuration.

It is the mail log

**Comment by barrychapman** [comment]
@DavidGoodwin  And yes, that particular log, happens to show someones login status with debug enabled. It shows much more than just login status, but also nifty things like SSL status, forwarding status, mailbox deliverability status, and so much more.

**Comment by barrychapman** [comment]
> @barrychapman for those log messages, they're only showing that someone can login using dovecot. I thought the problem was postfix not delivering mail as expected.

@DavidGoodwin also - you may notice that @AnastaZIuk was able to find his problem. Maybe by debug, maybe not.

Either way he is good. And I have done no harm.

Unless of course he leaves debug on and runs out of space due to not using some log rotate. The mail log can fill up very quickly.
