### ISSUE TITLE
Postfix aliases Utility released in new repo

### ISSUE THREAD

**Issue by platipusica** [postfixadmin/postfixadmin#196]
Hey guys,

Sorry for intrusion postfixadmin! Hope this does not offend you :)

We maintain a hundreds of domains with Aliases files for postfix. It's a ssh access, flat files editing, as you guys know.

So, I was looking into the postfixadmin repo here, no go for us, and I'm sorry. We just need a simple way to update Aliases file by different ppl over the Web, preferably AD authenticated.

Hence, decided to develop something based on my experience with Jam.py.com, and here it is:

https://github.com/platipusica/jampy-posfixaliases

It's first release. I'm counting on you guys to help with ideas or even join for further developing!

Thanks and enjoy!

**Comment by DavidGoodwin** [comment]
The UI looks nice (on the demo site).

I don't understand why postfixadmin couldn't have worked for you but ... nevermind. Each to their own! 

Good luck :)

**Comment by platipusica** [comment]
Thank you so much David!

This is a good question, but I'm guessing we just need one single postfixadmin feature:)

Same to you, cheers
