### ISSUE TITLE
How to correctly specify a pregenerated setup password

### ISSUE THREAD

**Issue by user34545** [postfixadmin/postfixadmin#198]
Hi,
I am trying to setup postfixadmin, but I want to use a pregenerated setup password.
The problem is that I can't seem to put it in config.local.php the right way.
I would like to use dovecot:SHA512 (or better SHA512-CRYPT, but I heard this is even more problematic) as the hashing algorithm.

So, I've set this in the config:
```
$CONF['encrypt'] = 'dovecot:SHA512';
$CONF['setup_password'] = '{SHA512}myhash';
```

The hash was generated with doveadm.
I also tried different ways of specifying the hash algorithm before the password or just leaving it out.
But everytime I try to create a admin user afterwards, postfixadmin tells me the setup password was not specified correctly.

So, how can I do this the right way?
Are you using some sort of own hashing algorithm in the end? Because the hash displayed by postfixadmin does not seem familiar to me.

I use postfixadmin 3.2 and dovecot 2.3.0.
Any help is much appreciated.
I will provide more info, if needed.

Thanks a lot.

**Comment by DavidGoodwin** [comment]
the setup password is checked at https://github.com/postfixadmin/postfixadmin/blob/master/public/setup.php#L461

it's generated by e.g. https://github.com/postfixadmin/postfixadmin/blob/master/public/setup.php#L450

which has a salt from https://github.com/postfixadmin/postfixadmin/blob/master/public/setup.php#L444 (which I'm inclined to think should be using random_bytes()).

**Comment by user34545** [comment]
Thank you for your answer.
So how would I generate a password in the right format with doveadm and then set it in the config, so that postfixadmin can actually use it?

**Comment by DavidGoodwin** [comment]
The setup password has nothing to do with postfix admin users, and isn't generated by doveadm. The setup password is ONLY used to add admin users to postfixadmin (i.e. what's in the 'admin' database table).

It's in the format of ```salt:hash``` where the hash is a sha1 of (hash . ':' . password )

I've no idea if doveadm can generate this; but I doubt it.

**Comment by user34545** [comment]
Oh okay.
Then I misunderstood something.
Thank you for the clarification.
