### ISSUE TITLE
Quota display and setting 

### ISSUE THREAD

**Issue by danchao** [postfixadmin/postfixadmin#201]
I'm using postfixadmin 3.2.

Here's my quota settings in config.inc.php
```
// Default Domain Values
// Specify your default values below. Quota in MB.
$CONF['aliases'] = '100';
$CONF['mailboxes'] = '100';
$CONF['maxquota'] = '0';
$CONF['domain_quota_default'] = '20480';

// Quota
// When you want to enforce quota for your mailbox users set this to 'YES'.
$CONF['quota'] = 'YES';
// If you want to enforce domain-level quotas set this to 'YES'.
$CONF['domain_quota'] = 'YES';
// You can either use '1024000' or '1048576'
$CONF['quota_multiplier'] = '1024000';
```
The dovecot configuration looks like this,
```
user_query = SELECT 5000 AS uid, 5000 AS gid, concat('/home/vmail/',maildir) as home, CONCAT('*:bytes=', quota) AS quota_rule FROM mailbox WHERE local_part = substring_index('%n','+',1) AND domain = '%d' AND active = '1';
```
I've been using this config for past few years without changing.

But while I do domain list in postfixadmin, it seems the domain quota part never get divided.
Also, when I create a new domain or new user, the quota also not multiplied.
Is there any configuration wrong?

The output from "postfixadmin/list.php?table=domain&output=cvs" as below,
```
ia.org.tw;;"0 / ∞";"7 / ∞";0;"71680 / 24792727826";0;1;0000-00-00
```

**Comment by DavidGoodwin** [comment]
It's quite possible - but I don't use quota anywhere, so wouldn't know what to look at / check.
