### ISSUE TITLE
some bugs with images

### ISSUE THREAD

**Issue by Nurlan199206** [postfixadmin/postfixadmin#202]
Hi.

i'm installed postfixadmin with command `apt install postfixadmin` but after installation something wrong with images. Postfixadmin directory located `/usr/share/postfixadmin`

my config `/etc/apache2/conf-enabled/postfixadmin.conf` is below.

`Alias /postfixadmin /usr/share/postfixadmin/public`

HELP PLS!!!

![image](https://user-images.githubusercontent.com/22808731/45274604-08e69700-b4da-11e8-8a99-3a5d2be07066.png)

**Comment by DavidGoodwin** [comment]
http://isientrance.com/postfixadmin/login.php looks like it works from here.
