### ISSUE TITLE
Date field at sendmail.php

### ISSUE THREAD

**Issue by genofire** [postfixadmin/postfixadmin#203]
i receive errors with 
```
INVALID HEADER

  Missing required header field: "Date"
```

**Comment by DavidGoodwin** [comment]
What version of Postfixadmin are you using? 

Is it possible that error is coming from the SMTP server you're connecting to?

**Comment by genofire** [comment]
Yes, it is a Form my Mailserver/postfix ... broadcast works, there is a Date-header set.

(It would also be at master like the sourcecode look linke)

**Comment by genofire** [comment]
Date-header in broadcast:

https://github.com/postfixadmin/postfixadmin/blob/b1795ab596e2d87cc172e698ba1f536095d5e777/public/broadcast-message.php#L92

Nothing at sendmail:
https://github.com/postfixadmin/postfixadmin/blob/b1795ab596e2d87cc172e698ba1f536095d5e777/public/sendmail.php#L65

**Comment by DavidGoodwin** [comment]
Ok, so adding a Date header is fairly easy at least :)

Your initial 'bug' report made me think the problem was with the PFA code (which might not strictly be the case ... if it's your mail server moaning about a Date header missing).

**Comment by genofire** [comment]
Sorry, for this misleading title.
Thanks for assigned ;)

(One question Off-Topic, when u release it / normally? I also want to try the bootstrapthemen - or create a own one)
