### ISSUE TITLE
Setup password not working..

### ISSUE THREAD

**Issue by kapitanf** [postfixadmin/postfixadmin#204]
Hi, i have problem with superadmin account creation. Setup password is not working, after save "config text"
to config.local.php.  
config text:
$CONF['setup_password'] = 
e.g.
'b42d5db8725369462cdeb401b6a072f3:892bf9fe4cc4264267a777489895637a4125dc8f';

System is Archlinux
WebServer: nginx latest
php, php-fpm, sqlite3, dovecot, postfix.

Database is up to date: 1840/0

**Setup password not specified correctly**

**If you want to use the password you entered as setup password, edit config.inc.php or config.local.php and set**

$CONF['setup_password'] = '8fb839b87fc4bd393297f9f1d7fbe682:522c0832ce9599b4d2a6bc684a1fb426e008f697';

**Comment by DavidGoodwin** [comment]
@kapitanf can you reopen this if you still have a problem; you've not provided enough information for us to fix it.

**Comment by BA18NN** [comment]
Hello Gitters

I have run into the same issue, trying to set the admin login creds , via browser :

I believe I have everything "correct" 

a/.   I created the hash for the password, on the page : 
    https://myserver/postfixadmin/setup.php

b/.   Copied it to the file "/var/www/html/postfixadmin/config.local.php " and saved it,

c/.  Returned to the browser page, and entered the appropriate data.

The set-up password I just applied
a new admin test email address
a new password for admin 
retype new admin password.


Click "add admin"

See output below,   including another "hashed" string...?



Postfix Admin Setup Checker

Running software:

PHP version 7.2.24-0ubuntu0.18.04.1
Apache/2.4.29 (Ubuntu)
Checking for dependencies:

Magic Quotes: Disabled - OK
Depends on: presence config.inc.php - OK
Checking $CONF['configured'] - OK
Depends on: presence config.local.php - OK
Depends on: MySQL 4.1 - OK
Testing database connection (using mysqli) - OK
Depends on: session - OK
Depends on: pcre - OK
Depends on: multibyte string - OK
Depends on: IMAP functions - OK
Everything seems fine... attempting to create/update database structure

Database is up to date: 1840/0

                          Setup password not specified correctly

If you want to use the password you entered as setup password, edit config.inc.php or config.local.php and set

$CONF['setup_password'] = '20e3f0af3cddc6216bd5d1916df903bf:63c2870ad519440040aed5f4b7d171939e6f1ef7';


And here I am stuck,  

also to note... I have the "cookie.php " and it  tested fine, worked as expected.

**Comment by BA18NN** [comment]
by the ways,   I tried with and without the php head/tail

<?php
$CONF['setup_password'] = '941c2ecb125762513dbc35eb750d0c7e:b686f1ff4306012303cfba55d90ce518852e267c';
?>

**Comment by DavidGoodwin** [comment]
It's probably the case that you're updating/editing the "wrong" config.local.php file.

Are you sure there isn't one hiding in e.g. /etc/postfixadmin/ that is being used instead ?

If you put a ```die('hi mum!');``` in the one you think you should be editing, do you see everything exploding when you refresh the setup page?

**Comment by BA18NN** [comment]
Thanks David!!!  
that was is, I was following a online guide and it included creating a file in /var/www/html/...etc..

but when I used the file you suggested instead, I have progress, 

So to confirm I create the hash key,  and then copied the details to 

/srv/postfixadmin/config.local.php

(diff folder but is now the only config.local.php on my env.. )

after saving the details, I could continue and create the admin creds..and then login ..

thanks!!!

**Comment by dangraves101** [comment]
Hi Gitters, 

I ran into the same issue. I followed the instructions from this website "https://www.exratione.com/2019/02/a-mailserver-on-ubuntu-18-04-postfix-dovecot-mysql/"

I entered the hash created to  /var/www/html/postfixadmin/config.local.php after entering the setup password. The setup.php page keeps telling me " Setup password not specified correctly".

I used <?php ?> and without in the /var/www/html/postfixadmin/config.local.php

I used the instructions from  "https://www.exratione.com/2019/02/a-mailserver-on-ubuntu-18-04-postfix-dovecot-mysql/". I do not see /etc/postfixadmin/config.local.php as i downloaded i followed the instructions. I am new, not sure how I can fix this

Details are as same as BA18NN's :=

a/. I created the hash for the password, on the page :
https://myserver/postfixadmin/setup.php

b/. Copied it to the file "/var/www/html/postfixadmin/config.local.php " and saved it,

c/. Returned to the browser page, and entered the appropriate data.

The set-up password I just applied
a new admin test email address
a new password for admin
retype new admin password.

Click "add admin"

See output below, including another "hashed" string...?

Postfix Admin Setup Checker

Running software:

PHP version 7.2.24-0ubuntu0.18.04.6
Apache
Checking for dependencies:

Magic Quotes: Disabled - OK
Depends on: presence config.inc.php - OK
Checking $CONF['configured'] - OK
Depends on: presence config.local.php - OK
Depends on: MySQL 4.1 - OK
Testing database connection (using mysqli) - OK
Depends on: session - OK
Depends on: pcre - OK
Depends on: multibyte string - OK
Depends on: IMAP functions - OK
Everything seems fine... attempting to create/update database structure

Database is up to date: 1840/0

                      Setup password not specified correctly

Thanks

**Comment by DavidGoodwin** [comment]
Hi - commenting on a closed issue isn't the best of ideas, as many people will not see it.

Have you followed through the steps / suggestions above ? They should help verify that you're actually editing the right file :-)

**Comment by cooperdk** [comment]
I can say personally that I am having the same issue. And I DO get the "Die mom" message. The config is inside the script directory and the script used to work. After deleting the db, I cannot get past this same issue.

**Comment by DavidGoodwin** [comment]
* What version of postfixadmin are you installing?
 * What is in your config.local.php file?
 * Are there remnants of a debian (or rpm) package lying around in /etc/postfixadmin that MIGHT be causing trouble?
 
The "Setup password" is only for accessing https://server/setup.php. Each time you submit a form on that page (e.g. adding an admin user) you need to supply the setup password. 

Since version 3.3 (I think) the setup password has changed to be something compatible with PHP's password_hash() method - so it'll look a little like : 

`$2y$10$naNgaRv/Dmp3siMBDzPVO.z9lIcYTF1mGOVrsA2IT6wAl5rCsO446` 

(via: ` php -r 'echo password_hash("foobarbaz", PASSWORD_DEFAULT);' ` )

If your setup password contains colons (:) then it's probably in the old format and won't work.

**Comment by saintfrater** [comment]
I'm a dum guy... 

I'm trying to "copy-past" the hashed password for several minutes now, trying to figuring out why the heck it's not working...

Then I've the *illumination*: I've to enter the password I've specified during the setup phase, not the hashed (from the <code>config.local.php</code>) one....

I feel so stupid now...
