### ISSUE TITLE
postfixadmin-cli does not work

### ISSUE THREAD

**Issue by Isa001** [postfixadmin/postfixadmin#207]
PostfixAdmin 3.2
PHP 7.2
OS Raspbian Strech (raspberry)

`bash postfixadmin-cli admin add myemail@domain.com --superadmin 1 --active 1 --password myPswd --password2 myPswd`

=>

> Welcome to Postfixadmin-CLI v0.2
> ---------------------------------------------------------------
> Error: invalid parameter --0 => postfixadmin-cli.php
> 
> Error: invalid parameter --1 => admin
> 
> Error: invalid parameter --2 => add
> 
> Error: invalid parameter --3 => myemail@domain.com
> 
> Error: invalid parameter --4 => --superadmin
> 
> Error: invalid parameter --5 => 1
> 
> Error: invalid parameter --6 => --active
> 
> Error: invalid parameter --7 => 1
> 
> Error: invalid parameter --8 => --password
> 
> Error: invalid parameter --9 => myPswd
> 
> Error: invalid parameter --10 => --password2
> 
> Error: invalid parameter --11 => myPswd

So, what's wrong ??

**Comment by DavidGoodwin** [comment]
I think I fixed this in master a few days ago; are you able to check/confirm?

**Comment by blaarb** [comment]
So how was the issue resolved? I've run into the same problem now on CentOS 7, apache + php 7.2 (remi), postfixadmin 3.2 (latest).

**Comment by DavidGoodwin** [comment]
What's in 'master' works for me - e.g.

```
david@walnut:~/src/postfixadmin-stuff/postfixadmin/scripts$ bash postfixadmin-cli admin add test2@example.com --superadmin 1 --active 1 --password foobar12 --password2 foobar12

Welcome to Postfixadmin-CLI v0.2
---------------------------------------------------------------

The admin test2@example.com has been added!

---------------------------------------------------------------
```

I've had a look through the commit history but can't spot the relevant changeset which presumably fixed it (which is no doubt my fault as I'm not very good at splitting up changes into distinct units)

**Comment by Corvan** [comment]
For when is the next release planned? Because only then this fix will end up in the FreeBSD-Ports collection, which would be nicer to use than to check out master manually

**Comment by GoofyAdmin** [comment]
I have the exact problem and have tried both the postfixadmin-3.2.tar.gz here and on sourceforge.  was really hoping to use it to automate adding mailboxes.
