### ISSUE TITLE
super admin was not created

### ISSUE THREAD

**Issue by Glangouet** [postfixadmin/postfixadmin#208]
Hello,
i use the tag 3.2 clone from the repo git.
When i create the setup password it works, and i paste the password in the config file, my db was created too but when i fill out the super admin form and submit, nothing is happening, user admin was not created in the db and only still one message with the password crypted.
Do you know what's happen? 
Thanks

**Comment by Glangouet** [comment]
fixed, just bad config with my php7.2 cli / apache php.ini

**Comment by DavidGoodwin** [comment]
thanks for providing the resolution :)
