### ISSUE TITLE
setup.php says php dependencies are not installed when they are (FreeBSD)

### ISSUE THREAD

**Issue by planet-winter** [postfixadmin/postfixadmin#209]
_setup.php_ complains about not installed packages with Postfixadmin 3.2_1 on FreeBSD 11.2-RELEASE-p2 (see below)
And setup can not be continued:

php5-pgsql
php5-mbstring
php5-imap

The packages are installed. however their name differs:

pkg info php56-pgsql
pkg info php56-mbstring
pkg info php56-imap

show installed pacakges.

How is an installed php library detected?

```
Postfix Admin Setup Checker

Running software:

    PHP version 5.6.37

Checking for dependencies:

    Magic Quotes: Disabled - OK
    Depends on: presence config.inc.php - OK
    Checking $CONF['configured'] - OK
    Depends on: presence config.local.php - OK
    Depends on: SQLite - OK
    (change the database_type to 'sqlite' in config.local.php if you want to use SQLite)
    Error: Can't connect to database
    Please edit the $CONF['database_*'] parameters in config.local.php.

    DEBUG INFORMATION:
    PostgreSQL functions not available! (php5-pgsql installed?)
    database_type = 'pgsql' in config.inc.php, are you using a different database?
    Depends on: session - OK
    Depends on: pcre - OK
    Error: Depends on: multibyte string - NOT FOUND
    To install multibyte string support, install php5-mbstring
    Warning: Depends on: IMAP functions - NOT FOUND
    To install IMAP support, install php5-imap
    Without IMAP support, you won't be able to create subfolders when creating mailboxes.

Please fix the errors listed above.
```

**Comment by DavidGoodwin** [comment]
Hi - the code should be looking to see whether a specific extension or function is present in PHP.

(see: 
https://github.com/postfixadmin/postfixadmin/blob/master/public/setup.php#L37 )

It's possible you need to restart Apache (or whatever) after you have installed those packages in order for PHP to pickup any new modules.

The "you need to install php5-pgsql" ... or whatever is just a hint, it isn't checking your system for a package of that exact name.

**Comment by planet-winter** [comment]
@DavidGoodwin Thanks
**restarting php-fpm** solved the issue.
I forgot I already stumbled upon this. Will make sure Ansible is restarting php-fpm now :)
