### ISSUE TITLE
SQLite schema

### ISSUE THREAD

**Issue by RickD123** [postfixadmin/postfixadmin#212]
Hi,

is there any documentation available on the SQLite schema that Postfixadmin requires? I need to check whether my own database on Postfix based on SQLite would be compatible.

Thank you.

Kind regards
RickD

**Comment by DavidGoodwin** [comment]
something close to : ```sqlite> .schema
CREATE TABLE config (
        `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
        `name` TEXT NOT NULL UNIQUE DEFAULT '',
        `value` TEXT NOT NULL DEFAULT ''
        );
CREATE TABLE admin (
          `username` varchar(255) NOT NULL,
          `password` varchar(255) NOT NULL,
          `superadmin` tinyint(1) NOT NULL DEFAULT '0',
          `created` datetime NOT NULL default '2000-01-01',
          `modified` datetime NOT NULL default '2000-01-01',
          `active` tinyint(1) NOT NULL DEFAULT '1', phone varchar(30)  NOT NULL DEFAULT '', email_other varchar(255)  NOT NULL DEFAULT '', token varchar(255)  NOT NULL DEFAULT '', token_validity datetime NOT NULL default '2000-01-01',
          PRIMARY KEY (`username`));
CREATE TABLE alias (
          `address` varchar(255) NOT NULL,
          `goto` text NOT NULL,
          `domain` varchar(255) NOT NULL,
          `created` datetime NOT NULL default '2000-01-01',
          `modified` datetime NOT NULL default '2000-01-01',
          `active` tinyint(1) NOT NULL DEFAULT '1',
          PRIMARY KEY (`address`));
CREATE TABLE alias_domain (
          `alias_domain` varchar(255) NOT NULL,
          `target_domain` varchar(255) NOT NULL,
          `created` datetime NOT NULL default '2000-01-01',
          `modified` datetime NOT NULL default '2000-01-01',
          `active` tinyint(1) NOT NULL DEFAULT '1',
          PRIMARY KEY (`alias_domain`));
CREATE TABLE domain (
          `domain` varchar(255) NOT NULL,
          `description` varchar(255) NOT NULL,
          `aliases` int(11) NOT NULL DEFAULT 0,
          `mailboxes` int(11) NOT NULL DEFAULT 0,
          `maxquota` bigint(20) NOT NULL DEFAULT 0,
          `quota` bigint(20) NOT NULL DEFAULT 0,
          `transport` varchar(255) NOT NULL,
          `backupmx` tinyint(1) NOT NULL DEFAULT '0',
          `created` datetime NOT NULL default '2000-01-01',
          `modified` datetime NOT NULL default '2000-01-01',
          `active` tinyint(1) NOT NULL DEFAULT '1',
          PRIMARY KEY (`domain`));
CREATE TABLE domain_admins (
          `username` varchar(255) NOT NULL,
          `domain` varchar(255) NOT NULL,
          `created` datetime NOT NULL default '2000-01-01',
          `active` tinyint(1) NOT NULL DEFAULT '1');
CREATE TABLE fetchmail (
          `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
          `domain` varchar(255) DEFAULT '',
          `mailbox` varchar(255) NOT NULL,
          `src_server` varchar(255) NOT NULL,
          `src_auth` varchar(255) DEFAULT NULL,
          `src_user` varchar(255) NOT NULL,
          `src_password` varchar(255) NOT NULL,
          `src_folder` varchar(255) NOT NULL,
          `poll_time` int(11)  NOT NULL DEFAULT '10',
          `fetchall` tinyint(1) NOT NULL DEFAULT '0',
          `keep` tinyint(1) NOT NULL DEFAULT '0',
          `protocol` text DEFAULT NULL,
          `usessl` tinyint(1) NOT NULL DEFAULT '0',
          `sslcertck` tinyint(1) NOT NULL DEFAULT '0',
          `sslcertpath` varchar(255) DEFAULT '',
          `sslfingerprint` varchar(255) DEFAULT '',
          `extra_options` text,
          `returned_text` text,
          `mda` varchar(255) NOT NULL,
          `date` datetime NOT NULL default '2000-01-01',
          `created` datetime NOT NULL default '2000-01-01',
          `modified` datetime NOT NULL default CURRENT_TIMESTAMP,
          `active` tinyint(1) NOT NULL DEFAULT '0');
CREATE TABLE mailbox (
          `username` varchar(255) NOT NULL,
          `password` varchar(255) NOT NULL,
          `name` varchar(255) NOT NULL,
          `maildir` varchar(255) NOT NULL,
          `quota` bigint(20) NOT NULL DEFAULT 0,
          `local_part` varchar(255) NOT NULL,
          `domain` varchar(255) NOT NULL,
          `created` datetime NOT NULL default '2000-01-01',
          `modified` datetime NOT NULL default '2000-01-01',
          `active` tinyint(1) NOT NULL DEFAULT '1', phone varchar(30)  NOT NULL DEFAULT '', email_other varchar(255)  NOT NULL DEFAULT '', token varchar(255)  NOT NULL DEFAULT '', token_validity datetime NOT NULL default '2000-01-01',
          PRIMARY KEY (`username`));
CREATE TABLE quota (
          `username` varchar(255) NOT NULL,
          `path` varchar(100) NOT NULL,
          `current` bigint(20) NOT NULL DEFAULT 0,
          PRIMARY KEY (`username`,`path`));
CREATE TABLE quota2 (
          `username` varchar(255) NOT NULL,
          `bytes` bigint(20) NOT NULL DEFAULT 0,
          `messages` int(11) NOT NULL DEFAULT 0,
          PRIMARY KEY (`username`));
CREATE TABLE vacation (
          `email` varchar(255) NOT NULL,
          `subject` varchar(255) NOT NULL,
          `body` text NOT NULL,
          `activefrom` datetime NOT NULL default '2000-01-01',
          `activeuntil` datetime NOT NULL default '2038-01-18',
          `cache` text NOT NULL DEFAULT '',
          `domain` varchar(255) NOT NULL,
          `interval_time` int(11) NOT NULL DEFAULT 0,
          `created` datetime NOT NULL default '2000-01-01',
          `modified` datetime NOT NULL default CURRENT_TIMESTAMP,
          `active` tinyint(1) NOT NULL DEFAULT '1',
          PRIMARY KEY (`email`));
CREATE TABLE vacation_notification (
          `on_vacation` varchar(255) NOT NULL,
          `notified` varchar(255) NOT NULL,
          `notified_at` datetime NOT NULL default CURRENT_TIMESTAMP,
          PRIMARY KEY (`on_vacation`,`notified`),
          CONSTRAINT `vacation_notification_pkey` FOREIGN KEY (`on_vacation`) REFERENCES `vacation` (`email`) ON DELETE CASCADE);
CREATE TABLE log (
          `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
          `timestamp` datetime NOT NULL default '2000-01-01',
          `username` varchar(255) NOT NULL,
          `domain` varchar(255) NOT NULL,
          `action` varchar(255) NOT NULL,
          `data` text NOT NULL);
```
