### ISSUE TITLE
maildirmake is not universal anymore

### ISSUE THREAD

**Issue by oliv3r** [postfixadmin/postfixadmin#213]
https://github.com/postfixadmin/postfixadmin/blob/056e8af99bdfa382d5203728efe1b0eeca3e1a9c/ADDITIONS/postfixadmin-mailbox-postcreation.sh#L55

maildirmake, atleast for courier, is now installed as courier-maildirmake.

**Comment by DavidGoodwin** [comment]
Debian Stretch maintains /usr/bin/maildirmake through the /etc/alternatives stuff ... 

What distro are you using?

Perhaps we just need a 
```
if [ -x /usr/bin/maildirmake ]; then .... 
elseif [ -x /usr/bin/courier-maildirmake ]; then ....
fi 
``` ?

**Comment by oliv3r** [comment]
probably not a bad idea; gentoo doesn't have debian's nice alternatives system afaik.
but sure, as long as the syntax to the tools remain similar enough ...

**Comment by DavidGoodwin** [comment]
that good enough?

**Comment by oliv3r** [comment]
i think that's probably the best we can do until they start changing their interfaces ... I wonder _why_ courier renamed the tool ...
