### ISSUE TITLE
no update on CHANGELOG.TXT

### ISSUE THREAD

**Issue by tdmdema** [postfixadmin/postfixadmin#214]
Hi,
we're in trouble because CHANGELOG.TXT has not been updated for 7 months.
There where a lot of braking changes have merged even in these days and undocumented.
Moreover, that file is useful for creating automatic deployments, but only if it is constantly maintained.
I ask the mainteners to provide.

**Comment by Lonni93** [comment]
> Hi,
> we're in trouble because CHANGELOG.TXT has not been updated for 7 months.
> There where a lot of braking changes have merged even in these days and undocumented.
> Moreover, that file is useful for creating automatic deployments, but only if it is constantly maintained.
> I ask the mainteners to provide.

Yep, +1 here... pretty annoying. Many "invasive" changes and not a single edit to the changelog. I thought i went crazy cause the files changes but not the changelog.

**Comment by DavidGoodwin** [comment]
Historically we've only updated the changelog when we've made a release.... 

There's always https://github.com/postfixadmin/postfixadmin/commits/master - but I admit that isn't quite as easy to read as a .txt file .... I'll see if I can update it soon.

**Comment by tdmdema** [comment]
I suggest to introduce a sub-release versioning, like 3.2.1 3.2.2 etc.
I think it's important to track only major improvements and breaking changes.

**Comment by DavidGoodwin** [comment]
We have done this in the past; but normally only for security related issues.
