### ISSUE TITLE
deb package: setup.php does not see config.local.php

### ISSUE THREAD

**Issue by cweiske** [postfixadmin/postfixadmin#217]
I installed the .deb package `postfixadmin_3.2-1_all.deb` and ran `setup.php`. It complains that it cannot find a `config.local.php` file even though I have one:

> Warning: config.local.php - NOT FOUND

The reason for this is that the .deb package correctly symlinks config.inc.php to /etc/postfixadmin/config.inc.php, but this is not done for config.local.php.

I'm not sure if that symlink should be created at all, since not all people have that local file. Maybe the check should be changed.

**Comment by cweiske** [comment]
Oh, you misunderstood me.

`config.local.php` gets loaded fine by `/etc/postfixadmin/config.inc.php`.

The problem is the detection if `config.local.php` exists in `setup.php`, which does not know about the different directory `/etc/postfixadmin` in which `config.inc.php` is located, and in which the local config resides.

**Comment by DavidGoodwin** [comment]
aaaah. Thanks for the clarification.
