### ISSUE TITLE
Accent/special caracters not shown

### ISSUE THREAD

**Issue by ouafnico** [postfixadmin/postfixadmin#219]
Hi ;)

Is it a way to use accent/special caracters on text? Actually all email sends from vacation don't have any accent/special caracters.

Thanks

**Comment by DavidGoodwin** [comment]
Hmm, that's probably a limitation of the vacation.pl code - but I thought we used utf8 for the message body/email that's sent.
e.g. 
https://github.com/postfixadmin/postfixadmin/blob/eb61141d2fbf9ba18e0b20fa8fe730bc5c81540e/VIRTUAL_VACATION/vacation.pl#L478
