### ISSUE TITLE
When installing a postfixadmin problem

### ISSUE THREAD

**Issue by lilongen1** [postfixadmin/postfixadmin#22]
Suggest the following error during installation.
But I checked the IMAP and php5-imap Have no problem.
How did this happen?
Have another posftixadmin logging, can see.
Help me! thanks!
<img src="https://raw.githubusercontent.com/lilongen1/ziluopao/master/postfixadmin_q1.png"/>

**Comment by cboltz** [comment]
This check basically does
`function_exists ("imap_open") == 1;`
and the message you see means this function doesn't exist.

Maybe you have php[57]-imap installed, but not enabled in the PHP config? Or you just didn't restart apache after installing it?

**Comment by lilongen1** [comment]
No, no, no
I do php[57]-imap installed
And also enable it
After server restart, often, of course, start, I will first check whether the service is started, the work should be performed

**Comment by DavidGoodwin** [comment]
do you see 'imap' in the output of ```php -m``` or when you view a page that contains ```<?php phpinfo(); ?>``` ?
