### ISSUE TITLE
SQLite schema upgrade - Admin table already exists

### ISSUE THREAD

**Issue by RickD123** [postfixadmin/postfixadmin#225]
Hi,

I am trying to install PostfixAdmin 3.2 and need to update my Sqlite schema (old version: 1767; target version: 1840). When doing so, I am getting the following error message:

`
updating

 to version 1824 (SQLite)...

CREATE TABLE admin ( `username` varchar(255) NOT NULL, `password` varchar(255) NOT NULL, `superadmin` tinyint(1) NOT NULL DEFAULT '0', `created` datetime NOT NULL default '2000-01-01', `modified` datetime NOT NULL default '2000-01-01', `active` tinyint(1) NOT NULL DEFAULT '1', PRIMARY KEY (`username`));

DEBUG INFORMATION:
Invalid query: table admin already exists

Obviously this happen as I already have an admin table from an earlier release - how can I fix this? Why is there no "if not exists" in the SQL statement above?

Thanks!

Kind regards
RickD

**Comment by DavidGoodwin** [comment]
Try updating your database's config table to be on version 1825? 
Does sqlite support a "if not exists" ?

**Comment by RickD123** [comment]
What surprises me is that „if not exists“ is in place I think for all other SQL commands executed for SQLite but apparently not for the admin table. How do I update my config table to version 1825?

**Comment by DavidGoodwin** [comment]
I didn't realise sqlite supported "if not exists".... 

```bash
sqlite3 /path/to/sqlite-database 
```
then

```sql
select * from config;
update config set value = 1825 where name = 'version';
```

**Comment by DavidGoodwin** [comment]
(the select * from config is just to check/show what's there).

**Comment by RickD123** [comment]
Hi,

all okay but I am getting SQLIte errors now due to an invalid SQL query:

(from Apache’s error_log)

[Fri Dec 28 14:09:53.797698 2018] [:error] [pid 15393] [client 85.10.210.200:51442] caused by query: SHOW COLUMNS FROM admin LIKE ‚phone'

[root@myserver /etc/postfix/db]# sqlite3 maildb.sqlite
SQLite version 3.26.0 2018-12-01 12:34:55
Enter ".help" for usage hints.
sqlite> show columns from admin like phone;
Error: near "show": syntax error

Personally, I believe the „show columns“ command is not supported in SQLite. I think this should be either a select statement or use pragma table_info(admin), see https://stackoverflow.com/questions/685206/how-to-get-a-list-of-column-names/685212 <https://stackoverflow.com/questions/685206/how-to-get-a-list-of-column-names/685212>.

Kind regards
RickD

**Comment by DavidGoodwin** [comment]
Hmm. What do you have in your config for database_type ? **sqlite** ?

```php
$CONF['database_type'] = 'sqlite';
```

**Comment by RickD123** [comment]
Correct, I have:

$CONF['database_type'] = 'sqlite';

**Comment by DavidGoodwin** [comment]
I don't know where you've got your use of ```show columns....``` from - the code shouldn't try and run that.

I've just checked my local development variant, and it's quite happy building an sqlite database from public/upgrade.php ... note; I've pushed a few fixes to master.

**Comment by RickD123** [comment]
Almost works now with the latest code from Github, setup goes through. When being asked to create admin account (after having defined the super password), I am getting the following error message:

[Fri Dec 28 21:21:18.633800 2018] [:error] [pid 23916] [client X:61220] Invalid query: NOT NULL constraint failed: domain_admins.id, referer: https://mydomain.com/mailadmin/setup.php
[Fri Dec 28 21:21:18.633895 2018] [:error] [pid 23916] [client X:61220] caused by query: INSERT INTO domain_admins (username,domain,created) VALUES ('s@w.com','ALL',datetime('now')), referer: https://mydomain/mailadmin/setup.php

I suppose this happens as domain_admins.id <http://domain_admins.id/> is not being set despite the fact that the SQLite database considers it a mandatory, not null field. Here is the table definition:

CREATE TABLE IF NOT EXISTS "domain_admins" (
  "id" int(11) NOT NULL ,
  "username" varchar(255) NOT NULL,
  "domain" varchar(255) NOT NULL,
  "created" datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  "active" tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY ("id")
);

Is this a known issue?

**Comment by DavidGoodwin** [comment]
oooh, interesting...

```SQL
sqlite> INSERT INTO domain_admins (username,domain,created) VALUES ('s@w.com','ALL',datetime('now'));
sqlite> select * from domain_admins;
support@palepurple.co.uk|ALL|2018-12-28 19:38:59|1
s@w.com|ALL|2018-12-28 20:38:54|1
sqlite> .schema domain_admins
CREATE TABLE domain_admins (
          `username` varchar(255) NOT NULL,
          `domain` varchar(255) NOT NULL,
          `created` datetime NOT NULL default '2000-01-01',
          `active` tinyint(1) NOT NULL DEFAULT '1');
```

I wonder how you have a slightly different schema to me.

**Comment by RickD123** [comment]
Okay now I recreated the domain_admins table removing the ID column and works fine now. Thanks.
