### ISSUE TITLE
mysql notification interval query in vacation.pl is wrong

### ISSUE THREAD

**Issue by john48938** [postfixadmin/postfixadmin#226]
This query does not give the correct result in vacation.pl:

`qq{SELECT NOW()-notified_at FROM vacation_notification WHERE on_vacation=? AND notified=?};`

You cannot just subtract two datetime fields in MySQL. It does return some kind of integer but that is definitely not the number of seconds elapsed. Result is that notifications are sent out again after less than a day even if you set the interval to the default 7 days.

A solution could be:

`qq{SELECT UNIX_TIMESTAMP(NOW())-UNIX_TIMESTAMP(notified_at) FROM vacation_notification WHERE on_vacation=? AND notified=?};`

or even better: use the MySQL TIMESTAMPDIFF method.

**Comment by DavidGoodwin** [comment]
Thanks; hopefully fixed/patched.
