### ISSUE TITLE
Error: Smarty template compile directory templates_c is not writable.

### ISSUE THREAD

**Issue by schel4ok** [postfixadmin/postfixadmin#228]
I cannot install postfixadmin
Setup.php gives me following info

```
Postfix Admin Setup Checker

Running software:

    PHP version 7.0.33-0+deb9u1
    Apache/2.4.25 (Debian)

Checking for dependencies:

    Magic Quotes: Disabled - OK
    Depends on: presence config.inc.php - OK
    Checking $CONF['configured'] - OK
    Error: Smarty template compile directory templates_c is not writable.
    Please make it writable.
    If you are using SELinux or AppArmor, you might need to adjust their setup to allow write access.
    Depends on: MySQL 4.1 - OK
    Testing database connection - OK - mysqli://postfixadmin:xxxxx@localhost/postfixadmin
    Depends on: session - OK
    Depends on: pcre - OK
    Depends on: multibyte string - OK
    Depends on: IMAP functions - OK

Please fix the errors listed above.
```
Then I tried to do actions described in https://github.com/postfixadmin/postfixadmin/blob/master/INSTALL.TXT
```
root@mail:~# mkdir -p /srv/postfixadmin/templates_c
root@mail:~# chown -R www-data /srv/postfixadmin/templates_c
```
But nothing changed. I have same error anyway.

My system is Debian GNU/Linux 9.6 (stretch)
10.1.37-MariaDB
PHP version 7.0.33-0+deb9u1
Apache/2.4.25 (Debian)

**Comment by DavidGoodwin** [comment]
Hmm.... can you look at your version of setup and see where it's expecting the templates_c directory to be?

**Comment by schel4ok** [comment]
What do you mean under "version of setup"?
I also want to know where it's expecting the templates_c directory to be.

**Comment by DavidGoodwin** [comment]
OK, well.... in master, we've removed the check for templates_c from setup.php; there is now just https://github.com/postfixadmin/postfixadmin/blob/master/lib/PFASmarty.php#L29 - whereby we log the full path to templates_c in the Apache (or PHP) error log.

**Comment by schel4ok** [comment]
I did installation like that 
`apt-get install -y postfix postfixadmin`

**Comment by DavidGoodwin** [comment]
Aaah.... so what does ```apt-cache policy postfixadmin``` show ?

There is no check in 3.2's setup.php for templates_c ( https://github.com/postfixadmin/postfixadmin/blob/postfixadmin_3.2/public/setup.php ).

Can Apache read /srv, /srv/postfixadmin and also write to /srv/postfixadmin/templates_c ? Do the directories have +x on them? What ownership is there?

Is there anything logged to your Apache error log?

**Comment by schel4ok** [comment]
so I should do like that?
```
apt-get remove postfixadmin
cd /srv/
wget -O postfixadmin.tgz https://github.com/postfixadmin/postfixadmin/archive/postfixadmin-3.2.tar.gz
tar -zxvf postfixadmin.tgz
mv postfixadmin-postfixadmin-3.2 postfixadmin
```

**Comment by schel4ok** [comment]
Yes that solved my problem.
It works now.
So please put update to INSTALL.TXT to avoid installation using DEB package

**Comment by DavidGoodwin** [comment]
Hmm; I think something else is going on there - e.g. the .deb package is trying to use some other directory - e.g. /var/lib/postfixadmin/templates_c or something like that .... 

The .deb SHOULD work .... (obviously!)

**Comment by DavidGoodwin** [comment]
Your permissions/ownership on /srv, and /srv/postfixadmin were fine. /srv/postfixadmin/templates_c should be owned by www-data - assuming that's your web server using (if using Apache). Otherwise, I'm not sure what's going on. I have a vague memory of official Debian packages using /var/lib/postfixadmin/templates_c or something. 

It's a bit hard to know more without either you editing lib/smarty.inc.php and var_dumping the realpath($template_c) dir ... or checking /var/log/apache2/error.log

**Comment by schel4ok** [comment]
I didn't edit  lib/smarty.inc.php 
and as you saw by default from deb package I had postfix 3.0.2-2, not 3.2

**Comment by neuffer** [comment]
@schel4ok: Which Debian release are you using?

**Comment by schel4ok** [comment]
it is written in the first message My system is Debian GNU/Linux 9.6 (stretch)

**Comment by schel4ok** [comment]
```
root@mail:~# uname -a
Linux mail.iserver.ru 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
root@mail:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.6 (stretch)
Release:        9.6
Codename:       stretch
root@mail:~# apt-cache show postfixadmin
Package: postfixadmin
Version: 3.0.2-2
Installed-Size: 3675
Maintainer: Norman Messtorff <normes@normes.org>
Architecture: all

```

**Comment by neuffer** [comment]
On 05.01.19 20:49, schel4ok wrote:
> |root@mail:~# uname -a Linux mail.iserver.ru 4.9.0-8-amd64 #1 SMP
> Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux root@mail:~#
> lsb_release -a No LSB modules are available. Distributor ID: Debian
> Description: Debian GNU/Linux 9.6 (stretch) Release: 9.6 Codename:
> stretch root@mail:~# apt-cache show postfixadmin Package: postfixadmin
> Version: 3.0.2-2 Installed-Size: 3675 Maintainer: Norman Messtorff
> <normes@normes.org> Architecture: all |
>

Have you tried:

http://ftp.debian.org/debian/pool/main/p/postfixadmin/postfixadmin_3.2-4_all.deb

It is as of last September, but that is at least 1.5 years better/newer
then the package you have installed currently.


@David:
This is a perfect example of what we've discussed earlier. A release
would be great so that I can push for an update of the Debian package. :-)

**Comment by neuffer** [comment]
On 06.01.19 10:28, David Goodwin wrote:
>
> Yes...... I discussed creating a new release briefly with @cboltz
> <https://github.com/cboltz> a few days ago on IRC.
>
> I believe he's going to test a few things.
>

Great!

> I'm toying with the idea of migrating the codebase to PDO (which would
> give us prepared statements).
>

You're talking about PHP Data Objects? http://php.net/manual/de/book.pdo.php
Interesting idea, but that will take some time to implement and test I
belive and should be something for release+1 if we want to have a chance
to get the current code into the next Debian release.

> I'm also not terribly happy with some of the password expiration stuff
> - I think it possibly needs to change so we have a password_updated
> timestamp column or we have a better mechanism for hooks - as the
> existing code (e.g.
> https://github.com/postfixadmin/postfixadmin/blob/eb61141d2fbf9ba18e0b20fa8fe730bc5c81540e/functions.inc.php#L1920)
> is a bit fragile...
>

I agree.

Cheers
  Mike
