### ISSUE TITLE
installation with php7 fails - php5 EOL

### ISSUE THREAD

**Issue by planet-winter** [postfixadmin/postfixadmin#237]
**Description:**

Installation on FreeBSD 12.0 from ports fails with 
```
DEBUG INFORMATION:
PostgreSQL functions not available! (php5-pgsql installed?)
database_type = 'pgsql' in config.inc.php, are you using a different database?
...
```
Used FreeBSD Ports version is based on postfixadmin 3.2 with PGSQL enabled
```
#pkg info postfixadmin
postfixadmin-3.2_2
Name           : postfixadmin
Version        : 3.2_2
...
Options        :
        DOCS           : on
        MYSQL          : off
        PGSQL          : on
        SQLITE         : off
```
and php73-pgsql installed
```
#pkg info php73-pgsql
php73-pgsql-7.3.1_1
```
output of setup.php?debug=1
```
Postfix Admin Setup Checker

Running software:

    PHP version 7.3.1

Checking for dependencies:

    Magic Quotes: Disabled - OK
    Depends on: presence config.inc.php - OK
    Checking $CONF['configured'] - OK
    Depends on: presence config.local.php - OK
    Depends on: SQLite - OK
    (change the database_type to 'sqlite' in config.local.php if you want to use SQLite)
    Error: Can't connect to database
    Please edit the $CONF['database_*'] parameters in config.local.php.

    DEBUG INFORMATION:
    PostgreSQL functions not available! (php5-pgsql installed?)
    database_type = 'pgsql' in config.inc.php, are you using a different database?
    Depends on: session - OK
    Depends on: pcre - OK
    Error: Depends on: multibyte string - NOT FOUND
    To install multibyte string support, install php5-mbstring
    Warning: Depends on: IMAP functions - NOT FOUND
    To install IMAP support, install php5-imap
    Without IMAP support, you won't be able to create subfolders when creating mailboxes.

Please fix the errors listed above.
```
PHP5 is End Of Life see: http://php.net/supported-versions.php

**Expected behaviour:**

 - postfixadmin should check installed library/package against higher php versions as well
 - Postfixadmin should support a current PHP version

**Comment by DavidGoodwin** [comment]
* What's the output of 'php -m' -> is the 'pgsql' module listed? Is 'mbstring' listed?
 * Yes, we know PHP5 is EOLed - the current master variant of postfixadmin does moan at you a little if you're using PHP5 - see https://github.com/postfixadmin/postfixadmin/blob/master/public/setup.php#L73

**Comment by planet-winter** [comment]
Thanks @DavidGoodwin for your prompt answer

the module is installed:
```
# php -m | grep pgsql
pgsql
# php -m | grep mbstring
mbstring
```
Sifted through the code and started to try to get master running on Freebsd12 but have to continue later.

**Comment by DavidGoodwin** [comment]
Can I close this?

**Comment by DavidGoodwin** [comment]
see also : https://sourceforge.net/p/postfixadmin/discussion/676076/thread/5919fdea6e/?limit=25

**Comment by WeebHiroyuki** [comment]
I can reproduce this. Was there ever a fix to it?

**Comment by DavidGoodwin** [comment]
@WeebHiroyuki - What variant of Postfixadmin are you using?
