### ISSUE TITLE
vacation.conf did not return a true value

### ISSUE THREAD

**Issue by VersusBG** [postfixadmin/postfixadmin#238]
in vacation.conf if i set $smtp_ssl = ''; i got error "did not return a true value". The require function from vacation.pl  that invoke vacation.conf file expect a true value so at the end of the vacation.conf file i added 1; which accept the empty variable for $smpt_ssl

Command died with status 255: "/usr/local/lib/postfixadmin/vacation.pl". Command output: /etc/mail/postfixadmin/vacation.conf did not return a true value at /usr/local/lib/postfixadmin/vacation.pl line 129. 

http://perldoc.perl.org/functions/require.html

**Comment by DavidGoodwin** [comment]
We don't ship a sample vacation.conf as far as I know - the vacation.pl code just says something woolly (https://github.com/postfixadmin/postfixadmin/blob/master/VIRTUAL_VACATION/vacation.pl#L127). 

I suppose "just use Perl syntax there ...." is not obvious.

**Comment by VersusBG** [comment]
I was following INSTALL.md 
https://github.com/postfixadmin/postfixadmin/blob/master/VIRTUAL_VACATION/INSTALL.md

I needed to disable starttls because of another error and found out that setting $smtp_ssl = '' in the configuration file return that error, but editing directly in vacation.pl file works. So i start reading how .conf file is included in vacation.pl and found similar threads that the conf file have to end with 1; like this:

```
$smtp_ssl = '';
1;
```

Which is not specified in the  INSTALL.md and it's not easy to figured out. 
Using the default 'starttls' give me another error that's is most likely not related with postfixadmin but it's caused by openssl and Email::Sender::Transport::SMTP on FreeBSD 11.2-RELEASE-p8 with OpenSSL 1.0.2o-freebsd

warning: TLS library problem: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:/usr/src/crypto/openssl/ssl/s3_pkt.c:1498:SSL alert number 80:

**Comment by DavidGoodwin** [comment]
https://github.com/postfixadmin/postfixadmin/commit/63f63a58b77c2b2a5861f4c02cd48e7ad92161ad then! :)

thanks!
David.
