### ISSUE TITLE
Error "Modifying the alias failed" when I try to change email password

### ISSUE THREAD

**Issue by oukb** [postfixadmin/postfixadmin#239]
Hi

I can't change the password on the email from administrator.
Error - "Modifying the alias email@domain failed!"

But the password can be changed if login as user and new boxes are created without errors.
Error logs was empty.

PHP 7.2.14+fastcgi(or php 7.2.14 as apache module) and postfixadmin from master.
Git version from 18 November working without errors from web and from cli.

Could you help me to debug and fix it ?

**Comment by oukb** [comment]
```
bash-4.2$ ./postfixadmin-cli mailbox add test4@domain.com

Welcome to Postfixadmin-CLI v0.2
---------------------------------------------------------------
PHP Warning:  A non-numeric value encountered in /var/www/postfixadmin_dir/model/MailboxHandler.php on line 221

Warning: A non-numeric value encountered in /var/www/postfixadmin_dir/model/MailboxHandler.php on line 221

Password: vLx3948NXU5R
The mailbox test4@domain.com has been added to the mailbox table.

---------------------------------------------------------------
bash-4.2$
bash-4.2$
bash-4.2$ ./postfixadmin-cli mailbox update test4@domain.com

Welcome to Postfixadmin-CLI v0.2
---------------------------------------------------------------
Error: Modifying the alias test4@domain.com failed!
```


PHP 7.2.15, MySQL 8.0 and MariaDB 10.2, branch master
I tried my previous copy from backup (~2 month ago, with mysqli_real_connect, before PDO) and it's worked.

```
bash-4.2$
bash-4.2$ ./postfixadmin-cli mailbox update test4@att.org.ru

Welcome to Postfixadmin-CLI v0.2
---------------------------------------------------------------

The mailbox test4@domain.com has been updated.

---------------------------------------------------------------
```


what could be the cause of the error?

**Comment by fedelebrero** [comment]
Same issue here.

My system info:
- CentOS 7.6
- php 7.2.15 (mod_php)
- MariaDB 10.2

I've also tried with same results:
- CentOS 7.6
- php 7.1.26 (mod_php)
- MariaDB 5.5 & 5.6

I'm getting this error since postfixadmin added support for password expiration.

**Comment by DavidGoodwin** [comment]
Is there anything logged to wherever PHP has it's error_log set? e.g. Web server error log file?

**Comment by DavidGoodwin** [comment]
can you retest with master now?

**Comment by oukb** [comment]
Working with latest master, thanks

**Comment by DavidGoodwin** [comment]
@oukb thank you for confirming :)
