### ISSUE TITLE
Invalid token!

### ISSUE THREAD

**Issue by flatonfloor** [postfixadmin/postfixadmin#240]
Hi! 

I'm gettin `invalid token!` when i try to log in. PFA installed succecfully, without any issue. 

CeontOS, apache, mariadb, PFA 3.2

**Comment by DavidGoodwin** [comment]
That probably implies there is some sort of problem with your server's PHP session storage. 

Are you using multiple web servers behind some sort of load balancer?
Do PHP sessions work?

```
<?php
session_start();
$_SESSION['test'] += 1;
var_dump($_SESSION['test']);
````

Refreshing a page containing that should show an increasing number. I suspect it won't for you. You probably need to check PHP's configuration file (session.save_path ?) and make sure that location on disk is writeable?

**Comment by flatonfloor** [comment]
> Refreshing a page containing that should show an increasing number. I suspect it won't for you. You probably need to check PHP's configuration file (session.save_path ?) and make sure that location on disk is writeable?

PHP session works, number increesing, location is writeable, but i'm still gettin' `invalid token` message.

**Comment by DavidGoodwin** [comment]
```if (safepost('token') != $_SESSION['PFA_token']) {```

Somehow whatever is in $_POST['token'] is not matching what's in $_SESSION['PFA_token'].

This is possible if somehow the session storage isn't working, or your browser is blocking cookies.

**Comment by DavidGoodwin** [comment]
token's expire after an hour; is it possible yours is just old?

**Comment by flatonfloor** [comment]
> token's expire after an hour; is it possible yours is just old?

Definitely no. I decided not use PFA, but i'm pretty sure there's something wrong with server configuration, not with PFA. Anyway thanks a lot for spending time trying' help me.

**Comment by DavidGoodwin** [comment]
https://sourceforge.net/p/postfixadmin/discussion/676076/thread/70ed9843c0/?limit=25

Perhaps it's a timezone issue?

**Comment by DavidGoodwin** [comment]
```For the record: I'm on Arch Linux, where apparently the php function date_default_timezone_get() returned UTC (don't know why, may be my fault in the setup but that's what it did). Since the machine is on Europe/Berlin timezone (GMT+2), the token_validity - which is supposed to be set 1 hour in the future - was set to 1 hour in the past.

Setting the correct "date.timezone = 'Europe/Berlin'" in php.ini (/etc/php/php.ini) and restarting php-fpm (systemctl restart php-fpm) resolved the issue.```

**Comment by flatonfloor** [comment]
Thank you.
