### ISSUE TITLE
Error creating email account

### ISSUE THREAD

**Issue by FlorianneRaven** [postfixadmin/postfixadmin#241]
Invalid query: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: 'now() + interval 0 day' for column `postfixadmin`.`mailbox`.`password_expiry` at row 1 caused by INSERT INTO `mailbox` (username,local_part,domain,maildir,password,name,quota,active,phone,email_other,token,token_validity,created,modified,password_expiry) VALUES (:username,:local_part,:domain,:maildir,:password,:name,:quota,:active,:phone,:email_other,:token,:token_validity,now(),now(),:password_expiry),

Centos 7.6
php 7.3
Mariadb 10.3.12

so it create only aliases, not mailboxes/email account

**Comment by FlorianneRaven** [comment]
after changing it to:

$values['password_expiry'] = date('Y-m-d H:i:s', strtotime("now + 3 years"));

seems working with mariadb

**Comment by DavidGoodwin** [comment]
Yeah, I've changed the code to do something like this now - see https://github.com/postfixadmin/postfixadmin/commit/9cc04df973f3146bd954b1d4fef9d8c7018e8eb2 

Sorry for not spotting your ticket - I should have referenced it in the commit but hadn't remembered/realised it was here.

**Comment by DavidGoodwin** [comment]
@Liionboy what version of PostfixAdmin are you using?

**Comment by Liionboy** [comment]
I fixed after i see on Domain List was at Pass Expired 999999 not 9999
