### ISSUE TITLE
invalid connection option "charset"

### ISSUE THREAD

**Issue by rayfun** [postfixadmin/postfixadmin#243]
Hi,

I'm using Postfixadmin from git master and after a recent pull it stopped working with the below error message in my Apache server log.

I'm using PostgreSQL db at version 9.5.14.

To fix it, without any further knowledge about the inner workings, I just removed the charset part from the dsn in functions.inc.php:1493 and it worked.

Please also see my config.local.php further below. (I've removed all sensitive info from it)

Best regards,
Rayfun

`[Sat Feb 09 10:52:11.151094 2019] [proxy_fcgi:error] [pid 20227:tid 140381224113920] [client 77.182.89.197:55968] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[08006] [7] invalid connection option "charset" in /var/www/html/vhosts/prod/postfixadmin/functions.inc.php:1499\nStack trace:\n#0 /var/www/html/vhosts/prod/postfixadmin/functions.inc.php(1499): PDO->__construct('pgsql:host=loca...', 'mail', 'bXsyNfEYX1IHttb...', Array)\n#1 /var/www/html/vhosts/prod/postfixadmin/functions.inc.php(1446): db_connect_with_errors()\n#2 /var/www/html/vhosts/prod/postfixadmin/functions.inc.php(1655): db_connect()\n#3 /var/www/html/vhosts/prod/postfixadmin/functions.inc.php(1627): db_query('SELECT value FR...', Array)\n#4 /var/www/html/vhosts/prod/postfixadmin/functions.inc.php(1982): db_query_one('SELECT value FR...')\n#5 /var/www/html/vhosts/prod/postfixadmin/public/login.php(37): check_db_version()\n#6 {main}\n  thrown in /var/www/html/vhosts/prod/postfixadmin/functions.inc.php on line 1499\n'`

```
<?php
$CONF['configured'] = true;
$CONF['database_type'] = 'pgsql';
$CONF['database_user'] = 'mail';
$CONF['database_name'] = 'mail';
$CONF['domain_path'] = 'YES';
$CONF['domain_in_mailbox'] = 'NO';
$CONF['aliases'] = '0';
$CONF['mailboxes'] = '0';
$CONF['maxquota'] = '0';
$CONF['show_footer_text'] = 'NO';
$CONF['password_validation'] = array(
#    '/regular expression/' => '$PALANG key (optional: + parameter)',
    '/.{8}/'                => 'password_too_short 5',      # minimum length 5 characters
    '/([a-zA-Z].*){3}/'     => 'password_no_characters 3',  # must contain at least 3 characters
    '/([0-9].*){1}/'        => 'password_no_digits 2',      # must contain at least 2 digits
);
$CONF['page_size'] = '25';
$CONF['show_header_text'] = 'YES';
$CONF['theme'] = 'bootstrap';
$CONF['theme_css'] = 'css/bootstrap.css';
?>
```

```
diff --git a/functions.inc.php b/functions.inc.php
index a6de101..695babe 100644
--- a/functions.inc.php
+++ b/functions.inc.php
@@ -1490,7 +1490,7 @@ function db_connect_with_errors() {
         if (!isset($CONF['database_port'])) {
             $CONF['database_port'] = '5432';
         }
-        $dsn = "pgsql:host={$CONF['database_host']};port={$CONF['database_port']};dbname={$CONF['database_name']};charset=UTF8";
+        $dsn = "pgsql:host={$CONF['database_host']};port={$CONF['database_port']};dbname={$CONF['database_name']}";
     } else {
         die("<p style='color: red'>FATAL Error:<br />Invalid \$CONF['database_type']! Please fix your config.inc.php!</p>");
     }
```

**Comment by DavidGoodwin** [comment]
Does this work? ^

**Comment by rayfun** [comment]
Yes. :-)

**Comment by rayfun** [comment]
Yes! Thank you!

**Comment by DavidGoodwin** [comment]
Thanks for confirming it.
