### ISSUE TITLE
Missing files in source tree

### ISSUE THREAD

**Issue by babykart** [postfixadmin/postfixadmin#247]
Hi,

There are missing files between tag 3.1 and 3.2: login.php, sendmail.php, setup.php ...
Same problem with sf's archives.

**Comment by DavidGoodwin** [comment]
you did check the public/ folder, right?

**Comment by babykart** [comment]
No. :/
And obviously I haven't read the changelog that describes this tree structure modification... -_-
Sorry for the noise.
And thank you for your 'job' ...

**Comment by DavidGoodwin** [comment]
Hah; it's fine - it's a quick fix thankfully .... ;-)
