### ISSUE TITLE
PHP IMAP extension unmaintained, replace with PHP implementation?

### ISSUE THREAD

**Issue by hcderaad** [postfixadmin/postfixadmin#251]
First of all thanks for creating this extremely useful application! I have one issue with the current installation routine, that is that the php-imap extension appears to have been abandoned by its maintainers and distro's like openSUSE no longer ship it.
https://wiki.php.net/todo/extensions#imap
https://bugzilla.opensuse.org/show_bug.cgi?id=1089061#c18

Roundcube and other mail apps appear to have moved to a custom PHP IMAP protocol implementation using the generic sockets extension. 

Would it be possible to consider replacing this unmaintained dependency to a similar solution?
https://github.com/roundcube/roundcubemail/blob/82974289b98d2d00251e55f1719c4522598d7ef5/program/lib/Roundcube/rcube_imap_generic.php 

I'd be happy to help out in testing, fwiw!

**Comment by DavidGoodwin** [comment]
I'm failing to spot many (if any) pure PHP based packages on packagist which handle imap.

As far as I can (quickly) see, PostfixAdmin only has the imap extension for creating initial folders within a new account; and that's only if the appropriate config setting (create_mailbox_subdirs) is present.

The roundcube code you've linked to does allow for folder creation, subscription and retrieval of the hierarchical separator so it could potentially be used.

**Comment by hcderaad** [comment]
@DavidGoodwin Initial folder creation can be done through an IMAP server extension like Dovecot autocreation: https://wiki.dovecot.org/MailboxSettings 
Does PostfixAdmin do anything other than initial creation?
Perhaps it might be less effort to simply drop the functionality from PA and no longer have php-imap as a dependency?

**Comment by DavidGoodwin** [comment]
I think you may be right - however while autocreation within Dovecot would be a better solution, it probably doesn't help anyone using courier or some other backend.

**Comment by hcderaad** [comment]
At least Dovecot and Cyrus have auto creation capabilities (I use them both in production intensively). Courier I am not sure, but I'd guess that it might have a similar approach.

**Comment by mc0e** [comment]
It might be helpful to say in the warning given by setup.php that users of some IMAP servers (Dovecot, Cyrus) can safely ignore this in postfixadmin and let their IMAP server create the skeleton mailbox structure.
