### ISSUE TITLE
Feature Request: Dovecot local_name certs for virtual domains

### ISSUE THREAD

**Issue by CoryGH** [postfixadmin/postfixadmin#256]
At [https://wiki.dovecot.org/SSL/DovecotConfiguration](https://wiki.dovecot.org/SSL/DovecotConfiguration) in the Dovecot documentation it specifies the notation:

```
local_name imap.example.org {
  ssl_cert = </etc/ssl/certs/imap.example.org.crt
  ssl_key = </etc/ssl/private/imap.example.org.key
}
local_name imap.example2.org {
  ssl_cert = </etc/ssl/certs/imap.example2.org.crt
  ssl_key = </etc/ssl/private/imap.example2.org.key
}
# ..etc..
```

For client TLS SNI - the format doesn't seem to lend itself to integration via SQL calls, but that might well be my own misunderstanding of the Dovecot configuration file syntax.

**Comment by DavidGoodwin** [comment]
This is a dovecot configuration problem ... I'm not sure it falls into the "remit" of Postfixadmin.
