### ISSUE TITLE
Broadcast Message is not being sent.

### ISSUE THREAD

**Issue by hendrikzuellig** [postfixadmin/postfixadmin#257]
I was trying to use the Broadcast function of the postfixadmin Webgui but the mails never arrived.
I think the following log is relevant but I cant make any sense of it.
My mail setup is based on [the Docker hardware/mailserver](https://github.com/hardware/mailserver)

`2019-03-20T08:03:33.041170+00:00 mail postfix/smtpd[26391]: NOQUEUE: reject: RCPT from unknown[172.x.0.x]: 553 5.7.1 <postfixadmin@domain.com>: Sender address rejected: not logged in; from=<postfixadmin@domain.com> to=<anouk.ugolini@domain.com> proto=ESMTP helo=<mail.domain.com>
2019-03-20T08:03:33.041649+00:00 mail postfix/smtpd[26391]: warning: non-SMTP command from unknown[172.x.0.x]: To: user@domain.com
2019-03-20T08:03:33.042139+00:00 mail postfix/smtpd[26391]: disconnect from unknown[172.x.0.x] ehlo=1 mail=1 rcpt=0/1 data=0/1 unknown=0/1 commands=2/5
2019-03-20T08:03:33.043669+00:00 mail postfix/smtpd[26391]: connect from unknown[172.x.0.x]`

**Comment by DavidGoodwin** [comment]
Sorry; I managed to miss this. I suspect your postfix instance isn't configured with the webserver as a trusted host (not listed in mynetworks or similar).

**Comment by AlphaJack** [comment]
For me I also needed to:

```ini
# 1. comment out these two restrictions if present
smtpd_helo_restrictions =
    [...]
    #reject_non_fqdn_helo_hostname,
    #reject_unknown_helo_hostname

# 2. set this to "may" instead of "encrypt"
smtpd_tls_security_level = may
```

**Comment by DavidGoodwin** [comment]
(I suspect really we should be using one of the PHP SMTP libraries to send out mail - so we handle ssl / tls correctly etc etc ... rather than our naive approach to speaking SMTP to the mail server - https://github.com/postfixadmin/postfixadmin/blob/d391847ed98311c607857be175088fe25a701480/functions.inc.php#L1412 )
