### ISSUE TITLE
How can I add admin user in postfix.admin

### ISSUE THREAD

**Issue by forrotransfer** [postfixadmin/postfixadmin#261]
Hello,
We are using in our company postfix.admin v 2.3.6
The person who installed the application is not working any more in our co. We need to create another admin user. I attached a picture with the login screen.
May anybody help us?
Thank you for your support,

**Comment by DavidGoodwin** [comment]
Hi - go to https://xxxxxxxxx/postfixadmin/setup.php - in there you can generate a new 'setup' password. 

You'll see something like : ```
$CONF['setup_password'] = 'e92df810317434d465301dd337682d9f:e76cf263108da17bd8d74018aa0900c961ec1502';
``` 

You need to put that into the config.inc.php (perhaps) or config.local.php (better) file. That might be in somewhere like /etc/postfixadmin on the server.

Once that's done, you can use setup.php to create a new admin account (the Create superadmin account form is only shown after you've submitted the form with something in).

**Comment by forrotransfer** [comment]
thank you for your response. I looked into setup.php and I did not find $CONF['setup_password'] = 
Brgds,

**Comment by DavidGoodwin** [comment]
sorry; i screwed up my formatting; does it make more sense now?

**Comment by forrotransfer** [comment]
Sorry, but I do not understand: in setup.php i do not find the field $CONF['setup_password'] =
I must put it manually in the file setup.php?
When i try to  access https://xxxxxxxxx/postfixadmin/setup.php the message is: Forbidden
You don't have permission to access /postfixadmin/setup.php on this server.
brgds,

**Comment by DavidGoodwin** [comment]
Look in **config.inc.php** (perhaps) or **config.local.php** (better) file.

**Comment by forrotransfer** [comment]
I found the field: $CONF['setup_password'] ='85b.........' in the config.local.php
What should I do?

**Comment by DavidGoodwin** [comment]
As I said above, change it .... to a newly generated value that you know. 

The setup.php page will generate a setup password for you if you from the 'Change setup password' form (just type a new one into each box and click 'Generate password hash'). This will output what you need to put in your $CONF['setup_password'] entry (along with instructions)

Then use that setup password to create a superadmin account using the form that's shown to you. In the screenshot attached I used something like 'asdf123' 

![postfixadmin-setup](https://user-images.githubusercontent.com/203929/55620442-ceed2300-5792-11e9-9f8c-ce04367e6898.png)

**Comment by forrotransfer** [comment]
When i try to access   https://xxxxxxxxx/postfixadmin/setup.php, the result is:
Forbidden
You don't have permission to access /postfixadmin/setup.php on this server.

How can i change the password if i can not access https://xxxxxxxxx/postfixadmin/setup.php?

**Comment by DavidGoodwin** [comment]
Check the web server config (and look for a .htaccess file too).

**Comment by forrotransfer** [comment]
Hello ,
May I open the below issue?
Thx

**Comment by forrotransfer** [comment]
Hello David, 
First of all thank you for re opening the tkt.
I did not manage to resolve the issue regarding adding user in our postfix.admin application. I still get the following answer when I try to open  https://xxxxxxxxx/postfixadmin/setup.php
Answer:
Forbidden
You don't have permission to access /postfixadmin/setup.php on this server.
I found a .htcaccess file:
![image](https://user-images.githubusercontent.com/49266813/79217440-895c3f00-7e57-11ea-9e71-a704aeef7082.png)

I did not mention that I m a beginner in Linux enviroment.
Thank you for your support,

**Comment by DavidGoodwin** [comment]
Sorry; I missed this.

Update your .htaccess file and change the line that currently says : 
```
RewriteRule ^/?(README(.md) ?|INSTALL|LICENSE|CHANGELOG|UPGRADING|setup.php)$ - [F]
```

with

```
RewriteRule ^/?(README(.md) ?|INSTALL|LICENSE|CHANGELOG|UPGRADING)$ - [F]
```

and you should be able to access setup.php (i.e. remove `|setup.php` )

**Comment by forrotransfer** [comment]
Hello David,
It worked. Thank you for your support

**Comment by 0x00002152** [comment]
what a piece of shit

**Comment by 0x00002152** [comment]
it doesn't seem to like my email address email address 
![image](https://user-images.githubusercontent.com/60234097/85906107-da47c680-b7fc-11ea-83b2-69ed07620d10.png)

**Comment by 0x00002152** [comment]
is there an alternative way I can not do this shit and still somehow use this php script?

**Comment by 0x00002152** [comment]
ok this is what you need to start telling people: 

HOW 2 FIXX 

```
root@postfixadmin:/var/www/html# echo "\$CONF['encrypt'] = 'md5';" >> config.inc.php 
```
```
UPDATE `admin` SET `password` = MD5('password') WHERE `admin`.`username` = 'root@localhost'; 
```

**Comment by DavidGoodwin** [comment]
> it doesn't seem to like my email address email address
> ![image](https://user-images.githubusercontent.com/60234097/85906107-da47c680-b7fc-11ea-83b2-69ed07620d10.png)

At a guess, I would suspect your computer has problems performing DNS lookups.
