### ISSUE TITLE
Cannot change password - Syntax Error (PGSQL)

### ISSUE THREAD

**Issue by rayfun** [postfixadmin/postfixadmin#264]
Hi,

On a PGSQL-based installation on an uptodate git master changing a user's mailbox password fails:

`[Sat Apr 13 15:29:07.146118 2019] [proxy_fcgi:error] [pid 16595:tid 140282096305920] [client 77.185.205.184:39198] AH01071: Got error 'PHP message: Invalid query: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "0"\nLINE 1: ..._expiry = $6 , password_expiry = now() + interval 0 day WHER...\n                                                             ^ caused by UPDATE mailbox SET  password = :password , name = :name , quota = :quota , active = :active , email_other = :email_other , password_expiry = :password_expiry , password_expiry = now() + interval 0 day WHERE username = :where', referer: https://xxx.de/mailadmin/edit.php?table=mailbox&edit=xxx%40xxx.de`

Best regards,
rayfun

**Comment by rayfun** [comment]
@DavidGoodwin any ideas here? another PGSQL related issue like #227 ? thanks a lot!

**Comment by DavidGoodwin** [comment]
I think this is fixed.

**Comment by rayfun** [comment]
Fixed! Thanks!
