### ISSUE TITLE
Error: Creating the mailbox failed!

### ISSUE THREAD

**Issue by oukb** [postfixadmin/postfixadmin#266]
Hi

Latest master, PHP 7.2.17, MySQL 8.0.15

This errors, when I tried to add mailbox:
```
Invalid query: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime
 value: '' for column 'password_expiry' at row 1 caused by INSERT INTO `mailbox` (username,local_part,domain,maildir,password,name,quota,active,phone,email_other,token,t
oken_validity,created,modified,password_expiry) VALUES (:username,:local_part,:domain,:maildir,:password,:name,:quota,:active,:phone,:email_other,:token,:token_validity,
now(),now(),:password_expiry), referer: http://postfixadmin/edit.php?table=mailbox&domain=domain.com
```
```
[Tue Apr 16 03:10:50.408199 2019] [php7:notice] [pid 3331] [client 1.1.1.1:37592] PHP Notice:  Undefined index: conf in /var/www/postfixadmin/templates_c/f3f745418159c81e423495d18f080bfc035d50c0_0.file.list.tpl.php on line 184, referer: http://postfixadmin/list-virtual.php
[Tue Apr 16 03:10:50.408201 2019] [php7:notice] [pid 3331] [client 1.1.1.1:37592] PHP Notice:  Trying to get property 'value' of non-object in /var/www/postfixadmin/templates_c/f3f745418159c81e423495d18f080bfc035d50c0_0.file.list.tpl.php on line 184, referer: http://postfixadmin/list-virtual.php
```
And tried to clean cache.

The same error with cli.

```
Invalid query: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'password_expiry' at row 1 caused by INSERT INTO `mailbox` (username,local_part,domain,maildir,password,name,quota,active,phone,email_other,token,token_validity,created,modified,password_expiry) VALUES (:username,:local_part,:domain,:maildir,:password,:name,:quota,:active,:phone,:email_other,:token,:token_validity,now(),now(),:password_expiry)
Error: Creating the mailbox test@domain.com failed!
```

Could you help me to fix it ?

**Comment by Neurozone** [comment]
See this :

https://github.com/postfixadmin/postfixadmin/issues/241

https://github.com/postfixadmin/postfixadmin/commit/9cc04df973f3146bd954b1d4fef9d8c7018e8eb2

**Comment by oukb** [comment]
Same errors after latest commits

[Sat Jun 08 23:22:24.762153 2019] [php7:notice] [pid 16764] [client 1.1.1.1:45318] PHP Notice:  Undefined index:
conf in /var/www/postfixadmin/templates_c/6515bbb620e36542a104b51b05837a500c416d52_0.file.list-virtual_mailbox.tpl.php on line 116, referer: http://postfixadmin/list.php?table=domain
[Sat Jun 08 23:22:24.762176 2019] [php7:notice] [pid 16764] [client 1.1.1.1:45318] PHP Notice:  Trying to get property 'value' of non-object in /var/www/postfixadmin/templates_c/6515bbb620e36542a104b51b05837a500c416d52_0.
file.list-virtual_mailbox.tpl.php on line 116, referer: http://postfixadmin/list.php?table=domain
[Sat Jun 08 23:22:39.556309 2019] [php7:notice] [pid 18279] [client 1.1.1.1:45768] Invalid query: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'password_expiry' at row 1 caused by INSERT INTO `mailbox` (username,local_part,domain,maildir,password,name,quota,active,phone,email_other,token,token_validity,created,modified,password_expiry) VALUES (:username,:local_part,:domain,:maildir,:password,:name,:quota,:active,:phone,:email_o
ther,:token,:token_validity,now(),now(),:password_expiry), referer: http://postfixadmin/edit.php?table=mailbox&domain=domain.com

**Comment by DavidGoodwin** [comment]
Can you confirm what version you're using please?

I thought https://github.com/postfixadmin/postfixadmin/commit/03b94832049f91863dbfd96016364328c97a7215 would have fixed this problem

**Comment by oukb** [comment]
Yes, I tried lastest master, removed all files from templates_c
No problem with aliases, only with adding mailboxes

`$CONF['password_expiration'] = 'NO';`

./postfixadmin-cli mailbox add test@domain.com
PHP Warning:  A non-numeric value encountered in /var/www/mon/data/www/post.aeh.ru/model/MailboxHandler.php on line 225

Warning: A non-numeric value encountered in /var/www/postfixadmin/model/MailboxHandler.php on line 225
Invalid query: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'password_expiry' at row 1 caused by INSERT INTO `mailbox` (username,local_part,domain,maildir,password,name,quota,active,phone,email_other,token,token_validity,created,modified,password_expiry) VALUES (:username,:local_part,:domain,:maildir,:password,:name,:quota,:active,:phone,:email_other,:token,:token_validity,now(),now(),:password_expiry)
Error: Creating the mailbox test@domain.com failed!

How I can turn on full debug for more information ?

PHP 7.2.19 (FastCGI or module)
MySQL 8.0.15


Notice: Undefined index: conf in `/var/www/postfixadmin/templates_c/6515bbb620e36542a104b51b05837a500c416d52_0.file.list-virtual_mailbox.tpl.php on line 116`

**Comment by DavidGoodwin** [comment]
Normally enough (error wise) is written to the PHP error_log file or to Apache's error log.

Are you really really sure you're running the latest code from 'master' - as mailbox creation is working for me on my test system (PHP 7.2 + Maria DB 10.2 from Debian Stretch).

I have $CONF['password_expiration'] set to false (or NO).

```
MariaDB [postfixadmin]> select * From mailbox where username = 'bob1@test.com' \G
*************************** 1. row ***************************
       username: bob1@test.com
  ....
        created: 2019-06-10 20:18:19
       modified: 2019-06-10 20:18:19
         active: 1
 ..... 
          token: 
 token_validity: 2019-06-10 20:18:19
password_expiry: 2020-06-09 20:18:00
```

So valid values are being given to password_expiry.

model/MailboxHandler.php should contain this change at around line 260

https://github.com/postfixadmin/postfixadmin/commit/03b94832049f91863dbfd96016364328c97a7215

**Comment by oukb** [comment]
With this error added only alias

I enabled MySQL logging:

1. "old" version> working:

2019-06-10T22:03:07.969154Z      5488 Query     INSERT INTO `alias` (address,domain,goto,created,modified,active) VALUES
('test@domain.com','domain.com','test@domain.com',now(),now(),'1')
2019-06-10T22:03:08.067771Z      5488 Query     INSERT INTO `log` (username,domain,action,data,timestamp) VALUES ('admin@admindomain.com (1.1.1.1)','domain.com','create_alias','test@domain.com',now())
2019-06-10T22:03:08.153075Z      5488 Query     INSERT INTO `mailbox` (username,local_part,domain,maildir,password,name,
quota,active,phone,email_other,token,token_validity,created,modified) VALUES ('test@domain.com','test','domain.com','domain.com/test@domain.com/','{CRYPT}$2.........','test','10240000','1','','','','
2019-06-11 01:03:07',now(),now())
2019-06-10T22:03:08.210033Z      5488 Query     INSERT INTO `log` (username,domain,action,data,timestamp) VALUES ('log1@
bk.ru (1.1.1.1)','domain.com','create_mailbox','test@domain.com',now())

2. latest master (with two commits)

2019-06-10T22:18:11.226091Z      5510 Query     INSERT INTO `alias` (address,domain,goto,created,modified,active) VALUES ('test3@domain.com','domain.com','test3@domain.com',now(),now(),'1')
2019-06-10T22:18:11.318951Z      5510 Query     INSERT INTO `log` (username,domain,action,data,timestamp) VALUES ('admin@admindomain.com (1.1.1.1)','domain.com','create_alias','test3@domain.com',now())
2019-06-10T22:18:11.419588Z      5510 Query     INSERT INTO `mailbox` (username,local_part,domain,maildir,password,name,quota,active,phone,email_other,token,token_validity,created,modified,password_expiry) VALUES ('test3@domain.com','test3','domain.com','domain.com/test3@domain.com/','{CRYPT}$2.........','test3','10240000','1','','','','2019-06-11 01:18:10',now(),now(),'')
2019-06-10T22:18:11.464845Z      5510 Quit

**Comment by DavidGoodwin** [comment]
I'm having trouble replicating this. Please can you state the git hash of the code you're running (```git show``` in the postfixadmin directory).

If you can, could you also use your browser's Network Inspector to record a curl request of the mailbox creation you're trying to issue. I don't need any cookies, and make sure you overwrite any password field value if necessary.

Finally, can you confirm that you have : 

```$CONF['password_expiration'] = 'NO'; ``` (or boolean false) in config.local.php

**Comment by oukb** [comment]
I created new folder, git clone ...
created new db

```
$ git show
commit ae476950f29ab2dd27e47dbf4792e75d008a2a23
Author: David Goodwin <david@codepoets.co.uk>
Date:   Mon Jun 10 20:14:50 2019 +0100

    try and avoid smarty complaining about no variable $conf - see https://github.com/postfixadmin/postfixadmin/issues/2

diff --git a/templates/list-virtual_mailbox.tpl b/templates/list-virtual_mailbox.tpl
index c0cad18..f466b5e 100644
--- a/templates/list-virtual_mailbox.tpl
+++ b/templates/list-virtual_mailbox.tpl
@@ -60,9 +60,9 @@
                                        {if $boolconf_used_quotas}


-                                               {if $divide_quota.quota_width[$i] > $conf.quota_level_high_pct}
+                                               {if $divide_quota.quota_width[$i] > $CONF.quota_level_high_pct}
                                                        {assign var="quota_level" value="high"}
-                                               {elseif $divide_quota.quota_width[$i] > $conf.quota_level_med_pct}
+                                               {elseif $divide_quota.quota_width[$i] > $CONF.quota_level_med_pct}
                                                        {assign var="quota_level" value="mid"}
                                                {else}
                                                        {assign var="quota_level" value="low"}
```

I confirm, that $CONF['password_expiration'] = 'NO'; 


And...
Working, when I set both password fields...

2019-06-11T19:09:02.556257Z      6603 Query     INSERT INTO `alias` (address,domain,goto,created,modified,active) VALUES ('test4@domain.com','domain.com','test4@domain.com',now(),now(),'1')
2019-06-11T19:09:02.654679Z      6603 Query     INSERT INTO `log` (username,domain,action,data,timestamp) VALUES ('admin@admindomain.com (1.1.1.1)','domain.com','create_alias','test4@domain.com',now())
2019-06-11T19:09:02.817646Z      6603 Query     INSERT INTO `mailbox` (username,local_part,domain,maildir,password,name,quota,active,phone,email_other,token,token_validity,created,modified,password_expiry) VALUES ('test4@domain.com','test4','domain.com','domain.com/test4@domain.com/','{CRYPT}$2.............','test4','10240000','1','','','','2019-06-11 22:09:01',now(),now(),'2020-06-10 22:09')
2019-06-11T19:09:02.927854Z      6603 Query     INSERT INTO `log` (username,domain,action,data,timestamp) VALUES ('admin@admindomain.com (1.1.1.1)','domain.com','create_mailbox','test4@domain.com',now())


I'm used postfixadmin's passwords generator...

**Comment by DavidGoodwin** [comment]
Ah hah - I had forgotten there was a 'generate_password' config feature - thanks for pointing me at that :)

I've also changed the form so it won't display the password box if you've set generate_password = YES in the config file. That feels like the right setting to me anyway....

**Comment by DavidGoodwin** [comment]
(Should be fixed, please re-test)

**Comment by oukb** [comment]
))))))))))
Working, thanks!
//future request :)
But maybe return an opportunity to generate a password if the fields are not filled(only when $CONF['generate_password'] = 'YES'; ).

**Comment by DavidGoodwin** [comment]
Yes, I did consider this ... and if I could figure out how to add a blurb of text to the password field to say something useful like "If left blank, a password will be generated" it might be a better way.
