### ISSUE TITLE
No user is created

### ISSUE THREAD

**Issue by DevScyu** [postfixadmin/postfixadmin#267]
I followed the postfix and dovecot guides and can't get this thing to work.

I believe the postfix side is all good as i can manage aliases through the admin panel, but i can't create new mailboxes so i think there is something wrong with my dovecot.

I can upload the files i am using if someone could help ;-;

**Comment by DevScyu** [comment]
Running on Centos 7

[Linux Configs.zip](https://github.com/postfixadmin/postfixadmin/files/3100690/Linux.Configs.zip)

**Comment by DavidGoodwin** [comment]
Are there any relevant messages in e.g. /var/log/mail.log (or /var/log/maillog or journalctl -u postfix, perhaps?).

**Comment by DevScyu** [comment]
```
Apr 21 00:33:36 wynntils postfix/smtpd[8165]: 26C54CA8: client=localhost[127.0.0.1]
Apr 21 00:33:36 wynntils postfix/cleanup[8283]: 26C54CA8: message-id=<20190420223336.26C54CA8@example.com>
Apr 21 00:33:36 wynntils postfix/qmgr[8153]: 26C54CA8: from=<admin@example.com>, size=469, nrcpt=1 (queue active)
Apr 21 00:33:36 wynntils postfix/smtpd[8165]: disconnect from localhost[127.0.0.1]
Apr 21 00:33:36 wynntils postfix/trivial-rewrite[8279]: warning: do not list domain example.com in BOTH mydestination and virtual_mailbox_domains
Apr 21 00:33:36 wynntils postfix/local[8284]: 26C54CA8: to=<test2@example.com>, relay=local, delay=0.04, delays=0.02/0.01/0/0.02, dsn=5.1.1, status=bounced (unknown user: "test2")
Apr 21 00:36:27 wynntils postfix/smtpd[8165]: 0A338CA8: client=localhost[127.0.0.1]
Apr 21 00:36:27 wynntils postfix/cleanup[8650]: 0A338CA8: message-id=<20190420223627.0A338CA8@example.com>
Apr 21 00:36:27 wynntils postfix/qmgr[8153]: 0A338CA8: from=<admin@example.com>, size=469, nrcpt=1 (queue active)
Apr 21 00:36:27 wynntils postfix/smtpd[8165]: disconnect from localhost[127.0.0.1]
Apr 21 00:36:27 wynntils postfix/trivial-rewrite[8647]: warning: do not list domain example.com in BOTH mydestination and virtual_mailbox_domains
Apr 21 00:36:27 wynntils postfix/local[8651]: 0A338CA8: to=<test3@example.com>, relay=local, delay=0.06, delays=0.03/0.01/0/0.02, dsn=5.1.1, status=bounced (unknown user: "test3")
```

Maillog when i tried to create new mailbox using admin panel. @DavidGoodwin

**Comment by cboltz** [comment]
> warning: do not list domain example.com in BOTH mydestination and virtual_mailbox_domains

That says it all - remove the domain from `mydestination`

**Comment by DevScyu** [comment]
@cboltz That is only a warning and doesn't affect the creation of mailboxes, i have been able to create other mailboxes manually and they work perfectly fine, along with this warning.

**Comment by DavidGoodwin** [comment]
What does 

```postmap -q test2@example.com mysql:/etc/postfix/sql/mysql_virtual_mailbox_maps.cf``` 

give?

I think you need to fix main.cf so : 
```
mydestination = $myhostname, localhost.$mydomain, localhost, $mydomain
```
becomes ....
```
mydestination = $myhostname, localhost.$mydomain, localhost 
```

Else Postfix may not bother trying to do a virtual mailbox/domain lookup and therefore not check the virtual mailbox maps? (after all, the log message shows it using the local transport and not the virtual one)


Apr 21 00:36:27 wynntils postfix/**local**[8651]: 0A338CA8: to=<test3@example.com>, relay=**local**, delay=0.06, delays=0.03/0.01/0/0.02, dsn=5.1.1, status=bounced (unknown user: "test3")


I'd expect that to look more like : 


Apr 21 00:36:27 wynntils postfix/**virtual**[8651]: 0A338CA8: to=<test3@example.com>, relay=**virtual**, delay=0.06, delays=0.03/0.01/0/0.02, dsn=2.0.0, status=send (delivered to maildir)

**Comment by DevScyu** [comment]
@DavidGoodwin Thank you for the explination, i thought this was just a warning and not much to look at, i had to tweak more settings to get it to fully work, but i can now create and manage accounts using postfix admin! Thank you.
