### ISSUE TITLE
incompatibility with PHP 7.3.5?

### ISSUE THREAD

**Issue by schickel007** [postfixadmin/postfixadmin#270]
I'm running for a big while postfixadmin on my arch linux server. My last login to postfixadmin is month ago. But now I can't open postfixadmin and getting a blank page.

The only thing what's changes is upgrade apache to 2.4.39 and PHP to 7.3.5.

In the error log I get:

[Thu May 09 12:15:06.737510 2019] [php7:warn] [pid 6687] [client 62.245.156.58:27897] PHP Warning:  require_once(/etc/webapps/postfixadmin/config.inc.php): failed to open stream: Permission deni
ed in /usr/share/webapps/postfixadmin/common.php on line 60
[Thu May 09 12:15:06.737590 2019] [php7:error] [pid 6687] [client 62.245.156.58:27897] PHP Fatal error:  require_once(): Failed opening required '/usr/share/webapps/postfixadmin/config.inc.php'
(include_path='.:') in /usr/share/webapps/postfixadmin/common.php on line 60

Don't know where my problem is. Any hints?

EDIT: PLEASE CLOSE THIS - IS AN ARCH LINUX FAULT

**Comment by digorgonzola** [comment]
Can you please share what the issue was? I have the same problem...

**Comment by DavidGoodwin** [comment]
Check the permissions on /etc/webapps/postfixadmin/config.inc.php and the parent directories. The webserver probably doesn't have read permission on the file, or execute permissions on the parent directories.

**Comment by digorgonzola** [comment]
Thanks @DavidGoodwin . Figured it out on the end!
