### ISSUE TITLE
Add config option to set password for admin_email

### ISSUE THREAD

**Issue by Nutomic** [postfixadmin/postfixadmin#272]
We are having a problem on our server with the password reset. The `admin_email` is configured correctly and exists on the mail server. However, the mail server requires a password to send from this address. As far as I can see, Postfixadmin has no option to use a password with `admin_email`. We could maybe avoid this problem by allowing passwordless login with an IP whitelist. But it would be much simpler if we could simply configure `admin_email_password` in postfixadmin.

I can probably implement this if you agree with the idea.

**Comment by DavidGoodwin** [comment]
Thanks; I'll try and review it soon.
