### ISSUE TITLE
postfixadmin v 3.1  How to reset admin password?

### ISSUE THREAD

**Issue by supersophie** [postfixadmin/postfixadmin#273]
Hi all,

Aplogies that this is not a bug, but actually a support question.

How might i reset the admin ( postfixadmin) password for the installation?  I seem to have mislaid mine. This is the admin account of login.php   e.g https://postfixadmin.example.co.uk/login.php

I am using postfixadmin with sqlite3.

Best, S

**Comment by DavidGoodwin** [comment]
Go to https://server/postfixadmin/setup.php and you'll see a form at the bottom of the page to login as an admin. It should have two password fields. Using the new password you want, submit the form, and upon refreshing it should show something like  the below (using 'Abcdef12') : 

```php
$CONF['setup_password'] = 'b36af086d3826a64d2de5e948acf7c78:a8cd34f0dbed7f1f5f482f47e15a068dabcb9f8f';
```

Now edit your config.local.php file and replace what was already in it for 'setup_password' ....

**Comment by supersophie** [comment]
Thanks David for the link. 

I had tried this and amended this setup_password in the config.local.php but it didn’t work. 

The setup.php give this: 

Setup password not specified correctly

"If you want to use the password you entered as setup password, edit config.inc.php or config.local.php and set

$CONF['setup_password'] = 'xxxxxxxxxxxx:xxxxxxxxxxxxx';
Create superadmin account

Setup password		Lost password?
Admin:		postfixemail@example.com
Password:		newpassword
Password (again):	newpassword"

**Comment by DavidGoodwin** [comment]
Is it possible you're editing the wrong file somehow? Are there config files in e.g /etc/postfixadmin that are being used? Are you looking at the right place on the server (could there be multiple installations of Postfixadmin?)

**Comment by supersophie** [comment]
> On 27 May 2019, at 21:53, David Goodwin <notifications@github.com> wrote:
> 
> Is it possible you're editing the wrong file somehow? Are there config files in e.g /etc/postfixadmin that are being used? Are you looking at the right place on the server (could there be multiple installations of Postfixadmin?)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nope. There is only one postfixadmin installation on the server, and the vhost config points to the right directory.  It’s a ilttle odd.

**Comment by supersophie** [comment]
> On 27 May 2019, at 21:53, David Goodwin <notifications@github.com> wrote:
> 
> Is it possible you're editing the wrong file somehow? Are there config files in e.g /etc/postfixadmin that are being used? Are you looking at the right place on the server (could there be multiple installations of Postfixadmin?)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Update: Fixed it. Had to run it twice. New user was added and could log in again.  Thanks lots ! Most appreciated.

**Comment by enderandrew** [comment]
So I just upgraded to a new version of postfixadmin, which told me I needed to re-do the password hash. I did that and updated my config.local.php file with the new hash. The login page will come up, but I can't login, even though my password is stored in a password locker and I know it is correct. Is there truly no way to reset an admin password?

So I used setup.php to create new admin accounts 5 times in a row, copy/pasting a password in notepad and also having the browser save the password and Lastpass.

I know the password is correct and even with 5 more new admin accounts I created, I can't login when I know the password is correct.

**Comment by DavidGoodwin** [comment]
Hi - @enderandrew it's a bit risky commenting on the bottom of a closed ticket from about a year ago - you're more likely to get help/be noticed if you create a new ticket.

Having said that, with the 3.3.x release, we ONLY changed the format of the setup_password (used for accessing setup.php). We haven't (knowingly) changed how other hashes work.

Are you using Dovecot? Have you recently upgraded that? If so, perhaps your problem is similar to some of the issues in https://github.com/postfixadmin/postfixadmin/issues/434#issuecomment-766756924 ?
