### ISSUE TITLE
mysqli wrong specification of different port

### ISSUE THREAD

**Issue by mkdruss** [postfixadmin/postfixadmin#274]
config.inc.php:
// If you need to specify a different port for a MYSQL database connection, use e.g.
//   $CONF['database_host'] = '172.30.33.66:3308';

PHP documentation:
https://www.php.net/manual/en/mysqli.construct.php
mysqli_connect ([ string $host = ini_get("mysqli.default_host") [, string $username = ini_get("mysqli.default_user") [, string $passwd = ini_get("mysqli.default_pw") [, string $dbname = "" [, int $port = ini_get("mysqli.default_port") [, string $socket = ini_get("mysqli.default_socket") ]]]]]] )

my hotfix

--- functions.inc.php-bak	2019-05-24 17:02:47.366223240 +0200
+++ functions.inc.php	2019-05-28 09:43:30.716707647 +0200
@@ -1271,7 +1271,10 @@
         }
     } elseif ($CONF['database_type'] == "mysqli") {
         if (function_exists ("mysqli_connect")) {
`-`            $link = @mysqli_connect ($CONF['database_host'], $CONF['database_user'], $CONF['database_password']) or $error_text .= ("<p />DEBUG INFORMATION:<br />Connect: " .  mysqli_connect_error () . "$DEBUG_TEXT");
`+`            if(!isset($CONF['database_port'])) {
`+`		$CONF['database_port'] = '3306';
`+`	    }
`+`            $link = @mysqli_connect ($CONF['database_host'], $CONF['database_user'], $CONF['database_password'], '', $CONF['database_port']) or $error_text .= ("<p />DEBUG INFORMATION:<br />Connect: " .  mysqli_connect_error () . "$DEBUG_TEXT");
             if ($link) {
                 @mysqli_query($link,"SET CHARACTER SET utf8");
                 @mysqli_query($link,"SET COLLATION_CONNECTION='utf8_general_ci'");

**Comment by DavidGoodwin** [comment]
We no longer use mysqli_ in master. I'm assuming you're using postfixadmin-3.2 or something? The line numbers in your patch don't match postfixadmin_3.2

**Comment by mkdruss** [comment]
hmm many changes in master
I checked only config in master, comment in config for different port was incompatible with mysqli
I am closing. Sorry.

**Comment by DavidGoodwin** [comment]
Thanks for confirming.
