### ISSUE TITLE
incompatible with < php5.4

### ISSUE THREAD

**Issue by mkdruss** [postfixadmin/postfixadmin#275]
INSTALL.TXT:
REQUIREMENTS
PHP 5.1.2 or higher.

PHP Documentation:
https://www.php.net/manual/en/language.types.array.php
As of PHP 5.4 you can also use the short array syntax, which replaces array() with []. 

fix:
--- setup.php-bak	2019-05-28 10:15:39.329005648 +0200
+++ setup.php	2019-05-28 10:16:12.485005648 +0200
@@ -58,7 +58,7 @@
 
 $error = 0;
 
`-`$errormsg = [];
`+`$errormsg = array(); 
 
 //
 // Check for PHP version

**Comment by DavidGoodwin** [comment]
Hi - There aren't really any valid reasons to use such an old PHP variant any longer. We were trying to only use the longer array notation - but I suspect I've reverted to using '[]' in a number of places already.

**Comment by DavidGoodwin** [comment]
which version of Postfixadmin are you looking at? 3.2 and master both have ```$errormsg = array();```  ...

**Comment by mkdruss** [comment]
I am sorry, mistake
i checked setup.php in 3.1, not actual file on github.
I hate obsolete servers.
