### ISSUE TITLE
Mailbox changes result in error

### ISSUE THREAD

**Issue by HeavyThumper** [postfixadmin/postfixadmin#276]
I'm sure it's something I've setup wrong - but I'm unable to make any edits to mailboxes via the web GUI. The command-line client does work.

Any edit to a mailbox results in the error displayed: Modifying the alias <whoever> failed!

I was on the released 3.2, I'm now on master, same issue. Server is Percona/Mysql. Looking at the tables I notice that token/token_validity appears not be getting written/updated.

I can delete and re-create a mailbox without issue - but I cannot make any changes. I don't see any other errors in logs - is there a debug option I should turn on?

**Comment by DavidGoodwin** [comment]
This should be fixed in master. (see : 03b94832049f91863dbfd96016364328c97a7215 ) ....

**Comment by DavidGoodwin** [comment]
password_expiry isn't available in postfixadmin 3.2; so there are probably two different issues.

There is apparently a problem with the token_validity tokens expiring immediately, if your server (PHP) timezone setting does not match that of MySQL - see also - https://github.com/postfixadmin/postfixadmin/issues/254
