### ISSUE TITLE
PHP Notice:  Undefined index: REQUEST_SCHEME in /postfixadmin/public/users/password-recover.php on line 42

### ISSUE THREAD

**Issue by hendrikzuellig** [postfixadmin/postfixadmin#279]
I'm trying to get the password reset function to work.
I'm having the following issue:
When trying to reset via https://domain.tld/users/password-recover.php
The postfixadmin log spills out an error:
```PHP Notice:  Undefined index: REQUEST_SCHEME in /postfixadmin/public/users/password-recover.php on line 42```

Any idea how to fix this? 
Thank's in advance!
https://github.com/postfixadmin/postfixadmin/blob/730a05cdd35db7200217879569264153db3151b6/public/users/password-recover.php#L42
Setup: [Postfixadmin is running inside docker](https://github.com/hardware/postfixadmin)

**Comment by Nutomic** [comment]
There is some discussion on stackoverflow about this, I think the summary is that it is very dependant on the webserver. There is probably no perfect solution, so I would suggest doing a best effort and then falling back on http. Or better, adding a config value.

https://stackoverflow.com/questions/18008135/is-serverrequest-scheme-reliable
