### ISSUE TITLE
Dont make password expiration mandatory

### ISSUE THREAD

**Issue by Nutomic** [postfixadmin/postfixadmin#280]
This was added recently in #200. And apparently, the expiration is mandatory, there seems to be no way to disable it, other than setting an expiration date far enough in the future. But even Microsoft is now recommending not to do password expiration. I think it should be disabled by default because it encourages bad practices.

https://techcrunch.com/2019/06/02/password-expiration-is-dead-long-live-your-passwords/

https://www.engadget.com/2019/04/24/microsoft-password-expiration-security/?guccounter=1

**Comment by DavidGoodwin** [comment]
It shouldn't be mandatory; that's an oversight/bug on my behalf.

**Comment by Nutomic** [comment]
The fix does not seem to work, this is what I get when testing with the code in #285 (which includes your fix).

```
# docker exec -t postfixadmin /postfixadmin/scripts/postfixadmin-cli domain add cloudtest.e.foundation
Config::read(): attempt to read undefined config option "database_socket", returning null

Welcome to Postfixadmin-CLI v0.2
---------------------------------------------------------------
Error: password_expiry must be numeric
```

It only works if I add `--password_expiry 0`.

**Comment by DavidGoodwin** [comment]
I've no idea why you can't reopen it.  Presumably there's a github permission hidden somewhere.

**Comment by DavidGoodwin** [comment]
Does the above commit help?

**Comment by Nutomic** [comment]
That fixed it, thanks!
