### ISSUE TITLE
Error: This domain does not exist!

### ISSUE THREAD

**Issue by adam12b1** [postfixadmin/postfixadmin#282]
In v3.2_2, on the mailbox creation page, if you're a naive user and try to enter the full address as the Mailbox name (`me@thisdomain.com`), you get a nice little in-lined red error message telling you the address is invalid and showing the full broken `me@thisdomain.com@thisdomain.com` value. That's good.

But if instead you enter `me@anythingelse`, including just plain `me@` with no domain, you instead get a totally separate blank white page with the unhelpful message **Error: This domain does not exist!** at the top. That's not good.

Is there a reason the error for invalid domain doesn't work exactly like the error for invalid mailbox? Could it be made to do so?

(Even better might be to have the code look specifically for @ in the input and give a specific error message like "Please enter local part only, no @, no domain" or similar. But now I'm probably just dreaming.)

**Comment by DavidGoodwin** [comment]
I've (possibly) fixed this in master; the change should be relatively easy to backport to 3.2 (assuming I've understood the problem)

**Comment by adam12b1** [comment]
Oh, that's fabulous, thank you! Looks like exactly what I was dreaming of.

**Comment by DavidGoodwin** [comment]
Could you please test it and confirm it works for you ?

**Comment by adam12b1** [comment]
Okay, done - it's great, I now get the same "invalid address" error in all cases.
