### ISSUE TITLE
Bracket constantly appears after the body tag

### ISSUE THREAD

**Issue by Fiorinol** [postfixadmin/postfixadmin#283]
This tiny annoying bracket keeps showing up in the body tag on every single page, it's driving me nuts:

https://i.imgur.com/CRBYJUX.png

I installed postfixadmin 3.2 following the instructions in the install text file, and looking through the configuration, I don't see anything that pops to my eyes. Is this behavior normal or did I do something wrong during the install? Everything seems to be working fine. I'm logging onto my superadmin account and adding domains/mailboxes, they get added properly to the MariaDB database.

I am using Nginx on fpm 7.3 on Ubuntu.

**Comment by DavidGoodwin** [comment]
What version are you using?
