### ISSUE TITLE
[vacation] - Mail::Sender is deprecated

### ISSUE THREAD

**Issue by pedromorgan** [postfixadmin/postfixadmin#284]
Jun 25 11:11:31 geo7 postfix/pipe[32195]: C6D1A1080489: to=<esharp#example.com@example.com>, orig_to=<esharp@example.com>, relay=vacation, delay=1.6, delays=1.5/0/0/0.19, dsn=2.0.0, status=sent (delivered via vacation service (Mail::Sender is deprecated and you should look to Email::Sender instead at /var/spool/vacation/vacat))

**Comment by DavidGoodwin** [comment]
you need to update your vacation.pl script - fixes for this have already been merged in.

See b781195526bf8ff0d4907e308b0fe16294827140 from back in 2017 :)
