### ISSUE TITLE
Bad character encoding in vacation.pl

### ISSUE THREAD

**Issue by Liberasys** [postfixadmin/postfixadmin#288]
Hello,

I had problem with characters encoding in vacation messages.
Mails received had Western (ISO) charset whereas modern mail applications wait for unicode.
By using encode from perl, the problem has disappeared.

Context:
debian 9.9
Virtual Vacation 4.2

Solution:
use Encode qw(decode **encode**);
body => **encode("UTF-8",** $body**)**,

**Comment by DavidGoodwin** [comment]
Thanks! I've not tested the patch, if you could confirm it's correct that'd be ace.

**Comment by Liberasys** [comment]
Hello,
Code modification is in production on 2 servers.
I tested it on my Linux desktop with firefox (WEB interface access) and Thunderbird (mail client).
Maybe it needs further testing ?

**Comment by DavidGoodwin** [comment]
OK - it's more of just a sanity check to make sure I made the modification you suggested correctly! 

Thank you for taking the time to contribute

**Comment by Liberasys** [comment]
Ah ok, I didn't understood :-) Anyway I shoud have done a pull request, sorry :-)
Your code modification is OK (rev c3d3a9d, 11 mn ago).

**Comment by pumpal** [comment]
Please be warned, that this did NOT WORK for us and actually started BRAKING the body encoding. In my case Cyrillic text (I believe it was saved as UTF-8 in the DB). After  upgrading from 4.0 to 4.2 of the vacation.pl script it started to brake the encoding of email body.  Googling brought me here to this thread. Restoring the previous state on line 486  from "=> encode('UTF-8', $body),"  back to just body => $body,   made it work fine again. 

System runs Debian 10.0, Postfixadmin 3.1 . 
Let me know if I can be of any help with more debugging or information.  
Thanks for your work.

**Comment by mzmrk** [comment]
I just spent entire day to fix this issue.
Mails containing ś, ó, ż, ź etc. in body were not working.
Manually added   `my $body = Encode::encode('utf-8',$row[1]);` to code. And it works again.

System is Debian 9, Postfix 3, Postgres 9.4 encoded in UTF-8

What do we do?
Maybe add this as an config option until we figure it out? 
Both Polish letters and Cyrillic works fine with encode('utf-8',$row[1]) on my end.
Hmm, why do we need to encode it if database is showing letters correctly, is encoding lost during transformations in vacation.pl? 
Why is it different for @pumpal ?

**Comment by ltachev** [comment]
Could it have something to do with the locale settings? Or database collation settings ..  I can provide database dump if that can be of any use. But fact that I am using MySQl and @mzmrk PG leads to the thought that it is probably not related to the DB but more of how the client connection interprets the pulled data ..
