### ISSUE TITLE
Need some more functions

### ISSUE THREAD

**Issue by volker-raschek** [postfixadmin/postfixadmin#29]
Hello,
I use postfixadmin since 2 years and it's great, but i need some more functions. 
I stored about the postfixadmin gui some domains as relay and I want to configure postfix with mysql-statements to relay the stored domains to the real smtp server, but i can't find some mysql-statements on github. Please add some statements an githib for right relay configuration.

I want to fillout this postfix configuration settings about mysql-statements.
- relay_recipients 
- relay_domains
- relay_transport
- transport_maps 

Next, it's great if you could implement a mask to configure some relocated settings for user@domain, users or catch all domains as example @domain 

faq to relocated_maps http://www.postfix.org/relocated.5.html

Volker

**Comment by dimejo** [comment]
> I use postfixadmin since 2 years and it's great, but i need some more functions.
I stored about the postfixadmin gui some domains as relay and I want to configure postfix with mysql-statements to relay the stored domains to the real smtp server, but i can't find some mysql-statements on github. Please add some statements an githib for right relay configuration.

You can use the `description` field to define a relay transport.

**main.cf**
```
transport_maps = btree:${config_directory}}/transport_maps,
    proxy:mysql:${sql_directory}/mysql_relay_transport_maps.cf
```

**mysql_relay_transport_maps.cf**
```
user = postfixadmin
password = secret
hosts = 127.0.0.1:3306
dbname = postfixadmin
query = SELECT description FROM domain WHERE domain = '%s' AND transport = 'relay' AND active = '1'
```
