### ISSUE TITLE
FressBSD 11 port : php72  is hardlind and not use flavour

### ISSUE THREAD

**Issue by bugsbriez** [postfixadmin/postfixadmin#291]
Hello,

An verry annoying problem, when installed from port collection postfix admin depend explicitly from php72 and not the flavour, the result is a complete desinstallation of all the other port/pkg depending of php73 and the extentions :
[...]
Checking integrity... done (9 conflicting)
  - php72-session-7.2.21 [Synth] conflicts with php73-session-7.3.8 [installed] on /usr/local/include/php/ext/session/php_session.h
  - php72-7.2.21 [Synth] conflicts with php73-7.3.8 [installed] on /usr/local/bin/php
  - php72-openssl-7.2.21 [Synth] conflicts with php73-openssl-7.3.8 [installed] on /usr/local/include/php/ext/openssl/config.h
  - php72-xmlrpc-7.2.21 [Synth] conflicts with php73-xmlrpc-7.3.8 [installed] on /usr/local/include/php/ext/xmlrpc/libxmlrpc/xmlrpc_private.h
  - php72-xml-7.2.21 [Synth] conflicts with php73-xml-7.3.8 [installed] on /usr/local/include/php/ext/xml/php_xml.h
  - php72-pgsql-7.2.21 [Synth] conflicts with php73-pgsql-7.3.8 [installed] on /usr/local/include/php/ext/pgsql/php_pgsql.h
  - php72-mbstring-7.2.21 [Synth] conflicts with php73-mbstring-7.3.8 [installed] on /usr/local/include/php/ext/mbstring/php_mbregex.h
  - php72-phar-7.2.21 [Synth] conflicts with php73-phar-7.3.8 [installed] on /usr/local/include/php/ext/phar/func_interceptors.h
  - php72-hash-7.2.21 [Synth] conflicts with php73-hash-7.3.8 [installed] on /usr/local/include/php/ext/hash/php_hash_crc32_tables.h
Checking integrity... done (0 conflicting)
The following 106 package(s) will be affected (of 0 checked):

Installed packages to be REMOVED:
        php73-xmlrpc-7.3.8
        php73-xml-7.3.8
        php73-7.3.8
        php73-gettext-7.3.8
        php73-extensions-1.0
        php73-tidy-7.3.8
        php73-session-7.3.8
        php73-wddx-7.3.8
        roundcube-php73-1.3.9,1
        php73-dom-7.3.8
        php73-xmlreader-7.3.8
[...]

postfixadmin installed from git working fine with php73 can you please honor flavours in the future release.

Regards

**Comment by DavidGoodwin** [comment]
I don't think we (the postfixadmin developers) have anything to do with the FreeBSD port.

**Comment by DavidGoodwin** [comment]
(is there not a FreeBSD bug tracker ?)
