### ISSUE TITLE
[FEATURE REQUEST] transport_maps sql support in postfix

### ISSUE THREAD

**Issue by AkhilJalagam** [postfixadmin/postfixadmin#292]
**Before:**
transport_maps = hash:/etc/postfix/transport

**After:**
transport_maps = mysql:mysql_virtual_transports_maps.cf

# mysql_virtual_transports_maps.cf
user = postfix
password = postfix
hosts = localhost
dbname = postfixadmin
query = SELECT dest_domain FROM transports WHERE domain='%s' AND active = '1'

_postfixadmin database init script should add transports table in database_

**Comment by adrium** [comment]
This seems to be ready to use in PostfixAdmin, but some configuration flag is needed.

I opened pull request #321 to use the feature in postfix.
