### ISSUE TITLE
Please relase a new version with the fixed cli

### ISSUE THREAD

**Issue by Corvan** [postfixadmin/postfixadmin#296]
Hey,

could you please release a new Version with the fixed cli. This will trigger that the FreeBSD-Port Maintainer will be notified and the change willl be added to the postfixadmin FreeBSD-Port. This will help a lot.
Thanks
Lars

**Comment by DavidGoodwin** [comment]
you mean you want a new release with this : https://github.com/postfixadmin/postfixadmin/pull/295 ?

**Comment by Corvan** [comment]
Yes, and #207 please

**Comment by Corvan** [comment]
Thank you!
