### ISSUE TITLE
sasal authentication

### ISSUE THREAD

**Issue by munagala05** [postfixadmin/postfixadmin#297]
pam_mysql - pam_mysql_check_passwd() returning 6.
auth_pam: pam_authenticate failed: Authentication failure

**Comment by DavidGoodwin** [comment]
You've not provided anyone with enough information to help you, and the problem does not look like it's related to Postfixadmin.

**Comment by munagala05** [comment]
Hi,
I am installed the postfixadmin and postfix courier for authentication libsasl2-2 we are using. While sending the mail we are getting this error
