### ISSUE TITLE
Error when creating new domain

### ISSUE THREAD

**Issue by Huxtor** [postfixadmin/postfixadmin#299]
When i want to create new domain in postfixadmin i got and error:

Invalid query: Incorrect integer value: '' for column 'quota' at row 1

Check your error_log for the failed query.

**Comment by DavidGoodwin** [comment]
Hi - what version of postfixadmin? What database? Can you see anything in e.g. /var/log/apache2/error.log or wherever you're logging to?

**Comment by Huxtor** [comment]
Version 3.2, database MySQL 5.5, anything in logs

**Comment by MadCamel** [comment]
I just ran into this and can share the cause and solution on my particular system.

I've upgraded postfixadmin multiple times while keeping the same config.inc.php file.
The code to create new domains breaks if the domain_quota_default config option isn't set. My ancient config doesn't have it as this feature was added later.

Adding this to my config fixed the issue with creating domains:
$CONF['domain_quota_default'] = -1;

Lesson: When updating postfixadmin it's probably good idea to build a new configuration file based on the template in the latest version.

**Comment by DavidGoodwin** [comment]
Thanks

**Comment by davidjmcq** [comment]
thank you MadCamel .... I copied the line from the distribution version, (which Debian conveniently leaves for you to check against), and inserted it into /etc/postfixadmin/config.inc.php under the heading "// Default Domain Values".

I used the distribution version: `$CONF['domain_quota_default'] = '2048';` and that worked.
