### ISSUE TITLE
vacation is not working

### ISSUE THREAD

**Issue by munagala05** [postfixadmin/postfixadmin#300]
can't STARTTLS: 2.0.0 Ready to start TLS line 193#012Email::Sender::Transport::SMTP::_throw('Email::Sender::Transport::SMTP=HASH(0x557226d81ee8)', 'can\'t STARTTLS: 2.0.0 Ready to start TLS^J') called at /usr/local/share/perl/5.26.1/Email/Sender/Transport/SMTP.pm line 151#012Email::Sender::Transport::SMTP::_smtp_client('Email::Sender::Transport::SMTP=HASH(0x557226d81ee8)') called at /usr/local/share/perl/5.26.1/Email/Sender/Transport/SMTP.pm line 202#012Email::Sender::Transport::SMTP::send_email('Email::Sender::Transport::SMTP=HASH(0x557226d81ee8)', 'Email::Abstract=ARRAY(0x557226d82608)', 'HASH(0x557226d826c8)') called at /usr/local/share/perl/5.26.1/Email/Sender/Role/CommonSending.pm line 45#012Email::Sender::Role::CommonSending::try {...}  at /usr/local/share/perl/5.26.1/Try/Tiny.pm line 102#012eval {...} at /usr/local/share/perl/5.26.1/Try/Tiny.pm line 93#012Try::Tiny::try('CODE(0x557226daf4c0)', 'Try::Tiny::Catch=REF(0x557226d6dcd8)') called at /usr/local/share/perl/5.26.1/Email/Sender/Role/CommonSending.pm line 58#012Email::Sender::Role::CommonSending::send('Email::Sender::Transport::SMTP=HASH(0x557226d81ee8)', 'Email::Abstract=ARRAY(0x557226d82608)', 'HASH(0x557226daf280)') called at /usr/local/share/perl/5.26.1/Email/Sender/Simple.pm line 119#012Email::Sender::Simple::send_email('Email::Sender::Simple', 'Email::Abstract=ARRAY(0x557226d82608)', 'HASH(0x557226d82830)') called at /usr/local/share/perl/5.26.1/Email/Sender/Role/CommonSending.pm line 45#012Email::Sender::Role::CommonSending::try {...}  at /usr/local/share/perl/5.26.1/Try/Tiny.pm line 102#012eval {...} at /usr/local/share/perl/5.26.1/Try/Tiny.pm line 93#012Try::Tiny::try('CODE(0x557226d826b0)', 'Try::Tiny::Catch=REF(0x55722659cf10)') called at /usr/local/share/perl/5.26.1/Email/Sender/Role/CommonSending.pm line 58#012Email::Sender::Role::CommonSending::send('Email::Sender::Simple', 'Email::Simple=HASH(0x557226ca0500)', 'HASH(0x557226d827a0)') called at /usr/local/share/perl/5.26.1/Sub/Exporter/Util.pm line 18#012Sub::Exporter::Util::__ANON__('Email::Simple=HASH(0x557226ca0500)', 'HASH(0x557226d827a0)') called at /var/spool/vacation/vacation.pl line 495#012main::try {...}  at /usr/local/share/perl/5.26.1/Try/Tiny.pm line 102#012eval {...} at /usr/local/share/perl/5.26.1/Try/Tiny.pm line 93#012Try::Tiny::try('CODE(0x557226d38370)', 'Try::Tiny::Finally=REF(0x557225e424c0)') called at /var/spool/vacation/vacation.pl 

Please help me on this.

**Comment by DavidGoodwin** [comment]
edit the top of vacation.pl and change : 

```
our $smtp_ssl = 'starttls';
```

to something like :+1: 
```
our $smtp_ssl = 0;
```

I assume the server you're trying to send through does not support SSL / starttls.

**Comment by munagala05** [comment]
Thanks for replay
Actually i installed the courier-imap-ssl is it required to install any another package are how it will work with ssl/starttls please guide me.

**Comment by DavidGoodwin** [comment]
https://github.com/postfixadmin/postfixadmin/blob/master/VIRTUAL_VACATION/vacation.pl#L65

**Comment by munagala05** [comment]
vacation: ERROR - Failed to send vacation response unable to establish SMTP connection

**Comment by munagala05** [comment]
vacation: ERROR - Failed to send vacation response to example1@domainname.in from example@domainname.in subject I'm out of office  from 14-12-2021 to 16-12-2021: unable to establish SMTP connection to (host.domainname.in) port 25#012#012Trace begun at /usr/local/share/perl/5.30.0/Email/Sender/Transport/SMTP.pm line 232#012Email::Sender::Transport::SMTP::_throw('Email::Sender::Transport::SMTP=HASH(0x55807bc8e278)', 'unable to establish SMTP connection to (host.domainname.in) port 25') called at /usr/local/share/perl/5.30.0/Email/Sender/Transport/SMTP.pm line 175#012Email::Sender::Transport::SMTP::_smtp_client('Email::Sender::Transport::SMTP=HASH(0x55807bc8e278)') called at /usr/local/share/perl/5.30.0/Email/Sender/Transport/SMTP.pm line 241#012Email::Sender::Transport::SMTP::send_email('Email::Sender::Transport::SMTP=HASH(0x55807bc8e278)', 'Email::Abstract=ARRAY(0x55807bc9bac0)', 'HASH(0x55807bc8dc90)') called at /usr/local/share/perl/5.30.0/Email/Sender/Role/CommonSending.pm line 45#012Email::Sender::Role::CommonSending::try {...}  at /usr/local/share/perl/5.30.0/Try/Tiny.pm line 102#012eval {...} at /usr/local/share/perl/5.30.0/Try/Tiny.pm line 93#012Try::Tiny::try('CODE(0x55807bd1cf28)', 'Try::Tiny::Catch=REF(0x55807bcf4740)') called at /usr/local/share/perl/5.30.0/Email/Sender/Role/CommonSending.pm line 58#012Email::Sender::Role::CommonSending::send('Email::Sender::Transport::SMTP=HASH(0x55807bc8e278)', 'Email::Abstract=ARRAY(0x55807bc9bac0)', 'HASH(0x55807bd08c70)') called at /usr/local/share/perl/5.30.0/Email/Sender/Simple.pm line 119#012Email::Sender::Simple::send_email('Email::Sender::Simple', 'Email::Abstract=ARRAY(0x55807bc9bac0)', 'HASH(0x55807bca10a8)') called at /usr/local/share/perl/5.30.0/Email/Sender/Role/CommonSending.pm line 45#012Email::Sender::Role::CommonSending::try {...}  at /usr/local/share/perl/5.30.0/Try/Tiny.pm line 102#012eval {...} at /usr/local/share/perl/5.30.0/Try/Tiny.pm line 93#012Try::Tiny::try('CODE(0x55807bc9baf0)', 'Try::Tiny::Catch=REF(0x55807b48aa08)') called at /usr/local/share/perl/5.30.0/Email/Sender/Role/CommonSending.pm line 58#012Email::Sender::Role::CommonSending::send('Email::Sender::Simple', 'Email::Simple=HASH(0x55807bc94978)', 'HASH(0x55807bc8fdb8)') called at /usr/share/perl5/Sub/Exporter/Util.pm line 18#012Sub::Exporter::Util::__ANON__('Email::Simple=HASH(0x55807bc94978)', 'HASH(0x55807bc8fdb8)') called at /var/spool/vacation/vacation.pl line 511#012main::try {...}  at /usr/local/share/perl/5.30.0/Try/Tiny.pm line 102#012eval {...} at /usr/local/share/perl/5.30.0/Try/Tiny.pm line 93#012Try::Tiny::try('CODE(0x55807bc8fc20)', 'Try::Tiny::Finally=REF(0x55807acb5eb0)') called at /var/spool/vacation/vacation.pl line 519#012main::send_vacation_email('example@domainname.in', 'example1@domainname.in', 'example@domainname.in', '<7a8ea499-b207-1110-c534-fe5dcfe7bcd0@pragatiautomation.in>', 'Fwd: Test for vacation', 0) called at /var/spool/vacation/vacation.pl line 676#012

**Comment by DavidGoodwin** [comment]
can you connect to host.domainname.in on port 25?

**Comment by munagala05** [comment]
yes
