### ISSUE TITLE
Table 'mail.vacation' doesn't exist in engine 

### ISSUE THREAD

**Issue by zer0nem0** [postfixadmin/postfixadmin#304]
Can someone help me how can i solve this debug?
I cant use my postfixadmin because 3 table is "in use" 

fetchmail

vacation

vacation_notificaton

I cant repair that 3 table why? Every other table ist ok (domain, alias etc..)

**Comment by DavidGoodwin** [comment]
What database are you using?

**Comment by zer0nem0** [comment]
Hi David!

I have Debian 9 OS
I copied the files over my old server backup.. it was this actually same OS debian 9
Copied with r-sync
But idk why "in use" the fetchmail, vacation etc..
I have "mail" database from my friend.. i dont know where can i download the real database on the NET.
I send you pictures abut my structure.
I tried to repair.. doesnt work..
ii  libmariadbclient18:amd64              10.1.41-0+deb9u1                            amd64        MariaDB database client library
ii  mariadb-client                        10.1.41-0+deb9u1                            all          MariaDB database client (metapackage depending on the latest version)
ii  mariadb-client-10.1                   10.1.41-0+deb9u1                            amd64        MariaDB database client binaries
ii  mariadb-client-core-10.1              10.1.41-0+deb9u1                            amd64        MariaDB database core client binaries
ii  mariadb-common                        10.1.41-0+deb9u1                            all          MariaDB common metapackage
ii  mariadb-server                        10.1.41-0+deb9u1                            all          MariaDB database server (metapackage depending on the latest version)
ii  mariadb-server-10.1                   10.1.41-0+deb9u1                            amd64        MariaDB database server binaries
ii  mariadb-server-core-10.1              10.1.41-0+deb9u1                            amd64        MariaDB database core server files

mysql -V

mysql  Ver 15.1 Distrib 10.1.41-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Mariadb -v

mariadb  Ver 15.1 Distrib 10.1.41-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Thanks o lot..

KR: Alex

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cboltz** [comment]
> I copied the files over my old server backup.. it was this actually same OS debian 9
> Copied with r-sync
> But idk why "in use" the fetchmail, vacation etc..
> I have "mail" database from my friend.. i dont know where can i download the real database on the NET.

That sounds like you copied over files from/to `/var/lib/mysql/`. That works if you copy over the whole directory (and stop mysql/mariadb before), but for sure won't work if you copy over a single database subdirectory. To be exact, the 3 tables you mentioned are InnoDB, while the (somewhat?) working ones are MyISAM.

If my guess is right, I'd recommend to delete your mail database (using `DROP DATABASE mail;`, and only if that fails delete it manually on disk), ask your friend to export the mail database with `mysqldump`, and then import this dump.

**Comment by zer0nem0** [comment]
Ok its worked..
I stopped... copied all of them from old server /var/lib.. and chown -R mysql:mysql before start now OK:D

Thanks!

Maybe i need some help later over postfix ssl TLS etc :)

KR: Alex

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by zer0nem0** [comment]
Hi

Pls help me again last time :D

i have this error:

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by zer0nem0** [comment]
Sorry again...

I have this error:

warning: /etc/postfix/main.cf, line 30: overriding earlier entry: smtpd_tls_security_level=encrypt

and my smtp test is:

Connecting to 188.165.52.172

220 s.localdomain ESMTP Postfix [672 ms]
EHLO keeper-us-east-1b.mxtoolbox.com
250-s.localdomain
250-PIPELINING
250-SIZE 10240000
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN [688 ms]
MAIL FROM:<supertool@mxtoolbox.com>
250 2.1.0 Ok [703 ms]
RCPT TO:<test@mxtoolboxsmtpdiag.com>
454 4.7.1 <test@mxtoolboxsmtpdiag.com>: Relay access denied [703 ms]

LookupServer 4250ms

I cant send and receive mail.. should i change something?

postfix/main.cf

relay_domains =
#virtual_alias_maps = proxy:pgsql:/etc/postfix/virtual_alias_maps.cf
#virtual_mailbox_domains = proxy:pgsql:/etc/postfix/virtual_mailbox_domains.cf
#virtual_mailbox_maps = proxy:pgsql:/etc/postfix/virtual_mailbox_maps.cf
virtual_mailbox_base = /home/vmail
virtual_mailbox_limit = 512000000
virtual_minimum_uid = 5000
virtual_transport = dovecot
virtual_uid_maps = static:5000
virtual_gid_maps = static:5000
local_transport = virtual
local_recipient_maps =
transport_maps = hash:/etc/postfix/transport

smtpd_sasl_auth_enable = yes
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination
smtpd_sasl_security_options = noanonymous
smtpd_sasl_tls_security_options =
smtpd_tls_auth_only = yes

smtpd_tls_cert_file = /etc/letsencrypt/live/alexcom.at/fullchain.pem
smtpd_tls_key_file = /etc/letsencrypt/live/alexcom.at/privkey.pem

smtpd_sasl_local_domain =
broken_sasl_auth_clients = yes
smtpd_tls_loglevel = 1
html_directory = /usr/share/doc/postfix/html
queue_directory = /var/spool/postfix
mydestination = localhost
virtual_mailbox_domains = mysql:/etc/postfix/mysql_virtual_domains_maps.cf
virtual_mailbox_maps = mysql:/etc/postfix/mysql_virtual_mailbox_maps.cf
virtual_alias_maps = mysql:/etc/postfix/mysql_virtual_alias_maps.cf
content_filter = smtp-amavis:[127.0.0.1]:10024
mailbox_command = /usr/lib/dovecot/dovecot-lda
smtpd_use_tls = yes
smtpd_tls_ciphers = high
tls_high_cipherlist=EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:+CAMELLIA256:+AES256:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!ECDSA:CAMELLIA256-SHA:AES256-SHA:CAMELLIA128-SHA:AES128-SHA

smtp_bind_address = xx.xx.xx.xx

Thanks!

KR: Alex

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DavidGoodwin** [comment]
> Sorry again... I have this error: warning: /etc/postfix/main.cf, line 30: overriding earlier entry: smtpd_tls_security_level=encrypt 

it's a warning, not an error. It's just saying you have the same configuration key listed twice in the config file ( look for the other smtpd_tls_security_level ... )

e.g.

```bash
$ postconf | grep smtpd_tls_s
postscreen_tls_security_level = $smtpd_tls_security_level
smtpd_tls_security_level = may
....
```

(I'd strongly suggest you use 'may' and not 'encrypt' as i doubt enough mail servers support TLS to do 'encrypt' ).
