### ISSUE TITLE
FetchmailHandler: "You must override domain_from_id()!"

### ISSUE THREAD

**Issue by Gurkengewuerz** [postfixadmin/postfixadmin#306]
Hey,

i installed the *master* branch recently, because i wanted to test out the bootstrap theme, and setted up fetchmail. After installing the pearl script from _ADDITIONS_ i tried to added a new server for fetchmail but I got the following error _[You must override domain_from_id()!](https://github.com/postfixadmin/postfixadmin/blob/80418e64127e13ea26252abe95ed306f499a2933/model/PFAHandler.php#L384)_

My temporary fix was to implement the following in FetchmailHandler.php ¯\_(ツ)_/¯
```
protected function domain_from_id() {
    return "";
}
```

Best geetings from Germany

**Comment by DavidGoodwin** [comment]
Works for me! thanks!
