### ISSUE TITLE
cannot use postfixadmin-cli tool from sourceforge

### ISSUE THREAD

**Issue by resonancellc** [postfixadmin/postfixadmin#309]
While attempting to run 

bash /postfix/scripts/postfixadmin-cli admin add superadmin@test.com --superadmin 1 --active 1 --password foobar12 --password2 foobar12

I continued to get:

Welcome to Postfixadmin-CLI v0.2
---------------------------------------------------------------
Error: invalid parameter --0 => postfixadmin-cli.php

Error: invalid parameter --1 => admin

Error: invalid parameter --2 => add

Error: invalid parameter --3 => superadmin@test.com

Error: invalid parameter --4 => --superadmin

Error: invalid parameter --5 => 1

Error: invalid parameter --6 => --active

Error: invalid parameter --7 => 1

Error: invalid parameter --8 => --password

Error: invalid parameter --9 => foobar12

Error: invalid parameter --10 => --password2

Error: invalid parameter --11 => foobar12

I backed up the associated php file.  Replaced with version on github.  Then it accepted the command.   Thought I should leave a note here to let you know about the issue on the sourceforge repo.

root@mail /var/www/html/postfix/scripts # cat postfixadmin-cli.php |wc -l
424
root@mail /var/www/html/postfix/scripts # mv postfixadmin-cli.php postfixadmin-cli.php.bak
root@mail /var/www/html/postfix/scripts # vi postfixadmin-cli.php
root@mail /var/www/html/postfix/scripts # cat postfixadmin-cli.php |wc -l                                         357
root@mail /var/www/html/postfix/scripts # bash postfixadmin-cli admin add superadmin@test.com --superadmin 1 --active 1 --password foobar12 --password2 foobar12

Welcome to Postfixadmin-CLI v0.3
---------------------------------------------------------------

The admin superadmin@test.com has been added!

---------------------------------------------------------------
root@mail /var/www/html/postfix/scripts #

**Comment by DavidGoodwin** [comment]
Sourceforge needs to be removed / deactivated or something.

**Comment by DavidGoodwin** [comment]
(it should behave better if you install / use what's here on github)
