### ISSUE TITLE
Feature Request: about mailbox deletion

### ISSUE THREAD

**Issue by coldsmile** [postfixadmin/postfixadmin#310]
I have configured [separate storage for attachments](https://doc.dovecot.org/settings/dovecot_core_settings/#mail-attachment-dir), so... to keep it clean, additional actions should be performed before db-record deletion...

It would be helpful to find config options like:
- mailbox_predeletion_script
- mailbox_deletion_disabled

**Comment by DavidGoodwin** [comment]
I think this might be best handled by some sort of additional hooks ....  see also 

https://github.com/postfixadmin/postfixadmin/issues/314

and

https://github.com/postfixadmin/postfixadmin/pull/338

and

https://github.com/postfixadmin/postfixadmin/pull/157 ....
