### ISSUE TITLE
setup.php ends in loop when creating superadmin

### ISSUE THREAD

**Issue by inoculator** [postfixadmin/postfixadmin#311]
Hi Team,
I have read some issues about this, where the last statement was "...it had to run twice.." o.s.
At the moment I run into this and even after 10 retries, there is no change, so what is wrong?

After performing the setup.php, I come to this point:

![2019-11-07-postfixadmin-setup-001](https://user-images.githubusercontent.com/14196051/68391770-979b8600-0168-11ea-86cb-003257c0c131.png)

Now I enter a password of my choice and click on "Generate password hash".
Result:
![2019-11-07-postfixadmin-setup-002](https://user-images.githubusercontent.com/14196051/68391872-cfa2c900-0168-11ea-94e8-4e57c39597a6.png)

Now I switch to my ssh console on the server and edit the "config.local.php" like so:
![2019-11-07-postfixadmin-setup-003](https://user-images.githubusercontent.com/14196051/68392075-4049e580-0169-11ea-8d68-7962c68b889f.png)
Next I reenter the just set password to the form and fill the fields for the superuser like this:
![2019-11-07-postfixadmin-setup-004](https://user-images.githubusercontent.com/14196051/68392200-8dc65280-0169-11ea-8861-3a4bd2b04d07.png)

And click "Admin hinzufügen" [add admin] -yea, I am from germany ;-)
This is the result:
![2019-11-07-postfixadmin-setup-005](https://user-images.githubusercontent.com/14196051/68392293-c8c88600-0169-11ea-8200-a5eb905d717a.png)

Watch the hash code. Even I have entered the correct password, it results in a complete different hash value.

And I can repeat this as often as I like. no change.
A check on the mysql database does not show any user being created.
What am I doing wrong?
br
Carsten

**Comment by DavidGoodwin** [comment]
the first part of the setup password is the salt, and that changes every time - so the entire hash will change each time.

Are you sure you're editing the 'right' config.local.php file? Is it actually looking in e.g. /etc/postfixadmin or something ?

Try sticking a : 

var_dump($CONF);
die('x');

in config.local.php and see if that causes $CONF to be printed out etc.

**Comment by inoculator** [comment]
okkkeeyyy.... blame it on me, or blame it on a lack of documentation.
Indeed there were two file pairs.
I started setting up with "/opt/postfixadmin" and was hit by "please link "./public" to your webserver.
So I switched and copied the two initial files into "./public"
As all the values for the database were correct, the setup now ran seamless. But when editing the "/opt/postfixadmin/public/config.local.php" the change was now read.
The scripts look for their config in the "/opt/postfixadmin" which I did not recognized.
When deleting these two files, the browser returns: "there is no "config.inc.php".
Moving the pair out of "../public" to "/opt/postfixadmin" did the trick.
Thanks for the quick help!
