### ISSUE TITLE
SCRAM-SHA-***(-PLUS) supports

### ISSUE THREAD

**Issue by Neustradamus** [postfixadmin/postfixadmin#313]
It is possible to add compatibility with Cyrus SASL which now supports:
- SCRAM-SHA-1
- SCRAM-SHA-1-PLUS
- SCRAM-SHA-224
- SCRAM-SHA-224-PLUS
- SCRAM-SHA-256
- SCRAM-SHA-256-PLUS
- SCRAM-SHA-384
- SCRAM-SHA-384-PLUS
- SCRAM-SHA-512
- SCRAM-SHA-512-PLUS
-> https://cyrusimap.org/sasl/sasl/authentication_mechanisms.html
-> https://github.com/cyrusimap/cyrus-sasl/commits/master

**Comment by DavidGoodwin** [comment]
postfixadmin is not the same as postfixadm .... they're two very different projects - albeit both using PHP.

postfixadmin already supports ....
 * sha-1
 * sha-256
 * sha-512
 * blowfish
 * anything dovecot supports via doveadm
 * mysql ENCRYPT (useful for PAM or just if you want to use whatever MySQL supports)
 * courier authlib (md5/md5raw/crypt/sha1).
...

**Comment by Neustradamus** [comment]
@DavidGoodwin: No, SHA-1, SHA-256, SHA-512 are not SCRAM-SHA-1, SCRAM-SHA-1-PLUS, SCRAM-SHA-224, SCRAM-SHA-224-PLUS, SCRAM-SHA-256, SCRAM-SHA-256-PLUS, SCRAM-SHA-384, SCRAM-SHA-384-PLUS, SCRAM-SHA-512, SCRAM-SHA-512-PLUS....

**Comment by DavidGoodwin** [comment]
my other point still stands - you reference postfixADM.com ... which is not this project.


I'd be more than happy to merge a PR for all of the above if someone understands the SCRAM protocol / behaviour.

**Comment by Neustradamus** [comment]
@DavidGoodwin: I have removed the bad link.
Can you reopen this ticket?

**Comment by DavidGoodwin** [comment]
I was assuming you'd confused the project with another etc etc .... which is why i closed it.

**Comment by DavidGoodwin** [comment]
https://github.com/pear/Auth_SASL2

**Comment by Neustradamus** [comment]
@DavidGoodwin: Happy New Year!
It has been solved?
The gift of the new year?

**Comment by DavidGoodwin** [comment]
Hah - if only - hence the 'wontfix' label. I was trying to cleanup the issue list a bit given it's a new year.

When I looked last, my limited understanding was there would be a 'server side' hash that needs generating for the SCRAM protocol to work.

I could not find any examples of SCRAM in PHP. I don't want to implement it if I can help it.

I could find the 'client' part - but that's of no use when it comes to generating the hash that we store within a database for e.g. dovecot to use.

**Comment by Neustradamus** [comment]
@DavidGoodwin: The important rule: When it is not solved, tickets must not be closed.

**Comment by DavidGoodwin** [comment]
I know, but realistically, I don't think it's likely this will ever be implemented (unless someone provides a patch/pull request).

Therefore, 'wontfix' + closing seems acceptable to me.
