### ISSUE TITLE
Wrong translation - italian

### ISSUE THREAD

**Issue by masbaehr** [postfixadmin/postfixadmin#318]
$PALANG['pSendmail_result_error'] = 'Impossibile creare la casella di posta! (%s)'; # XXX text change - new: Unable to send email to %s!
$PALANG['pSendmail_result_success'] = 'La casella di posta è stata creata! (%s)'; # XXX text change - new: Email sent to %s.

I don't know why it has been done like that but the actual correct text is the one on the comment. instead it shows "the mailbox has been created" on sending mail

**Comment by DavidGoodwin** [comment]
If I understand correctly, you're saying the translated Italian matches the comment, and therefore the translated string is in the 'wrong place' within the translation file?

**Comment by DavidGoodwin** [comment]
According to Google translate : 

 | italian | english |
| --- | ---|
| Impossibile creare la casella di posta!  | Unable to create mailbox! |
| La casella di posta è stata creata!| The mailbox has been created! |


So, it looks like the translation file needs updating; I'll resort using Google translate, so 

 'Unable to send email to Fred' becomes 'Impossibile inviare e-mail a Fred' 

and

 'Email sent to Fred' becomes 'Email inviata a Fred'

**Comment by DavidGoodwin** [comment]
see 55661a80c60bdc43bb91aee780acbb06251bb33e

**Comment by masbaehr** [comment]
Thanks! Sorry i did not have the time to respond earlier. But everything looks good now!
