### ISSUE TITLE
I received an error while trying to edit a mailbox named with a period.

### ISSUE THREAD

**Issue by touristo7** [postfixadmin/postfixadmin#319]
I received an error while trying to edit a mailbox named with a period. For example Mr.Smith@my.domain
The edit form does not display the user name, and attempting to change any field (name, password, etc.) results in an error.

**Comment by trippleflux** [comment]
Found a workaround or fix?

find the following in the functions.inc.php
```
    if (!preg_match('/^[-!#$%&\'*+\\.\/0-9=?A-Z^_{|}~]+' . '@' . '[^@]+$/i', $ce_email)) {
```

change it into : 
```
    if (!preg_match('/^[-!#$%&\'*+\\.\/0-9=?A-Z^_{|}~]+@[^@]+$/i', $ce_email)) {
````

**Comment by DavidGoodwin** [comment]
>     if (!preg_match('/^[-!#$%&\'*+\\.\/0-9=?A-Z^_{|}~]+' . '@' . '[^@]+$/i', $ce_email)) {
> ```
> 
> change it into :
> 
> ```
>     if (!preg_match('/^[-!#$%&\'*+\\.\/0-9=?A-Z^_{|}~]+@[^@]+$/i', $ce_email)) {
> ```

Aside from concatenating that string, what change did you make? Just concatenating the regex string isn't going to change it's behaviour ....

**Comment by trippleflux** [comment]
@DavidGoodwin 
Only deleted this part in the middle of the regex :
```
' . '@' . '
```
Was doing some testing on regexr.com.

**Comment by DavidGoodwin** [comment]
Your '_change it to...._' above doesn't include the deletion of that bit though :-)

**Comment by trippleflux** [comment]
@DavidGoodwin 
I think i did, please check/compare again, what i have meant by ' . '' . ' is the "' . '@' . '", i wrote ' . '' . ' because we need to add "@" inclusion to the regex.

**Comment by DavidGoodwin** [comment]
Can you change this into a pull request please?

**Comment by DavidGoodwin** [comment]
I can't replicate this.

**Comment by DavidGoodwin** [comment]
* The system won't let you change an existing mailbox name.
 * The system will let you edit an existing mailbox (e.g. changing the password or user's name).

https://github.com/postfixadmin/postfixadmin/blob/master/tests/MailboxHandlerTest.php#L31
