### ISSUE TITLE
Wrong sql query for password_expiration

### ISSUE THREAD

**Issue by puflet** [postfixadmin/postfixadmin#323]
I have installed the new version, in order to implement the password expiration functionality.
Everything went smooth, but saw that all accounts are showing as "expired" in the interface. After some debugging, found that the actual query, that is sent to the sql server is:
SELECT * FROM `mailbox` WHERE username = 'puflet@[removed].com' AND password_expiry <= 'now()' AND active = '1'
As you can see "now()" is not transformed to date, but taken literally.
My quick and dirty 'fix' was to edit functions.inc.php and replace the variable in the query with the hardcoded 'now'.

**Comment by DavidGoodwin** [comment]
Thanks for the bug report!
