### ISSUE TITLE
Installation hangs on "Everything seems fine"

### ISSUE THREAD

**Issue by stone212** [postfixadmin/postfixadmin#326]
Ubuntu 18.04
mariadb
PHP 7.2

fresh `dpkg-reconfigure` of `postfixadmin`

Running setup.php shows me no errors in config and then:

`Everything seems fine... attempting to create/update database structure`

But there is no change after 30 minutes.

Notes:

1.  I ran `mysql> SET GLOBAL default_storage_engine = 'InnoDB';`

2. I am using the current/updated `update.php` from this git repo.

viewing the login page shows this error:

```
DEBUG INFORMATION:
Invalid query: Table 'postfixadmin.config' doesn't exist

Check your error_log for the failed query.

Please check the documentation and website for more information. 
```

What can I do to de-bug this error and provide more information?  Thank you.

**Comment by DavidGoodwin** [comment]
Can you retry ... with the latest update.php after dropping the postfixadmin database and recreating it.

(e.g something like 

 ```echo 'drop database postfixadmin' | mysql --defaults-extra-file=/etc/mysql/debian.cnf ``` 

and 

```echo 'create database postfixadmin' | mysql --defaults-extra-file=/etc/mysql/debian.cnf ```

**Comment by stone212** [comment]
@DavidGoodwin I'm sorry I did not see your comment from 18 days ago.  I solved the problem in the other thread so I have not looked at PFadmin for a few weeks.  I guess Everything seems fine for real now.
