### ISSUE TITLE
setup.php says imap is ok - its not even installed...

### ISSUE THREAD

**Issue by Benman2785** [postfixadmin/postfixadmin#329]
i did run setup.php and it said imap is OK

i neither had php7.4-imap nor dovecot and not even postfix installed...

that needs a fix

**Comment by DavidGoodwin** [comment]
Nah; setup is looking for IMAP support in PHP - it doesn't care about dovecot or even postfix running locally - as potentially they could be on other server(s)

(postfixadmin could be just installed on a standalone webserver with nothing else on it)

**Comment by DavidGoodwin** [comment]
(The imap stuff is only used in one certain edge case, and even if it's not present, it doesn't really matter ... it's a quite a weak dependency ).
