### ISSUE TITLE
Bug: Editing (super) admin user does not check password and password2 to match

### ISSUE THREAD

**Issue by veitw** [postfixadmin/postfixadmin#331]
Hi,

I noticed that when editing a (super) admin, the "password" and "password2" values are not compared to check whether they match, causing the value of "password" to be set even if "password2" is empty.
This is especially dangerous if ones admin login credentials are stored in the webbrowser keychain, which fills your own password into every other field named password, resulting in accidentally setting your own password for other (super) admins.

As I assume the latter is a common issue, I'd also suggest that the "password" input on the login page is renamed, so stored passwords do no longer interfere with the admin and mailbox edit masks.

Best regards,
// Veit

**Comment by DavidGoodwin** [comment]
Hopefully relevant - https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
