### ISSUE TITLE
Mojibake in message sent from vacation.pl

### ISSUE THREAD

**Issue by jackdeguest** [postfixadmin/postfixadmin#337]
When adding a vacation text in non us-ascii such as Japanese, or French, then this vacation script will send a mail with mojibake.
The software does properly transcode mail from utf8 in database into perl internal extended utf8 version, but does not encode it back to standard utf8 before creating the mail.
Version used is Postfixadmin 3.2 and vacation version 4.2
I have attached a patch that solves this problem. Confirmed with proper testing.
[vacation.patch.txt](https://github.com/postfixadmin/postfixadmin/files/4280388/vacation.patch.txt)

**Comment by DavidGoodwin** [comment]
Thank you!
