### ISSUE TITLE
Error: value=127, first line of output=" while reading response header from upstream

### ISSUE THREAD

**Issue by ozgurkazancci** [postfixadmin/postfixadmin#339]
Greetings. when I try to delete a mailbox via PostFixAdmin, I get the following error (within nginx's log file) :

PHP message: Running /usr/bin/doas -u vmail /var/pfix/postfixadmin-mailbox-postdeletion.sh 'test@mydomain.com' 'mydomain.com' yielded return value=127, first line of output= while reading response header from upstream." 

Running the same command/script in the shell by 'www' (web server) user works fine. 

Any idea on how can I solve this, would be much appreciated! 

P.S: The OS is OpenBSD, and 'doas' does exactly what sudo does. 

P.S-2: Nginx is chrooted into /var/www under OpenBSD by the default installation. Could that be the main issue? But IF so, how could Roundcube's password-change plugin call (and it works) a line like:

$config['password_dovecotpw'] = '/usr/local/bin/doveadm pw';

Got confused a lot..

Many thanks.

**Comment by DavidGoodwin** [comment]
Try putting 'set -x' near the top of the post deletion script ?

It's more likely there is a path or something that's not matched up. I doubt it's been tested very well against OpenBSD.

**Comment by kr1pt0ph0b14** [comment]
Nothing has changed. 

Got the same output in the log file. One thing: I tried to rename/move /usr/bin/doas binary, and re-tried it again, the output was still same. Whatever happens, obviously happens before reaching&calling /usr/bin/doas. 

Any idea?

**Comment by DavidGoodwin** [comment]
Is there something like apparmor or selinux which is stopping the webserver from executing the shell script?

Is the shell script executable?

**Comment by kr1pt0ph0b14** [comment]
Well, obviously on OpenBSD no daemon like selinux exists. And I'm not aware of any prevention by the system/nginx. (As I mentioned earlier, Roundcube executes "/usr/local/bin/doveadm" fine. 

An another try: I just wanted to set the binary that Roundcube calls and executes:
$CONF['mailbox_postdeletion_script'] = '/usr/local/bin/doveadm pw';
(I know that's not where it should be - but just to see how it performs and what it outputs out of curiosity), the error is still same:
2020/03/08 11:37:43 [error] 17430#0: *1344 FastCGI sent in stderr: "PHP message: Running /usr/local/bin/doveadm pw 'test@mydomain.com' 'mydomain.com' yielded return value=127, first line of output=" 

So it seems there must be something wrong with the way PostfixAdmin calls/executes that line?

**Comment by kr1pt0ph0b14** [comment]
Running the script in the shell by www (nginx) user:
kript0f0bya$ su - www
kript0f0bya$ id
uid=67(www) gid=67(www) groups=67(www)

kript0f0bya$ /usr/bin/doas -u vmail /var/pfix/postfixadmin-mailbox-postdeletion.sh 'test@mydomain.com' 'mydomain.com' (trying test@mydomain.com which is valid)
kript0f0bya# 
kript0f0bya# ls -al /usr/local/virtual/deleted/mailboxes/mydomain.com/
total 20
drwxr-xr-x   5 vmail  vmail   512 Mar  8 11:46 .
drwx------   3 vmail  vmail   512 Mar  7 18:59 ..
drwx------   5 vmail  vmail   512 Mar  8 11:45 2020-03-08_11:45:59_test
kript0f0bya# 

So it works in the shell.

**Comment by DavidGoodwin** [comment]
> Well, obviously on OpenBSD no daemon like selinux exists. And I'm not aware of any prevention by the system/nginx. (As I mentioned earlier, Roundcube executes "/usr/local/bin/doveadm" fine.
>

I know OpenBSD etc isn't going to have SELinux; perhaps I should have put more emphasis on 'something like' ....  :-)


`2020/03/08 11:37:43 [error] 17430#0: *1344 FastCGI sent in stderr: "PHP message: Running /usr/local/bin/doveadm pw 'test@mydomain.com' 'mydomain.com' yielded return value=127, first line of output="`


See: https://stackoverflow.com/questions/1763156/127-return-code-from

**Comment by kr1pt0ph0b14** [comment]
I'm sorry, it was my bad didn't really noticed "something"  :) 

Anyway, since days I've been reading all those S.O. posts. The link has indeed useful info regarding the status code, but that's all. Nothing more. 

Could we somehow execute the file postfixadmin-mailbox-postdeletion.sh in an another way? 
At the worst scenario, I was thinking implementing something like mailboxes-to-delete.txt, within the chroot /var/www, and execute it via crontab from time to time.. No idea how that'd really work - though... If a user create a mailbox, delete and create it again and start using it, and cron job would still erase it because it was listed in that file once..? Dunno.. So confused.

And, noone uses PostfixAdmin on a OpenBSD?

**Comment by DavidGoodwin** [comment]
Well, it's probably more of ...

What percentage of Postfixadmin users run OpenBSD ? And have a mailbox post deletion script configured .... and perhaps also those who are running the same version of OpenBSD as you .... there may not be very many of them?

I've no idea of how many Postfixadmin users there are. 

https://qa.debian.org/popcon.php?package=postfixadmin 

Try reducing the script down to something that's just e.g. doing `echo "hello world" ` or something else, and see if that behaves differently? 

Try moving the script into a different directory - does that have an impact on it working ?
