### ISSUE TITLE
vacation.pl : Log4perl: Seems like no initialization happened. Forgot to call init()?

### ISSUE THREAD

**Issue by VictorJosso** [postfixadmin/postfixadmin#340]
Hi, 

I know that my issue is very close to #160 but I didn't find an answer there. So here is my concern. I have set up the vacation script as told in the [documentation](https://github.com/postfixadmin/postfixadmin/blob/master/VIRTUAL_VACATION/INSTALL.md) and here are my postfix logs: `mail postfix/pipe[1078]: 57A6D204EE: to=<test#domain.tld@autoreply.domain.tld>, orig_to=<test@domain.tld>, relay=vacation, delay=0.53, delays=0.08/0.02/0/0.43, dsn=2.0.0, status=sent (delivered via vacation service (Log4perl: Seems like no initialization happened. Forgot to call init()?))`

There was nothing more and the error happened every time. So I decided to strace the execution and here is what I found : 
```socket(AF_INET, SOCK_STREAM, IPPROTO_TCP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(3306), sin_addr=inet_addr("192.168.0.3")}, 16) = 0
setsockopt(3, SOL_IP, IP_TOS, [8], 4)   = 0
setsockopt(3, SOL_TCP, TCP_NODELAY, [1], 4) = 0
setsockopt(3, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
recvfrom(3, "p\0\0\0\n5.5.5-10.2.31-MariaDB-1:10."..., 16384, 0, NULL, NULL) = 116
brk(0x56115bb5a000)                     = 0x56115bb5a000
stat("/usr/share/mysql/charsets/Index.xml", 0x7ffe7a8fd9f0) = -1 ENOENT (No such file or directory)
futex(0x7f4c83e6bee0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
sendto(3, "\322\0\0\1\217\242>\0\0\0\0@\10\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 214, 0, NULL, 0) = 214
recvfrom(3, "\7\0\0\2\0\0\0\2@\0\0", 16384, 0, NULL, NULL) = 11
poll([{fd=3, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
sendto(3, "\30\0\0\0\3SET CHARACTER SET utf8;", 28, 0, NULL, 0) = 28
recvfrom(3, "\7\0\0\1\0\0\0\2\0\0\0", 16384, 0, NULL, NULL) = 11
write(2, "Log4perl: Seems like no initiali"..., 72) = 72
read(0, "Hello World!\n", 8192)         = 13
read(0, "", 8192)                       = 0
```

I'm not familiar with strace but I believe there is a problem here. If someone has a clue on what is going on I would be very happy ;)

**Comment by DavidGoodwin** [comment]
Hmm, do you know what version of log4perl you have installed ?

On my desktop, I have Debian Buster's 1.49-1 and it doesn't seem to output anything about not being initialised.

**Comment by VictorJosso** [comment]
Hi, thanks for your answer. Here is the output of apt list for this package : 
`liblog-log4perl-perl/oldstable,now 1.48-1+deb9u1 all [installed]`

I do not have Debian buster installed but Debian stretch. In fact, the script is running inside of a docker container, witch runs Debian 9.

**Comment by DavidGoodwin** [comment]
I'm not sure if this is relevant - my perl is rusty - 

https://metacpan.org/pod/Log::Log4perl::FAQ#Log4perl-complains-that-no-initialization-happened-during-shutdown!
