### ISSUE TITLE
Invalid token! (CSRF check failed)

### ISSUE THREAD

**Issue by xpunkt** [postfixadmin/postfixadmin#341]
postfixadmin version 3.2.3, php version 7.4.3
same problem with php 7.3.15 and 7.2.28

am i alone ? :(

**Comment by xpunkt** [comment]
Google Chrome er opdateret
Version 80.0.3987.132 (Officiel version) (64-bit)

failed with that browser, its seems no error with microsoft edge ?

**Comment by DavidGoodwin** [comment]
if your token is invalid, it implies there's a problem with session support (are you blocking cookies)?

Is anything logged in the browser's development tools console ? Does the network log show a cookie being sent - and if so, does the PHP session id remain stable ?

**Comment by xpunkt** [comment]
it was a chrome plugin that manglede session, removed that plugin and all is now ok
