### ISSUE TITLE
Include hash-type in password hash

### ISSUE THREAD

**Issue by Yannik** [postfixadmin/postfixadmin#344]
`doveadm pw` generates passwords in the following way:
```
doveadm pw -p hello -s SHA256-CRYPT
{SHA256-CRYPT}$5$VhqhhsXJtPFeBX9e$kz3/CMIEu80bKdtDAcISIrDfdwtc.ilR68Vb3hNhu/7
```
This is exactly what I need in my database.

Unfortunately, I cannot use `CONF['encrypt'] = 'dovecot:SHA256-CRYPT';`, because `doveadm pw `   fails due to `/etc/dovecot/dovecot.conf` not being readable by my php user: 

```
doveadm pw
doveconf: Fatal: open(/etc/dovecot/dovecot.conf) failed: Permission denied
``` 

As `doveadm pw` is not available on this system, I'd like to use the encrypt type `php_crypt` introduced in #170.

Unfortunately, this generates hashes without the hash-type prefix: `$6$GW9o.Hfg8T3cI8Ho$TpUqcFrhjQg2ASNuvPJc0n734uwnSs`.

Would it be possible to prefix these hashes with the hash-type, like `doveadm pw` does?

**Comment by DavidGoodwin** [comment]
Try editing functions.inc.php and look for the _pacrypt_php_crypt(... ) function. Try replacing it with the below.

```
function _pacrypt_php_crypt($pw, $pw_db)
{
    $configEncrypt = Config::read_string('encrypt');

    // use PHPs crypt(), which uses the system's crypt()
    // same algorithms as used in /etc/shadow
    // you can have mixed hash types in the database for authentication, changed passwords get specified hash type
    // the algorithm for a new hash is chosen by feeding a salt with correct magic to crypt()
    // set $CONF['encrypt'] to 'php_crypt' to use the default SHA512 crypt method
    // set $CONF['encrypt'] to 'php_crypt:METHOD' to use another method; methods supported: DES, MD5, BLOWFISH, SHA256, SHA512
    // set $CONF['encrypt'] to 'php_crypt:METHOD:difficulty' where difficulty is between 1000-999999999
    // set $CONF['encrypt'] to 'php_crypt:METHOD:difficulty:PREFIX' to prefix the hash with the {PREFIX} etc.
    // tested on linux

    $prefix = '';

    if (strlen($pw_db) > 0) {
        // existing pw provided. send entire password hash as salt for crypt() to figure out
        $salt = $pw_db;

        // if there was a prefix in the password, use this (override anything given in the config).

        if (preg_match('/^\{([-A-Z0-9]+)\}(.+)$/', $pw_db, $method_matches)) {
            $salt = $method_matches[2];
            $prefix = "{" . $method_matches[1] . "}";
        }

    } else {
        $salt_method = 'SHA512'; // hopefully a reasonable default (better than MD5)
        $hash_difficulty = '';
        // no pw provided. create new password hash
        if (strpos($configEncrypt, ':') !== false) {
            // use specified hash method
            $spec = explode(':', $configEncrypt);
            $salt_method = $spec[1];
            if (isset($spec[2])) {
                $hash_difficulty = $spec[2];
            }
            if (isset($spec[3])) {
                $prefix = $spec[3]; // hopefully something like {SHA256-CRYPT}
            }
        }
        // create appropriate salt for selected hash method
        $salt = _php_crypt_generate_crypt_salt($salt_method, $hash_difficulty);
    }

    $password = crypt($pw, $salt);

    return "{$prefix}{$password}";
}
```

And then change your config encrypt setting to e.g. 

php_crypt:SHA256::{SHA256-CRYPT}

I've tested this a bit locally; so I think it'll work ...

**Comment by DavidGoodwin** [comment]
@Yannik  - please can you confirm if this ... thanks!

**Comment by tokul** [comment]
{SHA256-CRYPT} is still {CRYPT}. Crypt type is detected in hashed string itself. There is no need to duplicate that information.

**Comment by tokul** [comment]
"drop apparently unnecessary -CRYPT suffix - see #344"

Ehm. {SHA256}.... is one type of hash and {CRYPT}$5$ is other.

At least they would be in LDAP passwords. Was away for some time and my code ends at SHA1. Maybe people did not start calling SHA256 hashes SHA256_CRYPT for funzies.

**Comment by DavidGoodwin** [comment]
Yeah, the comment (and test) no longer have the -CRYPT in the starting {...} bit.

(so {SHA256-CRYPT}.... -> {SHA256}.... ) .

**Comment by tokul** [comment]
IMHO

{SHA256} is '{SHA256}' . base64_encode( mhash( MHASH_SHA256, $pass) );

"sha256 crypt" is '{CRYPT}' . crypt($pass,'$5$' . $salt)

and you assume that crypt supports CRYPT_SHA256, if you are not checking the constant.

**Comment by DavidGoodwin** [comment]
*Shrug* I'm no expert .... the prefix is just a textual blob the code is putting in place, it could be anything. 

What's going into the config option as the bit in the { .... } at the end is just a label so both of these would result in the same sort of hash being produced.

 * php_crypt:SHA256::{SHA256-CRYPT}
 * php_crypt:SHA256::{CRYPT}

mhash has been deprecated from PHP so that's not available to use any longer.

**Comment by tokul** [comment]
> mhash has been deprecated from PHP so that's not available to use any longer.

https://www.php.net/hash

Drop in replacement for mhash with nearly identical syntax.

**Comment by BotoX** [comment]
Thanks, this is much less cumbersome with dovecot than using /usr/bin/doveadm pw (which loves complaining about permissions for stuff it absolutely needs no access to)
Would be nice to include it in master.
The commit kind of disappeared in the void: https://github.com/postfixadmin/postfixadmin/commit/d9f38e8ee7b2f78e3c0e3e5238e609643721a71b

**Comment by DavidGoodwin** [comment]
See also : https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/HASHING.md
