### ISSUE TITLE
error: Mysql functions not available

### ISSUE THREAD

**Issue by vadimkim** [postfixadmin/postfixadmin#345]
Hi!
After set of PHP and MySQL updates postfixadmin stops working. Have an error while trying to load login.php

> DEBUG INFORMATION:
> MySQL 4.1 functions not available! (php5-mysqli installed?)
> database_type = 'mysqli' in config.inc.php, are you using a different database?

MySQL version 5.7.29
PHP 7.2.29

Help me to find the problem. Thanks

**Comment by vadimkim** [comment]
PostfixAdmin 3.2.3

**Comment by DavidGoodwin** [comment]
I can't see how you can get that message from 

https://github.com/postfixadmin/postfixadmin/blob/postfixadmin_3.2/public/setup.php

**Comment by vadimkim** [comment]
let me check... I is not a new installation - it worked more than a year, but suddenly stops working

**Comment by vadimkim** [comment]
Sorry for the late reply - has prepared for debugging, but it was not necessary. Actually there is no error. Problem was at module mysqli that I have installed after problem has been detected and forgot to re-start php-fpm service. My bad. After php-fpm restart error disappeared.
