### ISSUE TITLE
postfix.admin 

### ISSUE THREAD

**Issue by viorel30** [postfixadmin/postfixadmin#346]
Is there an API for updating postfix.admin aliases?
I wish that when I add an email address I can also select the alias to which it will be added

**Comment by DavidGoodwin** [comment]
There is scripts/postfixadmin-cli which might allow you to do what you want from the command line?

**Comment by viorel30** [comment]
I would like to know if it is possible to add an email address in an alias, automatically

**Comment by DavidGoodwin** [comment]
If you wanted to add an alias based on some custom PHP logic after you've added a mailbox, you could write something to go in the config maildir_name_hook setting.

**Comment by viorel30** [comment]
I want certain addresses to be able to automatically go into a defined alias. This thing is possible?

**Comment by DavidGoodwin** [comment]
Technically yes, but I'm not sure of the best way to do it.

You could use the maildir_name_hook - so after adding an address, it calls the CLI to add something. It feels a bit yucky calling the CLI interface to do that, so perhaps you'd be better off calling something in the database to add something to an existing alias?
