### ISSUE TITLE
create_page_browser MySQL query syntax error

### ISSUE THREAD

**Issue by userabuser** [postfixadmin/postfixadmin#349]
### **Version**

3.2 - 2018/05/02

### **Issue**

In MySQL 8.* the following query located in `functions.inc.php` line `540` results in an error:

```sql
SELECT *
FROM (
	SELECT `mailbox`.username AS label, @row:= @row+ 1 AS row
	FROM `mailbox`
	LEFT JOIN `alias` ON `mailbox`.username=`alias`.address
	LEFT JOIN `vacation` ON `mailbox`.username=`vacation`.email
	WHERE `mailbox`.domain='example.com'
	ORDER BY `mailbox`.username 
) idx
WHERE MOD(idx.row, 10) IN (0,9) OR idx.row = 15
```

### Error
```
Invalid query: You have an error in your SQL syntax; check the manual that corresponds 
to your MySQL server version for the right syntax to use near 'row  FROM `mailbox`  
LEFT JOIN `alias` ON `mailbox`.username=`alias`.address  L' at line 2
```

It appears that the session variable `@row` cannot be the same as the alias `AS row`.

### **Solution**
To fix the issue I implemented:

 ```SELECT `mailbox`.username AS label, @row:= @row+ 1 AS row_index```

Instead of:

 ```SELECT `mailbox`.username AS label, @row:= @row+ 1 AS row```

Example:

```sql
SELECT *
FROM (
	SELECT `mailbox`.username AS label, @row:= @row+ 1 AS row_index
	FROM `mailbox`
	LEFT JOIN `alias` ON `mailbox`.username=`alias`.address
	LEFT JOIN `vacation` ON `mailbox`.username=`vacation`.email
	WHERE `mailbox`.domain='example.com'
	ORDER BY `mailbox`.username 
) idx
WHERE MOD(idx.row_index, 10) IN (0,9) OR idx.row_index= 15
```

I'm not sure which version of MySQL this particular change has come into effect, I suspect it may exist in versions beneath `8.*` however I've not had the opportunity to test.

I am unable to submit a PR at the moment, however hopefully this may help others.

**Comment by userabuser** [comment]
Of course, I've just noticed:

https://github.com/postfixadmin/postfixadmin/pull/175

I've installed via `apt install postfixadmin` so this may be out of data with master and current releases.

**Comment by userabuser** [comment]
Closing.

No longer an issue in version 3.2.1 and above.

If following installation method number in [INSTALL.TXT](https://github.com/postfixadmin/postfixadmin/blob/master/INSTALL.TXT#L40) and running MySQL >= 8 be sure to alter the version of the release:

```
1. Unarchive new Postfix Admin
------------------------------
  ...snipped
  $ wget -O postfixadmin.tgz https://github.com/postfixadmin/postfixadmin/archive/postfixadmin-3.2.tar.gz
```
To:

```
1. Unarchive new Postfix Admin
------------------------------
  ...snipped
  $ wget -O postfixadmin.tgz https://github.com/postfixadmin/postfixadmin/archive/postfixadmin-3.2.1.tar.gz
```

Or the latest applicable version of a release: 

- https://github.com/postfixadmin/postfixadmin/releases 

(if not installing via RPM/DEB).

**Comment by DavidGoodwin** [comment]
Thanks for reporting - INSTALL.TXT has been updated ....
