### ISSUE TITLE
Cannot install postfixadmin on AWS EC2 instance

### ISSUE THREAD

**Issue by zeyingli** [postfixadmin/postfixadmin#35]
I have checked everything and made sure all fields filled in are correct.
----------------------------------------------------------------------------------------
Postfix Admin Setup Checker

Running software:

PHP version 7.0.15-0ubuntu0.16.04.4
Apache/2.4.18 (Ubuntu)
Checking for dependencies:

Magic Quotes: Disabled - OK
Depends on: presence config.inc.php - OK
Checking $CONF['configured'] - OK
Depends on: MySQL 4.1 - OK 
(change the database_type to 'mysqli' in config.inc.php if you want to use MySQL)
Depends on: PostgreSQL - OK 
(change the database_type to 'pgsql' in config.inc.php if you want to use PostgreSQL)
Error: Can't connect to database
Please edit the $CONF['database_*'] parameters in config.inc.php.
DEBUG INFORMATION:
MySQL 3.x / 4.0 functions not available! (php5-mysql installed?)
database_type = 'mysql' in config.inc.php, are you using a different database?

Depends on: session - OK
Depends on: pcre - OK
Depends on: multibyte string - OK
Depends on: IMAP functions - OK
Please fix the errors listed above.
-----------------------------------------------------------------------------------------------------

**Comment by zeyingli** [comment]
// Database connection details.
$CONF['database_type'] = 'mysqli';
$CONF['database_host'] = 'localhost';
$CONF['database_user'] = 'postfix';
$CONF['database_password'] = 'postfixadmin';
$CONF['database_name'] = 'postfix';

**Comment by zeyingli** [comment]
MySQL Connection Tester

**Connection test result: PASSED**

Host name: localhost
Database name: postfix
Username: postfix
Password: postfixadmin

Test Connection

**Comment by cboltz** [comment]
> DEBUG INFORMATION:
> MySQL 3.x / 4.0 functions not available! (php5-mysql installed?)
> database_type = 'mysql' in config.inc.php, are you using a different database?

This is a very strong indication that you have `$CONF['database_type'] = 'mysql';` somewhere, and that it overrides the mysqli in the config you pasted above. (If in doubt, grep your config files for "database_type".)
