### ISSUE TITLE
transport_maps and virtual_transport conflict?

### ISSUE THREAD

**Issue by ZsZs73** [postfixadmin/postfixadmin#350]
Hi,
This is rather a clarification request than an issue.
I have the following virtual configs in postfix:
```# Domains managed by this host
virtual_mailbox_domains = proxy:pgsql:/etc/postfix/pgsql_virtual_domains_maps.cf
# Delivery method for domains in $virtual_mailbox_domains
virtual_transport = lmtp:unix:private/dovecot-lmtp
# Mailboxes managed by this host
virtual_mailbox_maps =
  proxy:pgsql:/etc/postfix/pgsql_virtual_mailbox_maps.cf,
  proxy:pgsql:/etc/postfix/pgsql_virtual_alias_domain_mailbox_maps.cf
# Aliases managed by this host
virtual_alias_maps =
  proxy:pgsql:/etc/postfix/pgsql_virtual_alias_maps.cf,
  proxy:pgsql:/etc/postfix/pgsql_virtual_alias_domain_maps.cf,
  proxy:pgsql:/etc/postfix/pgsql_virtual_alias_domain_catchall_maps.cf
# Relayed domains
relay_domains = proxy:pgsql:/etc/postfix/pgsql_relay_domains.cf
# Transport maps
transport_maps = 
  proxy:pgsql:/etc/postfix/pgsql_transport_maps.cf,
  hash:/etc/postfix/transport
```
Note that I have two transport configs:
- transport_maps: 
  - pgsql_transport_maps.cf: set different transport method per domain from the DB
  - /etc/postfix/transport: define extra transports (ex: vacation)
- virtual_transport: to do the final delivery via dovecot (I'd keep dovecot due to sieve capability)

The problem I face with is that if both `transport_maps=` and `virtual_transport=` are defined in `main.cf` then `virtual_transport` gets ignored. According to the postfix [docs](http://www.postfix.org/postconf.5.html#virtual_transport) it is by design: _"**virtual_transport (default: virtual)**
The default mail delivery transport and next-hop destination for final delivery to domains listed with $virtual_mailbox_domains. This information can be overruled with the transport(5) table."_
The output of postmap -q is:
```
postmap -q mydomain.com pgsql:/etc/postfix/pgsql_transport_maps.cf
virtual
```
so the mail gets delivered with `virtual` transport instead of `lmtp`

The only 'workaround' I found is to replace:
```
$CONF['transport_options'] = array (
    'virtual',  // for virtual accounts
    'local',    // for system accounts
    'relay'     // for backup mx
);
```
with
```
$CONF['transport_options'] = array (
    'lmtp:unix:private/dovecot-lmtp',  // for virtual accounts
    'local',    // for system accounts
    'relay'     // for backup mx
);
```
in `config.local.php` and change the transport value for the domain.
This way `virtual_transport` is not needed anymore.
Is the above how it is intended to work, or I missed something?

**Comment by DavidGoodwin** [comment]
What's in /etc/postfix/pgsql_transport_maps.cf ?

Can't you just change the SQL query in pgsql_transport_maps.cf to default to lmtp (if that's what you want) ?

(I'm not sure if I totally understand your problem; as I've never needed transport maps to come from the database)

**Comment by ZsZs73** [comment]
David, thanks for your reply.
The query in `pgsql_transport_maps.cf` is adapted from #292 to PostgreSQL:
```
query = SELECT transport FROM domain WHERE domain='%s' AND active
```
The value of 'transport' can be selected from the array `$CONF['transport_options']`

Ooops, just found in #321 that the `pgsql_relay_domains.cf` should be also adapted to use transport instead of backupmx as follows:
```
query = SELECT domain FROM domain WHERE domain='%s' AND active AND (transport LIKE 'smtp%' OR transport LIKE 'relay%')
```
and consequently `pgsql_virtual_domain_maps.cf` should be adapetd also:
```
query = SELECT domain FROM domain WHERE domain='%s' AND active AND NOT (transport LIKE 'smtp%' OR transport LIKE 'relay%')
```

'backupmx' field's value is irrelevant as it is not used in any queries anymore. 
Would it be possible to:
- make 'backupmx' visibility configurable, like the transport field, ex: `$CONF['backupmx'] = 'NO';`
- or `$CONF['transport'] = 'YES';` could make 'backupmx' invisible, as IMHO 'transport' and 'backupmx' are kind of redundant.

Maybe it would also make sense to make it clear that using 'transport_map' overrides the setting in 'virtual_transport'.
If you agree I can create a separate PRs for the above.

**Comment by DavidGoodwin** [comment]
Er, I use backupmx on my mail server - 

relay_domains = .... proxy:pgsql:/etc/postfix/pgsql/relay_domains.cf

and relay_domains.cf contains :

```
user = postfix
password = password
hosts = localhost
dbname = postfix
query = SELECT domain FROM domain WHERE domain='%s' and backupmx = true
```

My virtual_domain_maps.cf file has a query of  : 

```
query = SELECT domain FROM domain WHERE domain='%s' and backupmx = false and active = true
```

**Comment by DavidGoodwin** [comment]
Please feel free to create PRs for the above as you see appropriate.
