### ISSUE TITLE
FREQ: Add support for multi-relay mail architectures

### ISSUE THREAD

**Issue by rootwyrm** [postfixadmin/postfixadmin#354]
This one's been a bit of a thorn in my side for quite a while. Postfixadmin doesn't really mesh well out of the box with more complex/advanced architectures, in part because it only understands the concept of 'backupmx.' In a typical semi-complex scenario, postfixadmin itself will NOT be running on the mail or database server, the database will be replicated to one or more sites with each site serving a specific domain.

Because of the way PostfixAdmin handles servers, it doesn't handle this well. Instead one has to use selective replication and multiple PostfixAdmin installations (which is undesirable for many reasons) or basically introduce significant hard-coding that renders the `backupmx` context useless. Hopefully the following illustration is illuminating:

![Drawing1](https://user-images.githubusercontent.com/2403335/81203226-b94dbc80-8f95-11ea-97d8-cefde6113a1d.png)

The solution I would propose to this is to introduce the concept of gateways to PostfixAdmin. A gateway is a specific server which serves as the primary or secondary relay or MX associated to a specific domain configured within PostfixAdmin. In the illustration here, "example.com" is the primary relay for the domain "example.com", and "contoso.com" is the primary relay for "contoso.com", and each site has it's own replica of the single PostfixAdmin database. PostfixAdmin itself and the main database lives in a secure enclave with replication being performed over TLS1.3.

Unfortunately, I am very much not a PHP person. However, I am a database person, so at least there's that. ;) So I have come up with a rough draft which is based along the lines of what I'm using to achieve similar behavior currently with a single central PostfixAdmin installation, database replication to multiple sites, and specific relays for each domain.

```
-- Version proposed for PostfixAdmin; prod does not have relay user passwords
-- PostgreSQL 10+
CREATE TABLE public.gateways
(
	domain character varying(255) COLLATE pg_catalog."default" NOT NULL,
	primary_relay character varying(255) NOT NULL,
        -- For SMTP AUTH relays
	primary_relay_password character varying(255),
	backup_relay character varying(255),
        -- For SMTP AUTH relays
	backup_relay_password character varying(255),
	CONSTRAINT servers_domain_fkey FOREIGN KEY (domain)
		REFERENCES public.domain (domain) MATCH SIMPLE
		ON UPDATE NO ACTION
		ON DELETE NO ACTION
)
WITH (
	OIDS = FALSE
)
```

Example use in Postfix (assumes configuration management can insert the hostname)
```
# Mailbox Mapping
... db configuration pointing to replica ...

query = SELECT mailbox.maildir FROM public.mailbox, public.gateways WHERE \
	active = 'true' AND mailbox.domain = '%d' AND gateways.domain = '%d' \
	AND (primary_relay='$(hostname -f)' OR backup_relay='$(hostname -f)')
```
```
# Domain Mapping
... db configuration pointing to replica ...

query = SELECT domain FROM public.domain WHERE \
    public.domain='%s' AND gateway.domain='%s' \
    AND active='true' \
    AND (primary_relay='$(hostname -f)' OR backup_relay='$(hostname -f)')
```

The purpose of the `primary_relay_password` and `backup_relay_password` field is basically to store encrypted authentication strings for SMTP AUTH if someone wants to use that as part of their transport maps (something that should be left as an exercise to the user.) 

There are definitely some potential weaknesses here as well, since it only allows a domain to have a primary and backup. An alternative might be to create a 'server' concept where instead, the administrator creates a server and selects which domains it is permitted to service, and selects a 'primary' server for a domain (used for PostfixAdmin emails and such,) which could scale better in large environments. However, this would likely be more complicated to implement.

**Comment by cboltz** [comment]
That sounds somewhat similar to https://github.com/postfixadmin/postfixadmin/pull/12
