### ISSUE TITLE
Code error on setup.php

### ISSUE THREAD

**Issue by pajafumo** [postfixadmin/postfixadmin#357]
I'm getting this error:
Notice: Undefined index: setup_password in /etc/gpanel/postfixadmin/public/setup.php on line 353

Centos 8
PHP 7.2.11 with php-fpm enable and opcache

Does anyone knows how to fix it?

**Comment by DavidGoodwin** [comment]
a. It's only a notice, so it's not critical and shouldn't break anything.

b. It'd help if you could tell us what version of postfixadmin you're seeing this on - I thought the problem had been fixed a long time ago (possibly by 71e412f6c239f5c3469e834959efe35d9b837fa8 which is from 2017).

**Comment by pajafumo** [comment]
Well, thank you for your answer. 
I can't create admin account, I think is because of that notice.
I use latest cloning from master 
`wget https://github.com/postfixadmin/postfixadmin/archive/master.zip`
then unziped to desire dir

Thanks

**Comment by DavidGoodwin** [comment]
Oh ... 

```
                                    <td><?= _error_field($errormsg, 'setup_password'); ?><?php print $PALANG['setup_password'] ?></td>
```

That could be your $PALANG array isn't set correctly. Do you know what language you're trying to use?
