### ISSUE TITLE
Your password must contain at least 2 digit(s).

### ISSUE THREAD

**Issue by DevDorrejo** [postfixadmin/postfixadmin#360]
Hello, i install postfixadmin using this guide, https://linuxize.com/post/install-and-configure-roundcube-webmail/

now the spec of my server is:
Opensuse TW last snapshot
PostfixAdmin 3.5.4
php 7.4.6
mariaDB 10.4.13

when i was creating the user on the setup got this message show on the picture:
![image](https://user-images.githubusercontent.com/7697566/84561138-f2591980-ad17-11ea-81ff-bb04e79f3f10.png)

found that introducing the passwords 2 time on the row:

password password >> yeah with the space between word, will take the password like valid, but i cant continue using this because i need to create more email for more ppl and the condition is for everyone, i am new on this on email server and i am a little stressed, if you need a log or config, at least give me the path or the name of the log, thank you.

**Comment by DavidGoodwin** [comment]
Add something to your config.local.php file like the below (Which is from: https://github.com/postfixadmin/postfixadmin/blob/master/config.inc.php#L226 ) and change as necessary ... 

```
$CONF['password_validation'] = array(
#    '/regular expression/' => '$PALANG key (optional: + parameter)',
    '/.{5}/'                => 'password_too_short 5',      # minimum length 5 characters
    '/([a-zA-Z].*){3}/'     => 'password_no_characters 3',  # must contain at least 3 characters
    '/([0-9].*){2}/'        => 'password_no_digits 2',      # must contain at least 2 digits
);
```


e.g. to  
```
$CONF['password_validation'] = array(
#    '/regular expression/' => '$PALANG key (optional: + parameter)',
    '/.{5}/'                => 'password_too_short 5',      # minimum length 5 characters
    '/([a-zA-Z].*){3}/'     => 'password_no_characters 3',  # must contain at least 3 characters
);
```

**Comment by DevDorrejo** [comment]
ok, thank you very much, i recommend first change digit for number is easiest for dumb ppl like me XD!!.

second, where can i get assist or help with postfix miss configuration? any irc channel (hate irc) or other github repo?

**Comment by DavidGoodwin** [comment]
Postfix - There is a #postfix channel on irc.freenode.net. Alternatively, one of the stackoverflow variants?
