### ISSUE TITLE
Need some sort of debug logging 

### ISSUE THREAD

**Issue by jacksnodgrass** [postfixadmin/postfixadmin#362]
I am trying to create a mailbox. 

I am using postfixadmin 3.2 ( from github ) 

The mailbox alias gets created in the alias table... 
address, goto, domain, etc. ... 

but the malbox tables does not get updated. 

there is a log table that has a create_alias function but nothing else related to my user. 

They system says: 
Creating the mailbox jacktest2@my-domain.com failed!

no idea why it's failing... it created the alias.... would be nice to see what the last command that the script tried to run before it tossed out this useless message. 

what am I supposed to do with: Creating the mailbox jacktest2@my-domain.com failed! ?

**Comment by jacksnodgrass** [comment]
Just for notes.... not to close this issue... my mailbox creation failed because my db tables were not updated. The config table said that I had one version of the db.. ( 1840 ) but the token fields that were supposed to be in the mailbox table were missing. The SQL Insert failed because of the missing fields.... but the user ( me ) was not notified of this specific information .... just a generic can't create mailbox message.   KNOWING why it failed would have saved me HOURS of debugging this.

**Comment by DavidGoodwin** [comment]
I'd expect something to be written to PHP's error log somewhere (perhaps e.g. /var/log/apache2/error.log)
