### ISSUE TITLE
function check_db_version() failed me... 

### ISSUE THREAD

**Issue by jacksnodgrass** [postfixadmin/postfixadmin#364]
I had several issues with my system because: 
function check_db_version() 
got version 1840 from the db table... BUT my tables were NOT that version. 

I don't know what got screwed up or when... but for some reason my config table said: 1840 but my mailbox and admin tables did not have these token fields... 

```php
function upgrade_1837() {
    global $CONF;

    if ($CONF['database_type'] == 'sqlite') {
        return;
    }
    # alternative contact means to reset a forgotten password
    foreach (array('admin', 'mailbox') as $table) {
        _db_add_field($table, 'phone', "varchar(30) {UTF-8} NOT NULL DEFAULT ''", 'active');
        _db_add_field($table, 'email_other', "varchar(255) {UTF-8} NOT NULL DEFAULT ''", 'phone');
        _db_add_field($table, 'token', "varchar(255) {UTF-8} NOT NULL DEFAULT ''", 'email_other');
        _db_add_field($table, 'token_validity', '{DATETIME}', 'token');
    }
}
```

so I had to manually set my db version to 1830 and re-run the upgrade.php script to get these fields added.  

so maybe checking that version number in one field isn't such a good idea.

**Comment by DavidGoodwin** [comment]
Hi - yeah - the upgrade stuff is fairly silent unless you have &debug=1 on the end of the URL ... which doesn't help if it's a one time thing ...

I've added something to perhaps put something into PHP's error log ... it might help.
