### ISSUE TITLE
Can't install on Debian 10 with MySQL 8

### ISSUE THREAD

**Issue by MESWEB** [postfixadmin/postfixadmin#365]
I'm trying install using this command:

> sudo dpkg-reconfigure postfixadmin

Durning installation after type " Name of the database's administrative user:" root and password then I see this error:

> ─────────────────────────────────────────────Configuring postfixadmin───────────────────────────────────────────────┐
│ An error occurred while installing the database:                                                                   │
│                                                                                                                    │
│ mysql said: ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that              │
│ corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'my_password'' at line 1

**Comment by DavidGoodwin** [comment]
This feels like an issue with the debian packaging?

**Comment by MESWEB** [comment]
@DavidGoodwin nope. It's seems like SQL query error. Maybe actual SQL query is for MYSQL 5.7 not 8.
https://stackoverflow.com/questions/57016805/mysql-error-1064-42000-you-have-an-error-in-your-sql-syntax-check-the-manual

**Comment by connortechnology** [comment]
We had this problem in zoneminder.  Mysql8 no longer supports the identified by shortcut in the grant statement.  You have to do user creation and rights granting in two statements now.  The new syntax is backwards compatible though.

CREATE USER 'USER'@localhost IDENTIFIED BY 'PASS'
GRANT *  on DB_NAME.* to 'USER'@localhost;

**Comment by DavidGoodwin** [comment]
@MESWEB - the only 'CREATE USER' statements in PostfixAdmin are in INSTALL.txt, so I don't think it's something we can fix.

```
$ ack-grep -i 'create user'
INSTALL.TXT
85:  CREATE USER 'postfix'@'localhost' IDENTIFIED BY 'choose_a_password';
90:  CREATE USER postfix WITH PASSWORD 'whatever';

```

See : https://github.com/postfixadmin/postfixadmin/blob/master/INSTALL.TXT#L83
```
....
For MySQL:
  CREATE DATABASE postfix;
  CREATE USER 'postfix'@'localhost' IDENTIFIED BY 'choose_a_password';
  GRANT ALL PRIVILEGES ON `postfix` . * TO 'postfix'@'localhost';
  FLUSH PRIVILEGES;
...
```

So again, I'm failing to see how this is a PostfixAdmin problem (the bug needs to be addressed to someone in Debian ?)

**Comment by MESWEB** [comment]
@DavidGoodwin OK where I can find and modify adding user to database by postfixadmin installation in linux?

**Comment by DavidGoodwin** [comment]
PostfixAdmin doesn't handle the addition of a MySQL user account. It assumes you've done this already in one way or another.

To find out what the debian package is trying to use try looking in /etc/postfixadmin. 

'grep' for 'database_user' and 'database_password' and 'database_name' .... 

With the values you have, use your preferred way of talking to MySQL to perform the steps manually?
