### ISSUE TITLE
Invalid token (session timeout; refresh the page and try again?)

### ISSUE THREAD

**Issue by bestpaydeals** [postfixadmin/postfixadmin#367]
Everything is done correctly. However, I get this error on browser after I try login:

Invalid token (session timeout; refresh the page and try again?)

How do I fix it?

**Comment by DavidGoodwin** [comment]
Seen https://github.com/postfixadmin/postfixadmin/issues/341 ?

It probably implies there's something wrong with how your server is generating/storing PHP session files (e.g. an invalid path or storage backend that's not working) or there's something messing up your browser's cookie storage?

**Comment by svenseeberg** [comment]
I'm having the same issues. I can see that the tokens stored in the session on the server differ from the one being sent in the form. The session ID itself is okay.

**Comment by svenseeberg** [comment]
I can reproduce this with the tracking protection enabled in Firefox. As soon as I deactivate the tracking protection, it works.

**Comment by svenseeberg** [comment]
It seems that Firefox replaces the value of the token field. The value in the source code differs from the one being received when looking in the network section of developer tools.

**Comment by svenseeberg** [comment]
It seems that replacing the name of the token input field mitigates this problem. We renamed it to `__csrf_magic` and have no more issues in Firefox.

**Comment by DavidGoodwin** [comment]
how annoying! but thanks for providing a possible workaround.

**Comment by bestpaydeals** [comment]
This is the solution via SSH:
sudo chown -R nginx /var/opt/remi/php74/lib/php/session

If your user is apache then you keep apache in place on nginx. It works as per your configuration.
