### ISSUE TITLE
I can not install on PostgreeSQL

### ISSUE THREAD

**Issue by player1905** [postfixadmin/postfixadmin#368]
I try to install postfixadmin on a server with a post-hess database and get the following errors:

2020/06/19 21:02:45 [error] 14580#0: *643 FastCGI sent in stderr: "PHP message: Invalid query: ERROR:  invalid input syntax for integer: "t" 
LINE 1: ..._domain_count,0) as domain_count,CASE active WHEN 't' THEN '... 
                                                            ^ 
PHP message: caused by query:  SELECT username,password,password as password2,CASE superadmin WHEN 't' THEN '1'    WHEN 'f' THEN '0'   END as superadmin,CASE superadmin WHEN 't' THEN 'ДА' W
HEN 'f' THEN 'НЕТ' END as _superadmin,coalesce(domains,'') as domains,coalesce(__domain_count,0) as domain_count,CASE active WHEN 't' THEN '1'    WHEN 'f' THEN '0'   END as active,CASE acti
ve WHEN 't' THEN 'ДА' WHEN 'f' THEN 'НЕТ' END as _active,TO_CHAR(modified, 'YYYY-mm-dd') AS modified, modified AS _modified,1 as _can_edit,1 as _can_delete  FROM admin  LEFT JOIN (  SELECT 
count(*) AS __domain_count, array_to_string(array_agg(domain), ',') AS domains, username AS __domain_username  FROM domain_admins WHERE domain != 'ALL' GROUP BY username  ) AS __domain on u
sername = __domain_username 
 WHERE 1=1    AND    ( username='pg@test.loc' )  ORDER BY username" while reading response header from upstream, client: 192.168.0.1, server: _, request: "POST /postfixadmin/setup.
php?debug=1 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9999"
Please tell me what they are connected with, how can I fix them?

**Comment by DavidGoodwin** [comment]
What PostgreSQL variant are you trying to use?

**Comment by player1905** [comment]
What is under option? Version? If so, then tried various from standard to centos to 10; all is useless. I'm already desperate ...

**Comment by player1905** [comment]
Standard is:
Title: postgresql
Architecture: x86_64
Version: 9.2.24
Release: 4.el7_8
Volume: 3.0 M

**Comment by player1905** [comment]
At the moment I use this:
Installed Packages
Name: postgresql10-server
Architecture: x86_64
Version: 10.13
Issue: 1PGDG.rhel7
Volume: 18 M
Source: installed

**Comment by player1905** [comment]
Please help if possible. I spent a day with this problem. Result 0. I don’t even have any assumptions what’s the matter .... All preparations for the installation pass without problems, and when I create the user and password (at the final stage), I see this error. And that only I did not do ....

**Comment by DavidGoodwin** [comment]
oddly, i think everything is working fine with PostgreSQL 11 for me (using current 'master' variant).

**Comment by DavidGoodwin** [comment]
I guess I'd better try and use PostgreSQL 10 too!

**Comment by player1905** [comment]
Just wanted to write, what can I try PostgreSQL 11? This error was repeated for me both on 9 and on the current version 10. I did not try version 11.

**Comment by player1905** [comment]
Upgrade to PostgreSQL 11 I can only try tomorrow .... The error clearly looks because of a script and database problem .... But what is it. I can’t imagine ...

**Comment by DavidGoodwin** [comment]
I have PostgreSQL 9.6 and 11 ... both work.

What PostfixAdmin version are you trying to use ?

**Comment by player1905** [comment]
I'm sorry, I made a mistake on this server currently installed:
Title: postgresql-server
Architecture: x86_64
Version: 9.2.24
Issue: 1.el7_5
Volume: 16 M
Source: installed
From source: base
Summary: The programs needed to create and run a PostgreSQL server
Link: http://www.postgresql.org/
License: PostgreSQL
Description: PostgreSQL is an advanced Object-Relational database management system (DBMS).
        : The postgresql-server package contains the programs needed to create
        : and run a PostgreSQL server, which will in turn allow you to create
        : and maintain PostgreSQL databases.

Available Packages
Title: postgresql-server
Architecture: x86_64
Version: 9.2.24
Release: 2.el7_7
Volume: 3.8 M
Source: updates / 7 / x86_64
Summary: The programs needed to create and run a PostgreSQL server
Link: http://www.postgresql.org/
License: PostgreSQL
Description: PostgreSQL is an advanced Object-Relational database management system (DBMS).
        : The postgresql-server package contains the programs needed to create
        : and run a PostgreSQL server, which will in turn allow you to create
        : and maintain PostgreSQL databases.
This is from the standard centos repository, I tried changing it to 10, then returned again, since it did not lead to positive results.

**Comment by DavidGoodwin** [comment]
* rpm -qa | grep post
 * systemctl status postgre* 

and what version of PostfixAdmin are you trying to use ?

**Comment by player1905** [comment]
rpm -qa | grep post
postgresql-server-9.2.24-1.el7_5.x86_64
postgresql-libs-9.2.24-1.el7_5.x86_64
postfix-2.10.1-6.el7.centos.x86_64
postgresql-9.2.24-1.el7_5.x86_64
postgresql-contrib-9.2.24-1.el7_5.x86_64
sope49-gdl1-postgresql-4.9-20190613_1664.el7.1.x86_64

systemctl status postgre*
● postgresql.service - PostgreSQL database server
   Loaded: loaded (/usr/lib/systemd/system/postgresql.service; enabled; vendor preset: disabled)
   Active: active (running) since Сб 2020-06-20 04:23:47 MSK; 3 days ago
  Process: 3928 ExecStart=/usr/bin/pg_ctl start -D ${PGDATA} -s -o -p ${PGPORT} -w -t 300 (code=exited, status=0/SUCCESS)
  Process: 3904 ExecStartPre=/usr/bin/postgresql-check-db-dir ${PGDATA} (code=exited, status=0/SUCCESS)
 Main PID: 3965 (postgres)
   CGroup: /system.slice/postgresql.service
           ├─ 3965 /usr/bin/postgres -D /var/lib/pgsql/data -p 5432
           ├─ 3998 postgres: logger process   
           ├─ 4195 postgres: checkpointer process   
           ├─ 4196 postgres: writer process   
           ├─ 4198 postgres: wal writer process   
           ├─ 4200 postgres: autovacuum launcher process   
           ├─ 4201 postgres: stats collector process   
           ├─ 4742 postgres: netdata postgres [local] idle
           ├─12310 postgres: amavisd amavisd 127.0.0.1(41130) idle
           ├─12521 postgres: amavisd amavisd 127.0.0.1(41522) idle
           ├─14488 postgres: vmail vmail 127.0.0.1(44654) idle
           ├─14489 postgres: amavisd amavisd 127.0.0.1(44656) idle
           ├─14490 postgres: iredapd iredapd 127.0.0.1(44658) idle
           ├─16040 postgres: vmail vmail 127.0.0.1(47164) idle
           ├─16041 postgres: vmail vmail 127.0.0.1(47166) idle
           ├─16049 postgres: vmailadmin vmail 127.0.0.1(47198) idle
           ├─16050 postgres: vmailadmin vmail 127.0.0.1(47200) idle
           ├─16165 postgres: vmail vmail 127.0.0.1(47364) idle
           ├─16166 postgres: vmail vmail 127.0.0.1(47366) idle
           ├─16195 postgres: vmailadmin vmail 127.0.0.1(47398) idle
           ├─16196 postgres: vmailadmin vmail 127.0.0.1(47400) idle
           ├─19667 postgres: vmail vmail 127.0.0.1(40662) idle
           └─19668 postgres: vmail vmail 127.0.0.1(40664) idle

**Comment by player1905** [comment]
at the moment 9.2.24

**Comment by DavidGoodwin** [comment]
ok, and what version of PostfixAdmin ?

**Comment by player1905** [comment]
Sorry for the long reply. Yesterday I went to bed, when we corresponded, it was already one in the morning. PostfixAdmin I took the latest version, from here - https://sourceforge.net/projects/postfixadmin/files/postfixadmin/postfixadmin-3.2/

**Comment by DavidGoodwin** [comment]
Hm, I'm not sure how up to date that is. And it looks like the files there have just been rebuilt ....

**Comment by player1905** [comment]
I took the assembly which postfixadmin-3.2.tar.gz, it was published on 2018-05-02, I also tried postfixadmin-3.2.4.tar.gz it was published 2020-04-17

**Comment by player1905** [comment]
With none of these assemblies did I manage to configure the work of postgres ....

**Comment by DavidGoodwin** [comment]
I tested using Postfxadmin 3.2.4 ... it installs fine with ....

 * PostgreSQL 9.4
 * PostgreSQL 9.6
 * PostgreSQL 11

Those are just variants of PostgreSQL installed through Debian (Buster etc).

**Comment by player1905** [comment]
Thank you, I will try to put 3.2.4.

**Comment by player1905** [comment]
again

**Comment by player1905** [comment]
Как изменится история переводов
В будущем для доступа к истории переводов потребуется выполнять вход в аккаунт, а ее настройки будут перенесены на страницу Мои действия. История после обновления будет удалена, поэтому сохраните нужные переводы на будущее.
ОК
Так и не получилось настроить.... Что поставил:
PHP version 7.4.7
postfixadmin-3.2.4
postgresql11
Похоже postfixadmin не для меня.... При установке та же ошибка:
Database is up to date: 1841/0

DEBUG INFORMATION:
Invalid query: ERROR: invalid input syntax for integer: "t" LINE 1: ..._domain_count,0) as domain_count,CASE active WHEN 't' THEN '... ^ 

Так же при обновлении БД сыпались следуюшие ошибки:
updating to version 2 (PgSQL)...
CREATE TABLE log ( timestamp timestamp with time zone default now(), username character varying(255) NOT NULL default '', domain character varying(255) NOT NULL default '', action character varying(255) NOT NULL default '', data text NOT NULL default '' ); COMMENT ON TABLE log IS 'Postfix Admin - Log';
CREATE TABLE vacation ( email character varying(255) PRIMARY KEY, subject character varying(255) NOT NULL, body text NOT NULL , cache text NOT NULL , "domain" character varying(255) NOT NULL REFERENCES "domain", created timestamp with time zone DEFAULT now(), active boolean DEFAULT true NOT NULL ); CREATE INDEX vacation_email_active ON vacation(email,active);
CREATE TABLE vacation_notification ( on_vacation character varying(255) NOT NULL REFERENCES vacation(email) ON DELETE CASCADE, notified character varying(255) NOT NULL, notified_at timestamp with time zone NOT NULL DEFAULT now(), CONSTRAINT vacation_notification_pkey primary key(on_vacation,notified) );
ALTER TABLE domain ADD COLUMN transport VARCHAR(255)
Invalid query: ERROR: column "transport" of relation "domain" already exists
ALTER TABLE domain ADD COLUMN backupmx BOOLEAN DEFAULT false
Invalid query: ERROR: column "backupmx" of relation "domain" already exists
  done


updating to version 730 (PgSQL)...
CREATE LANGUAGE plpgsql
Invalid query: ERROR: language "plpgsql" already exists


Язык оригинала: английский
1800/5000
It didn’t work out .... What I set:
PHP version 7.4.7
postfixadmin-3.2.4
postgresql11
It seems postfixadmin is not for me .... When installing the same error:
Database is up to date: 1841/0

DEBUG INFORMATION:
Invalid query: ERROR: invalid input syntax for integer: "t" LINE 1: ..._ domain_count, 0) as domain_count, CASE active WHEN 't' THEN '... ^

Also, when updating the database, the following errors were poured:
updating to version 2 (PgSQL) ...
CREATE TABLE log (timestamp timestamp with time zone default now (), username character varying (255) NOT NULL default '', domain character varying (255) NOT NULL default '', action character varying (255) NOT NULL default '', data text NOT NULL default ''); COMMENT ON TABLE log IS 'Postfix Admin - Log';
CREATE TABLE vacation (email character varying (255) PRIMARY KEY, subject character varying (255) NOT NULL, body text NOT NULL, cache text NOT NULL, "domain" character varying (255) NOT NULL REFERENCES "domain", created timestamp with time zone DEFAULT now (), active boolean DEFAULT true NOT NULL); CREATE INDEX vacation_email_active ON vacation (email, active);
CREATE TABLE vacation_notification (on_vacation character varying (255) NOT NULL REFERENCES vacation (email) ON DELETE CASCADE, notified character varying (255) NOT NULL, notified_at timestamp with time zone NOT NULL DEFAULT now (), CONSTRAINT vacation_notification_pkey primary key (on_vacation, ));
ALTER TABLE domain ADD COLUMN transport VARCHAR (255)
Invalid query: ERROR: column "transport" of relation "domain" already exists
ALTER TABLE domain ADD COLUMN backupmx BOOLEAN DEFAULT false
Invalid query: ERROR: column "backupmx" of relation "domain" already exists
done


updating to version 730 (PgSQL) ...
CREATE LANGUAGE plpgsql
Invalid query: ERROR: language "plpgsql" already exists
Отправить отзыв
История
Сохранено
Сообщества

**Comment by DavidGoodwin** [comment]
if there's no content in your database, can you drop the postfixadmin database and recreate it before trying to run public/upgrade.php please?

**Comment by player1905** [comment]
There is data in the database. Therefore, I do not want to do this ....
