### ISSUE TITLE
Add postfix mail queues management to postfixadmin

### ISSUE THREAD

**Issue by pgaufillet** [postfixadmin/postfixadmin#369]
Adding the capability to monitor/review/release or suppress hold mails (or other queues) to postfixadmin would be very useful.

**Comment by DavidGoodwin** [comment]
Can hold emails get put into a database? I've only ever seen them live on the filesystem ....

**Comment by pgaufillet** [comment]
I think your are right.

**Comment by pgaufillet** [comment]
I confess I don't understand why this is a killer point for a such useful admin feature. Can you please elaborate a bit?
