### ISSUE TITLE
Feature request: Use unix domain socket on local PostgreSQL

### ISSUE THREAD

**Issue by malibata** [postfixadmin/postfixadmin#370]
Probably the best way to connect to local PostgreSQL database is to use Unix domain socket ...
In PHP pg_pconnect function this is achieved by simply omitting host parameter. Also default port is 5432 so no reason to push it if it isn't set by user ...
Attached i am sending  a diff text file 
[functions.inc.php.diff.txt](https://github.com/postfixadmin/postfixadmin/files/4937081/functions.inc.php.diff.txt)
with simple change to achieve just this ...

**Comment by DavidGoodwin** [comment]
that could apply to postfixadmin 3.2.x but the latest 'master' variant uses PDO.... see e.g. https://github.com/postfixadmin/postfixadmin/blob/master/functions.inc.php#L1530

**Comment by malibata** [comment]
Basically there isn't much of a difference, the following diff applies to latest master branch with PDO ...
[functions.inc.php.diff.txt](https://github.com/postfixadmin/postfixadmin/files/4938014/functions.inc.php.diff.txt)

**Comment by DavidGoodwin** [comment]
thank you.
