### ISSUE TITLE
Getting invalid token error

### ISSUE THREAD

**Issue by KostLinux** [postfixadmin/postfixadmin#372]
Getting invalid token error when trying to login. Saw same issue, tried to change the timezone and restart apache2 but still invalid token.
I use PHP 7.4 and Apache2
OS is Ubuntu 18.04
Here's log
```
[Fri Jul 24 14:14:42.349827 2020] [php7:notice] [pid 16566] [client 192.168.0.200:46682] PostfixAdmin login failed (username: someadmin@itarchive.eu, ip_address: 192.168.0.200), referer: https://webmail.itarchive.eu/login.php
```

**Comment by KostLinux** [comment]
Fixed this and now getting Invalid token (session timeout; refresh the page and try again?)
Can someone guide me please?

**Comment by DavidGoodwin** [comment]
You need to make sure you're not blocking any cookies from the site. I'd suggest you use your browser's dev tools to look at the HTTP requests, and verify that the PHP session ID isn't changing between requests.

**Comment by KostLinux** [comment]
When i'm trying to log in, it doesn't do anything
Seems like authentication is success, but he doesn't redirect me to anywhere
About cookies, i allowed all cookies and still got this error

**Comment by DavidGoodwin** [comment]
In your case, the error message you mentioned above, is when there is no PFA_token value in your PHP session state. This could be because : 

 a. You've done something in another window that's led to the session being recreated (e.g. going to a login / logout page)
 b. Your browser is blocking / stopping the HTTP Cookie header, so PHP is creating a new session on each page load
 c. Your browser is setup to block or drop cookies
 d. Your server has broken PHP session storage - so it's always creating new sessions as it has no memory of old ones.

**Comment by DavidGoodwin** [comment]
I'd suggest creating a PHP page like the following and refreshing it a few times, it will probably help ....

```
<?php
session_start();
$_SESSION['counter']++;

var_dump($_SESSION);
```

You should see a number incrementing each time you refresh the page. For you this probably won't be the case, and will confirm that there's some sort of server side problem (or your browser is dropping cookies).

**Comment by KostLinux** [comment]
Oke, i will try

**Comment by KostLinux** [comment]
I commented line `Header edit Set-Cookie ^(.*)$ $1;HttpsOnly;Secure` in Apache conf
Now i'm getting `Invalid token! (CSRF check failed)` when trying to log in

**Comment by KostLinux** [comment]
@DavidGoodwin Do you have any ideas, what can i try more ?

**Comment by DavidGoodwin** [comment]
What do you see in the HTTP request/responses from the server when you use your browser's network inspection tools?

Is the cookie identifier stable, and being passed around amongst subsequent requests?

**Comment by KostLinux** [comment]
> What do you see in the HTTP request/responses from the server when you use your browser's network inspection tools?
> 
> Is the cookie identifier stable, and being passed around amongst subsequent requests?

**Comment by KostLinux** [comment]
Sry, missclick
I will answer as soon i will find time

**Comment by KostLinux** [comment]
I will close this issue and write to you as soon as i'll check the HTTP req/res.
