### ISSUE TITLE
unable to login - no idea whats going on

### ISSUE THREAD

**Issue by damnms** [postfixadmin/postfixadmin#373]
I have an old server running postfixadmin 3.0.x, self maintained. 
This server should be migrated to a new one with 3.2.x (from official debian repo).
I migrated the mysql database successfully.

When i try to login through the webinterface, nothing happens.
In the log i can see: PostfixAdmin login failed (username: root@xxx.de)

I debugged a lot and noticed that the password is set to "Thepasswortcannotbeverified". This should be somewhere in any log!
I came across functions.php, ~line 1000, method function _pacrypt_dovecot($pw, $pw_db)

The first thing is: please make it the same way like in https://github.com/postfixadmin/postfixadmin/issues/58
Do not rely on external programs whenever possible, please. That makes it very very hard for others to e.g. hardening the php.ini, just because of that.

I let it print the command it executes. When i execute the exact same command on command line, i get that (verified) string. But seems like, i do not get that when it runs in functions.php. Please enhance some kind of logging. Thats such an important part here.

$password = fread($pipes[1], "200"); <- leads to nothing, empty string

also, all those calls to fwrite/fread are NOT checked if they really did what is expected! even no check for "false" return value

found the error:
stream: doveadm: Fatal: Error reading configuration: stat(/etc/dovecot/dovecot.conf) failed: Permission denied (euid=33(www-data) egid=33(www-data) missing +x perm: /etc/dovecot, dir owned by 0:0 mode=0700)

i printed the stderr/stdout pipes and got that.
it would be really nice if there is something in stderr, then do an error_log() with that content and maybe add some more checks to function calls, because nowadays some people configure their system with some paranoia (e.g. using systemd-analyze security $service.unit), configure something and then *something* does not work anymore and no one knows why.
a log entry would be soooo helpful!

**Comment by cboltz** [comment]
Looking at `_pacrypt_dovecot()` in master, the `error_log()` call only happens if you don't use a salted hashing method.

`$dovepasstest` can be a) empty or b) `"-t $hash_from_database"`. Therefore   `if (empty($dovepasstest))`   probably isn't the correct condition for the error check - basically that means that you'll only get the `error_log()` if you don't use a salted hashing method.

**Comment by DavidGoodwin** [comment]
That any better?

**Comment by damnms** [comment]
imo it looks ok, but i would abort asap when stderr contains anything, something like:

$stderr_output = stream_get_contents($pipes[2]);
if(!empty($stderr_output)) { 
error_log("An error occured using doveadm: $stderr_output ");
	throw new Exception("$dovecotpw failed, see error log for details");
}

that makes clear that this stream must never contain anything or else an error occured.
