### ISSUE TITLE
ru-translation updates

### ISSUE THREAD

**Issue by i47320673** [postfixadmin/postfixadmin#376]
I've check ru.lang for some missing translations.

Here is my own view.
Can be commited if ok
[ru.lang.txt](https://github.com/postfixadmin/postfixadmin/files/5053429/ru.lang.txt)

**Comment by DavidGoodwin** [comment]
* Are you able to submit this as a pull request ? 
 * What version of PostfixAdmin is your new file made against ?  master ? 3.2 ?

see also : 13549cea0fcc686341179d0426f4ab496a7ee773

**Comment by i47320673** [comment]
>Are you able to submit this as a pull request ?

So sorry, but have no possibility at now.

>What version of PostfixAdmin is your new file made against ? master ? 3.2 ?

master
<changelog.txt>
Version 3.2 - 2018/05/02

As i see all fixes already done in [13549ce](https://github.com/postfixadmin/postfixadmin/commit/13549cea0fcc686341179d0426f4ab496a7ee773)

so my early attached ru-translation can be ignored.

**Comment by DavidGoodwin** [comment]
Thank you!
