### ISSUE TITLE
Update-check.php does not find latest versions

### ISSUE THREAD

**Issue by ikarisan** [postfixadmin/postfixadmin#377]
The update check (http://postfixadmin.sf.net/update-check.php?version=3.2) does not to find the latest version, available at Github or sourceforge. I was running Postfixadmin-3.2 and thought that this is the latest release, because the update-check.php told me. After Upgrading to Ubuntu 20.04 and MySQL8.0.21 I got some "Invalid query:" errors and figured out, that there where some more releases since 3.2(.0).  

Maybe the update-check.php?version=3.2 should tell that there is a more recent (sub)version 3.2.4 available.

On Linux I would use something like this:
curl -s https://api.github.com/repos/postfixadmin/postfixadmin/releases/latest | grep "tag_name"
But this should be possible with PHP, too.

**Comment by DavidGoodwin** [comment]
Hi - Fixed.

Unsurprisingly, sourceforge don't allow PHP scripts running on their infrastructure to make HTTP requests out, so I can't do check on github like you suggest.
