### ISSUE TITLE
MySQLi: Reuse existing connection

### ISSUE THREAD

**Issue by killerbees19** [postfixadmin/postfixadmin#38]
It looks like Postfixadmin opens more than 45 **new** connections to the database for a single page without any real items. This is extremely slow, especially with external MySQL servers. Instead of using the existing connection, it creates a new one for each `db_query`, `escape_string`, …

There's a simple patch to fix this behavior: e28f3f5959e67cb0be04ff0dd36c71fc8331ebed (from [this](https://github.com/froonix/postfixadmin/tree/mysqli-connect) branch)

I've uploaded a backtrace without the patch here: [pfa-backtrace.txt](https://www.happytec.at/upload_files/something/pfa-backtrace.txt)

**Comment by cboltz** [comment]
Are you sure this still happens with the latest code we have on github?

Commit c253ef7dbdc2a92ff1c4193c587acfe1539d617e (done about a month ago) claims to have this fixed ;-)

That said - your fix looks better, so I seriously think about accepting your patch and reverting c253ef7dbdc2a92ff1c4193c587acfe1539d617e ;-)

**Comment by DavidGoodwin** [comment]
My fix was only to allow a connection to be passed into the escape_string() function; this on the other hand short cuts the db_connect() function if a connection has been opened before. So they're slightly different.

There is already a static $link in db_query() ...

https://github.com/postfixadmin/postfixadmin/blob/master/functions.inc.php#L1419

**Comment by killerbees19** [comment]
> Are you sure this still happens with the latest code we have on github?

Nope, it's the Debian package from Stretch. Sorry, I didn't see the issue/commit. But I think it's a little bit different.

**Comment by killerbees19** [comment]
> There is already a static $link in db_query() ...

But it's useless when calling db_connect() from other functions like escape_string().

mysqli_connect() returns always a new connection:

> (PHP 5, PHP 7)
> mysqli::__construct -- mysqli_connect — Open a **new** connection to the MySQL server

**Comment by cboltz** [comment]
Agreed, db_connect() is irrelevant for escape_string() - and caching the connection directly in db_connect() is probably the best thing we can do.

I still think that this fix is better than c253ef7dbdc2a92ff1c4193c587acfe1539d617e ;-)

**Comment by cboltz** [comment]
I merged #41 (thanks!) and also reverted most of c253ef7 - there's no need for additional caching in escape_string().
