### ISSUE TITLE
Unable to login after Dovecot upgrade version v2.3.11+

### ISSUE THREAD

**Issue by j4Hu** [postfixadmin/postfixadmin#382]
hey

there are several auth changes in this version:
https://dovecot.org/doc/NEWS

	- auth-worker: Process keeps slowly increasing its memory usage and
	  eventually dies with "out of memory" due to reaching vsz_limit.
	- auth: Prevent potential timing attacks in authentication secret
	  comparisons: OAUTH2 JWT-token HMAC, imap-urlauth token, crypt() result.
	- **auth: Several auth-mechanisms allowed input to be truncated by NUL
	  which can potentially lead to unintentional issues or even successful
	  logins which should have failed.**
	- auth: When auth policy returned a delay, auth_request_finished event
	  had policy_result=ok field instead of policy_result=delayed.
	- auth: auth process crash when auth_policy_server_url is set to an
	  invalid URL.

postfixadmin code has triggererd only error_log - failed login messsage.
_Aug 22 09:34:35 web01 ix[16281]: PostfixAdmin login failed (username: x@x, ip_address: 1.1.1.1)_

**Comment by DavidGoodwin** [comment]
what version are you using? does it have 57a47874738e9b94f3c8168ed92f2764efb80ad3 and 502bfca2f56623941cd11c0aff2745c0ae830a71 and 2bb2460bf32190831a9d638276e1ae383424358a applied ?

**Comment by j4Hu** [comment]
using latest release 3.2.4 (sorry for not mentioning).
GIT tree works OK. no problem with login.
