### ISSUE TITLE
New release with current status and Bootstrap template

### ISSUE THREAD

**Issue by matzex** [postfixadmin/postfixadmin#383]
Hi all,

i know the development needs time and resources. I like this tool very much and use it on a regular basis. Since some time I also use the modern Bootstrap template and I have multiple issues with new updates from the 3.2.X releases. Most often some template details from old versions and the newer releases are not compatible or I miss some details. It would be very helpful to have a release with all changes from the git master branch and the bootstrap template integrated, maybe as 3.3.X release.

#172 integrates the Bootstrap template.

Thank you very much and keep up the good work!
Matthias

**Comment by DavidGoodwin** [comment]
Thanks for the feedback.

**Comment by DavidGoodwin** [comment]
https://github.com/postfixadmin/postfixadmin/milestone/3

**Comment by DavidGoodwin** [comment]
New release made.
