### ISSUE TITLE
admin can`t change password for users, if generate_password=yes

### ISSUE THREAD

**Issue by j4Hu** [postfixadmin/postfixadmin#384]
hey, 
if config variable:
$CONF['generate_password'] = 'YES';

then edit mailbox dialog for administrator, is without possibility to change user passwords.

resolution: revert commit back?
commit: 1d1960a47687490b2b1450fc1dc543a587369802 (parent  ae47695)

tnx

**Comment by DavidGoodwin** [comment]
thanks :)
