### ISSUE TITLE
get_magic_quotes_gps() deprecated warnings with postfixadmin-cli

### ISSUE THREAD

**Issue by jave** [postfixadmin/postfixadmin#385]
example:

[root@mailvm-dev dovecot]# /srv/postfixadmin/scripts/postfixadmin-cli  domain add asdfasdfasde3qwef.com

PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Welcome to Postfixadmin-CLI v0.2
---------------------------------------------------------------
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317

Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/postfixadmin/functions.inc.php on line 317
Error: Invalid domain asdfasdfasde3qwef.com, and/or not discoverable in DNS

**Comment by DavidGoodwin** [comment]
```PHP
    if (function_exists('get_magic_quotes_gpc') && get_magic_quotes_gpc()) {
        $string = stripslashes($string);
    }
```

Is that what you see at line 317 of the file ?

If so, you could silence it by changing your php.ini error_reporting level, or changing ... ` && get_magic_quotes_gpc() ` to ... ` && @get_magic_quotes_gpc() `

**Comment by jave** [comment]
I will try this and get back, thanks

**Comment by pgnd** [comment]
i've installed
```
	cd src/postfixadmin/
	git log -n1
		1 commit f7708520b36b07598db641bd076eee46fbdbf7af (HEAD, tag: postfixadmin-3.2.4)
		2 Author: David Goodwin <david@codepoets.co.uk>
		3 Date:   Fri Apr 17 09:15:04 2020 +0100
		4
		5     postfixadmin 3.2.4 changelog
```

with
```
	php -v
		PHP 7.4.10 (cli) (built: Sep  1 2020 13:58:08) ( NTS )
		Copyright (c) The PHP Group
		Zend Engine v3.4.0, Copyright (c) Zend Technologies
			with Zend OPcache v7.4.10, Copyright (c), by Zend Technologies
```

as above, on exec of 
```
	postfixadmin-cli domain view example.com
```

seeing the same
```
	PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /dev/src/postfixadmin/functions.inc.php on line 317

	Deprecated: Function get_magic_quotes_gpc() is deprecated in /dev/src/postfixadmin/functions.inc.php on line 317
	PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /dev/src/postfixadmin/functions.inc.php on line 317
	...
```

reading @

	https://www.php.net/manual/en/function.get-magic-quotes-gpc.php

states

	"Warning
	This function has been DEPRECATED as of PHP 7.4.0. Relying on this function is highly discouraged."

it was deprecated on Jul 22, 2019, with this commit:

	https://github.com/php/php-src/commit/b2ea507beab862a0167af6b99f44fe9c695ca4f0 

editing, as suggested,
```
	perl -pi -e 's|(&& )(get_magic_quotes_gpc\(\))|${1}\@${2}|g' functions.inc.php
```

silences the noise
```
	postfixadmin-cli domain view example.com

		Welcome to Postfixadmin-CLI v0.2
		---------------------------------------------------------------
					Domain: example.com
				Description:
					Aliases: 0 / ∞
				Mailboxes: 2 / ∞
		Mail server is backup MX: NO
					Active: YES
			Last modified:
```

checking source
```
	cd src/postfixadmin
	grep get_magic_quotes_gpc `grep -rlni get_magic_quotes_gpc .`
		./public/setup.php:$f_get_magic_quotes_gpc = function_exists("get_magic_quotes_gpc");
		./public/setup.php:if ($f_get_magic_quotes_gpc == 1) {
		./public/setup.php:    if (get_magic_quotes_gpc() == 0) {
		./public/setup.php:    print "<li><b>Unable to check for Magic Quotes. (missing function: get_magic_quotes_gpc())</b></li>\n";
		./public/sendmail.php:    if (get_magic_quotes_gpc()) {
		./public/sendmail.php:        $tBody = stripslashes($tBody); # TODO: check for get_magic_quotes_gpc inside safepost/safeget
		./functions.inc.php:    if (function_exists('get_magic_quotes_gpc') && get_magic_quotes_gpc()) {
```

looks like all those^ should be cleaned up to ack the deprecation.

**Comment by DavidGoodwin** [comment]
As far as I know, there are no references to get_magic_quotes_gpc() etc in the 'master' branch. 

I don't think it's a good idea for us to remove that from the stable / 3.2 branch as it could be used by people using older PHP versions.

**Comment by jave** [comment]
prefixing the function with @ worked for me as well.
I can try to switch over to the master branch as well.

**Comment by pgnd** [comment]
> I don't think it's a good idea for us to remove that from the stable / 3.2 branch as it could be used by people using older PHP versions.

imo, you'd like current/stable branch of postfixadmin that works with current/stable php release -- without need for any modification.

noting,

https://www.php.net/supported-versions.php

perhaps a conditional based on php version?

**Comment by DavidGoodwin** [comment]
Hopefully that's good enough for the 3.2.x branch.
