### ISSUE TITLE
Is it possible to run the installer from command line

### ISSUE THREAD

**Issue by jave** [postfixadmin/postfixadmin#386]
Atm I have a script like this:

#!bin/sh
echo "attempting to finalize postfixadmin"
while true;
do
    if curl   http://localhost/postfixadmin/setup.php|grep -q "Database is up to date"; then
        echo "done!";
        exit 0;
    fi;
done

But I guess it's kind of flaky. Are there better options?

The background is I'm making a reproducible setup with postfix, postfixadmin, dovecot, postgres, and so on.

**Comment by DavidGoodwin** [comment]
You could pre-populate a MySQL database (offline) and then embed that SQL file into your setup?

I assume it's "flaky" because your database server may not be ready by the time the above runs? 

Add a sleep call in the while loop to back off a little ?

**Comment by jave** [comment]
I use postgres, but that would be the same for mysql. 

The curl thing works, but the 1st time in the loop i get a server timeout. The setup completes however, and then you can re-run it until the setup is completed, so its only flaky in the sense that I cant differ from genuine faults and expected faults atm.

I dont want to pre-populate the db, because then I would need to rebuild the db manually before dumping it.

Anyway, thanks for your suggestions.
