### ISSUE TITLE
cant list domains

### ISSUE THREAD

**Issue by jave** [postfixadmin/postfixadmin#389]
I cant list domains anymore for unknown reasons.

I guess its a local issue, but I cant figure it out.

There are domains in the database.

sudo -i -u postgres psql -d postfix -c 'select * from domain;'
   domain   | description | aliases | mailboxes | maxquota | quota | transport | backupmx |            created            |           modified            | active | password_expiry 
------------+-------------+---------+-----------+----------+-------+-----------+----------+-------------------------------+-------------------------------+--------+-----------------
 narval.nu  |             |      10 |        10 |       10 |  2048 | virtual   | f        | 2020-09-16 22:22:09.012012+00 | 2020-09-16 22:22:09.012012+00 | t      |               0

**Comment by jave** [comment]
Perhaps my expectations are wrong, but as superadmin, im expecting to see all domains. This is not the case for me at the moment.

**Comment by jave** [comment]
I added the dummy ALL domain in the database, and bound an admin to that domain, this admin can now see all domains, as expected. 

AFAIU the code, the superadmin flag should have the same features as having the ALL domain, but that doesnt seem to be the case for me.

note: i tried 3.2.4, and then tried master.

**Comment by jave** [comment]
sudo -i -u postgres psql -d postfix -c \"insert into domain(domain,active) values('ALL',true);\"        #workaround

**Comment by DavidGoodwin** [comment]
I'm curious what changed; is it possible you or someone else accidentally deleted the 'ALL' record?
