### ISSUE TITLE
Invalid query: Field 'cache' doesn't have a default value 

### ISSUE THREAD

**Issue by blackadder719** [postfixadmin/postfixadmin#39]
Hello all, I have encountered this issue with postfixadmin 2.3.5. 
This happens when I try to set an autoreply for a mail account

Php version is 5.6.30 - debian wheezy 

> DEBUG INFORMATION:
> Invalid query: Field 'cache' doesn't have a default value
> 
> Please check the documentation and website for more information. 

Could you guys help me to figure out how to fix it? 
I think it came out when updating php and mysql version, could it be?

**Comment by cboltz** [comment]
There are ways to get this fixed:
* change your MySQL config (/etc/my.cnf) and disable the strict mode ("sql_mode") - or -
* update PostfixAdmin to 3.0.2, which should have this fixed (IIRC - otherwise, grab the latest upgrade.php from github)
