### ISSUE TITLE
Bad passwords blocklist

### ISSUE THREAD

**Issue by svenseeberg** [postfixadmin/postfixadmin#390]
On our mail server we modified the `validate_password($password)` function to check for well known passwords in a `password_blocklist` table and block their use. Would this feature be interesting for the postfixadmin project in general? If yes, we would spend some time on integrating this feature fully into the code base.

Alternatively, we could add a hook which allows custom password validation.

**Comment by DavidGoodwin** [comment]
I think it'd probably be best for the $CONF['password_validation'] list to be changed to support callable functions (as well as a list of regexps).

**Comment by DavidGoodwin** [comment]
Hi - does the above implementation work for you? I'll close this issue, but feel free to re-open it if necessary.

**Comment by svenseeberg** [comment]
We will do that. Hopefully soon.

**Comment by svenseeberg** [comment]
@DavidGoodwin works perfectly, thanks!
