### ISSUE TITLE
Postfixadmin: "Setup password not specified correctly"

### ISSUE THREAD

**Issue by dangraves101** [postfixadmin/postfixadmin#392]
Hi Gitters,

I ran into the same issue. I followed the instructions from this website "https://www.exratione.com/2019/02/a-mailserver-on-ubuntu-18-04-postfix-dovecot-mysql/"

I entered the hash created to /var/www/html/postfixadmin/config.local.php after entering the setup password. The setup.php page keeps telling me " Setup password not specified correctly".

I used and without in the /var/www/html/postfixadmin/config.local.php

I used the instructions from "https://www.exratione.com/2019/02/a-mailserver-on-ubuntu-18-04-postfix-dovecot-mysql/". I do not see /etc/postfixadmin/config.local.php as i downloaded i followed the instructions.

I did add the ahs to /srv/postfixadmin/config/local.php as well as to /var/www/html/postfixadmin/config.local.php am new, not sure how I can fix this.

Details are here :=

a/. I created the hash for the password, on the page :
https://myserver/postfixadmin/setup.php

b/. Copied it to the file "/var/www/html/postfixadmin/config.local.php " and saved it,

c/. Returned to the browser page, and entered the appropriate data.

The set-up password I just applied
a new admin test email address
a new password for admin
retype new admin password.

Click "add admin"

See output below, including another "hashed" string...?

Postfix Admin Setup Checker

Running software:

PHP version 7.2.24-0ubuntu0.18.04.6
Apache
Checking for dependencies:

Magic Quotes: Disabled - OK
Depends on: presence config.inc.php - OK
Checking $CONF['configured'] - OK
Depends on: presence config.local.php - OK
Depends on: MySQL 4.1 - OK
Testing database connection (using mysqli) - OK
Depends on: session - OK
Depends on: pcre - OK
Depends on: multibyte string - OK
Depends on: IMAP functions - OK
Everything seems fine... attempting to create/update database structure

Database is up to date: 1840/0

                  Setup password not specified correctly
Thanks

**Comment by DavidGoodwin** [comment]
The easy answer is you're probably editing the wrong file (as in, perhaps there are multiple instances of postfixadmin on your server somehow.

Find where postfixadmin is installed on your computer. The guide you followed uses /srv/postfixadmin. 

At the top of it's config.inc.php file, after the opening '<?php' put a **die("Hello!");**  in and try refreshing the setup.php page in a browser.

Hopefully you'll see that 'Hello' message. Repeat this with where you think the config.local.php file is .... 

If you don't see the output from setup.php changing, try searching your computer for config.inc.php files. 

 * find / -name config.inc.php -print

Once you've done that, you should at least know for certain WHERE you need to specify the setup_password.
