### ISSUE TITLE
icons  and Forward vs Alias 

### ISSUE THREAD

**Issue by Jan-Kruis** [postfixadmin/postfixadmin#393]
I have 2 questions.

Question 1
I am working on an adjustment to replace the texts “edit” and “delete” with icons so that there is more space for the text fields.
Now I would like to align the icons to the right so that they are not right behind the text fields and I would also like to give them a fixed width. How do I change this in the css file?
I made the change on the latest git version.
How can I offer this adjustment to you to possibly include it.

Question 2
In the Virtual List layout [../list-virtual.php] the term alias is used with a part of the mailboxes. I think you should actually use the term forwarding, as it is used in the user area. This also makes me wonder if the dialog should not be the same as the user dialog [..user / edit-alias.php]. In my opinion, texts are also used that have nothing to do with forwarding an email, such as' To create a catch-all use an "*" as alias. ', but pertain to the term alias. I would also like to make an adjustment for this if you agree with my point of 

![icon's for text](https://user-images.githubusercontent.com/860350/96006968-53b40500-0e3e-11eb-878a-5e199fa7f7ca.jpg)
![users forward](https://user-images.githubusercontent.com/860350/96007001-5ca4d680-0e3e-11eb-8440-c31da2093456.jpg)
![admin forward](https://user-images.githubusercontent.com/860350/96007004-5dd60380-0e3e-11eb-8512-1ef16df2bc65.jpg)
![alias or forward](https://user-images.githubusercontent.com/860350/96007011-5e6e9a00-0e3e-11eb-8b09-30cb818f0cac.jpg)

view

**Comment by DavidGoodwin** [comment]
> I have 2 questions.
> 
> Question 1
> I am working on an adjustment to replace the texts “edit” and “delete” with icons so that there is more space for the text fields.
> Now I would like to align the icons to the right so that they are not right behind the text fields and I would also like to give them a fixed width. How do I change this in the css file?

Normally, but some CSS rules may be inline in the Smarty template file.

> I made the change on the latest git version.
> How can I offer this adjustment to you to possibly include it.

Ideally as a pull request. If you can't figure out how to do that, if I know where your repo is, I can probably get it merged.



> 
> Question 2
> In the Virtual List layout [../list-virtual.php] the term alias is used with a part of the mailboxes. I think you should actually use the term forwarding, as it is used in the user area. This also makes me wonder if the dialog should not be the same as the user dialog [..user / edit-alias.php]. In my opinion, texts are also used that have nothing to do with forwarding an email, such as' To create a catch-all use an "*" as alias. ', but pertain to the term alias. I would also like to make an adjustment for this if you agree with my point of

'foward' may be a more common / user friendly term. I suspect Postfixadmin uses 'alias' as that's the Postfix term.

I'm happy with it changing

**Comment by DavidGoodwin** [comment]
see #496
