### ISSUE TITLE
enhancement proposition: outside page for user for changing their passwords

### ISSUE THREAD

**Issue by Neurozone** [postfixadmin/postfixadmin#394]
Let me explain :)
I'm running postfixadmin on my server in order to create users and mailboxes for my domain and well, it works fine :)

BUT ! When I'm creating a user, I wan to have for them a temporary password for them and if we can have a page for them to change themselves the new password  like with inputing current email, old pawword, and two times the new password for changing I think it will be better :)

Or maybe I miss something ?

**Comment by Yuubari** [comment]
Look under the administrator log in form; there is a link titled ‘Users click here to login to the user section.’
