### ISSUE TITLE
Unable to access configuration page

### ISSUE THREAD

**Issue by WeebHiroyuki** [postfixadmin/postfixadmin#396]
Hello.
Right after setting it up, I tried accessing the page. It redirects me to login.php. On that page, I get this response.
```DEBUG INFORMATION:
Invalid query: ERROR: relation "config" does not exist LINE 1: SELECT value FROM config WHERE name = 'version' ^

Check your error_log for the failed query.
```

Does anyone know how to fix this? I already configured the database and stuff, but when I tried to access the site, it returns that.
Thanks.

**Comment by WeebHiroyuki** [comment]
In case anyone was wondering, I'm using a PostgreSQL database. The credentials are correct. It can log in. As far as I know, the PHP configuration file is also correct. I'm not sure what's the issue here.

**Comment by DavidGoodwin** [comment]
What about going to setup.php in a browser?

**Comment by WeebHiroyuki** [comment]
Yes, my bad. Sorry about this. I had forgotten to do a step.

**Comment by DavidGoodwin** [comment]
thanks for confirming + closing :)
