### ISSUE TITLE
I can't log in.

### ISSUE THREAD

**Issue by piiskop** [postfixadmin/postfixadmin#399]
Some time ago, I installed my own mail server with postfixadmin. Lately, I wanted to log in for seeing around how to create a new mail address. And I couldn't log in. I still can't. Google has stored both my admin passwords and they just don't work. So I was looking for an option to change the admin password and a suggestion was to use _setup.php_ which I did. I also copied the hash to the right place. But this is only for the setup password, right? What can I do with it anyway, create a new account? I don't want to create a new account as I already have two admin accounts. I also restarted the service with no success regarding to logging in. Can I change the password of my admin account directly in the database somehow?

**Comment by DavidGoodwin** [comment]
I suspect your best bet is to ....

 a. Go to postfixadmin/setup.php -> and create a new setup hash ... put that in config.local.php
 b. With that hash, add a new admin user, with a password you know
 c. Using that, update the database and swap the password hashs around and delete the extra unnecessary admin user.

Or just delete all admin users from the database, and create a new one using setup.php.


(You might want to take a DB backup first....!)

**Comment by piiskop** [comment]
I did _a_ and _b_ after backing up DB first. The result is "can't encrypt password with dovecotpw, see error log for details". I don’t even know where to look for that log. It isn’t postfixadmin’s log as there are no errors reported. And “dovecot”‘s service’s status is active – no problems, only two warnings after restart regarding to creating clean config file and and obsolete setting in SSL config file. So how can I restore the access to postfixadmin?

**Comment by DavidGoodwin** [comment]
see https://github.com/postfixadmin/postfixadmin/issues/398

**Comment by piiskop** [comment]
What do you suggest exactly, that I change the ownerships as AlphaJack did?

I also gave a try for “postfixadmin-cli”:
“root@test:/usr/share/postfixadmin/scripts# php postfixadmin-cli.php admin add
PHP Warning: Cannot assign an empty string to a string offset in /usr/share/postfixadmin/variables.inc.php on line 31

Warning: Cannot assign an empty string to a string offset in /usr/share/postfixadmin/variables.inc.php on line 31

Welcome to Postfixadmin-CLI v0.2
—————————————————————

Admin:
> pandeero@gmail.com

Password:
> [my password]

Password (again):
> [my password]

Super admin:
(Super admins have access to all domains, can manage domains and admin accounts.) (y/n)
> y

Domain:
> test.tennis24.ee

Active: (y/n)
> y
PHP Notice: Undefined index: domain in /usr/share/postfixadmin/functions.inc.php on line 1744

Notice: Undefined index: domain in /usr/share/postfixadmin/functions.inc.php on line 1744

The admin pandeero@gmail.com has been added!

—————————————————————”

As a result, the admin record in the database is back that I deleted before but I still can’t login as that admin.

**Comment by Maekess** [comment]
Having same issue on new database, creating superadmin from cli (present in database) and can't login.
Creatint superadmin from setup not even working atm.

**Comment by DavidGoodwin** [comment]
I think you're running a fairly old version of Postfixadmin - as we don't have a 'variables.inc.php' file any longer. Updating Postfixadmin to v3.2 or v3.3.x will probably fix your problems.
