### ISSUE TITLE
Addons SOGo

### ISSUE THREAD

**Issue by MisterM74** [postfixadmin/postfixadmin#4]
Hello
Exist there an addon that adds a domain and email addresses to SOGo?
Many greetings
Mz

**Comment by palepurple** [comment]
What's SOGo?

**Comment by MisterM74** [comment]
https://en.wikipedia.org/wiki/SOGo

**Comment by palepurple** [comment]
I don't understand why you'd want to use PostfixAdmin if you're using SOGo. 
Surely it has it's own admin UI etc (and presumably a different database schema).
