### ISSUE TITLE
mail for autoreply.domain.tld loops back to myself

### ISSUE THREAD

**Issue by blackadder719** [postfixadmin/postfixadmin#40]
Hello, first of all I got to say thank you for the resolution with the mysql issue for the vacation feature I wrote this morning, very quick and easy. But now I have another issue and I can't figure out how to solve it. When I activate the vacation feature for a mailbox and I try to send a mail to it, I get a message back that says:

Mar 27 17:58:50 mail postfix/smtp[57684]: C428196BEB: to=<mailbox#domain.tld@autoreply.domain.tld>, relay=none, delay=0.03, delays=0.01/0/0.02/0, dsn=5.4.6, status=bounced (mail for autoreply.domain.tld loops back to myself)

postfixadmin autoreply feature used to work like a charm without the vacation.pl plugin, since I had to update the php and mysql version and maybe that screw up something. Waiting for your kindly response!

**Comment by cboltz** [comment]
"loops back to myself" means postfix doesn't feel responsible for the domain autoreply.domain.tld (while the nameserver says it is responsible for it).

Please make sure to
- have the correct autoresponder domain in config.local.php
- have the correct autoresponder domain in vacation.pl (better. /etc/postfixadmin/vacation.conf) 
- have postfix configured as described in the vacation README
