### ISSUE TITLE
Mailboxes root folder definition

### ISSUE THREAD

**Issue by oregszun** [postfixadmin/postfixadmin#400]
Hello Guys,

I have been checking the config.inc.php since an hour or two and unable to find where the root directory of virtual mailboxes are defined?

In the example it is /usr/local/virtual:

// Mailboxes
// If you want to store the mailboxes per domain set this to 'YES'.
// Examples:
//   YES: /usr/local/virtual/domain.tld/username@domain.tld
//   NO:  /usr/local/virtual/username@domain.tld

**Comment by DavidGoodwin** [comment]
The mail root is defined in Postfix, see 

e.g. in /etc/postfix/main.cf :

```
virtual_mailbox_base = /var/mail/vmail
```


You then effectively duplicate this in dovecot (or equivalent) 

with e.g. this in /etc/dovecot/dovecot.conf

```
mail_location = maildir:/var/mail/vmail/%u/
````

The path(s) stored within Postfixadmin's database are all relative to that root.
