### ISSUE TITLE
Phar present but postfixadmin thinks it isn't

### ISSUE THREAD

**Issue by dbostrom** [postfixadmin/postfixadmin#401]
This may not be an "issue" but instead incompetence, but in any case I'm stymied and must ask for help.

PHP 5.6.40

Adding a mailbox to a virtual domain produces: 

> /var/www/[domain]/postfixadmin/lib/block_random_int.php Postfixadmin security: Please install https://github.com/paragonie/random_compat OR enable the 'Phar' extension."

I've verified that Phar is present, per info:

> Registered PHP Streams | https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip

and

> Phar: PHP Archive support | enabled
> Phar EXT version | 2.0.2
> Phar API version | 1.1.1
> SVN revision | $Id: 6e5cec2462a6ded53d4379ea9a69487a60d5c43c $
> Phar-based phar archives | enabled
> Tar-based phar archives | enabled
> ZIP-based phar archives | enabled
> gzip compression | enabled
> bzip2 compression | enabled
> OpenSSL support | enabled
> 

Any suggestions (other than "upgrade php" yeah I know :-) ) would be welcome. Thanks!

Also thanks much for postfixadmin. We've been using it for years and it makes life much easier.

**Comment by DavidGoodwin** [comment]
* Is the .phar file in the right directory? 
 * Is the .phar file readable by the web server?

**Comment by DavidGoodwin** [comment]
I think you could download https://raw.githubusercontent.com/paragonie/random_compat/master/lib/random_int.php and require_once(...) it in config.local.php .... that'd give you a random_int() function that ought to be OK?

**Comment by dbostrom** [comment]
Thank you, David.

I'll check the above re .phar location and permissions, and then I have your suggestion for manually arranging random_int as a a backstop and which would be fine. 

Come to think of it, where _should_ the .phar file be located? (sorry, I'm stretched thin)

**Comment by DavidGoodwin** [comment]
phar -> I think it should be in the lib/ directory.
