### ISSUE TITLE
[BUG] Excessive information disclosure at setup.php

### ISSUE THREAD

**Issue by Raywando** [postfixadmin/postfixadmin#402]
The page setup.php discloses some information about the server and sometimes it even discloses the mysql database endpoint along with the username of the database which is not supposed to be public.

![P5WZALXIeP](https://user-images.githubusercontent.com/33800255/101378907-b7016700-38c4-11eb-8a9a-b13e7a0f84c8.png)

**Comment by DavidGoodwin** [comment]
Thanks for the report - would only showing that information if `$CONF['setup_password'] = 'changeme';` be acceptable?

**Comment by Raywando** [comment]
Hi, @DavidGoodwin 

So does that mean this information won't be visible if it was configured?

But there is always the risk of not configuring it, I've seen multiple postfixadmin panels where it was disclosed (not configured), too avoid that, maybe it would be mandatory to set the setup password when installing postfixadmin.

**Comment by DavidGoodwin** [comment]
Er, yeah, it'd become necessary to set the setup password first, before we tried to check / do any database stuff ... that might make it slightly harder to troubleshoot incorrect config, but probably the only way.

**Comment by Raywando** [comment]
This may sound like a noobie question but does this worth assigning a CVE for if you are planning to post an update to fix it?

**Comment by DavidGoodwin** [comment]
I've no idea how to go about getting a CVE - @cboltz any opinions ?

This is where I've got to with the feature-setup-bootstrap branch :

![image](https://user-images.githubusercontent.com/203929/101698675-d38ed200-3a71-11eb-9787-ad0fd4e3c92d.png)

**Comment by DavidGoodwin** [comment]
Once you've logged in with a setup_password : 

![image](https://user-images.githubusercontent.com/203929/101698764-fc16cc00-3a71-11eb-894e-baf3da977706.png)


Hmm, I can see I left some notes-to-myself in there that need removing ...

# Notes 

 * setup_password hash changed from a homegrown sha1 salt+ sha1 hash to use password_hash(...). 
 * Anyone upgrading to this variant / code would have to update their setup_password value with a new one.

**Comment by DavidGoodwin** [comment]
fixed in v3.3.0.
