### ISSUE TITLE
[BUG] Download this list as CSV file

### ISSUE THREAD

**Issue by mbonera** [postfixadmin/postfixadmin#404]
If you try do download CSV file from the domain details in virtual list, you get all aliases/mailboxes for all the domains that belong to the user currently logged in. To reproduce the wrong behavior, just go to virtual list, choose a random domain and click on "Download this list as CSV file".

I fixed the issue by doing that:

```
# diff /usr/share/postfixadmin.bug/templates/list.tpl  /usr/share/postfixadmin/list.tpl 
134c134
< <br /><a href="list.php?table={$table|escape:"url"}&amp;output=csv">{$PALANG.download_csv}</a>
---
> <br /><a href="list.php?table={$table|escape:"url"}&amp;output=csv&amp;domain={$domain_selected}">{$PALANG.download_csv}</a>
```
```
# diff /usr/share/postfixadmin.bug/templates/list-virtual.tpl  /usr/share/postfixadmin/templates/list-virtual.tpl 
67c67
< 	<br /><br /><a href="list.php?table=mailbox&amp;output=csv">{$PALANG.download_csv}</a>
---
> 	<br /><br /><a href="list.php?table=mailbox&amp;output=csv&amp;domain={$domain_selected}">{$PALANG.download_csv}</a>
```

```
# diff /usr/share/postfixadmin.bug/list.php  /usr/share/postfixadmin/list.php 
109a110,112
>     // Getting current domain (mbonera 20201210)
>     $fDomain = safepost('fDomain', safeget('domain', safesession('list-virtual:domain')));
>   
111a115,118
> 
> 	// Skip domains that not match selected domain (mbonera 20201210)
>         if (!empty($fDomain) && $item["domain"] != $fDomain) continue;
> 
113a121,122
>             // Modified by mbonera - skip status column that contains html code
>             if ($column == "status") continue;

```

**Comment by DavidGoodwin** [comment]
Hi -

Thanks for the bug report. What's the point of skipping the status column (last part of your patch above) ?


In future, it'd help if you created this as a pull request, or at least provided more context with the diff ....


I've attempted to merge this into 'master' anyway.

**Comment by DavidGoodwin** [comment]
merged into 3.2

**Comment by mbonera** [comment]
Il 24/12/20 11:46, David Goodwin ha scritto:
>
> Hi -
>
> Thanks for the bug report. What's the point of skipping the status 
> column (last part of your patch above) ?
>

Hi David.

First of all, sorry for the delay. I had a very busy time during holidays.

I removed the last column because it contains HTML code, not just a 
value. I thought that it was not useful to have a column like that in 
the CVS file.
Maybe we can do some transformation, stripping out the HTML code and 
leave only the content, so the column must not be removed.

> In future, it'd help if you created this as a pull request, or at 
> least provided more context with the diff ....
>

I'm sorry for the mistake, but I thought that it was a bug (for me it 
was) and I filed a bug report. The next time I'll be more careful and 
provide more info.

Cheers,
-- 
*Morrisoft di M. Bonera*
Via Piave, 15 - Collebeato (BS)
PIVA: IT03960790982
------------------------------------------------------------------------
<mailto:info@zipoware.com> 	info@morrisoft.eu <mailto:info@morrisoft.eu>
<mailto:info@zipoware.com> 	mbonera@pec.it <mailto:mbonera@pec.it>

**Comment by DavidGoodwin** [comment]
Hi again,

Submitting a pull request allows you to get credit for your work - and makes it less likely whoever merges it will mess up and break something :+1: 

Don't worry about the mistake - we all make them ! I'm more than happy receiving any sort of patch / bug report / enhancement ....

David.
