### ISSUE TITLE
[Feature Request] Darkmode

### ISSUE THREAD

**Issue by ayourk** [postfixadmin/postfixadmin#405]
[darkmode.css.txt](https://github.com/postfixadmin/postfixadmin/files/5728228/darkmode.css.txt)
I've prepared a Darkmode CSS that I hope you will include in new releases.

**Comment by DavidGoodwin** [comment]
what version / branch is this based on?

**Comment by ayourk** [comment]
This is based on the 3.2.4 release.  Should I have used something else as the base?

**Comment by DavidGoodwin** [comment]
Ideally, 'master' - but it's based on bootstrap - so looks somewhat different (and is presumably very different from a CSS PoV).

![image](https://user-images.githubusercontent.com/203929/103013147-91b36080-4534-11eb-8d8a-95e6742e656b.png)


![image](https://user-images.githubusercontent.com/203929/103013193-a1cb4000-4534-11eb-8b69-f26cb80eb17a.png)


etc.
