### ISSUE TITLE
Support for dovecot mail-crypt-plugin?

### ISSUE THREAD

**Issue by BotoX** [postfixadmin/postfixadmin#408]
I've recently setup a mostly standard virtual mail server with Postfix + Dovecot.
However I've decided to go with per-user encrypted maildir, using the users login passphrase.
For more info see: "Encrypted user key"
https://doc.dovecot.org/configuration_manual/mail_crypt_plugin/

When adding a new mailbox one has to pass the user + password to the following command in order to generate the encryption keys:
`doveadm -o plugin/mail_crypt_private_password="PASSWORD" mailbox cryptokey generate -u "user@example.org" -U`

Likewise when the user changes their password, the encryption keys have to be updated:
`doveadm mailbox cryptokey password -u "user@example.org" -o "OLD_PASSWORD" -n "NEW_PASSWORD"`
The old password is required to decrypt the key, which is then encrypted with the new password.

I've patched the latest stable release of postfixadmin (3.2.4) and tested it a bit, here are my changes:
https://github.com/BotoX/postfixadmin/commit/d88ed67a1aa2e3609e3186d77e219687eadc03f4

And here it is for the master branch:
https://github.com/BotoX/postfixadmin/commit/c6ae3ea2f3921c1a682315d1205bec42aaa32035

Should be flexible enough for similar setups.

Changing mailbox passwords without entering the old password (in the admin panel) is blocked by this patch, as this makes no sense.
If the user loses their mailbox password then all of their data is gone.
Changing the password in SQL without updating the encryption keys only makes dovecot scream in horror and crash.

This mail server setup is not fully in "production" yet (me and a few friends) so I can't tell how stable this dovecot feature is.

Inspired by: https://gist.github.com/yajrendrag/203b0172fee96a8b002a026362d27bf2#additional-postfixadminroundcube-setup-to-support-ispmail-optional-encryption
This also adds a new x_crypt option to the database to decide about encryption per mailbox, unlike my patch.

**Comment by DavidGoodwin** [comment]
Thanks for this - I've merged it into master.

**Comment by DavidGoodwin** [comment]
Hmm .... I had to comment out some of the code in Login - 

https://github.com/postfixadmin/postfixadmin/blob/70bf59edc4920ae7825857cbe76482d6a66722fc/model/Login.php#L125

as e.g. $this->id isn't defined.

What command should be being run here after someone's changed their password?

**Comment by BotoX** [comment]
I guess I should've tested the changes on master too instead of just blindly copy pasting stuff...
`$this->id` should be the email/username so `$username` is the correct one, have just tested it as well.

**Comment by DavidGoodwin** [comment]
> I guess I should've tested the changes on master too instead of just blindly copy pasting stuff...
> `$this->id` should be the email/username so `$username` is the correct one, have just tested it as well.

Thanks
