### ISSUE TITLE
CSS broken in 3.3.0?

### ISSUE THREAD

**Issue by mzch** [postfixadmin/postfixadmin#410]
Updating from 3.2 to 3.3, all screens look broken.

e.g.
<img width="1490" alt="スクリーンショット 2021-01-10 0 41 26" src="https://user-images.githubusercontent.com/621178/104095900-b18ca780-52dc-11eb-9daf-450f27baa760.png">

Would you fix this?

- OS: macOS 11.1
- Browser: Chrome 87, Safari 14.0.2

**Comment by qcybb** [comment]
I'm having the same issue. The display is all messed up.

**Comment by DavidGoodwin** [comment]
ah, it looks like we changed setup.php - presumably you've got the original values overriding the new ones somehow ?

See also : 6ad44679a7486e8d49b189f1d8d90bed464355ef


```
diff --git a/config.inc.php b/config.inc.php
index 949fe96e..97464412 100644
--- a/config.inc.php
+++ b/config.inc.php
@@ -672,11 +672,11 @@ function x_send_sms_clickatell($to, $message) {
 */
 
 // Theme Config
-$CONF['theme'] = 'default';
+$CONF['theme'] = 'bootstrap';
 // Specify your own favicon, logo and CSS file
 $CONF['theme_favicon'] = 'images/favicon.ico';
 $CONF['theme_logo'] = 'images/logo-default.png';
-$CONF['theme_css'] = 'css/default.css';
+$CONF['theme_css'] = 'css/bootstrap.css';

```

**Comment by qcybb** [comment]
Thank you, that fixed the issue for me.

**Comment by mzch** [comment]
Thanks! Fixed. :)
