### ISSUE TITLE
run setup or any to update create/database in an unatended way

### ISSUE THREAD

**Issue by Maekess** [postfixadmin/postfixadmin#411]
Hello,

You just updated to 3.3.0 which is great, security is good. I was just finishing my sever "automatic" installation, and you updated. So did I.
But now is my issue, is there a way to run setup.php after postfixadmin installation like i was doing before :
copy all my conf files, then run "sudo -u www-data php /usr/share/postfixadmin/public/setup.php" to create database and all.
I create all my domain during installation as the lazy one I am ^^. And now postfixadmin-cli returns "Table 'postfix.config' doesn't exist" because I can't run setup prior to it.

Any clue to help me do as before, or should I install 3.2 then update to last by hand.

I guess a parameter with password on my command line would work, but the idea is not to put the password in the script, and install would be still automatic.

Thanks

**Comment by DavidGoodwin** [comment]
Hi - Running public/upgrade.php should do all the database things.

(as long as you're confident your config ( $CONF ) is correct....)

**Comment by DavidGoodwin** [comment]
see also https://github.com/postfixadmin/docker/blob/296ae9a5163a6c0e19ab5cad5ebfddfda4ab9a6c/apache/docker-entrypoint.sh- which might give you some hints ....

**Comment by Maekess** [comment]
Seams to update Database, but now there is another error on cli : (may be another bug, should i log another one ?)

sudo postfixadmin-cli domain add domaine.test --default-aliases "0" --backupmx

Welcome to Postfixadmin-CLI v0.3
---------------------------------------------------------------
PHP Fatal error:  Uncaught Error: Call to undefined method DomainHandler::store() in /usr/share/postfixadmin/model/CliEdit.php:189
Stack trace:
#0 /usr/share/postfixadmin/model/CliEdit.php(65): CliEdit->__handle('domaine.test', Array)
#1 /usr/share/postfixadmin/model/CliEdit.php(21): CliEdit->__handle_params()
#2 /usr/share/postfixadmin/scripts/postfixadmin-cli.php(221): CliEdit->execute()
#3 /usr/share/postfixadmin/scripts/postfixadmin-cli.php(398): PostfixAdmin->dispatch()
#4 {main}
  thrown in /usr/share/postfixadmin/model/CliEdit.php on line 189

Fatal error: Uncaught Error: Call to undefined method DomainHandler::store() in /usr/share/postfixadmin/model/CliEdit.php:189
Stack trace:
#0 /usr/share/postfixadmin/model/CliEdit.php(65): CliEdit->__handle('domaine.test', Array)
#1 /usr/share/postfixadmin/model/CliEdit.php(21): CliEdit->__handle_params()
#2 /usr/share/postfixadmin/scripts/postfixadmin-cli.php(221): CliEdit->execute()
#3 /usr/share/postfixadmin/scripts/postfixadmin-cli.php(398): PostfixAdmin->dispatch()
#4 {main}
  thrown in /usr/share/postfixadmin/model/CliEdit.php on line 189

**Comment by DavidGoodwin** [comment]
Hm, I wonder if this is related to https://github.com/postfixadmin/postfixadmin/commit/6663a35bdba439076f21c235839b16e01b6fa6ce

**Comment by Maekess** [comment]
That last change "efb1897" did the trick.

Thanks
