### ISSUE TITLE
Non-working HTTPS links in footer

### ISSUE THREAD

**Issue by J0WI** [postfixadmin/postfixadmin#412]
a5c610baa9b0d5705412e1afe9756fec445031ee changed the links to `postfixadmin.sf.net` from HTTP to HTTPS. But the host does not support HTTPS.

https://github.com/postfixadmin/postfixadmin/blob/a5c610baa9b0d5705412e1afe9756fec445031ee/templates/footer.tpl#L4

https://github.com/postfixadmin/postfixadmin/blob/a5c610baa9b0d5705412e1afe9756fec445031ee/templates/footer.tpl#L7

**Comment by DavidGoodwin** [comment]
Grr - well spotted and sorry. I made the change without thinking, assuming that surely everywhere supports https now .... :-/
