### ISSUE TITLE
500 Internal Errors in 3.3.0

### ISSUE THREAD

**Issue by qcybb** [postfixadmin/postfixadmin#413]
The following pages produce a 500 internal error.

https://domain.com/postfixadmin/list.php?table=domain
https://domain.com/postfixadmin/list-virtual.php

Invalid query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'password_expiry' in 'field list'

I've ran setup.php and it shows 

Everything seems fine... attempting to create/update database structure
Database is up to date: 1843/0

**Comment by qcybb** [comment]
User did not have the right database permissions.

Closing this.

**Comment by DavidGoodwin** [comment]
Thanks for following up and specifying the solution !

**Comment by gampam2000** [comment]
We have a similar problem,
after update from 3.2 to 3.3.8 we can login into postfix but if you click on a page (domain list,..) than we get a blank page. In the Apache Log we get:

apache error log: [Sat May 08 09:39:29.382566 2021] [php7:error] [pid 42098] [client xxxx:37154] PHP Fatal error:  **Uncaught Exception: DEBUG INFORMATION: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'password_expiry' in 'field list'<br/>** Check your error_log for the failed query in /srv/postfixadmin.3.3.8/functions.inc.php:1858\nStack trace:\n#0 /srv/postfixadmin.3.3.8/functions.inc.php(1797): db_query()\n#1 /srv/postfixadmin.3.3.8/model/PFAHandler.php(772): db_query_all()\n#2 /srv/postfixadmin.3.3.8/model/PFAHandler.php(841): PFAHandler->read_from_db()\n#3 /srv/postfixadmin.3.3.8/public/list.php(91): PFAHandler->getList()\n#4 {main}\n  thrown in /srv/postfixadmin.3.3.8/functions.inc.php on line 1858, referer: https://xxx/postfixadmin/main.php
"/var/log/apache2/error.log" 30L, 10197

The setup.php file states that everything should be fine. We allready checked the database permissions, everything is granted. 

Any advice on how to fix this?

**Comment by klemens-u** [comment]
> User did not have the right database permissions.
> 
> Closing this.

Same problem here. Could you please provide details what you mean by that? Thanks!
