### ISSUE TITLE
Can't create new superadmin through CLI or web

### ISSUE THREAD

**Issue by jliguori1312** [postfixadmin/postfixadmin#415]
Fresh install, everything went fine until I got to adding a superadmin. The form on setup.php doesn't give an error but it just reloads with no indication of success or anything else. Logging in doesn't work so I assume this is not creating the account.

I then ran this:
 `/srv/postfixadmin/scripts/postfixadmin-cli admin add user@domain.com --superadmin 1 --active 1 --password passhere --password2 passhere`

and got this:
```
Welcome to Postfixadmin-CLI v0.3
---------------------------------------------------------------
PHP Fatal error:  Uncaught Error: Call to undefined method AdminHandler::store() in /srv/postfixadmin/model/CliEdit.php:189
Stack trace:
#0 /srv/postfixadmin/model/CliEdit.php(65): CliEdit->__handle('jliguori@jeremy...', Array)
#1 /srv/postfixadmin/model/CliEdit.php(21): CliEdit->__handle_params()
#2 /srv/postfixadmin/scripts/postfixadmin-cli.php(221): CliEdit->execute()
#3 /srv/postfixadmin/scripts/postfixadmin-cli.php(398): PostfixAdmin->dispatch()
#4 {main}
  thrown in /srv/postfixadmin/model/CliEdit.php on line 189

Fatal error: Uncaught Error: Call to undefined method AdminHandler::store() in /srv/postfixadmin/model/CliEdit.php:189
Stack trace:
#0 /srv/postfixadmin/model/CliEdit.php(65): CliEdit->__handle('jliguori@jeremy...', Array)
#1 /srv/postfixadmin/model/CliEdit.php(21): CliEdit->__handle_params()
#2 /srv/postfixadmin/scripts/postfixadmin-cli.php(221): CliEdit->execute()
#3 /srv/postfixadmin/scripts/postfixadmin-cli.php(398): PostfixAdmin->dispatch()
#4 {main}
  thrown in /srv/postfixadmin/model/CliEdit.php on line 189
```

Ubuntu 18.04, PHP 7.2 and MySQL.

**Comment by efelon** [comment]
I can confirm, but I only tried setup.php. I ended up going with the hint in #261:

1. Inset `$CONF['encrypt'] = 'md5';` into _config.local.php_
2. Add the admin manually into the database (mysql in my case):
`INSERT INTO admin(username,superadmin,password) VALUES ('YourUsername','1',MD5('YourSuperpassword'));`

I haven't tested any further but I'm able to login.

**Comment by jliguori1312** [comment]
Thanks, that worked for me as well.

However, I have a new issue now, adding a domain gets a failed error and the apache error log shows:
```Got error 'PHP message: Invalid query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'domainhere.com' for key 'PRIMARY' caused by INSERT INTO `domain` (domain,description,aliases,mailboxes,maxquota,quota,transport,backupmx,active,created,modified,password_expiry) VALUES (:domain,:description,:aliases,:mailboxes,:maxquota,:quota,:transport,:backupmx,:active,now(),now(),:password_expiry)\n', referer: https://mail.serverdomain.here/mailAccess/edit.php?table=domain```


> I haven't tested any further but I'm able to login.

Seems unrelated, but curious if you're also getting this?

**Comment by DavidGoodwin** [comment]
I think efb1897a4f632c0fb574f0ccbb4facc6fbe18df2 will fix the cli problem?

**Comment by DavidGoodwin** [comment]
This works on my local copy based on what's in the postfixadmin_3.3 branch : 

```
./postfixadmin-cli admin add dg@example.com --superadmin 1 --active 1 --password blahblah22 --password2 blahblah22

Welcome to Postfixadmin-CLI v0.3
---------------------------------------------------------------

The admin dg@example.com has been added!

---------------------------------------------------------------
```

and I can login as that new user.

I'll do a 3.3.1 release.

**Comment by efelon** [comment]
@jliguori1312 

> However, I have a new issue now, adding a domain [...]

Works fine for me on the web interface. It gives me a success message and inserts a row in the table.:

```
+-------------------+-------------+---------+-----------+----------+-------+-----------+----------+---------------------+---------------------+--------+-----------------+
| domain            | description | aliases | mailboxes | maxquota | quota | transport | backupmx | created             | modified            | active | password_expiry |
+-------------------+-------------+---------+-----------+----------+-------+-----------+----------+---------------------+---------------------+--------+-----------------+
| newdomain.com     |             |       0 |         0 |       10 |  2048 | virtual   |        0 | 2021-01-11 11:56:29 | 2021-01-11 11:56:29 |      1 |               0 |
+-------------------+-------------+---------+-----------+----------+-------+-----------+----------+---------------------+---------------------+--------+-----------------
```
@DavidGoodwin You fix works. I can add admins also in the web UI again. But there, the admin username needs to be a valid mail address. Whereas in the setup script it can be just a name.

**Comment by efelon** [comment]
@DavidGoodwin Creating an admin with the setup.php still doesn't work.

And one addition if I may a little offtopic. The "setup password" field for creating an admin in setup.php is not a password field:
![Bildschirmfoto von 2021-01-11 13-10-58](https://user-images.githubusercontent.com/10722552/104181180-9c179a80-540e-11eb-8edd-58929a1ebe86.png)
