### ISSUE TITLE
Update from 3.2 to 3.3.1 cannot manage vacation

### ISSUE THREAD

**Issue by tempixx** [postfixadmin/postfixadmin#416]
Just updated from 3,2.4 to 3,3,1. The vacation management does not work: click on"Change/Set away message" "Remove away message" does nothing. Using the old 3.2 on the same installation works fine. PHP version is 7.4. I found nothing in the (apache) logs. Any idea?

PHP downgraded to 7.3: same issue.
Here are some PHP notices:
[Tue Jan 12 16:18:37.582443 2021] [php7:notice] [pid 29253:tid 139799474189888] [client 10.10.0.6:57651] PHP Notice:  Trying to get property 'value' of non-object in /var/www/
localhost/htdocs/postfixadmin-3.3.1/templates_c/a6214ae899960f3574d56b959778a14a118574b7_0.file.list.tpl.php on line 277, referer: https://XX/postfixadmin/public/vaca
tion.php?username=xx%40XX
[Tue Jan 12 16:19:01.224673 2021] [php7:notice] [pid 29253:tid 139799474189888] [client 10.10.0.6:57651] PHP Notice:  Undefined index: domain_selected in /var/www/localhost/ht
docs/postfixadmin-3.3.1/templates_c/a6214ae899960f3574d56b959778a14a118574b7_0.file.list.tpl.php on line 277, referer: https://XX/postfixadmin/public/vacation.php?use
rname=xx%40XX

Just recognized that the 3.3 version is really fresh :-)  Dear developers, thanks and keep up the good work!

**Comment by DavidGoodwin** [comment]
Thanks for the bug report! I think it may be fixed. Please could you test it? Either in master or the postfixadmin_3.3 branch (they're pretty much identical at the moment still).

**Comment by tempixx** [comment]
Dear David, thank you for your quick reaction. Just tried the master branch, it WORKS now :-)

Found a small bug in the header layout, the link under the postbox.png will open .../main.phpmain.php
