### ISSUE TITLE
Question - Confused about postfix maps

### ISSUE THREAD

**Issue by IbrahimS2** [postfixadmin/postfixadmin#417]
Why the maps and aliases pointed to multiple files? Can someone explain the purpose of the highlighted configurations?

virtual_mailbox_domains = proxy:mysql:/etc/postfix/sql/mysql_virtual_domains_maps.cf

**virtual_alias_maps** =
   proxy:mysql:/etc/postfix/sql/mysql_virtual_alias_maps.cf,
   **proxy:mysql:/etc/postfix/sql/mysql_virtual_alias_domain_maps.cf,
   proxy:mysql:/etc/postfix/sql/mysql_virtual_alias_domain_catchall_maps.cf**

**virtual_mailbox_maps** =
   proxy:mysql:/etc/postfix/sql/mysql_virtual_mailbox_maps.cf,
   **proxy:mysql:/etc/postfix/sql/mysql_virtual_alias_domain_mailbox_maps.cf**

**Comment by DavidGoodwin** [comment]
Try checking the contents of those files, along with their names.

I assume it's to allow you to have catch all domains (i.e. anything@example.org -> somewhere) AND so you can treat e.g. me@example.org as the same as me@example.com

**Comment by IbrahimS2** [comment]
@DavidGoodwin I am getting the hang of it so far, another question so I do not have to start new issue and I hope you do not mind, transports we do want to be able to map transports to specific domains, this is not possible from what I can see in the control panel, any suggestions?

**Comment by DavidGoodwin** [comment]
e.g. https://sourceforge.net/p/postfixadmin/discussion/676076/thread/7d24dd93/


transports -> I don't know much more - I know it's been discussed a few times either in closed tickets here, or on the sourceforge forum  .... it's not a feature I've looked at.
