### ISSUE TITLE
Unable to create a superadmin account in setup.php

### ISSUE THREAD

**Issue by boily** [postfixadmin/postfixadmin#418]
https://github.com/postfixadmin/postfixadmin/blob/bb37912a100890b03be907d7a2e4b3ac56a62046/public/setup.php#L391

On a new installation we are unable to create a superadmin account because
safepost("form") returns empty al line 391.

A possible fixe would be to change the submit value to "createadmin" at line 380
and change line 391 from
`if (safepost("form") === "createadmin" && $authenticated) {`
to
`if (safepost("submit") === "createadmin" && $authenticated) {`

thank you
Roger

**Comment by DavidGoodwin** [comment]
Thank you for reporting this. It's in the postfixadmin_3.3 branch....

**Comment by DavidGoodwin** [comment]
I believe this is fixed with release 3.3.3
