### ISSUE TITLE
$CONF['password_validation'] default prevents a012312321 as a valid password

### ISSUE THREAD

**Issue by ShamimIslam** [postfixadmin/postfixadmin#423]
Checked on **[https://regex101.com/](https://regex101.com)**

Current default does not allow a password that does not have **3 consecutive letters**. Correct validation should be **3 consecutive CHARACTERS**. **Spaces** should be **allowed inside** the password as well as special characters. Otherwise this restriction violates the premise of strong passwords. 
```
$CONF['password_validation'] = array(
#    '/regular expression/' => '$PALANG key (optional: + parameter)',
    '/.{5}/'                => 'password_too_short 5',      # minimum length 5 characters
    '/([a-zA-Z]){3}/'     => 'password_no_characters 3',  # must contain at least 3 characters
    '/([0-9].*){2}/'        => 'password_no_digits 2',      # must contain at least 2 digits
);
```

Should be
```
$CONF['password_validation'] = array(
#    '/regular expression/' => '$PALANG key (optional: + parameter)',
    '/.{5}/'                => 'password_too_short 5',      # minimum length 5 characters
    '/[a-zA-Z0-9!@#$%^&*\(\)~`;:\'\",.<>\/?{}\[\]\\=+-_][ a-zA-Z0-9!@#$%^&*\(\)~`;:\'\",.<>\/?{}\[\]\\=+-_]{2}/'     => 'password_no_characters 3',  # must contain at least 3 characters
    '/([0-9].*){2}/'        => 'password_no_digits 2',      # must contain at least 2 digits
);
```

**Comment by DavidGoodwin** [comment]
can any bits of your refined regex be replaced with one of the magic characters (like \w or \N?) see also https://www.pcre.org/original/doc/html/pcrepattern.html

**Comment by ShamimIslam** [comment]
Not by much. Actually, I missed some of the punctuation. Could have been done with POSIX REGEX. but 

```
$CONF['password_validation'] = array(
#    '/regular expression/' => '$PALANG key (optional: + parameter)',
    '/.{5}/'                => 'password_too_short 5',      # minimum length 5 characters
    '/(\d|\w|[!@#$%^&*\(\)~`;:\'\",.<>\/?{}\[\\=+_\-?|])( |\d|\w|[!@#$%^&*\(\)~`;:\'\",.<>\/?{}\[\\=+_\-?|]){2}/'     => 'password_no_characters 3',  # must contain at least 3 characters
    '/([0-9].*){2}/'        => 'password_no_digits 2',      # must contain at least 2 digits
);
```

The not-word matches everything that is a word so it's not much use. POSIX REGEX has more predefined character classes like digit, and punct and so on. Lengthwise, would still be almost the same number of characters, but might compile faster. But given the incredibly low volume of access on this one function, it doesn't make sense to attempt to optimize is much more than this. The point of diminishing returns has been reached.

**Comment by DavidGoodwin** [comment]
Hmm, my worry is that a regex like : "    ```'/(\d|\w|[!@#$%^&*\(\)~`;:\'\",.<>\/?{}\[\\=+_\-?|])( |\d|\w|[!@#$%^&*\(\)~`;:\'\",.<>\/?{}\[\\=+_\-?|]){2}/' ``` is almost unintelligible. 

Should we just have `if(mb_strlen($password) < 3) { .... }`  somewhere in the same code path?  With 3.3.0+ each of those 'things' can be a callable - and if it returns a non-zero length string, then it's assumed to be an error. Is there a better way of doing this than using a regex?

**Comment by ShamimIslam** [comment]
You can use strlen(trim($password)).

I was attempting to stick to what you used. I didn't realize the "things"
are callable. When/where can I get the RPM for 3.3.0+?

Thanks.

**Comment by DavidGoodwin** [comment]
See e.g. https://github.com/postfixadmin/postfixadmin/blob/36193c934eaa408dccc0f61f2e79fd96d9ed3d61/config.inc.php#L227 for a commented out example.

@cboltz any RPMs floating around that you know of?

**Comment by ShamimIslam** [comment]
So using a non-regex, executes the lambda function instead?

**Comment by ShamimIslam** [comment]
I'm running postfixadmin-3.2-128.1.noarch.

**Comment by DavidGoodwin** [comment]
> So using a non-regex, executes the lambda function instead?

For v3.3.0+, yes. 

Added as part of 4712d83c9839ec51f71caa27b0ec37920fe574c2 / #390

**Comment by ShamimIslam** [comment]
Sweet. Your prior regex really wasn't doing what it said. I had a 9
character password that had 1 letter, followed by 2 digits, another letter,
and then 4 digits and then a punctuation character. Did not fit the "3
letters in a row" pattern, which claimed it was testing for minimum 3
character password. That's how this all got started.

**Comment by DavidGoodwin** [comment]
https://xkcd.com/1171/ seems apt ;-)

**Comment by DavidGoodwin** [comment]
I've added 'consecutive' into the comment next to the regex

**Comment by ShamimIslam** [comment]
David,

3 consecutive letters is not a valid password requirement. You should be
able to have 3 digits or letters.

That was the problem.

**Comment by DavidGoodwin** [comment]
@ShamimIslam - yes, I'd agree the 3 consecutive letters is not a very good password requirement!  It was more a question of how to address it - I hoped leaving the choice to the end user would suffice :)

**Comment by ShamimIslam-V35362** [comment]
Better yes. Absolutely. But can we at least have something in the config.local.php that makes it obvious how to fix the password validation to the user's choice? As I understood it, we were not supposed to modify config.php.

**Comment by ShamimIslam** [comment]
Absolutely almost better. 

```
strlen(trim($password))>2
```

Can we also have something in config.local.php that makes it obvious how to make changes to the password validation. As I understand it, we should not be updating config.php.

**Comment by DavidGoodwin** [comment]
config.local.php overrides whatever is in config.inc.php - so technically the two files could start identical, and you then just change some things config.local.php - and shouldn't need to worry if the Postfixadmin project decides to (for example) change the default pacrypt method.

So if you want to have your own password_validation stuff - add something like this to config.local.php :

```php
$CONF['password_validation'] = array(
    '/([0-9].*){2}/'        => 'password_no_digits 2',      # must contain at least 2 digits
    'my_super_validator' =>  function($password) { return strlen(trim($password)) > 5; },
);
```

You can add many callables into the password_validation list, so if you want you could also have something checking a service like HaveIBeenPwned (https://haveibeenpwned.com/API/v2)

**Comment by DavidGoodwin** [comment]
see commits in https://github.com/postfixadmin/postfixadmin/issues/440

**Comment by ShamimIslam** [comment]
Is this in the documentation?

**Comment by DavidGoodwin** [comment]
> Is this in the documentation?

see e.g. https://github.com/postfixadmin/postfixadmin/blob/master/config.inc.php#L18

**Comment by ShamimIslam** [comment]
Got it. :)

**Comment by cboltz** [comment]
> When/where can I get the RPM for 3.3.0+? Thanks.

You can find them in the openSUSE build service in my home:cboltz repo, download at http://download.opensuse.org/repositories/home:/cboltz/ (but I have to admit that David is currently doing releases faster than I can package them ;-) - I'll update the package after the next release)

**Comment by lordofbikes** [comment]
> ```
> $CONF['password_validation'] = array(
>     '/([0-9].*){2}/'        => 'password_no_digits 2',      # must contain at least 2 digits
>     'my_super_validator' =>  function($password) { return strlen(trim($password)) > 5; },
> );
> ```
This provided me some headache, as it seems no longer be valid, at least in [3.3.11](https://github.com/postfixadmin/postfixadmin/releases/tag/postfixadmin-3.3.11).

Source documentation says:
https://github.com/postfixadmin/postfixadmin/blob/05d87b16fefab114e3a806eb4e4d41b5b71bfee1/config.inc.php#L250-L252

Thus, the above code returned an `int(1)` in my case. That was also the output from `postfixadmin-cli` and `setup.php`.
The result is this trivial error output:
```
Welcome to Postfixadmin-CLI v0.3
---------------------------------------------------------------
Error: 1
```
Works for me now with this code:
```
$CONF['password_validation'] = array(
    '/([0-9].*){2}/'        => 'password_no_digits 2',      # must contain at least 2 digits
    'my_super_validator'    =>  function($password) { return strlen(trim($password)) > 5 ? '' : 'password_too_short'; },
);
```
Hope this saves somebody some time and avoid headaches.
