### ISSUE TITLE
php8 compatibility

### ISSUE THREAD

**Issue by dvzrv** [postfixadmin/postfixadmin#426]
Hi! I'm packaging postfixadmin for Arch Linux.
We currently have php 8 in testing and are checking software that uses PHP for compatibility.

In the installation documentation I could not find a specific requirement towards php.
Has postfixadmin been tested with php8? [The travis file suggests otherwise](https://github.com/postfixadmin/postfixadmin/blob/0ba851833eaf43b4a66dedd2903718d764a1de68/.travis.yml#L3-L5).

**Comment by DavidGoodwin** [comment]
I've not gone any further than this so far  : 

```
$ php8.0 vendor/bin/psalm
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

------------------------------
No errors found!
------------------------------
393 other issues found.
You can display them with --show-info=true
------------------------------
Psalm can automatically fix 130 of these issues.
Run Psalm again with 
--alter --issues=MissingReturnType,MissingParamType --dry-run
to see what it can fix.
------------------------------

Checks took 4.23 seconds and used 142.389MB of memory
```

**Comment by DavidGoodwin** [comment]
I've applied some fixes from running the (limited!) test suite - there's a good chance it's now PHP 8.0 friendly.

**Comment by dvzrv** [comment]
Cool! Well, we can give it a try I guess and if something breaks either fix it right away or switch to php7 for the time being.
