### ISSUE TITLE
Improvement - Dockerised Mailserver integrated with Postfixadmin

### ISSUE THREAD

**Issue by IbrahimS2** [postfixadmin/postfixadmin#428]
I have been working for a while on creating dockerised Mailserver that works fluently with Postfixadmin and I have made good progress, I am just having few issues where I need some hints or clarifications if possible.

When adding a new mailbox I am getting this error:
```
Jan 20 12:49:30 mail postfix/postscreen[1872]: error: open database /var/lib/postfix/postscreen_cache.db: No such file or directory

Jan 20 12:49:30 mail postfix/master[1217]: warning: process /usr/lib/postfix/sbin/postscreen pid 1872 killed by signal 6

Jan 20 12:49:30 mail postfix/master[1217]: warning: /usr/lib/postfix/sbin/postscreen: bad command startup -- throttling

Jan 20 12:50:30 mail postfix/postscreen[2153]: cache btree:/var/lib/postfix/postscreen_cache full cleanup: retained=0 dropped=0 entries

Jan 20 12:50:30 mail postfix/postscreen[2153]: CONNECT from [172.20.0.3]:44458 to [172.20.0.4]:25

Jan 20 12:50:30 mail postfix/postscreen[2153]: PREGREET 19 after 0 from [172.20.0.3]:44458: EHLO 923d22128af3\r\n

Jan 20 12:50:32 mail postfix/postscreen[2153]: NOQUEUE: reject: RCPT from [172.20.0.3]:44458: 550 5.5.1 Protocol error; from=<admin@test2.com>, to=<admin@test.com>, proto=ESMTP, helo=<923d22128af3>

Jan 20 12:50:32 mail postfix/postscreen[2153]: DATA without valid RCPT from [172.20.0.3]:44458

Jan 20 12:50:32 mail postfix/postscreen[2153]: DISCONNECT [172.20.0.3]:44458

Jan 20 12:50:57 mail postfix/postscreen[2153]: CONNECT from [172.20.0.3]:44476 to [172.20.0.4]:25

Jan 20 12:51:03 mail postfix/postscreen[2153]: PASS NEW [172.20.0.3]:44476

Jan 20 12:51:03 mail postfix/smtpd[2316]: connect from PostfixAdmin.mailserver[172.20.0.3]

Jan 20 12:51:05 mail policyd-spf[2326]: prepend Received-SPF: None (mailfrom) identity=mailfrom; client-ip=172.20.0.3; helo=923d22128af3; envelope-from=admin@test2.com; receiver=<UNKNOWN>

Jan 20 12:51:05 mail postfix/smtpd[2316]: NOQUEUE: reject: RCPT from PostfixAdmin.mailserver[172.20.0.3]: 504 5.5.2 <923d22128af3>: Helo command rejected: need fully-qualified hostname; from=<admin@test2.com> to=<james@test.com> proto=ESMTP helo=<923d22128af3>
```

Also, when I log in to the mail server container which is separate from postfixadmin container, I am unable to see the mail data files that I am creating which supposed to be in /var/mail/, any clue what could the issue be especially if the postfix is on a separate container?

I can compress and send you the whole project files or just publish it on GitHub if required.

**Comment by DavidGoodwin** [comment]
I can't really help you with the above. There are appropriate error and warning messages, and they all look like 'postfix' issues, not ones from postfixadmin.

**Comment by IbrahimS2** [comment]
@DavidGoodwin I have managed to fix almost all the problems I had, and the dockerised mailserver working flawlessly right now with Postfixadmin, do you think we should have a separate repo for this or we can include it as part of postfixadmin?

**Comment by DavidGoodwin** [comment]
What changes do you have to make ? I assume you've seen https://github.com/postfixadmin/docker ?

**Comment by IbrahimS2** [comment]
My vision is to keep Postfixadmin GUI and the Mailserver in separate containers, and the only connection between the two is SQL and maybe in the future we can reconsider this and implement an API for better control over the mailserver.

Also, I would propose to consider Traefik with Nginx instead of Apache for the Postfixadmin GUI.

Right now the mailserver only supports, do you think I should implement PostgreSQL as well and give the user the option to choose between the two? and do you think we can extend Postfixadmin to support mapping external SMTP for outgoing emails per emails/domains or even globally?

**Comment by neuffer** [comment]
Yes please support PostgreSQL

**Comment by neuffer** [comment]
You might also want to look at https://github.com/mailserver2/  with their postfixadmin and mailserver installations.

**Comment by IbrahimS2** [comment]
@neuffer My apology for the sudden absence been really busy. @DavidGoodwin Are you open to a new mockup? or are we free to fork and modify postfixadmin maybe?

**Comment by DavidGoodwin** [comment]
@IbrahimS2 anyone is free to fork PostfixAdmin and make whatever changes they wish.

I would obviously prefer you to create a Pull Request, and hopefully for the eventual merging of changes into Postfixadmin it would probably be much better if you could somehow create pull requests for whatever your changes are though. 
- so everyone can benefit.

**Comment by IbrahimS2** [comment]
@DavidGoodwin Agreed, I want to prepare a new design for Postfixadmin and then update a few components i.e the transport I mentioned previously.

I have utilised Traefik so it auto-generates an SSL and redirects traffic from HTTP to HTTPS, shall I create a PR to the docker repo?

**Comment by DavidGoodwin** [comment]
OK. 

If it's something touching the PHP code of Postfixadmin, then a pull request on this (postfixadmin/postfixadmin) is probably best.

**Comment by IbrahimS2** [comment]
No, nothing related to PHP, it is just a proxy layer to route and manages traffic really.

**Comment by IbrahimS2** [comment]
@DavidGoodwin @neuffer only yesterday I had a bit of time to release this ;) 

https://github.com/aqeltech/Dockerised-GUI-Mailserver

I hope you bookmark this in your repository; I shall do the same in the readme section asap.

**Comment by DavidGoodwin** [comment]
Thanks!

**Comment by IbrahimS2** [comment]
Yep, now it is time to improve postfixadmin further so we can have more control over the dockerised mailserver; I am thinking of the following features:
- Transport/Relay per domain
- imapsync/fetchmail per mailbox/domain
- logs monitoring aka health checks and so on
