### ISSUE TITLE
DB mailbox table with token + token_validity cell doesnt get any data while login

### ISSUE THREAD

**Issue by studiowena** [postfixadmin/postfixadmin#433]
Hello,

Is this issue or its normal behavior (dont see any info about token on documentation)

on login.php token is in form as hidden field and its random but when logged on DB table mailbox cell token and token_validity doesnt change. Is this normal? maybe is used for other token functionality?

let me know

**Comment by DavidGoodwin** [comment]
They're two separate things, unfortunately sharing a similar name.

In the database, and via model/Login.php -

 * token - random hash generated for password recovery
 * token_validity - timestamp one hour in the future form when the token was changed

On the login form -

 * there's a 'token' field, but it's different and is used to avoid CSRF (Cross Site Request Forgery). It should match a value in the user's PHP $_SESSION array - and should help ensure that they viewed a specific page before a form was submitted ....

**Comment by studiowena** [comment]
Hello,

Thanks for the info. Now its clear and yes token seems to be inserted after password recovery but there is problem with templates, ill make another issue instance with error
