### ISSUE TITLE
postfixadmin 3.3.4 setup & login problem on CentOS7.9(x64)

### ISSUE THREAD

**Issue by Halcom-Fantasy** [postfixadmin/postfixadmin#434]
Dear postfixadmin creators.

My account name is Halcom-Fantasy.
I live in Japan.

And use CentOS7.9(x64),postfix,dovecot,MariaDB(mysql),postfixadmin.

When I set up "postfixadmin", I discovered an issue.

Case (1)
If I wrote "setup.local.conf" to  {$CONF['encrypt'] = 'cleartext';} 
,"postfixadmin" works definitely and moves to a login screen.
I was able to login to "postfixadmin" (by "..../login.php").

Case (2)
But , If I wrote "setup.local.conf" to  {$CONF['encrypt'] = 'dovecot:SHA512-CRYPT';} 
, setup of "postfixadmin" is not completed definitely.
And It is impossible to login to "postfixadmin" (by "..../login.php").

These do different movement since setup screen on "postfixadmin".

And a result of {Push "Generate setup_password hash"} is different from (1) with (2) to be concrete.

--
for example.(for add to "config.local.php")
Password="hunter22"

..../setup.php "Generate setup_password hash" result (1)
$CONF['setup_password'] = '$2y$10$diISloaO6XqmsSrOQ9JUKe9.Srl3IJZFe63G8d5FZJz3TAdSMCw2y';

..../setup.php "Generate setup_password hash" result (2)
$CONF['setup_password'] = '$2y$10$4aJli/p.ODBfO5OAyumCwOy2zyHWLLUjdZBEjelAxYWUcdXUwEeji';

Are these specifications right?

And why is it that I cannot log in in a setting of case (2)?

Is these situation , bug of current "postfixadmin 3.3.4"?

I am troubled as a system administrator very much.

Please please lend power to me.

Sincerely yours,

And excuse me.
I borrowed power of machine translation and wrote a sentence.

**Comment by DavidGoodwin** [comment]
Hi - Thanks for the bug report.

The setup_password hash now ALWAYS uses PHP's password_hash(...) function, and does not use any other mechanism (e.g. dovecot, md5 etc). The values you have above look like they're correct as far as I can tell.


The setup_password is NOT a password you can login via login.php with - it's only for gaining access to 'setup.php' (and through that adding super admins). Once you've added a 'super admin' you should then be able to gain access through login.php.

And don't worry about the translation / english - it's probably better than mine :)

**Comment by Halcom-Fantasy** [comment]
Dear DavidGoodwin
Thanks for quickly response :)

>The setup_password is NOT a password you can login via login.php with - it's only for gaining access to 'setup.php' (and through that adding super admins). Once you've added a 'super admin' you should then be able to gain access through login.php.

Unfortunately , I guess you did not understand the situation.

1."postfixadmin" is first need "setup password".
2. It is for "Generate setup_password hash".
3. "config.inc.php" does not touch me.
4. I touch only "config.local.php".
5.And I wrote to "config.local.php".....

5-1.$CONF['encrypt'] = 'dovecot:SHA512-CRYPT';
5-2. I do not write "$CONF['setup_password'] "
5-3.And I browsed URL ".../postfixadmin/setup.php".
5-4.For needs "Generate setup_password hash" of "postfixadmin"
5-5."postfixadmin" displayed a hash key.
5-6. I put a hash key in "config.local.php" ($CONF['setup_password'] =)

6.And I access URL ".../postfixadmin/setup.php" again.
7. "postfixadmin" initialized DB and displayed making of "superadmin" at bottom field.
8. I input information of "superadmin" for two people.
9. I watched next "URL" afterwards.

9-1. ".../postfixadmin/login.php"
9-2.And I was going to login to this page by information of "superadmin".
9-3.But , "postfixadmin" refused access.

10.Why "postfixadmin" refuse access of "superadmin" ?
11.And this issue cleared is settled entirely when this situation changes it of contents of "5-1" to "$CONF['encrypt'] = 'cleartext';".
12.Is not usable besides "cleatext" for setup of "postfixadmin" ?
13.I consider this situation to be a issue.

Were you able to understand the situation?

Please lend your power to me.

Sincerely yours,

And excuse me.
I borrowed power of machine translation and wrote a sentence.

**Comment by DavidGoodwin** [comment]
Ah - right ok.

I'd suggest you check your server's log file(s) to see if there's a problem with using dovecot - see also : 

 * https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/DOVECOT.txt#L140
 * #430 
 * #419
 * #398 

Perhaps /var/log/apache2/error.log - but it may be something like /var/log/httpd for CentOS.

**Comment by Halcom-Fantasy** [comment]
Dear DavidGoodwin.
"postfixadmin v3.3.4" is miss catch "$CONF['encrypt'] " on "config.local.php",
The matter that affects a hash-code of "$CONF['setup_password']".
Should I wait for release of "postfixadmin v3.3.5" ?

**Comment by Halcom-Fantasy** [comment]
Oh! now I can see "postfixadmin v3.3.5" on SourceForge.
I start testing just now.
More thanks :)

**Comment by Halcom-Fantasy** [comment]
Dear DavidGoodwin

Is this output "postfixadmin"'s right answer?

I think "$CONF['setup_password']" is only onetime setting for setup time.
It's in "config.local.php" (or "config.inc.php").
"setup.php" make the "setup_password" at "Generate Hash Password" button.
And

I think "$CONF['encrypt'] " is unrelated for  "$CONF['setup_password']".

But I tested "postfixadmin" v3.3.5.
"postfixadmin" output a different answer.

example.
---
$CONF['encrypt'] = 'cleartext';
$CONF['setup_password'] = '$2y$10$nl0S/Yj/su2qHCAYnv2tJuFco7mfjG8TmUmX5WS3KyjC3OvraZaIi';

$CONF['encrypt'] = 'dovecot:SHA512-CRYPT';
$CONF['setup_password'] = '$2y$10$ME66RN6UkstEY9Rrtb.sQu.tG/wUto1hpElGQwiq9KG0RzUSOCtsW';
---

$CONF['encrypt'] = 'cleartext';
or $CONF['encrypt'] = 'dovecot:SHA512-CRYPT';
different "setup_passsword" hash answer by postfixadmin's setup.php.

Is this right specifications of "postfixadmin" ?

And is it right behavior?

I report the above.

And I use only "cleartext" now.

Sincerely yours,

And excuse me.
I borrowed power of machine translation and wrote a sentence.

**Comment by DavidGoodwin** [comment]
Hi @Halcom-Fantasy - the reason I've put stuff about `$CONF['encrypt']` in setup.php is that people seem to be struggling with e.g. dovecot type problems.... and I'm tiring of asking people the same questions all the time - like :

 * is there anything in your PHP error log ....?
 * No, you're probably not looking in the right place - this is how to find where your PHP error log is ....
 * Are you sure you're editing the RIGHT config file ....
 * Ah, look, you're using dovecot, perhaps you're suffering from permission problems ... let's check that we can generate a password hash / login with it .... 


etc etc

**Comment by Halcom-Fantasy** [comment]
Dear DavidGoodwin

Oh I exemplified "dovecot".
There is not essence in "dovecot".

I think that "$CONF['setup_password'] " is necessary for "only the first time".
(Is it true?)

And I cannot understand why "a value of $CONF['setup_password']" changes by contents of "$CONF['encrypt']".

Sincerely yours,

And excuse me.
I borrowed power of machine translation and wrote a sentence.

**Comment by DavidGoodwin** [comment]
`$CONF['encrypt']` setting should not change the format / hashing used for `setup_password`. They're two independent things.

the `setup_password` is needed for at least the first time - but may also be useful if you need to come back and add a new administrator in.

**Comment by Halcom-Fantasy** [comment]
Dear DavidGoodwin

(I'm sorry that I ask to you question many times)

A hash value of "setup_password" is affected by "$CONF['encrypt']".

Is this behavior right specifications of postfixadmin?

Sincerely yours,

And excuse me.
I borrowed power of machine translation and wrote a sentence.

**Comment by DavidGoodwin** [comment]
> Dear DavidGoodwin
> 
> (I'm sorry that I ask to you question many times)
> 

It's fine. Keep asking. Eventually we'll both understand each other :-)


> A hash value of "setup_password" is affected by "$CONF['encrypt']".

No. The hash value of setup_password is generated using PHP's `password_hash()` function - see 

  * https://github.com/postfixadmin/postfixadmin/blob/5bcafb9c916c652d6666faf7beee0bdfa7455b20/public/setup.php#L222
  * https://www.php.net/password_hash

It MIGHT be the case that your `$CONF['encrypt']` setting results in hashes of the same format ( e.g. if you have $CONF['encrypt'] set to php_crypt:BLOWFISH - see https://github.com/postfixadmin/postfixadmin/blob/5bcafb9c916c652d6666faf7beee0bdfa7455b20/functions.inc.php#L1104 )
