### ISSUE TITLE
Password recover and mysql_crypt doesnt work - php fatal error and same password hash

### ISSUE THREAD

**Issue by studiowena** [postfixadmin/postfixadmin#435]
Installed newest postfixadmin 3.3.4 (on footer still 3.3.3 info exist) but i've checked everything is updated and it IS.

I'll try to recover password for one user and i can put email address and get message (in english dont know where to translate (Use the following link to change your email password) but when clicked on link i get blank page and apache give me that error php7.0 FPM

`[Mon Jan 25 09:44:25.416045 2021] [proxy_fcgi:error] [pid 6028] [client xxx.xxx.xxx.xxx:37176] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'PFASmarty' not found in /www/postfixadmin-new/postfixadmin-master/public/users/password-change.php:28\nStack trace:\n#0 {main}\n  thrown in /www/postfixadmin-new/postfixadmin-master/public/users/password-change.php on line 28\n', referer: https://xxx.com/users/password-recover.php`

mysql_crypt configured on config.inc.php when chaneging password get same hash everytime. SO i dont know but upgradeing from 3.3.3 > 3.3.4 doesnt resolve these problems or i doing something wrong.

**Comment by DavidGoodwin** [comment]
Hi - Thanks - this was (hopefully) fixed with this changeset - https://github.com/postfixadmin/postfixadmin/commit/7f8a3d4bde68cb660833fa71a4d890c7b8eb23df

It'll be part of 3.3.5 once that's released.
