### ISSUE TITLE
GUI font size (Font V3.3 is "huge" compared to 3.2 or older. ) - entry in bootstrap.css

### ISSUE THREAD

**Issue by tempixx** [postfixadmin/postfixadmin#438]
Just a question: I would like to display more entries on my screen, so I would lower the font size for displaying the mailbox entries. etc. What sould I change / add to the bootstrap.css? Thank you.

**Comment by studiowena** [comment]
hi,

Use browser console (code insepction) to check what css is used on text u want change. U'll can see what css code is used

**Comment by DavidGoodwin** [comment]
You could probably get away with adding something like this to the opening 'body' tag 

`style="font-size: 10px"`

See templates/header.tpl for where the body tag is defined.

Or you can indeed edit public/css/boostrap.css - and eg. add something into the `body { ... } ` section near the top - perahps : 

```
body {
  /* Margin bottom by footer height */
  margin-bottom: 60px;
  font-size: 10pt; /* new */
}
```

**Comment by tempixx** [comment]
That was easy... Thank you!
