### ISSUE TITLE
version 3.3.4 - 500 error

### ISSUE THREAD

**Issue by Alex-JTI** [postfixadmin/postfixadmin#439]
Updated to the version 3.3.4 and now getting the following error:
when database_socket is not set in config:

[Mon Jan 25 19:05:30.739949 2021] [proxy_fcgi:error] [pid 6608:tid 140195903002368] [client 93.92.199.232:34670] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined method Config::has() in /home/ipnets/public_html/postfixadmin/functions.inc.php:1591Stack trace:#0 /home/ipnets/public_html/postfixadmin/public/setup.php(568): db_connect()#1 /home/ipnets/public_html/postfixadmin/public/setup.php(255): do_software_environment_check()#2 {main} thrown in /home/ipnets/public_html/postfixadmin/functions.inc.php on line 1591', referer: https://pa.ipnets.ru/public/setup.php

when it's defined:
[Mon Jan 25 19:03:31.523823 2021] [proxy_fcgi:error] [pid 6608:tid 140195819075328] [client 93.92.199.232:34602] AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined method Config::has() in /home/ipnets/public_html/postfixadmin/functions.inc.php:1591Stack trace:#0 /home/ipnets/public_html/postfixadmin/functions.inc.php(1817): db_connect()#1 /home/ipnets/public_html/postfixadmin/functions.inc.php(1780): db_query('SELECT value FR...', Array)#2 /home/ipnets/public_html/postfixadmin/functions.inc.php(2114): db_query_one('SELECT value FR...')#3 /home/ipnets/public_html/postfixadmin/public/login.php(40): check_db_version()#4 {main} thrown in /home/ipnets/public_html/postfixadmin/functions.inc.php on line 1591', referer: https://pa.ipnets.ru/public/setup.php

Setup.php is not loaded completely, login.php generates 500 error.

**Comment by DavidGoodwin** [comment]
https://github.com/postfixadmin/postfixadmin/issues/429#issuecomment-766087028

**Comment by DavidGoodwin** [comment]
hmm - I only added Config::has() a few days ago and that's not yet gone into a new release?  I'm not sure I can see how you can get that error from v3.3.4

( 59db09d33 )

**Comment by Alex-JTI** [comment]
I just downloaded the whole master package currently available and extracted it over 3.3.1.

**Comment by Alex-JTI** [comment]
Sorry for the confusion.
I have re-extracted all the files from scratch from 3.3.4 master archive and no more issues in the logs at all. 
Seems something hasn't overwritten properly.
