### ISSUE TITLE
Chrome session not working => auto redirect to login.php

### ISSUE THREAD

**Issue by HLFH** [postfixadmin/postfixadmin#44]
Hi,

It works on Brave, and Firefox. But not Chrome.
After connection, when I want to click on some links, I am automatically redirected to postfixadmin.example.com/login.php
postfixadmin: 3.0.2
OS: ArchLinux x64
Chrome: 60.0.3080.6
nginx: 1.11.13
php-fpm: 7.1.4
mysq: Ver 15.1 Distrib 10.1.22-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by cboltz** [comment]
It might sound funny, but - can you please create a favicon as `postfixadmin.example.com/favicon.ico` and report back if this fixes the session problem?

If this helps, I'll probably have something else to test, but let's start with the easiest thing ;-)

**Comment by HLFH** [comment]
@cboltz Seriously ?? It works! 
![images](https://cloud.githubusercontent.com/assets/2359059/25582040/0656a6a8-2e83-11e7-8a02-d9abe53d748b.jpg)

So can you add a default favicon.ico within your project?

**Comment by DavidGoodwin** [comment]
empty file added.

**Comment by cboltz** [comment]
Can you please test if it still works if you
- move the favicon.ico to images/favicon.ico
- add `<link rel="shortcut icon" href="images/favicon.ico">` in templates/header.tpl inside the `<head>` section

**Comment by HLFH** [comment]
@cboltz Done. https://github.com/postfixadmin/postfixadmin/pull/108
