### ISSUE TITLE
The following is an valid password: a01d338Nt$

### ISSUE THREAD

**Issue by ShamimIslam** [postfixadmin/postfixadmin#440]
$CONF['password_validation'] default prevents this out of the box and there are no instructions in the config,.local.php to update this.

It prevents the password claiming there are not 3 letters present.

David has commented that it should be "3 consecutive letters"

My opinion and almost every other password verifier claims this is not a requirement.

It should be obvious how to fix this in config.local.php.

**Comment by DavidGoodwin** [comment]
see https://github.com/postfixadmin/postfixadmin/issues/423 - is the fix in 2acdcdbd75e305ce8cb3fb570af743b75ec80ed8 better for you?
