### ISSUE TITLE
Post-password not running

### ISSUE THREAD

**Issue by NicoloLazzaroni** [postfixadmin/postfixadmin#441]
Hello,

I am sorry for disturbing you.
I have a problem with the postpassword running script.

I finally implemented by user-password mail-crypt encryption. I am using the script you provided in addons to change the password of the user.

I've inserted it in the config as: `$CONF['mailbox_postpassword_script'] = 'sudo /etc/postfix/postpassword.sh';`

If I run it in the bash manually as `sudo /etc/postfix/postpassword.sh 'EMAIL' 'DOMAIN' "" 'PASSWORD'` it does work creating the keys, however if I run it in postfix admin by creating a new account I get the error:
`"The mailbox postpassword script failed, check the error log for details!"`.

I've checked the Apache2 logs and I just get `"Running sudo /etc/postfix/postpassword.sh 'EMAIL' 'DOMAIN' "" 'PASSWORD' yielded return value=1, first line of output=, referer: https://CENSORED/edit.php?table=mailbox&domain=CENSORED"`, but nothing happens and the get does not get created.

Is there anything I should change? I've also tried running it with `bash`.

Thank you very much.
Best Regards

**Comment by DavidGoodwin** [comment]
Hi - that functionality should only be in master at the moment - and I don't suspect it's been tested very well yet.

To try and help figure out what's going on, can you ....

 1. Create a 'phpinfo.php' style page (containing: `<?php phpinfo(); ?>`) then view it in your browser and see what value is set for error_log ...
 2. Look at that error_log file and see if there's anything helpful shown.

I've changed model/Login.php in 84ad0ebec79a01126dc821646b2e074245a7d076 which might help it log something better.

**Comment by NicoloLazzaroni** [comment]
Hello,

Thank you for your help.
I solved the running issue by using visudo and giving www-data the permission to sudo the command. I forgot to earlier.

However, I found a problem with the interface. I am debugging everything, but I saw that when adding a new user the option to add an additional recover email address disappeard, and when editing a user I can't edit the password and the additional email address. I had to edit them in MySQL.

May you add these options back? As a postadmin I can tell you they where very very useful.

Thank you.
Best Regards

**Comment by NicoloLazzaroni** [comment]
Hello,

For the recover problem, I think I found one of the issues:

I changed `$CONF['forgotten_admin_password_reset'] = false` to
`$CONF['forgotten_admin_password_reset'] = true;` to permit admins password recovers, however this disabled everything.

With this error: `Password reset is disabled by configuration option: forgotten_admin_password_reset or mailbox_postpassword_script`.

Thank you for your help.
Best Regards

**Comment by DavidGoodwin** [comment]
see 

 * 98dba48c70eead43292d8e4413d1260092a72454 - changed config.inc.php note
 * 96d071dffd663b2e1111d3cac9aca5671ff9532f to help people find Postfixadmin error messages

**Comment by NicoloLazzaroni** [comment]
Hello,

Is it possible to restore recover-password when a user has the postpassword script enabled?
The command to run would just be `rm /var/vmail/DOMAIN/USER/Maildir/dovecot-attributes` and re-generate the key.

That would be quite important.
Is it possible to re-insert the possibility to change user passwords and recovery email from the Admin CP?

Best Regards

**Comment by DavidGoodwin** [comment]
I think you're asking for the addition of another postpassword type callback / script ?

**Comment by DavidGoodwin** [comment]
see also https://github.com/postfixadmin/postfixadmin/issues/408 

@BotoX - any thoughts?

**Comment by NicoloLazzaroni** [comment]
Hello,

Exactly, I think you could use the same script with some editing:
eg.

`if [ -z "$3" ]; then
    doveadm -o plugin/mail_crypt_private_password="$4" mailbox cryptokey generate -u "$1" -U
    exit 0
fi

if [ "$3" == "CHANGEPW" ]; then
    rm /var/vmail/$2/$1/Maildir/dovecot-attributes
    doveadm -o plugin/mail_crypt_private_password="$4" mailbox cryptokey generate -u "$1" -U
    exit 0
fi

# Password change
doveadm mailbox cryptokey password -u "$1" -o "$3" -n "$4"
`
And the recover-password would need to send as OLD-PASSWORD Parameter "CHANGEPW".

Then if you add back the function for an admin to change the password of the User in the CP, you would need to either send the old password or send again "CHANGEPW".
This may, however give some problems if the user password is "CHANGEPW", but we can probably think about a solution.

Best Regards

**Comment by BotoX** [comment]
Account recovery, password change by admin, etc. doesn't make any sense with **encrypted** mailboxes and would only introduce errors (password hash in DB matches different password than the encryption keys)
The users password is used as the passphrase for the maildir encryption keys, if you forget it then the keys are GONE and with them the MAILS ARE GONE FOREVER
That's the entire point of this feature, that a server admin is never able to read your email (ofc. this feature can be circumvented by logging the password, etc. but we don't do that as it'd defeat the entire point and effort)

Also I probably should've included this in the commit/PR
sudoers which doesn't log the password to syslog when the script is called:
```
Cmnd_Alias POSTFIX_PWD = /usr/local/bin/postfixadmin-mailbox-postpassword.sh
Defaults!POSTFIX_PWD !syslog
postfixadmin ALL=(vmail) NOPASSWD: /usr/local/bin/postfixadmin-mailbox-postpassword.sh
```

If you actually want to reset a mailbox then just delete it and create it again.
I think that's a lot more sane as that's what'd actually happen if you delete the encryption keys, all of the mails are just random garbage after that.

Carefully read through the docs: https://doc.dovecot.org/configuration_manual/mail_crypt_plugin/
The functionality implemented in postfixadmin is for only this very simple use case and should never fail:
 - Admin or user creates maildir with initial password.
   - Mail encryption keys are created and encrypted with an initial passphrase.
 - User can change their password at any time with the current passphrase.
   - This re-encrypts the mail encryption keys with the new passphrase.
 
If you need recovery, etc. you should just use global encryption in dovecot.
I also use full disk encryption on my servers, which is never a bad idea.

**Comment by NicoloLazzaroni** [comment]
Hello,

Thank you for your answer.

I personally think that there should be an option.
It would not introduce any error, it would just reset the certificate and get the old messages unreadable for security reasons.

By removing dovecot-attributes.

Best Regards

**Comment by NicoloLazzaroni** [comment]
Hello,

So the recover may also remove all the emails from the directory home of the userdir with:
`  rm -rf /var/vmail/$2/$1/*`
to avoid any error.

This would just be very useful to authomatise everything.

Best Regards

**Comment by NicoloLazzaroni** [comment]
Hello,

I fixed it by myself, my version is too edited to coomi it so I ask @DavidGoodwin if he wants to to add these changes. (And maybe fix them if he finds some errors, I am not an amazing developer ahahah).

postpassword.sh:
```
#!/bin/bash

# Example script for dovecot mail-crypt-plugin
# https://doc.dovecot.org/configuration_manual/mail_crypt_plugin/
MAIL="$1"
DOMAIN="$2"
suffix="@${DOMAIN}"
NAME=${MAIL%"$suffix"}
DIR="/var/vmail/$2/${NAME}"
# New user
if [ -z "$3" ]; then
  if [ -d "$DIR" ]; then
  ### Take action if $DIR exists ###
  echo "Removing ${DIR}..."
  rm -rf "$DIR"
  else
  echo "Not Found ${DIR}..."
  fi
    echo "Generating Key"
    doveadm -o plugin/mail_crypt_private_password="$4" mailbox cryptokey generate -u "$1" -U
    exit 0
fi
# Password change
doveadm mailbox cryptokey password -u "$1" -o "$3" -n "$4"
```


MailboxHandler.php

```
        $reset_by_sms = 0;
        if ($passwordReset && Config::read_string('sms_send_function')) {
            $reset_by_sms = 1;
        }
        $editPw = 1;

```
From line 16 to 20


And change:
```
        if ($this->new) {
            $cmd_pw = Config::read('mailbox_postpassword_script');
            $warnmsg_pw = Config::Lang('mailbox_postpassword_failed');
        }

```
To:
```
        if ($this->new) {
            $cmd_pw = Config::read('mailbox_postpassword_script');
            $warnmsg_pw = Config::Lang('mailbox_postpassword_failed');
        } else {
            $cmd_pw = Config::read('mailbox_postpassword_script');
            $warnmsg_pw = Config::Lang('mailbox_postpassword_failed');
        }
```


Then re-enable all the recover-password in `password-recover.php`, `password-change.php` and `public/users/login.php`.

David, a suggestion that I couldn't add as an if statement: Add that if postpassword is enabled a message saying:
`Warning, this will reset all your emails.` will appear on the recover pages and admin change password page.

Thank you,

Best Regards

**Comment by ean365** [comment]
I know this is closed -- I am just adding some hopefully useful commentary with regard to @BotoX changes and also @NicoloLazzaroni desire for password recovery of mail-crypt and postfixadmin...

A couple of months ago, I made some quick changes to my postfixadmin to do exactly what @BotoX did, which works well, but @BotoX did a much more thorough job of it.  **So, first off, thanks go to @Botox -- I am looking forward to this rolling out in the next release!**

_I would, however, suggest one fairly important change to your (@BotoX) implementation.  Your call to doveadm places the old and new passwords on the command line in plaintext, which could show up if someone views processes (`ps` command) at the right instant.  Better, of course, to pipe passwords through stdin of the doveadm command.  See my code snippet below._

(If anyone's interested, I even identified a minor bug in the `doveadm mailbox cryptokey password` '-O' option, while working on it.  It currently (erroneously) requires a "dummy" argument, even though it is a boolean option.  I reported it to dovecot forums, but they haven't fixed it yet.  See how I worked around this in the code snippet below.)


@NicoloLazzaroni, I also implemented "_almost_ totally secure" mail-crypt password recovery by doing the following.

1. Create a random public/private key pair.
2. Encrypt the private key with a password that would be very difficult to guess or brute force.  Do not share this password, or the private key with anyone -- lock it away somewhere -- entrust it only to two people, split it between three people, etc.  This is the "master" key.
3. Every time a user changes their password using postfixadmin, encrypt it using the public key above, then base64 encode the now encrypted mailbox password, and log it in the postfixadmin database log.  (Another way to accomplish this is to similarly escrow their mail-crypt private keys, which essentially never change, but I decided to do it this way instead.)

Yes, there is now a "hole" in otherwise more-or-less perfect security.  However, it still effectively keeps all email from prying eyes of other admins, and even "privileged" "most trusted" admins who have the "master key" from any casual prying, especially if you implement a procedure, make it difficult and auditable, to access the master key.

I weigh this against the "**_absolute fury and dismay_**" that my _unsophisticated_ users will feel when they screw up a password change (type it in wrong twice), or forget a password, or my system screws up a mail-crypt re-key, and the user irretrievably loses years of extremely important email archive, I now have encrypted traceability of their password changes.


FWIW...Here is a snippet from my modified postfixadmin/model/MailboxHandler.php that I used to accomplish this:

```
    /********************************************************************************************************************
         old functions - we'll see what happens to them
         (at least they should use the *Handler functions instead of doing SQL)
    /********************************************************************************************************************/

    /**
     * Update user's mailbox mail-crypt key password.
     *
     * @param string $username
     * @param string $new_password
     * @param string $old_password
     *
     * All passwords need to be plain text; they'll be encrypted as per dovecot mail-crypt configuration
     *
     * @return 0 on success; !0 on failure
     *
     */
    public function dovecot_cryptokeypw($username, $new_password, $old_password) {
        global $CONF;

        $doveadm = "/usr/bin/doveadm";
    //  if (!empty($CONF['doveadm'])) {
    //      $doveadm = $CONF['doveadm'];
    //  }

        # Use proc_open call to avoid safe_mode problems and to prevent showing plain password in process table
        $spec = array(
            0 => array("pipe", "r"), // stdin
            1 => array("pipe", "w"), // stdout
            2 => array("pipe", "w"), // stderr
        );

        $proc = proc_open("/usr/bin/sudo -u vmail $doveadm mailbox cryptokey password -u $username -N -O \"\"", $spec, $pipes);

        if (!$proc) {
            die("can't proc_open $doveadm");
        }

        // Write passwords through pipe to doveadm stdin -- provide old password, then new password.
        fwrite($pipes[0], $old_password . "\n", 1+strlen($old_password));
        usleep(1000);
        fwrite($pipes[0], $new_password . "\n", 1+strlen($new_password));
        usleep(1000);
        fclose($pipes[0]);
        fclose($pipes[1]);
        fclose($pipes[2]);
        return proc_close($proc);
    }

    /**
     * @return boolean true on success; false on failure
     * @param string $old_password
     * @param string $new_passwords
     * @param bool $match = true
     *
     * All passwords need to be plain text; they'll be hashed appropriately
     * as per the configuration in config.inc.php
     */
    public function change_pw($new_password, $old_password, $match = true) {
        list(/*NULL*/, $domain) = explode('@', $this->id);

        if ($match == true) {
            if (!$this->login($this->id, $old_password)) {
                db_log($domain, 'edit_password', "MATCH FAILURE: " . $this->id);
                $this->errormsg[] = Config::Lang('pPassword_password_current_text_error');
                return false;
            }
        }

        $set = array(
            'password' => pacrypt($new_password) ,
        );

        $result = db_update('mailbox', 'username', $this->id, $set);

        if ($result != 1) {
            db_log($domain, 'edit_password', "FAILURE: " . $this->id);
            $this->errormsg[] = Config::lang('pEdit_mailbox_result_error');
            return false;
        }

        db_log($domain, 'edit_password', $this->id);

        if ($match == true) {
            $result = $this->dovecot_cryptokeypw($this->id, $new_password, $old_password);
            if ($result != 0) {
                db_log($domain, 'edit_password', "FAILURE: dovecot mailbox cryptokey password - ($result): " . $this->id);
                $this->errormsg[] = "Failed to update user's dovecot mail-crypt password. WARNING: Record this and your previous password and notify your system administrator immediately!";
                return false;
            }
        }

        $pubkey=file_get_contents("/var/vmail/public.key");
        if (!$pubkey) {
            db_log($domain, 'edit_password', "WARNING: Could not open public.key. " . $this->id);
            $this->errormsg[] = "Failed to update user's dovecot mail-crypt password. WARNING: Record this and your previous password and notify your system administrator immediately!";
            return false;
        }
        if (preg_match("/^-+BEGIN (\S* )?PUBLIC KEY-+\R([0-9A-Za-z\+\/=\r\n]+)\R-+END (\S* )?PUBLIC KEY-+$/", $pubkey, $pubkey)) {
            $pubkey=substr(sodium_base642bin($pubkey[2], SODIUM_BASE64_VARIANT_ORIGINAL, "\n\r"),-32);
            $ephemkey=sodium_crypto_aead_xchacha20poly1305_ietf_keygen();
            $message=sodium_bin2base64(
                sodium_crypto_box_publickey_from_secretkey($ephemkey) .
                    sodium_crypto_aead_xchacha20poly1305_ietf_encrypt(
                        $new_password,
                        NULL,
                        sodium_crypto_generichash(
                            sodium_crypto_box_publickey_from_secretkey($ephemkey) . $pubkey,
                            NULL,
                            SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES
                        ),
                        sodium_crypto_scalarmult($ephemkey,$pubkey)
                    ),
	            SODIUM_BASE64_VARIANT_ORIGINAL
            );
        }

        db_log($domain, 'edit_password', "mail-crypt password update: " . $this->id . ":" . $message);

        return true;
    }

```
