### ISSUE TITLE
Empty spaces on forward (aliases) setting textarea - user dashboard

### ISSUE THREAD

**Issue by studiowena** [postfixadmin/postfixadmin#442]
Hi,

I've checked on FF and Chrome, textarea on user panel for forwardings (aliases) has empty spaces - textarea To:
It can be confusing for users to edit this textarea and maybe insert these empty spaces to DB - doesnt checked.

Best practice is to delete it and type forward address email but its not obvious for every user

**Comment by DavidGoodwin** [comment]
Thanks for reporting this - hopefully I've fixed the Smarty template so it behaves as expected :-)
