### ISSUE TITLE
Can not add Admin, not valid email error

### ISSUE THREAD

**Issue by sanyimano** [postfixadmin/postfixadmin#443]
Hi!

I use FreeBSD 12.2-RELEASE, php74, postfixadmin Version 3.3.5
Host Enviroment Cheks are all OK
Add Superadmin Account screen can not add Admin, does not accepr email addresses
Error message appears: Admin addition failed; check field error messages or server logs. the 
When accepts the email address, a red 1 appears under the text Admin.

Apache log:
Tue Jan 26 19:52:41.342356 2021] [php7:notice] [pid 58647] [client 91.82.57.190:63193] failed to add admin - [1,"",{"0":"**Invalid email address berta.sandor@nszi.hu, fails regexp check","username":"**Az Admin nem val\\u00f3s email c\\u00edm!"}], referer: https://mailadmin.nszi.hu/setup.php

I tested the command line script postfixadmin-cli.php
root@mail-nszi:/usr/local/www/postfixadmin/scripts # php postfixadmin-cli.php admin add

Welcome to Postfixadmin-CLI v0.3
---------------------------------------------------------------

Admin:
> berta.sandor@nszi.hu
Error: Invalid email address berta.sandor@nszi.hu, fails regexp check
Admin is not a valid email address!

When accepts the email address:
Admin:
> berta.sandor@ketto.hu

Password:
> AAbbCC2120
Error: 1

Please help, to overcome this problem.

**Comment by DavidGoodwin** [comment]
Hi - should have been fixed with changes to the postfixadmin_3.3 branch last night.

The changeset you should need is https://github.com/postfixadmin/postfixadmin/commit/e15d9abe06c0dd1f8fa4037004aeb7d4a648ddde

which fixes the `$CONF['password_verify']` default, when you have a callback in there.

**Comment by sanyimano** [comment]
Sorry for making an extra job for you. 
It was partly my mistake.  In my config.local.php this caused the problem.
...
$CONF['default_aliases'] = array (
    'abuse' => 'abuse@nszi.hu',
    'hostmaster' => 'hostmaster@nszi.hu',
    'postmaster' => 'postmaster@nszi.hu',
    'webmaster' => 'webmaster@nszi.hu'
);
.....
$CONF['vacation'] = 'YES';
$CONF['vacation_domain'] = 'nszi.hu';

After changing the **vacation_domain** to something else, it was working.
Accepted the email adresses from the nszi.hu domain.

Applying your patch the passwords were also accepted.
Thanks a lot!

**Comment by DavidGoodwin** [comment]
Thanks for the confirmation :)
