### ISSUE TITLE
Your email address or password are not correct.

### ISSUE THREAD

**Issue by Blisk** [postfixadmin/postfixadmin#444]
I dida an upgrade to latest version of postfixadmin.
But whatever I do I get the same problem.
Your email address or password are not correct.

I have setup $CONF['setup_password'] = 
but still the same

**Comment by Blisk** [comment]
I also have checked mysql database and there is no users or admins in it

**Comment by studiowena** [comment]
Hi,

Did You setup exist / correct DB on config.inc.php or config.local.php? Maybe You make new DB while upgrade process? Can You generate new hash password and add superadmin on domain.com/setup.php?

**Comment by Blisk** [comment]
Hi
Yes I did all of that more than 20 times and still the same.
I also nitice when I try to send me a new password as I forget it, it doesn't send any email.
Also I notice there is no user in database at all. And settings are ok I tested it.
Now I try to make a new setup on other server and I get white blank page.

**Comment by studiowena** [comment]
What PHP version R u using? and from what version Postfixadmin You make this upgrade?

From Version 3.3 - 2021/01/09 - PostfixAdmin requires PHP 7.0 or greater.

**Comment by DavidGoodwin** [comment]
Change your config.local.php to have :

```PHP
$CONF['setup_password'] = '$2y$10$yr/WtC85Pqhv9s9Terc53.neCW7RVCfSfcV4mNiejQDqZBwM6X.yi';
```

(Note, it MUST use single quotes. The above is from using a password of **topsecret** )

then using that on http://yourserver/setup.php in order to add a new admin.

If that doesn't do anything, add a line like : 

```
die(__FILE__);
```

do your config.local.php and refresh setup.php. If setup.php doesn't display a file name then you're editing the wrong config.local.php file!!

hope that helps.

**Comment by Blisk** [comment]
> 
> 
> What PHP version R u using? and from what version Postfixadmin You make this upgrade? Check Web server error log for any info.
> From Version 3.3 - 2021/01/09 - PostfixAdmin requires PHP 7.0 or greater.
> 
> Check yourdomain.com/setup.php if DB doesnt require to be updated with new version so new Postfixadmin to work properly.
> 
> Forget password feature works only when You setup "Other e-mail" (Used if the password is forgotten) on email account added to DB. Without it system doesnt know where to send reset code and dont do it.

thank you for info.
my php version is 7.4
I did check that yourdomain.com/setup.php I manage to add admin
I also did a fresh installation, delete database use new files and always is the same.
I did also new installation on new server and it is the same.

Your email address or password are not correct.

**Comment by Blisk** [comment]
> die(__FILE__);

I did that and I get on web page
/var/www/html/postfixadmin/config.inc.php

**Comment by studiowena** [comment]
Try make this - from UPGRADE.txt

```
3. Change permissions
----------------------
Since the database password is stored in the config.inc.php it's a good idea
to have change the permissions for Postfix Admin.

  $ cd /usr/local/www/postfixadmin
  $ find -type f -print0 | xargs -0 chmod 640
  $ find -type f -print0 | xargs -0 chown root:www-data

(the last command assumes your Apache is running with group "www-data")

Since version 3.0 we use smarty templates. That means the templates_c directory
needs to be writeable for your webserver.
```

**Comment by DavidGoodwin** [comment]
> > die(**FILE**);
> 
> I did that and I get on web page
> /var/www/html/postfixadmin/config.inc.php

OK that's fine.

So you said : 

> I did check that yourdomain.com/setup.php I manage to add admin

Can you login as that admin ?  If not, what to do you see? Any error message? Is there an error message in your webserver's log file(s) ( see https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/FAQ.txt#L38 )

Is there a row in the database 'admin' table ?

Are you using dovecot for your $CONF['encrypt'] setting ? 
(If so see https://github.com/postfixadmin/postfixadmin/issues/434#issuecomment-766756924 )

**Comment by studiowena** [comment]
Try to check mysql server logs while You trying to login and check encryption u setup on config.inc.php

`$CONF['encrypt'] = '';`

and set with Yours. Logs should tell You more

**Comment by SaraSmiseth** [comment]
You also get this error if doveadm pw tries to read your certificate and has no permissions. See #399 and #398.

**Comment by Blisk** [comment]
studiowena 
there is no related errors to to that problem

DavidGoodwin
No I can not login as admin I can setup admin but than login not possible I get this error
Your email address or password are not correct.
No error messages in log files for that.
I am not using dovecot encrypt if that is new installation. When upgrade didn't work I made fresh installation.

$CONF['encrypt'] = '';
if I set this than I get error
Invalid token! (CSRF check failed)

**Comment by studiowena** [comment]
> $CONF['encrypt'] = '';
> if I set this than I get error
> Invalid token! (CSRF check failed)

I've gave You example with empty field - You have to choose one of the type of encryption postfixadmin used to encrypt passwords on Your system.
 
> Where postfixadmin write admin user and password???

on config.inc.php You have:
`$CONF['setup_password'] = 'generated_hash';`
is setup password then u can add super admin which is added to postfiadmin DB table -> admin (Postfix Admin - Virtual Admins)

**Comment by Blisk** [comment]
I don't kno what I am doing wrong I cant even get to login with setup password anymore.
I have setup new password and when I try to login I get error
$CONF['setup_password'] = '$2y$10$LvdKt1hrqI.Qs0zlz.3sK.z6JWDFs5APcD0uxlE.MAL51Y5ylQTA6';
Password verification failed.

**Comment by DavidGoodwin** [comment]
* your setup_password looks like it's OK.
 * What do you have as $CONF['encrypt'] - it needs to be something ..... leaving it blank should trigger an error.
 * Check the FAQ link I gave earlier; https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/FAQ.txt#L38 - If you're not seeing anything logged, then you probably aren't looking in the right place?

**Comment by studiowena** [comment]
maybe You copy password from file with "empty space" and this is counted as one more character on password field. Yes this is stupid but possible :)

**Comment by Blisk** [comment]
I have alčl the time
$CONF['encrypt'] = 'md5crypt';


> 
> 
> maybe You copy password from file with "empty space" and this is counted as one more character on password field. Yes this is stupid but possible :)

I was carefull about that because yes I did that to in past. But now not.

**Comment by Blisk** [comment]
I manage to make it work. It was not possible to add admin into mysql database with setup.php. So I have add admin via phpmyadmin. And now it work ok.

**Comment by studiowena** [comment]
> I manage to make it work. It was not possible to add admin into mysql database with setup.php. So I have add admin via phpmyadmin. And now it work ok.

So, maybe Your mysql user used to read DB has no all privilages to make inserts to postfixadmin DB - check it.

btw good to hear You solve problem

**Comment by Blisk** [comment]
> 
> 
> > I manage to make it work. It was not possible to add admin into mysql database with setup.php. So I have add admin via phpmyadmin. And now it work ok.
> 
> So, maybe Your mysql user used to read DB has no all privilages to make inserts to postfixadmin DB - check it.
> 
> btw good to hear You solve problem

I have checked that many times and it has all possible rights and still the same

**Comment by DavidGoodwin** [comment]
I guess I need to add some sort of database read/write check to https://github.com/postfixadmin/postfixadmin/issues/445

**Comment by Blisk** [comment]
I am trying to setup this on other server and it is the same.
But I can access setup.php
when I open login.php I get white blank page and no error in log files
any idea?

**Comment by Blisk** [comment]
> 
> 
> I guess I need to add some sort of database read/write check to #445

I can't get information page, no way.

**Comment by Blisk** [comment]
Something here is not working ok. php files have no right access to database.
When I copied database from first server to second server and change domains than I can manage to acces login page and also login and add domain and users. Before that no way.

**Comment by bewam** [comment]
Hi @Blisk
I have the same issue. I'm wondering if you, like me, use a kind of reverse proxy with fpm php, in fast-cgi. 
It could cause my problem. I understood that it can't access ../common.php, because the file is not located in the root directory. So authentication can't occur.

**Comment by Blisk** [comment]
Hi
No I don't have reverse proxy.
I manage to make it work with copying database from working server now a problem is because I can not login into roundcubemail

**Comment by DavidGoodwin** [comment]
If you're feeling adventurous, try using either 'master' or the 'postfixadmin_3.3' branch. The setup.php page in either may now output some more helpful output (once you've authenticated using your setup_password).

**Comment by Blisk** [comment]
thank you but right now I have too much to do to make my self more problems.
:)

**Comment by corinthian13** [comment]
Has anyone at PostfixAdmin reproduced this issue and made any attempts to fix it ?

It's crazy closing the issue just because the OP got tired of trying out things that _just might_ fix it . . .

I ran into it when putting an Ubuntu mail server together yesterday via [this procedure](https://www.linuxbabe.com/mail-server/postfixadmin-ubuntu)

It's kind of a show-stopper . . .

**Comment by DavidGoodwin** [comment]
@corinthian13 providing information about your configuration (and raising it as a new issue, rather than commenting on something that's closed) would help. 

 * What version of postfixadmin are you trying to use? 
 * Have you checked the PHP/Apache etc log files for any relevant messages? 
 * Have you checked what entries are in the database (specifically the admin table, assuming your problem is not being able to login as an admin). 
 * Are you sure you're not trying to login with the users/login.php page as an admin?

**Comment by corinthian13** [comment]
1. PostfixAdmin v. 3.3.11

2. Looked at /var/log/apache2/postfixadmin_error.log  ....
Says there's a password not read from /usr/bin/doveadm  ... and references /var/www/postfixadmin/functions.inc.php line 1062:

error_log("Failed to read password from $dovecotpw ... stderr: $stderr_output, password: $password ");
        throw new Exception("$dovecotpw failed, see error log for details");

3. Yes. There's no entries in most/all of the tables in the postfixadmin database.

4. I was trying to login at URL: https://postfixadmin.example.com/login.php as superadmin (i.e. the email address representing that account) and the superadmin password just applied when creating the superadmin account.

**Comment by DavidGoodwin** [comment]
right - you've almost certainly got the problem where dovecot isn't able to read the ssl certificate files....  you probably need to look at https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/DOVECOT.txt#L157

alternatively, login as the www-data user (or whatever your webserver is running as) (e.g. `sudo -u www-data -s /bin/bash` ) and then try running the doveadm command that postfixadmin is using (i think it's logged in your error log) and you'll probably see something relevant - e.g.

```
www-data@mail:~$ doveadm pw
Error: net_connect_unix(/run/dovecot/stats-writer) failed: Permission denied
Enter new password: 
Retype new password: 
{CRYPT}$2y$05$k1KERBba84xxdfqnDqaf0O8T9WfYJtwVUndSx3JkqR.bVagY8aSKu
```

see also #381 and #398 


(so in my case, i need to change the permissions on that stats-writer file ... for which this is relevant : https://github.com/postfixadmin/postfixadmin/issues/381#issuecomment-690934726

**Comment by corinthian13** [comment]
The part that is supposed to do this is:

**Step 3: Setting Up Permissions**

PostfixAdmin requires a templates_c directory, and the web server needs read and write access to this directory, so run the following commands.

`sudo mkdir -p /var/www/postfixadmin/templates_c`

`sudo apt install acl`

`sudo setfacl -R -m u:www-data:rwx /var/www/postfixadmin/templates_c/`

Starting with Dovecot 2.3.11, the web server user needs permission to read Let’s Encrypt TLS certificate in order to do password hashing. Run the following two commands to grant permissions.

`sudo setfacl -R -m u:www-data:rx /etc/letsencrypt/live/ /etc/letsencrypt/archive/`

Yet after doing (and redoing) the above code I see that the contents of folders

/var/www/postfixadmin/templates_c
/etc/letsencrypt/live
/etc/letsencrypt/archive

remains root owned and the group is also root.

Group www-data exists among the users list and groups list on the server.

But I can't enter its user account

```
sudo su www-data
[sudo] password for xyzsdgr: 
This account is currently not available.
```

**Comment by corinthian13** [comment]
Well, even after ensuring www-data access to relevant files, it wasn't the password recognition thing per se.

The trouble was a pesky "WARNING" about an obsolete setting in a dovecot config file that turned out to be causing everything really:

```
[Fri Jun 28 12:55:32.030905 2024] [php:notice] [pid 6516] [client 80.233.56.66:6085] Failed to read password from /usr/bin/doveadm pw -r 5 ... stderr: doveconf: Warning: NOTE: You can get a new clean config file with: doveconf -Pn > dovecot-new.conf\ndoveconf: Warning: Obsolete setting in /etc/dovecot/conf.d/10-ssl.conf:64: ssl_protocols has been replaced by ssl_min_protocol\nFatal: Missing {scheme} prefix from hash\n, password:  , referer: https://postfixadmin.sandbarsoftware.ie/login.php
[Fri Jun 28 12:55:32.031073 2024] [php:notice] [pid 6516] [client 80.233.56.66:6085] Error trying to call pacrypt(), referer: https://postfixadmin.sandbarsoftware.ie/login.php
[Fri Jun 28 12:55:32.031100 2024] [php:notice] [pid 6516] [client 80.233.56.66:6085] Exception: /usr/bin/doveadm pw -r 5 failed, see error log for details in /var/www/postfixadmin/functions.inc.php:1066\nStack trace:\n#0 /var/www/postfixadmin/functions.inc.php(1281): _pacrypt_dovecot()\n#1 /var/www/postfixadmin/model/Login.php(49): pacrypt()\n#2 /var/www/postfixadmin/public/login.php(63): Login->login()\n#3 {main}, referer: https://postfixadmin.sandbarsoftware.ie/login.php
[Fri Jun 28 12:55:32.031135 2024] [php:notice] [pid 6516] [client 80.233.56.66:6085] PostfixAdmin admin login failed (username: sandsoft@sandbarsoftware.ie, ip_address: 80.233.56.66), referer: https://postfixadmin.sandbarsoftware.ie/login.php
```

Once this warning was fixed by commenting out the ssl_protocols assignment, all fell into place.

When following [the procedure here](https://www.linuxbabe.com/mail-server/secure-email-server-ubuntu-postfix-dovecot), I overlooked that assigning ssl_protocols only applied to Dovecot 2.2.x versions and mine was 2.3.x  . . .

Thanks to DavidGoodwin and Dana Booysen.

**Comment by DavidGoodwin** [comment]
Thanks for updating and stating what the problem is - hopefully it'll help others in the future :)
