### ISSUE TITLE
[Feature Request] - Improve setup

### ISSUE THREAD

**Issue by DavidGoodwin** [postfixadmin/postfixadmin#445]
setup.php probably needs improving to ....

 * Display where the error error log is, and perhaps display some of it
 * If $CONF['pacrypt'] = 'dovecot*' then it should test if pacrypt(...) works, and output some sort of helpful message

**Comment by DavidGoodwin** [comment]
see https://github.com/postfixadmin/postfixadmin/commit/4063ca151cda8b6ab0eac198464efdc9fe1c49e2

**Comment by DavidGoodwin** [comment]
![image](https://user-images.githubusercontent.com/203929/106206408-ec854b00-61b7-11eb-8ec8-f12854353dc8.png)

**Comment by DavidGoodwin** [comment]
there's a message shown if dovecot pw fails too...

![image](https://user-images.githubusercontent.com/203929/106206699-6ddcdd80-61b8-11eb-9cfc-87a447f75054.png)

**Comment by studiowena** [comment]
superb, just want to write that most common failures should be like You make this - log / display fatal errors

**Comment by DavidGoodwin** [comment]
Probably needs merging into postfixadmin_3.3
