### ISSUE TITLE
Minor bug with subdirectories

### ISSUE THREAD

**Issue by AlphaJack** [postfixadmin/postfixadmin#446]
Postfixadmin works great under subdirectories, but I noticed two bugs today:

1. https://example.org/postfixadmin/users redirects to https://example.org;1111/users/ (thus exposing the internal port), while https://example.org/postfixadmin/users/ (with trailing slash), https://example.org/postfixadmin, https://example.org/postfixadmin/ and everything else work fine
2. Mail to reset an account password omits the subdirectory from the link creation. Can you add a variable to specify the subdirectory?

```nginx
server {
 listen 443 ssl http2 default_server;

 [...]

 # postfixadmin location
 location /postfixadmin/ {
  proxy_pass http://127.0.0.1:1111/;
  proxy_redirect off;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Remote-User $remote_user;
 }

 [...]

}

# postfixadmin server
server {
 listen 127.0.0.1:1111;
 root /usr/share/webapps/postfixadmin/public/;
 index index.php;
 charset utf-8;

 location / {
  try_files $uri $uri/ index.php;
 }

 location ~* \.php$ {
  fastcgi_split_path_info ^(.+\.php)(/.+)$;
  include fastcgi_params;
  fastcgi_pass unix:/run/postfixadmin/postfixadmin.sock;
  fastcgi_index index.php;
  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  fastcgi_buffer_size 16k;
  fastcgi_buffers 4 16k;
 }
}
 ```

**Comment by DavidGoodwin** [comment]
it feels like you need a directive a bit like : https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypassreverse 

I've no idea what they'd be for nginx though sorry; I'm a luddite and have only really used Apache for the last ~20 years.

**Comment by AlphaJack** [comment]
The NginX configuration above seems fine, but I still don't get why it shows my port number. I'm using a workaround
```nginx
location /postfixadmin {

 [...]

 # regex for that particular location, otherwise it triggers a redirect loop
 location ~ /postfixadmin/users$ {
  return 301 https://$host/postfixadmin/users/;
 }
}
```
---

Any opinion about the subdirectory variable to generate password reset URLs?
The url variable is

```php
$url = $_SERVER['REQUEST_SCHEME'] . '://' . $_SERVER['HTTP_HOST'] . dirname($_SERVER['REQUEST_URI']) . '/password-change.php?username=' . urlencode($username) . '&code=' . $code;
```
and looks like this
```
http:/example.org/users/password-change.php?username=user@example.org&code=XXXXXX
```
instead of this
```
https://example.org/postfixadmin/users/password-change.php?username=user@example.com&code=XXXXXX
```

I also can't make it generate HTTPS URLs (there is no HTTPS between Nginx and Postfixadmin server), even if I set `proxy_set_header X-Forwarded-Proto $scheme;` in the location block or I explicitly set `fastcgi_param REQUEST_SCHEME https;`

**Comment by DavidGoodwin** [comment]
if you were using Apache ....

the ProxyPassReverse rewrites a redirect from the backend to something appropriate for the frontend (so it matches the address you're exposing your site as).

I think your problem is just that Nginx is returning a HTTP location header which includes the port number ... as that is the correct thing for it to do as it's running on port 1111 ... 

Your problem is that you're then hiding port 1111 behind a https config in a different nginx server instance ....

I think from PostfixAdmin we only ever do relative http location redirects.

**Comment by AlphaJack** [comment]
@DavidGoodwin What about URL creation? Can you add a variable to specify a subdirectory for this task or do I need to replace the string every time I update PA?

**Comment by DavidGoodwin** [comment]
@AlphaJack I think it's been discussed in the past, and wasn't found necessary .... it's something that could be done, but it shouldn't be necessary - there ought to be appropriate configuration in your webserver to fix the proxying issue.

**Comment by AlphaJack** [comment]
Wait, this second issue is unrelated to proxying (Apache/NginX).  
What I am saying is that Postfixadmin generates an URL like https://example.org/users/password-change.php and sends it via email. The URL should instead be https://example.org/postfixadmin/users/password-change.php in my case, according to the location where it is located.
My current workaround is hardcoding HTTPS and my subdirectory (/postfixadmin) in the PHP code I posted above, so I was suggesting to add a subdirectory variable that defaults to "/" (for subdomain setups) to generate that URL

**Comment by DavidGoodwin** [comment]
Ah. Is that URL just for e.g. password recovery ?

https://github.com/postfixadmin/postfixadmin/blob/5bcafb9c916c652d6666faf7beee0bdfa7455b20/public/users/password-recover.php#L52

But yes, that could be fixed through a config setting easily enough.

**Comment by AlphaJack** [comment]
Yes, exactly that line
