### ISSUE TITLE
User Quota is not shown/updated (UNKOWN) (Postfixadmin+Cyrus-Imapd)

### ISSUE THREAD

**Issue by nunix2** [postfixadmin/postfixadmin#449]
Hi,

I'm struggling with user quota configuration.
![Capture3](https://user-images.githubusercontent.com/77546397/106630712-fe7a3b80-6573-11eb-9469-370e73184231.JPG)
All mailboxes are set with quota limits per user, but postfixadmin is not getting quotas from cyrus-imap folders.

Tried to use quota_usage.pl perl script but it really does not work on cyrus-imap folders. Cyrus-Imap folders are configured:
$CONF['domain_path'] = 'NO';
$CONF['domain_in_mailbox'] = 'YES';
$CONF['maildir_name_hook'] = 'NO';

So mailbox folders are created like this:
/var/spool/imap/domain/n/nunix-it.pt/n/user/ncarrilho/

quota_usage.pl does not look inside this folders tree, so does not really works. example (configuring my $root_path   = '/var/spool/imap/domain';):
nunix-it.pt@n                                     4819 MB
nunix.eu@n                                        97 MB
nunix.pt@n                                        21891 MB

Can somebody help with this?

Thanks

**Comment by DavidGoodwin** [comment]
How should that quota_usage.pl script be working?

It looks like it is just doing a `du -0 --summarise /path/to/mailbox` and converting whatever that gives into KiB - although I'm not sure why, given the db field is called `bytes`.

It might be worth rewriting it into PHP as at least then it can use whatever PostfixAdmin config you have etc.

**Comment by nunix2** [comment]
Quota usage should get information directly from cyradm cli. When a mailbox is created through postfixadmin, using the cyrus perl scripts (inside ADDONS/cyrus folder), quota is added inside cyrus engine.

So, if I use cyrus cli, I can see user's quota (total, configured by those perl sscripts), and also user's quota usage.
 
Cyrus imap does not use normal system disk quotas.

Thanks

**Comment by DavidGoodwin** [comment]
Ah, ok. So I think what you're after is something like `quota_usage.pl` but instead it calls `cyrus quota -d <domain> -u username` and then parsing the output?

**Comment by DavidGoodwin** [comment]
( see: https://www.cyrusimap.org/imap/reference/manpages/systemcommands/quota.html )

**Comment by nunix2** [comment]
Hi, David,
Something like that:
# cyr_quota quota -d nmail.pt -u ncarrilho[!at!]nmail.pt
   Quota               % Used     Used                  Resource Root
 1024000000        0               311723              STORAGE user/ncarrilho@nmail.pt
                       525              MESSAGE user/ncarrilho@nmail.pt
                         0 X-ANNOTATION-STORAGE user/ncarrilho@nmail.pt
                         8        X-NUM-FOLDERS user/ncarrilho@nmail.pt

And with these results to populate the postfixadmin db (quota columns).

:)

**Comment by nunix2** [comment]
I'll check better on the server, but cyrus-imap perl scripts are not working 100%. :(
Some mailboxes do not have user quotas at all. Also updated the user quota from the user above and run the cli cyr_quota command again, and the result where the same values.
All config values are correct, otherwise user would no be created at all !
Wierd, very wierd ...

**Comment by nunix2** [comment]
Hi,
I have double checked the cyrus perl scripts, and they are working fine. Example, created new mailbox via postfiadmin, with quota 1024Mb:
usr/sbin/cyr_quota -d nmail.pt
   Quota   % Used     Used             Resource Root
 1048576000        0        0              STORAGE user/teste@nmail.pt

Then edited, and changed to 2048Mb:
usr/sbin/cyr_quota -d nmail.pt
   Quota   % Used     Used             Resource Root
 2097152000        0        0              STORAGE user/teste@nmail.pt

So perl scripts are working fine.

My question is how does postfixadmin looks for used quotas, so it can apply at dashboard? is ti looking on quota table at mysql DB?
If so, how is this table populated?
quota_usage.pl only lists domain quotas. Not user quotas.

Also I have an error when using flag -i:
perl quota_usage.pl -i
DBD::mysql::db do failed: Unknown column 'quota_usage' in 'field list' at quota_usage.pl line 112.
error when running UPDATE mailbox set quota_usage = 0 at quota_usage.pl line 112.

**Comment by nunix2** [comment]
P.S. **quota** cli command is for quota-4.06.x86_64.rpm packed, which does not work
cyrus uses cli command: **cyr_quota** 

# quota
Disk quotas for user root (uid 0): none

# cyr_quota 
   Quota   % Used     Used             Resource Root
 2097152000        0   415158              STORAGE user/a.h@xxxx

**Comment by DavidGoodwin** [comment]
Quota is stored in the 'quota' table, one row per username.

```
CREATE TABLE `quota` (
  `username` varchar(255) NOT NULL,
  `path` varchar(100) NOT NULL,
  `current` bigint(20) NOT NULL DEFAULT 0,
  PRIMARY KEY (`username`,`path`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

I'm not sure how that's linked to the quota in the 'domain' table -

```
CREATE TABLE `domain` (
  `domain` varchar(255) NOT NULL,
  `description` varchar(255) CHARACTER SET utf8 NOT NULL,
  `aliases` int(10) NOT NULL DEFAULT 0,
  `mailboxes` int(10) NOT NULL DEFAULT 0,
  `maxquota` bigint(20) NOT NULL DEFAULT 0,
  `quota` bigint(20) NOT NULL DEFAULT 0,
  `transport` varchar(255) NOT NULL,
  `backupmx` tinyint(1) NOT NULL DEFAULT 0,
  `created` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `modified` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `password_expiry` int(11) DEFAULT 0,
  PRIMARY KEY (`domain`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Postfix Admin - Virtual Domains'
```

**Comment by reinks2112** [comment]
I'm using https://github.com/o-m-d/cyrus-quotausage-to-pfa/ (with some local modifications).
