### ISSUE TITLE
Fetch email entry error?

### ISSUE THREAD

**Issue by FootballFan141** [postfixadmin/postfixadmin#45]
Hi,
When I added my first fetch email entry the 'Date' column on the page shows

2000-01-01 00:00:00 

Just thought I'd ask if it has happened to anyone else.

I **may** have just done something wrong... 😮

**Comment by cboltz** [comment]
That's just a default date that indicates the fetchmail cronjob did not run yet. When the fetchmail cronjob runs, it will update the date to the then-current date and time.

In the past, we used 0000-00-00, but that conflicts with MySQL's strict mode ;-)
