### ISSUE TITLE
alias doesn't work

### ISSUE THREAD

**Issue by Blisk** [postfixadmin/postfixadmin#450]
I need some help here please.
I have setup postfixadmin and it works, I can add domain, users and all works ok.
But when I add alias it doesn't work I get error. Email is always reyected.

reject: RCPT from mail-eopbgr70091.outbound.protection.outlook.com[40.107.7.91]: 550 5.1.1 <info@myalias.com>: Recipient address rejected: User unknown; from=<my.outsidemail@somedomain.com> to=<info@myalias.com> proto=ESMTP helo=<EUR04-HE1-obe.outbound.protection.outlook.

**Comment by DavidGoodwin** [comment]
Hi,

What do you have for `virtual_alias_maps` in postfix's main.cf ?

Try running this `postconf virtual_alias_maps`

for me, I see : 

```
virtual_alias_maps = hash:/etc/postfix/virtual proxy:pgsql:/etc/postfix/pgsql/virtual_alias_maps.cf
```

Then what does Postfix respond to an alias lookup with - 

`postmap -q info@myalias.com mysql:/path/to/virtual_alias_maps.cf`

e.g.

```
root@mail:~# postmap -q sales@example.co.uk pgsql:/etc/postfix/pgsql/virtual_alias_maps.cf
david@example.co.uk
```

(Which shows sales => david).

**Comment by Blisk** [comment]
Thank you I just found out a problem.
I use iredmail and mysql for virtual domains and aliases.
I need to change this line in postfix virtual_alias_maps.cf
query       = SELECT forwardings.forwarding FROM forwardings,domain WHERE forwardings.address='%s' AND forwardings.domain=domain.domain AND forwardings.active=1 AND domain.backupmx=0 AND domain.active=1

to this line and now it works
query       = SELECT alias.goto FROM alias,domain WHERE alias.address='%s' AND alias.domain='%d' AND alias.domain=domain.domain AND alias.active=1 AND domain.backupmx=0 AND domain.active=1
