### ISSUE TITLE
admin user does not work when $CONF['encrypt'] = 'dovecot:BLF-CRYPT'

### ISSUE THREAD

**Issue by nerijus** [postfixadmin/postfixadmin#451]
I cannot create admin user if I have `$CONF['encrypt'] = 'dovecot:BLF-CRYPT';` in `config.local.php` - the user is just not created.
If `$CONF['encrypt'] = 'md5crypt';` (default), then admin user creation works. Then I login, change `$CONF['encrypt'] = 'dovecot:BLF-CRYPT';` and I am able to create users with BLF-CRYPT encrypted passwords. But then I cannot login to admin interface anymore, unless I comment out  `$CONF['encrypt']`.

**Comment by nerijus** [comment]
BTW, if I update admin user password manually in mysql db:
```
update admin set password = "{BLF-CRYPT}$2y$05$My...." WHERE `username` = "postmaster@example.com";
```
and set `$CONF['encrypt'] = 'dovecot:BLF-CRYPT';` in `config.local.php`, I still cannot login to admin interface.

**Comment by DavidGoodwin** [comment]
Sounds like a problem with dovecot - please try using the code in 'master' and visit setup.php and enter in your setup_password. 
You should see some error messages.

Alternatively there are a few tickets to look at e.g. https://github.com/postfixadmin/postfixadmin/issues/434#issuecomment-766756924
