### ISSUE TITLE
Issue when trying to update from v3.2 to v3.3.1

### ISSUE THREAD

**Issue by raspifr** [postfixadmin/postfixadmin#452]
Hello all.

Sorry for my english, I'm french.

I try to update PostfixAdmin from 3.2 to 3.3.1 but I have an issue.
When I try to setup (just for upgrading database schema) using setup URL (https://my_domain/postfixadmin/setup.php) I can't login with setup_password ("Password verification failed") even generate a new setup_password hash. So host environment check can't be made.
When I try setup URL with old version (v3.2) checks are OK but no need to login with setup_password.

On my web server I use PHP8.0.2 and PHP7.4.13.

Thank's for your help.

**Comment by DavidGoodwin** [comment]
Hi - 

3.3.x requires a **new** setup_password hash to be generated and placed in your config.local.php file.

You can generate one on the command line using something like `php -r "echo password_hash('topsecret', PASSWORD_DEFAULT);"`

Are you seeing an error message somewhere?

I've improved setup.php in the master and postfixadmin_3.3 branches (it's just not found it's way into a release yet) which might help.

**Comment by raspifr** [comment]
I generate a new setup_password on the web page setup.php and add it in config.local.php but that doesn't works.
The only error message I can see it's "Password verification failed".

**Comment by DavidGoodwin** [comment]
Are you sure you're editing the 'right' config.local.php ? Try putting a `die('hello');` in it and refreshing the page ...just to make sure.

**Comment by raspifr** [comment]
Yes it's the right config.local.php.
I put "die('hello');" in config.local.php and I see "hello" on web page. But when I remove it I have an apache error message : HTTP ERROR 500 when I try to go to postfixadmin login page. Only with new version, no error with old version.

**Comment by raspifr** [comment]
Seems to be good now.
I just modify rights on postfixadmin folder.
Update OK.

**Comment by DavidGoodwin** [comment]
Thanks for confirming the problem is fixed.
