### ISSUE TITLE
Request 3.3.6 release

### ISSUE THREAD

**Issue by heliosyne** [postfixadmin/postfixadmin#454]
Can a new release on 3.3.x be made to cover the changes since 3.3.5? Things seem to have calmed down, and it would be nice to have a version tag now that the branch has stabilized.

**Comment by DavidGoodwin** [comment]
https://github.com/postfixadmin/postfixadmin/releases/tag/postfixadmin-3.3.6

**Comment by heliosyne** [comment]
Thanks!

**Comment by paulchen** [comment]
I'm afraid that something went wrong with that release.

It is based on revision 4d505211efa785242bc69b7e6f7ffea9cf3d32da where setup.php calls a function named db_connection_string(): https://github.com/postfixadmin/postfixadmin/blob/4d505211efa785242bc69b7e6f7ffea9cf3d32da/public/setup.php#L688

However, that function is not present anywhere in that revision. In master, it can be found in functions.inc.php: https://github.com/postfixadmin/postfixadmin/blob/master/functions.inc.php#L1563-L1601

In revision 4d505211efa785242bc69b7e6f7ffea9cf3d32da, functions.inc.php does not contain that method yet: https://github.com/postfixadmin/postfixadmin/blob/4d505211efa785242bc69b7e6f7ffea9cf3d32da/functions.inc.php

**Comment by DavidGoodwin** [comment]
Thanks @paulchen .... 8ebb985fc741d29f305e26c37eda1ca5cde84c90 is missing.

psalm is meant to notice this sort of thing ... clearly I've messed up in relying on it, or not configured it correctly.

**Comment by DavidGoodwin** [comment]
https://github.com/postfixadmin/postfixadmin/releases/tag/postfixadmin-3.3.7

**Comment by paulchen** [comment]
@DavidGoodwin Thanks for the quick response, 3.3.7 looks better :)
