### ISSUE TITLE
SQL error when user tries to change password

### ISSUE THREAD

**Issue by svenseeberg** [postfixadmin/postfixadmin#456]
On Postfixadmin 3.3.7, a user trying to change the mailbox password causes the following error message:
```
Invalid query: SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' caused by UPDATE ``mailbox`` SET  password = :password  WHERE username = :where, referer: https://example.com/postfixadmin/users/password.php
```

It seems that `$this->key_table` in 
https://github.com/postfixadmin/postfixadmin/blob/1a9d9847f5c5371b3ba756e9f21e3d694437c976/model/Login.php#L113 contains the string "\`mailbox\`", including backticks. I have not yet evaluated where the wrong string comes from. Replacing the parameter value with a literal `mailbox` string fixes the issue (which is currently my workaround in place).

I can see that the Login.php changed heavily since the 3.3.7 tag, but the line causing the error seems to be the same.

**Comment by svenseeberg** [comment]
I found the cause: the `db_update()` function calls the `table_by_key()` function for the table name. However, in the Login.php the `$this->table_key` attribute is used as parameter for the `db_update()` function. And `$this->table_key` already is the table name that was already modified by the `table_by_key()` function.

**Comment by DavidGoodwin** [comment]
thanks for finding the bug @svenseeberg
