### ISSUE TITLE
PHP 7.x Warnings & Deprecated Issues

### ISSUE THREAD

**Issue by qcybb** [postfixadmin/postfixadmin#46]
Will the next version of Postfixadmin address the following issues?

> PHP Warning:  Cannot assign an empty string to a string offset in /postfixadmin/variables.inc.php on line 31

> PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; cNav_bar has a deprecated constructor in /postfixadmin/list-virtual.php on line 325

So far, it appears these are the only issues.

**Comment by DavidGoodwin** [comment]
variables.inc.php has already been removed from master.

That just leaves https://github.com/postfixadmin/postfixadmin/blob/master/list-virtual.php#L333

**Comment by DavidGoodwin** [comment]
https://github.com/postfixadmin/postfixadmin/commit/27b835c161bc57a515c89c4b019ff900788713ad might clean up the rest.

**Comment by qcybb** [comment]
Is the list-virtual.php file from master a "drop in" replacement when using 3.0.2?

**Comment by DavidGoodwin** [comment]
Thanks; closing.
