### ISSUE TITLE
setup.php unable to add super user

### ISSUE THREAD

**Issue by Kassouma** [postfixadmin/postfixadmin#461]
New install from sourceforge version 3.3.7 , i don't see in the branches, so am I doing this right?

- debian 10
- postgresql

When reaching setup.php, login with super admin password.
The form to create super user is not available.

the following error is raised.

> [Wed Feb 24 18:07:55.062180 2021] [php7:error] [pid 3875] [client 83.35.34.238:34346] PHP Fatal error:  Uncaught Exception: DEBUG INFORMATION: SQLSTATE[42883]: Undefined function: 7 ERREUR:  l'op\xc3\xa9rateur n'existe pas : boolean = integer\nLINE 1: SELECT * FROM admin WHERE superadmin = 1 AND active = 1\n                                             ^\nHINT:  Aucun op\xc3\xa9rateur ne correspond au nom donn\xc3\xa9 et aux types d'arguments.\nVous devez ajouter des conversions explicites de type.<br/> Check your error_log for the failed query in /srv/postfixadmin/functions.inc.php:1857\nStack trace:\n#0 /srv/postfixadmin/functions.inc.php(1796): db_query('SELECT * FROM a...', Array)\n#1 /srv/postfixadmin/public/setup.php(398): db_query_all('SELECT * FROM a...')\n#2 {main}\n  thrown in /srv/postfixadmin/functions.inc.php on line 1857, referer: http://IPADDRESS/setup.php

Fix is in setup.php : 

from 

> SELECT * FROM $table_admin WHERE superadmin = 1 AND active = 1

to

> SELECT * FROM $table_admin WHERE superadmin = '1' AND active = '1'

Thank you for your work.

**Comment by DavidGoodwin** [comment]
Hi - Thank you for reporting the bug and providing a fix :-) 

I'll probably release 3.3.8 soon as there was another bug fixed recently ( #457 / #456 ) which should also be rolled out.
