### ISSUE TITLE
display 

### ISSUE THREAD

**Issue by Jan-Kruis** [postfixadmin/postfixadmin#462]
I previously worked with version 3.2 of PostfixAdmin and have installed a test version of 3.4-dev, what I noticed is that the optimal width of the (Laptop)screen is not used, this was the case with version 3.2 but not with 3.3 and 3.4 dev.
This has made the length of some fields small  (variable). In some cases this turns out to be negative in my opinion, such as for example with the container in which the mailboxes are displayed under the virtual list. The container in which the mailboxes comes, the displays is so small that a mailbox record consists of several lines (see pic).
For example, the length of the field for the mailbox depends on the amount of text it contains, however, there is a hyphen ( minus sign) in the domain name, the email name is displayed over two lines, as well as the time of modification of this record, for example, also over two lines divided.

I personally do not think this improves the clarity and would therefore like to adjust this so that the fields have, for example, a fixed length. My question is how can I realize this I know that I have to be in the css \ bootstrap.css, I would like to know which variable I should adjust for this for example because if I look for example in the domain list I see that the length of the screen for a container is used and not for the vital list I have already tried to adjust some vairable but without success

If I set the style-min-width: to 1200 via firefox (webtools) then the display is good

My knowledge of modifying CSS files is limited, hence my question where and how do I make these modifications. so that I can put it in its own theme file.

<img width="454" alt="afbeelding" src="https://user-images.githubusercontent.com/860350/109324162-9528d800-7854-11eb-8407-e8d1bfba052d.png">

<img width="454" alt="afbeelding" src="https://user-images.githubusercontent.com/860350/109324199-a40f8a80-7854-11eb-894c-5f93d7f61038.png">

**Comment by DavidGoodwin** [comment]
you should be able to set $CONF['theme_custom_css'] = 'css/custom.css';

create public/css/custom.css containing something like : 

```css
.container { 
    style-min-width: 1200;
    border: 1px solid red;
}
```

(The solid red border should help you tell whether your change works or not - remove that line when you're happy).
