### ISSUE TITLE
forwarding & icon

### ISSUE THREAD

**Issue by Jan-Kruis** [postfixadmin/postfixadmin#463]
What also strikes me is that the user dialog box talks about “forwarding” and that the term alias is used by the admin [Virutal List :: Mailbox], this should not be “forwarding” either, I have in a modified version of me replaced the buttons for “edit”, “delete” and “alias” with icons. I think this is an advantage so that we have less translator problems. 

What also seems useful to me is to make the dialog for both users and admin the same as these differences at the moment from each other. * "as alias." occurs
For me, this cannot be the case with a forwarding.
I also noticed that in the user dialog there is a possibility to choose whether to save the mail locally or that it is only forwarded. This option is not available in the administrator dialog.
I am working on an update, is there any interest in including this change in a subsequent or test version?
If so how can i get the from you (include translations) need some help with git to get it to you

**Comment by DavidGoodwin** [comment]
It'd be great if you could create a Pull Request (PR) on GitHub - at this would ensure you get credit for the code/change.

Failing that, you could post the changes (or full files) somewhere; as long as they're based on the 'master' branch, it should be fine to merge.

**Comment by csware** [comment]
Sorry, I just realized that an issue I just opened is likely to be a duplicate: #496

**Comment by DavidGoodwin** [comment]
see #496
