### ISSUE TITLE
Unable to load template 'file:message.tpl' in 'index.tpl'

### ISSUE THREAD

**Issue by dbratchenko** [postfixadmin/postfixadmin#465]
Try to send broadcast message gives the error:

Fatal error: Uncaught --> Smarty: Unable to load template 'file:message.tpl' in 'index.tpl' <-- thrown in .../padmin/lib/smarty/libs/sysplugins/smarty_internal_template.php on line 195

**Comment by DavidGoodwin** [comment]
Hi - thanks for the bug report - what version of PostfixAdmin are you using?

**Comment by dbratchenko** [comment]
Postfix Admin 3.3.7

**Comment by dbratchenko** [comment]
P.S. I did fix it by adding empty file "message.tpl".

**Comment by DavidGoodwin** [comment]
I think that'll fix it, but I've not had a chance to test it yet.
