### ISSUE TITLE
500 Internal server error on list.php

### ISSUE THREAD

**Issue by dejolt** [postfixadmin/postfixadmin#466]
I have recently updated PostfixAdmin to the version 3.3.7  on Ubuntu 20.04 LTS and everything works fine, except the domain list tab. I can add admins, super admins, mailboxes etc. but cannot see anything when I click the domain list tab (https://admin.domain.com/list.php?table=domain). It's just a blank page. So I checked the dev tools in the browser and on the network tab I can see that I get a 500 error when I visit the domains list page. Same error with the list-virtual.php (https://admin.domain.com/list-virtual.php).
I checked the user privileges from the database and all seems fine.

Any help?

Thanks in advance Chris!

**Comment by DavidGoodwin** [comment]
Hi -
What database are you using?
Is there anything in the PHP error log? 

(If you're not sure where to look, try looking at setup.php - I think you should see a line like : ✅ PHP Error log (error_log) is - /var/log/php.log ... once you've entered in your setup password )

**Comment by dejolt** [comment]
Hi David, thanks for the fast response.

I use Mysql for the database. The strange thing is that there is no error on the setup page. I checked the /var/log/php7.4-fpm.log and just a few lines:

[28-Feb-2021 00:00:03] NOTICE: error log file re-opened
[01-Mar-2021 15:48:10] NOTICE: Terminating ...
[01-Mar-2021 15:48:10] NOTICE: exiting, bye-bye!
[01-Mar-2021 15:48:30] NOTICE: fpm is running, pid 716
[01-Mar-2021 15:48:30] NOTICE: ready to handle connections
[01-Mar-2021 15:48:30] NOTICE: systemd monitor interval set to 10000ms
[02-Mar-2021 11:38:15] NOTICE: Terminating ...
[02-Mar-2021 11:38:15] NOTICE: exiting, bye-bye!
[02-Mar-2021 11:39:07] NOTICE: fpm is running, pid 712
[02-Mar-2021 11:39:07] NOTICE: ready to handle connections
[02-Mar-2021 11:39:07] NOTICE: systemd monitor interval set to 10000ms

Here's a screenshot of the setup.php. Nothing seem off to me.
![Screen Shot 2021-03-02 at 10 47 03 PM](https://user-images.githubusercontent.com/49002827/109719715-5921aa00-7ba9-11eb-8b27-632f37ecd290.png)


Thanks!

**Comment by dejolt** [comment]
Hi David, 

So, apparently everything was configured correctly, the issue at least in my case was that I had to upgrade my PHP version. I updated to the latest PHP 8.0.2 and that fixed everything.

Thanks!

**Comment by DavidGoodwin** [comment]
Oh interesting. Postfixadmin should be quite happy with e.g. PHP 7.0+ I think (at least I'm running PHP 7.4 here, and travis should be doing PHP 7.0+).

I think you didn't see an error_log message because your error log file doesn't exist.

The code has : 
```php
    $error_log_file = ini_get('error_log');

    if (file_exists($error_log_file) && is_writable($error_log_file)) {
        $info[] = "PHP Error log (error_log) is - $error_log_file";
    }

    if (file_exists($error_log_file) && !is_writeable($error_log_file)) {
        $warn[] = "PHP Error log (error_log) is - $error_log_file, but is not writeable. Postfixadmin will be unable to log error(s)";
    }

```

So, it ends up writing nothing out if there is no error_log file.
