### ISSUE TITLE
Stop using php-imap

### ISSUE THREAD

**Issue by bleve** [postfixadmin/postfixadmin#472]
PHP imap extension is using old uw-imap for imap support. That is quite obsolete, it would be better to stop using php-imap. For example rhel doesn't have php-imap extension any more.

**Comment by DavidGoodwin** [comment]
Hi @bleve - PostfixAdmin doesn't **require** an imap module - it's a soft dependency, and it should only try and use it if you've got $CONF['create_mailbox_subdirs'] set. 

See e.g. https://github.com/postfixadmin/postfixadmin/blob/823f27b29d9cd03445de79e4a85871109fe140ef/model/MailboxHandler.php#L698

Having said that .... if someone wants to submit a patch to refactor the code, or remove the dependency I'd probably be happy to merge it :)
