### ISSUE TITLE
Deletion of mailboxes

### ISSUE THREAD

**Issue by Polve** [postfixadmin/postfixadmin#473]
Currently when you delete a mailbox the entry will be deleted on the database, but the files are still in the filesystem.

It would be useful to make postfixadmin delete it from the filesystem otherwise with time it will be hard to keep track of what it will be needed to clean by hand.

**Comment by DavidGoodwin** [comment]
i feel there's a post deletion hook somewhere which does this.

The main problem would be that postfixadmin runs as the webserver user (e.g. www-data) while your mail files (if they're on the same server) will be owned by some different user account .... so a native file delete won't work.

**Comment by DavidGoodwin** [comment]
ah, yeah, see config.inc.php there is this comment block : 

```PHP
// Optional:
// Script to run after deletion of mailboxes.
// Note that this may fail if PHP is run in "safe mode", or if
// operating system features (such as SELinux) or limitations
// prevent the web-server from executing external scripts.
// Parameters: (1) username (2) domain
// $CONF['mailbox_postdeletion_script']='sudo -u courier /usr/local/bin/postfixadmin-mailbox-postdeletion.sh';
$CONF['mailbox_postdeletion_script'] = '';
```

**Comment by Polve** [comment]
Thanks!

**Comment by DavidGoodwin** [comment]
@amiroslavov see https://github.com/postfixadmin/postfixadmin/issues/473#issuecomment-817745810
