### ISSUE TITLE
Virtual List Problem

### ISSUE THREAD

**Issue by mahbodfo** [postfixadmin/postfixadmin#474]
My Email server was based on ubuntu 18.04 and postfixadmin 3.2 
I have upgrade it to ubuntu 20.04 also mysql 8 and php 7.4 
On the upgraded server I encountered to this problem on Virtual list of postfixadmin 
DEBUG INFORMATION:
Invalid query: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'row FROM `mailbox` LEFT JOIN `alias` ON `mailbox`.username=`alias`.address L' at line 2

Check your error_log for the failed query.

Please check the documentation and website for more information.

Would you please help me? 
Thanks in Advanced

**Comment by DavidGoodwin** [comment]
Hi - Probably need more information.

 * Is there anything relevant in the Apache ( ? ) error log ( see e..g /var/log/apache2/error.log or similar )
 * What version of Postfixadmin are you using? 

There was this commit in the 3.2 branch which might be relevant - https://github.com/postfixadmin/postfixadmin/commit/c65a99ce2d3800900fa9ca4b22f02ef955df3096 ?

**Comment by mahbodfo** [comment]
Hi, Thanks to your response,
The error.log related to this problem is : 
[[Tue Apr 13 14:31:35.953950 2021] [php7:notice] [pid 1190] [client 192.168.??.??:47156] Invalid query: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'row  FROM `mailbox` \n LEFT JOIN `alias` ON `mailbox`.username=`alias`.address  L' at line 2, referer: https://192.168.??.??/postfixadmin/list.php?table=domain
[Tue Apr 13 14:31:35.954037 2021] [php7:notice] [pid 1190] [client 192.168.??.??:47156] caused by query: \n        SELECT * FROM (\n            SELECT `mailbox`.username AS label, @row := @row + 1 AS row  FROM `mailbox` \n LEFT JOIN `alias` ON `mailbox`.username=`alias`.address  LEFT JOIN `vacation` ON `mailbox`.username=`vacation`.email \n WHERE  `mailbox`.domain='?????????????.com' \n ORDER BY `mailbox`.username \n        ) idx WHERE MOD(idx.row, 10) IN (0,9) OR idx.row = 10\n    , referer: https://192.168.??.??/postfixadmin/list.php?table=domain

The postfixadmin version is  3.2 also my database is mysql 
does that commit c65a99c work for mysql?

Thanks again

**Comment by DavidGoodwin** [comment]
Ah, sorry, you probably need : https://github.com/postfixadmin/postfixadmin/commit/885bad949d3b75e4045c35446c3348ed4f55a116

**Comment by DavidGoodwin** [comment]
Updating to a newer PostfixAdmin 3.2.x release would probably be a good idea anyway :)

**Comment by mahbodfo** [comment]
It's work 
Also I will update to newest minor version 

Thank you very much.
