### ISSUE TITLE
Database problems

### ISSUE THREAD

**Issue by sidboy55555** [postfixadmin/postfixadmin#476]
Hi,
I'm trying to install postfix admin but for some reason it won't create database tables.
I've tried to reconfigure with "dpkg-reconfigure postfixadmin" but that also didn't do the trick.
I got the database server on a different machine.

OS: debian 10
Mariadb version: 10.3.27
postfixadmin version: 3.2.1-2

My log file
`2021/04/15 10:29:32 [error] 31406#31406: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  mysqli_real_connect(): Cannot connect to MySQL by using SSL in /usr/share/postfixadmin/functions.inc.php on line 1465PHP message: PHP Warning:  mysqli_real_connect(): [2002]  (trying to connect via (null)) in /usr/share/postfixadmin/functions.inc.php on line 1465PHP message: PHP Warning:  mysqli_real_connect(): (HY000/2002):  in /usr/share/postfixadmin/functions.inc.php on line 1465PHP message: PHP Warning:  mysqli_error(): invalid object or resource mysqli
 in /usr/share/postfixadmin/functions.inc.php on line 1648PHP message: Invalid query: PHP message: caused by query: CREATE TABLE IF NOT EXISTS `config` (
        `id` int(11) not null auto_increment primary key,
        `name`  VARCHAR(20) /*!40100 CHARACTER SET latin1 */ NOT NULL DEFAULT '',
        `value` VARCHAR(20) /*!40100 CHARACTER SET latin1 */ NOT NULL DEFAULT '',
        UNIQUE name ( `name` )
        )
      COMMENT = 'PostfixAdmin settings'" while reading response header from upstream, client: 141.101.77.35, server: mail.mymchosting.xyz, request: "GET /setup.php?debug=1 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "mail.mymchosting.xyz"
2021/04/15 10:29:32 [error] 31406#31406: *5 FastCGI sent in stderr: "PHP message: PHP Warning:  mysqli_real_connect(): Cannot connect to MySQL by using SSL in /usr/share/postfixadmin/functions.inc.php on line 1465PHP message: PHP Warning:  mysqli_real_connect(): [2002]  (trying to connect via (null)) in /usr/share/postfixadmin/functions.inc.php on line 1465PHP message: PHP Warning:  mysqli_real_connect(): (HY000/2002):  in /usr/share/postfixadmin/functions.inc.php on line 1465PHP message: PHP Warning:  mysqli_error(): invalid object or resource mysqli
 in /usr/share/postfixadmin/functions.inc.php on line 1648PHP message: Invalid query: PHP message: caused by query: SELECT value FROM `config` WHERE name = 'version'" while reading response header from upstream, client: 141.101.77.35, server: mail.mymchosting.xyz, request: "GET /login.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "mail.mymchosting.xyz", referrer: "https://mail.mymchosting.xyz/setup.php?debug=1"
`

?debug=1 message:
`CREATE TABLE IF NOT EXISTS `config` ( `id` int(11) not null auto_increment primary key, `name` VARCHAR(20) /*!40100 CHARACTER SET latin1 */ NOT NULL DEFAULT '', `value` VARCHAR(20) /*!40100 CHARACTER SET latin1 */ NOT NULL DEFAULT '', UNIQUE name ( `name` ) ) COMMENT = 'PostfixAdmin settings'`

Edited lines in config.inc.php:
`$CONF['database_type'] = 'mysqli';
$CONF['database_host'] = 'external database ip';
$CONF['database_user'] = 'postfixuser';
$CONF['database_password'] = 'mypass';
$CONF['database_name'] = 'postfixadmin';
$CONF['database_port'] = '3306';

// Database SSL Config
$CONF['database_use_ssl'] = 'true';
$CONF['database_ssl_key'] = '/etc/mysql/ssl/mysql_client.key';
$CONF['database_ssl_cert'] = '/etc/mysql/ssl/mysql_client.pem';
$CONF['database_ssl_ca'] = '/etc/mysql/ssl/mysql_ca.pem';
$CONF['database_ssl_ca_path'] = '/etc/mysql/ssl/mysql_ca.pem';
$CONF['database_ssl_cipher'] = 'TLSv1.3';`

mariadb user grants:
`+----------------------------------------------------------------------------------------------------------------------------------------------------+
| Grants for postfixuser@mydomain                                                                                                        |
+----------------------------------------------------------------------------------------------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON *.* TO `postfixuser`@`mydomain` IDENTIFIED BY PASSWORD '*' REQUIRE SSL |
| GRANT ALL PRIVILEGES ON `postfixadmin`.* TO `postfixuser`@`mydomain`                                                                   |
+----------------------------------------------------------------------------------------------------------------------------------------------------+`

Thnx in advanced!
- sidboy55555

**Comment by DavidGoodwin** [comment]
I don't have much experience connecting to MySQL with SSL ... 

**PHP message: PHP Warning: mysqli_real_connect(): Cannot connect to MySQL by using SSL in /usr/share/postfixadmin/functions.inc.php on line 1465** is going to be the fundamental problem.

Does the user executing the PHP scripts have access to read the actual ssl files (/etc/mysql/ssl .... ) ?
