### ISSUE TITLE
Different server hosting postfix and dovecot

### ISSUE THREAD

**Issue by UMB8998** [postfixadmin/postfixadmin#477]
Hello
This project looks awesome to be able to manage mail servers for people that are not tech savvy, thank you!!!
I have a server on AWS with dovecot and postfix, the server is already configured to have virtual aliases, users and domains, but all the setting have to be trough the mysql server, there is a way to configure postfixadmin on another server and connect it to the aws for setting (I don't want to increase my quota on amazon) i saw that I could specify the smtp server on the config file, but is it enough for my use case?? do I have to reconfigure the aws server?
Thank you!!!
BTW sorry for my bad English

**Comment by DavidGoodwin** [comment]
Hi - there should be no problem using different servers for the different components. It doesn't have to all go on one server. 

However, you may find you need PostfixAdmin to be on the same server as dovecot if you want it to e.g. create some sort of customised folder structure upon account creation, or you want the mail files to be deleted if a mailbox is deleted etc etc.

**Comment by UMB8998** [comment]
Thank you very much for your fast answer, I will try it tomorrow morning, and update with the results

**Comment by UMB8998** [comment]
Hello, I tried setting it up but the Web Interface didn't got all the domains and mails that I already configured on my email server, i guess that there is no connection between them, on the application.ini 
I changed the setting of the SMTP server to talk to my server, but I guess that is not enough, what I'm missing?
