### ISSUE TITLE
Import users from csv

### ISSUE THREAD

**Issue by rdivo** [postfixadmin/postfixadmin#478]
Hello,
How do I call this script?
What should the csv file look like?

I will be grateful for some examples of use.

**Comment by DavidGoodwin** [comment]
You're referring to this ? https://github.com/postfixadmin/postfixadmin/blob/269515b1adf94ee1ee36dee0e734691d4939212a/ADDITIONS/import_users_from_csv.py#L50 ?

**Comment by rdivo** [comment]
So exactly about this script. I don't want to run on Debian 10. And I have
a very large number of accounts to import. Could I have a * .csv file
format with sample data please? How do I run the script? Maybe I'm doing
something wrong and that's why the script won't work.




sob., 24 kwi 2021 o 22:18 David Goodwin ***@***.***>
napisał(a):

**Comment by rdivo** [comment]
My users.csv file looks like this:
[image: obraz.png]
I set up the dand for the database.
I run the script  ./import_users_from_csv.py users.csv
After starting the script, there is no error but the users are not
importing to the database.

I am asking for help because I have 700 accounts to import.





niedz., 25 kwi 2021 o 22:47 Jamal Filowski ***@***.***> napisał(a):

**Comment by rdivo** [comment]
My users.csv file looks like this:

user;password;domain;name
test1;Password&123;domain.com;Test 1
test2;Password&123;domain.com;Test 2



pon., 26 kwi 2021 o 12:38 Jamal Filowski ***@***.***> napisał(a):

**Comment by DavidGoodwin** [comment]
I don't know if that python script can cope with ; as field separators ot not - it might want commas?

**Comment by rdivo** [comment]
I used commas and the script ran
./import_users_from_csv.py users.csv

user,password,domain,name
test11,Password&123,domain.com,Test 11
test22,Password&123,domain.com,Test 22


But I ran into another problem with adding records to the database

Database insertion error
(1062, "Duplicate entry 'domain.com' for key 'PRIMARY'")
Record was:
['2021-04-26 17:49:19', 'domain.com', '', '2021-04-26 17:49:19', 1, 0, 0,
0, 'virtual', 0]
Query was:
INSERT INTO
domain(modified,domain,description,created,active,backupmx,quota,mailboxes,transport,aliases)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)

What could be causing this problem?

**Comment by DavidGoodwin** [comment]
I'd suggest you use the postfixadmin-cli interface instead -

e.g.
```
david@laptop:~/src/postfixadmin/scripts$ bash postfixadmin-cli mailbox add help

Welcome to Postfixadmin-CLI v0.3
---------------------------------------------------------------
Usage:

    postfixadmin-cli mailbox add

        Adds mailbox in interactive mode.

- or -

    postfixadmin-cli mailbox add <address> --option value --option2 value [...]

        Adds mailbox in non-interactive mode.

        Available options are:

        --password
            Password
            Password for POP3/IMAP

        --password2
            Password (again)

        --name
            Name
            Full name

        --quota
            Quota
            MB (max: 10)

        --active
            Active

        --welcome-mail
            Send Welcome mail

        --email-other
            Other e-mail
            Used if the password is forgotten
```

**Comment by rdivo** [comment]
Can postfixadmin-cli import data from a csv file?
I'm asking because I have 700 import accounts.


Ja w jaki sposób użyć postfixadmin-cli  do importu z pliku csv ?



wt., 27 kwi 2021 o 22:02 David Goodwin ***@***.***>
napisał(a):

**Comment by DavidGoodwin** [comment]
postfixadmin-cli can't read a csv file, you'd need to do something funky in the shell, or similar to call it appropriately.

**Comment by rdivo** [comment]
Can postfixadmin-cli be used to add single users?
Can I add a dozen or so users at once with postfixadmin-cli?

How do I use postfixadmin-cli when adding users?
I am asking for some examples.

śr., 28 kwi 2021 o 14:24 David Goodwin ***@***.***>
napisał(a):

**Comment by DavidGoodwin** [comment]
# dirty bash script

```
#!/bin/bash
OFS=$IFS
IFS=","

while read username password domain name; do
 ./postfixadmin-cli mailbox add "$username@$domain" \
        --name "$name" \
        --password "$password" --password2 "$password" \
        --quota 1 --welcome-email=0
done < test.csv

IFS=$OFS
```

# output

```
Welcome to Postfixadmin-CLI v0.3
---------------------------------------------------------------

The mailbox test11@example.org has been added to the mailbox table.

---------------------------------------------------------------

Welcome to Postfixadmin-CLI v0.3
---------------------------------------------------------------

The mailbox test12@example.org has been added to the mailbox table.

---------------------------------------------------------------
```
