### ISSUE TITLE
Linux Gentoo package maintance

### ISSUE THREAD

**Issue by rutkas** [postfixadmin/postfixadmin#48]
The postfixadmin package in gentoo repository is too old and not maintained and going to be removed from the directory. However postfixadmin is noted in gentoo mail server guide. Can someone maintane the project in gentoo portage dir ?

[https://bugs.gentoo.org/show_bug.cgi?id=608726](https://bugs.gentoo.org/show_bug.cgi?id=608726)

**Comment by titanofold** [comment]
The Gentoo package is now maintained by myself at a minimum. Others are welcome to improve the ebuild through proxy.

**Comment by xpunkt** [comment]
would it be possible to get 2.3.8 back ?

i have only found one single problem with it /list-admin.php is empty when php 7.2 is on emerged, all other list * works, in php 7.0 and php 7.1 it worked

if not possible will update to later postfixadmin version still be backward compatibel with old postfix and dovecot setup in how sql database layout is ?

hope for guidense on this, there is imho none cve found in this old software so i like to stay with it

**Comment by DavidGoodwin** [comment]
There are probably XSS or SQL injection vulnerabilities in the old codebase(s). 

You should be able to update to a newer release - postfix and dovecot shouldn't need changing - but postfixadmin itself will probably have database schema changes to apply to support newer functionality.
