### ISSUE TITLE
Postfix admin don't work after moving from php 7.4 to 8.0.5

### ISSUE THREAD

**Issue by Arturitu12** [postfixadmin/postfixadmin#481]
After I moved from php 7.4 to 8.0.4 postfixadmin don't work, i didn't change any postfixadmin or database settings. When I try to connect to my domain under /postfixadmin i see HTTP 500 error, before update all works well.

**Comment by DavidGoodwin** [comment]
Hi - what version of Postfixadmin are you using?

If you're using the latest version, please check 'setup.php' after authenticating with the setup password; it might give you some hints.

Failing that, check the Apache ( ? ) error log - sometimes this is /var/log/apache2/error.log but your configuration may differ.

**Comment by Arturitu12** [comment]
I have that error in log: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /usr/share/postfixadmin/functions.inc.php on line 730, i go to the following line: 
![image](https://user-images.githubusercontent.com/58103832/116816054-acd85180-ab60-11eb-96dc-20f81b0c1ac2.png)

**Comment by DavidGoodwin** [comment]
i think your version of postfixadmin is old; updating will fix it.

**Comment by Arturitu12** [comment]
"postfixadmin is already the newest version (3.2.1-3)."

**Comment by DavidGoodwin** [comment]
there are newer versions than that ... https://github.com/postfixadmin/postfixadmin/releases

**Comment by Arturitu12** [comment]
So why ubuntu repository don't see it after apt-get update? Git clone downloading 3.2 too, I need manually extract this tar.gz?

**Comment by Arturitu12** [comment]
When i try to run new version after manually extracted this tar.gz it says postfixadmin is no installed

**Comment by Arturitu12** [comment]
i running my server at ubuntu 20.04

**Comment by DavidGoodwin** [comment]
'this new version'

 * what version are you trying to install / use ?
 * I personally wouldn't mix a debian package and installing from source.  I'd do: `dpkg -r --purge postfixadmin` and then configure / setup PostfixAdmin from a .tar.gz file

**Comment by Arturitu12** [comment]
When I installed postfixadmin 1st time i used this tutorial: https://www.linuxbabe.com/mail-server/postfixadmin-create-virtual-mailboxes-ubuntu-20-04 , it installed me 3.2.1.3 , ubuntu commands apt-get update and apt-get upgrade sees postfixadmin 3.2.1.3 as newest version, i really don't know how to install it from tar.gz

**Comment by Arturitu12** [comment]
i unistalled it and tried again but i say again that 3.2 is a newest

**Comment by Arturitu12** [comment]
I tried to install manually following the INSTALL.TXT but it seems that its not listening on url that it should

**Comment by DavidGoodwin** [comment]
are you sure there isn't another postfixadmin configuration within the webserver that's conflicting with what you're trying to use?

(dpkg --purge -r postfixadmin ?)

**Comment by Arturitu12** [comment]
I purged, apache virualhost config is ok too

**Comment by Arturitu12** [comment]
I just wondering why apt see only 3.2.1.3 when there is 3.3.8

**Comment by DavidGoodwin** [comment]
because Debian/Ubuntu don't roll out version updates within a release - they will patch bugs / security issues, but that's all.

**Comment by Arturitu12** [comment]
I turned off all other virtual apache hosts and still when i go to postfixadmin nothing load, when i type /setup.php i see error 403 even when www-data has priviliges to it

**Comment by Arturitu12** [comment]
So ubuntu apt dont work for postfixadmin mhm

**Comment by Arturitu12** [comment]
Ok I think better for to just switch back to php7.4 and wait for new erpository package ill close this
