### ISSUE TITLE
The password_expiry field get never updated when user changes his password (v3.3.8)

### ISSUE THREAD

**Issue by zentavr** [postfixadmin/postfixadmin#492]
When the user comes to `/users/password.php` and tries to change his password - the password gets changed, but the `password_expiry` column is not updated.

Also, there is no possibility to change that field over the admin portal as well - only manually by jumping inside MySQL console.

**Comment by DavidGoodwin** [comment]
Hi @zentavr - which version of PostfixAdmin does this issue refer to ? 'master' ? 3.3.x ?

**Comment by zentavr** [comment]
3.3.8

**Comment by zentavr** [comment]
Downloaded from https://github.com/postfixadmin/postfixadmin/archive/postfixadmin-3.3.8.tar.gz

**Comment by zentavr** [comment]
The other problem still persists: I cannot see anywhere at the admin portal where the admin can set (when creates the user) or update the password_expiry field even when there is `$CONF['password_expiration'] = 'YES';` in my `config.local.php` file.
