### ISSUE TITLE
setup.php refuses to upgrade database when not logged in, but one can't login when upgrade is required

### ISSUE THREAD

**Issue by C0rn3j** [postfixadmin/postfixadmin#494]
I do not believe the instructions/behavior about database upgrades is correct.

Take my case from today:

login.php (the quote is in functions.inc.php)
>ERROR: The PostfixAdmin database layout is outdated (you have r1843, but r1844 is expected). Please run setup.php to upgrade the database.

setup.php
>Please login to see perform database update.

upgrade.php
> Upgraded the database and all was fine

The upgrade logic in setup.php is as such:

```php
            <?php
            if ($authenticated) {
                $db = false;
                try {
                    $db = db_connect();
                } catch (\Exception $e) {
                    error_log("Couldn't perform PostfixAdmin database update - " . $e->getMessage());
                }

                if ($db) {
                    print "<p>Everything seems fine... attempting to create/update database structure</p>\n";
                    require_once(dirname(__FILE__) . '/upgrade.php');
                } else {
                    echo "<h3 class='h3 text-danger'>Could not connect to database to perform updates; check PHP error log.</h3>";
                }
            } else {
                echo "<h3 class='h3 text-warning'>Please login to see perform database update.</h3>";
            }
            ?>
```

In my case, I was not authenticated, so I could not run the upgrade from setup.php, but I also could not login, because I needed to run the upgrade.

I've two solutions and I am not sure which one is more correct

1) Edit the strings to mention running upgrade.php 
2) Try the upgrade anyways even when not authorized.

**Comment by DavidGoodwin** [comment]
I think anyone can hit the URL 'upgrade.php' - and it should run.

Can you clarify what version of PostfixAdmin you're trying to use please?

**Comment by C0rn3j** [comment]
Sorry about that, was filing this way too early.

I am running `postfixadmin 3.3.9-1` on Arch Linux, `PHP 8.0.6` and using php-fpm and nginx.

>I think anyone can hit the URL 'upgrade.php' - and it should run.

Correct, and it worked for me, but login page told me to run setup.php and setup.php told me to login.

upgrade.php was not ran (due to the code I described above), nor mentioned.

**Comment by DavidGoodwin** [comment]
I think the hope is that a packaged version of Postfixadmin would call 'upgrade.php' as some sort of postinstall task.

However, I see your point - hopefully running 'upgrade.php' in setup without authentication is safe enough - given someone knowing the URL could have run it anyway.

**Comment by C0rn3j** [comment]
Thanks a lot for a quick fix!

I do agree that this should also be run automatically on an update to completely avoid downtime, I added an example pacman hook that does just that to the [Arch Wiki page of Postfixadmin](https://wiki.archlinux.org/title/PostfixAdmin#Pacman_hook).
