### ISSUE TITLE
RFC: Rename the "Alias" button on virtual mailbox table

### ISSUE THREAD

**Issue by csware** [postfixadmin/postfixadmin#496]
The term "Alias" refers to the entry in the aliases table of postfixadmin's database and has the postfix point of view.

However, when a user opens that virtual mailbox table and he sees "Alias", this is likely to mean something different to him. I experienced several times that mail administrators put "aliases" in there and they tough, now these aliases are additional addresses of the mailbox. After that they wondered why they got bounces when they sent a mail to the original mailbox (and, of course, why the alias did not work).

RFC: Should the button text be renamed? && What could be a better name?

**Comment by DavidGoodwin** [comment]
'Forwards' ?

**Comment by DavidGoodwin** [comment]
* I suspect some language file(s) now need updating?  
 * Some documentation may need changing
