### ISSUE TITLE
dovecot:sha512-crypt for password encryption doesn't work

### ISSUE THREAD

**Issue by MrT0** [postfixadmin/postfixadmin#5]
In the config file I set the encryption method for passwords as follows:
$CONF['encrypt'] = 'dovecot:SHA512-CRYPT';$CONF['encrypt'] = 'dovecot:SHA512-CRYPT';

However, after the successful creation of the superuser account it's not possible to login to postfixadmin.
Any ideas to get rid of that issue without degrading security by using the functional md5crypt?

**Comment by palepurple** [comment]
I've had a quick look at the code, and it looks like it does us pacrypt to hash the password; is it just the case that you defined a setup password before you edited the config file to specify the dovecot: stuff?

**Comment by pedromorgan** [comment]
Am curious about this pasword business..

Afaik it end up here..
https://github.com/postfixadmin/postfixadmin/blob/master/functions.inc.php#L843

BUt Where is the salt from ??
Want to use same techniuqu here..
https://github.com/daffodil/go-mailkit/tree/master/postfixadmin

**Comment by palepurple** [comment]
The crypt password format stores the encryption type, salt and password all in one field. 

See http://php.net/crypt which documents it far better than I ever will ....
