### ISSUE TITLE
non lowercase names from goto, address, mailbox are causing some issues

### ISSUE THREAD

**Issue by reiffert2** [postfixadmin/postfixadmin#51]
14:13 <cboltz> hmm, uppercase vs. lowercase?
14:32 <cboltz> der Bug betrifft also "nur" den Altbestand
21:01 <reiffert> ich hab die accounts per insert into ... select ... from vexim.table angelegt

**Comment by DavidGoodwin** [comment]
I think you're asking if case is a problem ... and it shouldn't be ... at least for MySQL users. 

http://www.postfix.org/virtual.5.html

```raw
CASE FOLDING
       The search string is folded to lowercase before database lookup. As  of
       Postfix  2.3,  the search string is not case folded with database types
       such as regexp: or pcre: whose lookup fields can match both  upper  and
       lower case.
```

**Comment by cboltz** [comment]
Looking up my IRC log (it was a private discussion) - the problem was something like `Undefined index user@example.com in .../PFAHandler.php on line 708`, and PHP array keys are case sensitive ;-)

**Comment by DavidGoodwin** [comment]
hmm, well, if the user or domain had been added with mixed case, then this - https://github.com/postfixadmin/postfixadmin/blob/master/model/PFAHandler.php#L767  would probably fail as it's trying to do : 

```PHP
$result = $this->read_from_db(array($this->id_field => $this->id));
if (count($result) == 1) {
        $this->result = $result[$this->id];
        return true;
}
```

Which ought to be equivalent to  : 
```
$this->result = reset($result)
```
