### ISSUE TITLE
fetchmail.conf and fetchmail.pl secureity

### ISSUE THREAD

**Issue by xpunkt** [postfixadmin/postfixadmin#511]
i read mda in webui can be set to rm -f /

with is imho okay IF fetchmail.pl is not running with ROOT access !!

fetchmail does not need to be runned as root imho, i created this bug her to have it dokumented with things to make sure is not make many more problems for postfixadmin users

what is needed with ssl in fetchmail ?, will it work if fetchmail have no ssl support if mailboxes does not need ssl/tls ?, what about certs ?, have i misseed something ?

not all see football or tour de france :=)

**Comment by DavidGoodwin** [comment]
Hi - I assume you're referring to : 

https://github.com/postfixadmin/postfixadmin/blob/088c528d128d30cfd32ce9dd94c10579c046b27c/config.inc.php#L482

So ....

 * There is a bit warning next to it
 * The default value ('NO') should be safe ...

```PHP
// fetchmail_extra_options allows users to specify any fetchmail options and any MDA
// (it will even accept 'rm -rf /' as MDA!)
// This should be set to NO, except if you *really* trust *all* your users.
$CONF['fetchmail_extra_options'] = 'NO';
```
