### ISSUE TITLE
Is it possible to upgrade from Postfix Admin 3.1 ?

### ISSUE THREAD

**Issue by quicktrick** [postfixadmin/postfixadmin#514]
Excuse me for a stupid question, but is it possible to upgrade from Postfix Admin 3.1 to the current version 3.3.9 using the standard upgrade procedure?

**Comment by DavidGoodwin** [comment]
Yes. 

Any database updates should be handled by the public/upgrade.php script (called when you goto setup.php anyway).

**Comment by DavidGoodwin** [comment]
(the biggest recent change was moving to having the 'public/' directory - so you MIGHT need to reconfigure your Apache  ( ? ) virtual host .... or live with sticking '/public' on the end of all URLs. )

**Comment by quicktrick** [comment]
Thanks a lot David! I have a few other servers with newer versions of Postfix Admin, so I know what to change in my Nginx settings.
