### ISSUE TITLE
Crash when trying to see the logs while logged as an admin

### ISSUE THREAD

**Issue by pgimalac** [postfixadmin/postfixadmin#516]
When I am logged as an admin and I click on "journal", I can't see any logs because php crashes with
```
PHP message: Invalid query: SQLSTATE[HY093]: Invalid parameter number: :domain caused by SELECT extract(epoch from timestamp) as timestamp,username,domain,action,data FROM log  ORDER BY timestamp DESC LIMIT 10PHP message: PHP Fatal error:  Uncaught Exception: DEBUG INFORMATION: SQLSTATE[HY093]: Invalid parameter number: :domain
```
which I guess is because there is always an argument given to the query
https://github.com/postfixadmin/postfixadmin/blob/284e1f7eb276f27957a0cd54d58a6be4acdcea45/public/viewlog.php#L77
while if you are an admin there is no argument in the query (there is no `WHERE` condition on the domains).

**Comment by DavidGoodwin** [comment]
(I've not tested that)
