### ISSUE TITLE
Don't show postfixadmin version when not logged in

### ISSUE THREAD

**Issue by nanu-c** [postfixadmin/postfixadmin#517]
We are not updating always postfixadmin to the latest version, I know it's abad habit but sometimes we are short on resources.

I know, there are not many cve regarding postfixadmin but i still don't need the version info so present :)

**Comment by DavidGoodwin** [comment]
Thanks for the suggestion - the changeset above should result in the footer version bit only being shown if you are logged in.

**Comment by nanu-c** [comment]
Cool thank you, that was really fast :)
