### ISSUE TITLE
Use the Wiki for documentation

### ISSUE THREAD

**Issue by lrupp** [postfixadmin/postfixadmin#518]
At least when updating postfixadmin, I get a link that points to
  https://github.com/postfixadmin/postfixadmin/tree/master/DOCUMENTS 

Which is correct o none side, but on the other side a bit irritating, as it is just a directory containing a lot of files. It's not clear to me, which files are important or provide the help I'm looking for.

On the other side, I see you enabled the Wiki feature here in Github - but provide no content there. 

What about 
* migrating the content of the DOCUMENTS folder into the wiki here in Gitlab
* changing the "Documentation" URL to https://github.com/postfixadmin/postfixadmin/wiki
* if needed, include the files from the wiki as separate checkout in the download area?

I think this should make it not only easier for users and admins to check the documentation, it might also be an opportunity to get additional feedback (pull requests) for the documentation, as the wiki here allows this as well - even easier and more user friendly in my eyes.

**Comment by DavidGoodwin** [comment]
I suspect the problem is having someone who is willing to maintain any documentation :-) 

There is the old sourceforge Wiki - https://sourceforge.net/p/postfixadmin/wiki/Home/ - does this help?

**Comment by lrupp** [comment]
Well: as I made the suggestion, I'm happy to help. 

1. I would recommend to "migrate" the current content below the DOCUMENTS folder into the wiki
2. By doing this, some rewrite or update of the current content (screenshots for example) might not harm
3. Once your team is happy with the state of the wiki, the "code" that currently points to the DOCUMENTS folder could be updated - and point to the wiki instead
4. Once this is done, the content in the DOCUMENTS folder should be deleted. 
5. Either providing a README.md (which only contains basic information together with a link to the wiki) or a checkout of the wiki pages (inside the DOCUMENTS folder) should be the last step

What do you think?

I am not sure, if my help us welcome and how to help here exactly. Maybe by forking your project and preparing steps 1-3 ?
