### ISSUE TITLE
Cant add new alias, mailbox, domain, mysql statement failed

### ISSUE THREAD

**Issue by kamzar1** [postfixadmin/postfixadmin#519]
PHP 7.4.21
mariadb  Ver 15.1 Distrib 10.6.3-MariaDB
Postfix Admin 3.3.9

`"PHP message: Invalid query: SQLSTATE[HY000]: General error: 1364 Field 'user_id' doesn't have a default value caused by INSERT INTO `alias` (address,domain,goto,created,modified,active) VALUES (:address,:domain,:goto,now(),now(),:active)"`

`"PHP message: Invalid query: SQLSTATE[HY000]: General error: 1364 Field 'type' doesn't have a default value caused by INSERT INTO `alias` (address,domain,goto,created,modified,active) VALUES (:address,:domain,:goto,now(),now(),:active)"`

it's been fixed by changing the table fields: 
user_id to default '0'
type to default 'NULL'

**Comment by kamzar1** [comment]
Another way around to avoid STRICT_TRANS_TABLES is adding this statement at start:
`SET SQL_MODE = '';`

**Comment by DavidGoodwin** [comment]
Hi - what schema does your alias table have ? 

It should look like : 

```
CREATE TABLE `alias` (
  `address` varchar(255) NOT NULL,
  `goto` text NOT NULL,
  `domain` varchar(255) NOT NULL,
  `created` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `modified` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `active` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`address`),
  KEY `domain` (`domain`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Postfix Admin - Virtual Aliases'
```

and there's no 'user_id' or 'type' field in there - so I assume yours has some custom fields?

**Comment by kamzar1** [comment]
Indeed!
I double checked the original schema vs mine.
It seems application provider has added some fields.
Thanks for paying attention.
I am going to close this issue.
