### ISSUE TITLE
Allow authentication against OAuth2 or Apache REMOTE_USER

### ISSUE THREAD

**Issue by philpem** [postfixadmin/postfixadmin#522]
I'd like to use PostfixAdmin in an environment which uses an OAuth2 (OpenID Connect) single-signon system for authentication.
I'm using the mod_auth_openidc plugin already: https://github.com/zmartzone/mod_auth_openidc

Would it be possible to have PostfixAdmin check the `REMOTE_USER` environment variable Apache passes in?
If this is set, PostfixAdmin would look up REMOTE_USER (which would contain the user's email address) in the database and log the user in automatically as that user.

**Comment by DavidGoodwin** [comment]
You could probably cheat and put something in the bottom of  config.local.php a bit like this : 

You might not need this, and having it may make what's in the root common.php moan : 

```php
     session_cache_limiter('nocache');
     session_name('postfixadmin_session');
     session_start();
```

Code that might do the login : 

```php
$current_login = $_SESSION['sessid']['username'] ?? null;
$oauth_user = $_SERVER['REMOTE_USER'] ?? null;

if($oauth_user && $oauth_user !== $current_login) {
    init_session($oauth_user, false); // use true if you want the user to be an admin.
}
```

**Comment by DavidGoodwin** [comment]
There have been a few requests in the past to somehow make the authentication within Postfixadmin more customisable - e.g. supporting 2fa or something like this .... all of which could probably be supported by some sort of hook functions within Postfixadmin.

**Comment by pierreozoux** [comment]
@DavidGoodwin hey :)

I see you say that it was completed, but yet I don't see any documentation.

Or maybe the instructions you provided are enough?

Thanks for your help!

**Comment by DavidGoodwin** [comment]
Have you tried putting 
```PHP
$current_login = $_SESSION['sessid']['username'] ?? null;
$oauth_user = $_SERVER['REMOTE_USER'] ?? null;

if($oauth_user && $oauth_user !== $current_login) {
    init_session($oauth_user, false); // use true if you want the user to be an admin.
}
```

at the bottom of config.local.php ?

**Comment by DavidGoodwin** [comment]
Hello ...

So I've had a quick bash at doing something ... I'm not sure I'm happy with it yet (for a start it requires you to submit the login form, with rubbish, even when you have the $_SERVER['REMOTE_USER'] set.

See feature-admin-login-via-callback

You'll need to add something to your config.local.php file - there's an example at the bottom of config.inc.php to show you what it could look like.

For now, I couldn't think of anything better than a callable that returns a string to imply success, and false on failure.

**Comment by pierreozoux** [comment]
Thanks @DavidGoodwin for your comment.

It sounds like doable to do something with a bit of effort.

If we move in this direction, we'll come back to make PR to improve the workflow, have a nice day!

**Comment by matissime** [comment]
I would love to implement this on my instance, but I don't know how. If someone have managed to do it, please can you share the instructions ? Thanks :)

**Comment by MagicRB** [comment]
> for a start it requires you to submit the login form, with rubbish, even when you have the $_SERVER['REMOTE_USER'] set.

Is that still the case? looking into having postfix admin with oauth2 and also app passwords

**Comment by jeabapLANG** [comment]
Any news on this subjet ?

Would be great if we could just directly authenticate the admin with an external provider 👍
