### ISSUE TITLE
Extra semicolon in status field if custom_domains disabled

### ISSUE THREAD

**Issue by PF4Public** [postfixadmin/postfixadmin#524]
Setting
```php
$CONF['show_custom_domains']=array();
$CONF['show_custom_colors']=array();
```
I see an extra semicolon in mailboxes view:
![image](https://user-images.githubusercontent.com/10319700/128215259-77b1ac4d-917f-4652-904c-e2f2762140cc.png)
```html
<tr>
<td>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<span style="background-color:darkgrey">&nbsp;&nbsp;</span>
&nbsp;;&nbsp;
</td>
<td>dgfdfgdfhdfh@
```
Should these variables be nulled to disable custom_domains? Nulling them helps with the semicolon, but the resulting HTML doesn't look right:
```php
$CONF['show_custom_domains']="";
$CONF['show_custom_colors']="";
```

```html
<tr>
<td>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<span style="background-color:darkgrey">&nbsp;&nbsp;</span>
&nbsp;
<span style="background-color:">&nbsp;&nbsp;</span>
&nbsp;
</td><td>dgfdfgdfhdfh@
```

I suppose, that it is this semicolon, that sneaks into HTML:

https://github.com/postfixadmin/postfixadmin/blob/8518d53906293ae3f0bdf4db6e67f53975a112a9/functions.inc.php#L2375

I can do a PR to remove it :D

**Comment by DavidGoodwin** [comment]
Well spotted :)

Thank you for contributing/reporting it. Don't worry about the PR.

**Comment by PF4Public** [comment]
Wow, that was fast.
Thanks!

**Comment by PF4Public** [comment]
I wonder, why is this fix absent in master and in a recent tag?

**Comment by DavidGoodwin** [comment]
The fix is on master, I hadn't cherry-picked it into the 3.3 branch though (now done).

If there's a better way of working, I'm all 'ears' .... 

Thanks for spotting it wasn't in 3.3.

**Comment by PF4Public** [comment]
> If there's a better way of working, I'm all 'ears' ....

I'm not in a position to hand out advices, but from my own experience I found linear history the most comfortable to work with. In my projects I keep everything on one branch (master) and rebase and squash every PR I receive. This way I can take contributions even outside of GitHub by adding another remote and cherry-picking commits. And all that completely preserving commit authorship. At the time of a release I have to tag it and I'm done! I never have to provide support for past tags, but if I had to, I could simply branch at the needed tag and cherry-pick some commits extending a bit from master, fixing that release, bumping minor, not touching the master. I'm aware of some versioning patterns with heavy branching, but doubt it is that useful for small projects.

So if you ask me, I'd say one branch, linear history, rebasing/squashing PRs is all you need :)
