### ISSUE TITLE
print errors when doveadm fails

### ISSUE THREAD

**Issue by damnms** [postfixadmin/postfixadmin#528]
i have a bit of special configuration on my server (all new files have 500 instead of 755 etc.), so sometimes an application fails because of permission problems. thats fine as long as i can see the error.
unfortunately, in the current version of debian 11 / postfixadmin, there is no error log when the doveadm binary is called 
so i had to login as user www-data, then execute doveadm pw and fix the permission errors.

it would be nice if an error might be thrown (especially when relying on filesystem stuff) and logged.

even worse: that might lead to unreasonable ban's because each request resulted in an entry in the log that the password is wrong, which is wrong because the password is correct, but the process failed at proc_open with doveadm

the error:
su -s /bin/bash www-data # to get the actual error
doveadm pw
resulted in: doveconf: Fatal: Error in configuration file /etc/dovecot/conf.d/10-ssl.conf line 8: ssl_dh: Can't open file /etc/ssl/dh4096.pem: Permission denied

so guess $pipe is not false but contains those errors

**Comment by DavidGoodwin** [comment]
see also https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/HASHING.md#dovecotcrypt-method

**Comment by damnms** [comment]
thanks, i already switched to php_crypt, but as long as dovecot: is supported/documented as possible way for hashing, i would check the result of doveadm

**Comment by DavidGoodwin** [comment]
https://github.com/postfixadmin/postfixadmin/blob/ecc97439abab24c7e67cfd351ac82ba220c0f489/functions.inc.php#L1059 should result in the server error log containing something useful.
