### ISSUE TITLE
package maintaining for debian

### ISSUE THREAD

**Issue by damnms** [postfixadmin/postfixadmin#529]
i was a bit surprised that there is no postfixadmin for debian 11, so i create that as an issue here.
unfortunately, the bugs that prevented postfixadmin to be available in debian 11 are still open.

**Comment by DavidGoodwin** [comment]
Yeah - See also  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897683

**Comment by DavidGoodwin** [comment]
and primarily https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=926253
