### ISSUE TITLE
calender.js missing in postfixadmin_3.1-1_all.deb

### ISSUE THREAD

**Issue by hannesdorn** [postfixadmin/postfixadmin#53]
I just installed postfixadmin_3.1-1_all.deb from https://sourceforge.net/projects/postfixadmin/files/postfixadmin/postfixadmin-3.1/postfixadmin_3.1-1_all.deb

There is a reference to calendar.js in /usr/share/postfixadmin/templates/vacation.tpl, but the file is missing in /usr/share/postfixadmin/.

The same problem exists in postfixadmin_3.0.2-1_all.deb

Quick fix: copy /usr/share/postfixadmin/users/calendar.js to /usr/share/postfixadmin/calendar.js

In postfixadmin-3.1.tar.gz everything is ok.

With kind regards
Hannes

**Comment by DavidGoodwin** [comment]
I think the problem would/should exist in all installations - not just the .deb....

A better fix is to remove users/vacation.php and redirect the user to /vacation.php .... 

or find a clever way to autodiscover some sort of base href value for the app ... so the javascript file can be given an absolute path.
