### ISSUE TITLE
Invalid link on postfixadmin github front page

### ISSUE THREAD

**Issue by neuffer** [postfixadmin/postfixadmin#532]
The link below should either be https://sourceforge.net/projects/postfixadmin/ or https://postfixadmin.sourceforge.io/ or http://postfixadmin.sf.net
![Screenshot_2021-08-23_16-26-10](https://user-images.githubusercontent.com/16861599/130465837-6755160f-d21a-459d-aaba-7e1cfccff739.png)

**Comment by DavidGoodwin** [comment]
Well spotted; thank you!

I'm sure there will be other instances of that invalid link - but I've changed the github 'about' one at least.

David.

**Comment by neuffer** [comment]
If we find more,we'll change them.
