### ISSUE TITLE
kubernetes: POSTFIXADMIN_ENCRYPT=SHA512-CRYPT and other environment variables

### ISSUE THREAD

**Issue by volker-raschek** [postfixadmin/postfixadmin#534]
Hi, 
I am currently writing a helm chart for kubernetes and I get some struggle with the environment variable `POSTFIXADMIN_ENCRYPT` - documented [here](https://github.com/postfixadmin/docker#no-configlocalphp--no-existing-setup).

I defined `POSTFIXADMIN_ENCRYPT=SHA512-CRYPT` and get the following error messages over the setup menue. 

![Screenshot 2021-08-29 at 14-01-14 Postfix Admin - Setup](https://user-images.githubusercontent.com/18311012/131249650-3e734a78-d107-4257-8c4c-eca9fe470056.png)

In the section "host environment checking" seems to be the environment variable correct, but still I get some error messages. What is the right value for `POSTFIXADMIN_ENCRYPT`?

Furthermore, I don't know why I get a warning? I defined via `POSTFIXADMIN_DB_TYPE=pgsql` the database backend type. So no warning should not be displayed. 

Lastly a note, the environment variables are insufficiently documented. For example, in the docker project there is no mention of `POSTFIXADMIN_DB_HOST` and `POSTFIXADMIN_DB_PORT`.

**Comment by DavidGoodwin** [comment]
does `php_crypt:SHA512-CRYPT` work ?

**Comment by DavidGoodwin** [comment]
.... -e POSTFIXADMIN_ENCRYPT="sha512.b64" ..... will work if you want a SHA512-CRYPT password that's also base64 encoded.

.... -e POSTFIXADMIN_ENCRYPT="php_crypt:SHA512" will work if you want a SHA512-CRYPT password that's comparable to what PHP's crypt function will create (from memory, i think it's hex encoded?)

.... -e POSTFIXADMIN_ENCRYPT="dovecot:SHA512-CRYPT" .... should also work, but will depend upon 'doveadm pw' working, which often isn't the case on newer variants of Linux / dovecot.

**Comment by DavidGoodwin** [comment]
the sqlite warning is because the code detected that you had the sqlite extension installed, but didn't have it as your specified database backend. I'm not sure why this is the case - it seems like an unnecessary warning.
