### ISSUE TITLE
vacation.pl unusable on Debian Stretch - no package libmail-sender-perl

### ISSUE THREAD

**Issue by ondrej-zary** [postfixadmin/postfixadmin#54]
libmail-sender-perl package was removed from Debian Stretch, probably because Mail::Sender module is deprecated. This makes vacation.pl unusable on Debian Stretch.
Please update vacation.pl script to use a supported module to send mails.

**Comment by DavidGoodwin** [comment]
see https://github.com/postfixadmin/postfixadmin/pull/49

**Comment by DavidGoodwin** [comment]
and https://github.com/postfixadmin/postfixadmin/pull/61

**Comment by DavidGoodwin** [comment]
This should now be fixed - as of https://github.com/postfixadmin/postfixadmin/commit/d98e83e62445a77c54bff5aa2992acc700dd830c
