### ISSUE TITLE
3.3.10 has been retagged

### ISSUE THREAD

**Issue by dvzrv** [postfixadmin/postfixadmin#544]
Hi! I'm packaging postfixadmin for Arch Linux.

Downstream I have received this bug report in regards to a mismatch in the reported file checksums for the release tarball:
https://bugs.archlinux.org/task/72215

The previously downloaded tarball indeed differs from the current one:

```
$ diff -ruN postfixadmin-postfixadmin-3.3.10/ old_tarball/postfixadmin-postfixadmin-3.3.10
diff -ruN postfixadmin-postfixadmin-3.3.10/config.inc.php old_tarball/postfixadmin-postfixadmin-3.3.10/config.inc.php
--- postfixadmin-postfixadmin-3.3.10/config.inc.php     2021-08-17 16:08:20.000000000 +0200
+++ old_tarball/postfixadmin-postfixadmin-3.3.10/config.inc.php 2021-08-09 10:41:35.000000000 +0200
@@ -696,7 +696,7 @@
 //More details in README.password_expiration
 $CONF['password_expiration'] = 'YES';

-$CONF['version'] = '3.3.10';
+$CONF['version'] = '3.3.9';

 // If you want to keep most settings at default values and/or want to ensure
 // that future updates work without problems, you can use a separate config
diff -ruN postfixadmin-postfixadmin-3.3.10/public/viewlog.php old_tarball/postfixadmin-postfixadmin-3.3.10/public/viewlog.php
--- postfixadmin-postfixadmin-3.3.10/public/viewlog.php 2021-08-17 16:08:20.000000000 +0200
+++ old_tarball/postfixadmin-postfixadmin-3.3.10/public/viewlog.php     2021-08-09 10:41:35.000000000 +0200
@@ -69,15 +69,15 @@

     $where = [];
     $params = [];
-    if ($fDomain) {
+    if($fDomain) {
         $where[] = 'domain = :domain' ;
         $params['domain'] = $fDomain;
     }

     $where_sql = '';
-    if (!empty($where)) {
+    if(!empty($where)) {
         $where_sql = 'WHERE ' . implode(' AND ', $where);
-    }
+    }

     $query = "SELECT timestamp,username,domain,action,data FROM $table_log $where_sql ORDER BY timestamp DESC LIMIT $page_size";
```

This is obviously a trivial change to add the correct version number and to fix formatting.
However, please do not retag existing versions, but rather just create a new version, as retagging breaks downstream integration and reproducibility of packages. Additionally, each time this happens, it creates churn on the packagers to figure out what happened to the upstream (a supply chain attack may be in action). Thanks for your consideration! :)

**Comment by DavidGoodwin** [comment]
Hello - Thanks for reporting this. 

I know I did retag one build in the recent past .... I wasn't aware of the automated builds / problems it'd create (in my mind, I'm just updating github!) .... so consider me 'told off' and lesson learnt !

**Comment by dvzrv** [comment]
@DavidGoodwin Haha, no worries. :)
These things happen from time to time (and many upstreams are not necessarily aware of how integrated their projects are somewhere else).
