### ISSUE TITLE
vacation.pl - problem with status 255

### ISSUE THREAD

**Issue by marasek12345** [postfixadmin/postfixadmin#546]
Hi, i configured vacation.pl with manual file INSTALL.TXT .
Incomming message is in mailbox, but responder is not sending respone.

In log i have:

 status=bounced (Command died with status 255: "/var/spool/vacation/vacation.pl". Command output: Global symbol "$email_from" requires explicit package name (did you forget to declare "my $email_from"?) at /var/spool/vacation/vacation.pl line 500. Global symbol "$email_from" requires explicit package name (did you forget to declare "my $email_from"?) at /var/spool/vacation/vacation.pl line 502. Global symbol "$email_from" requires explicit package name (did you forget to declare "my $email_from"?) at /var/spool/vacation/vacation.pl line 508. Type of arg 1 to Try::Tiny::finally must be block or sub {} (not reference constructor) at /var/spool/vacation/vacation.pl line 533, near "}" Type of arg 1 to Try::Tiny::try must be block or sub {} (not reference constructor) at /var/spool/vacation/vacation.pl line 533, near "}" Execution of /var/spool/vacation/vacation.pl aborted due to compilation errors. )

Can someone help me , please ?

**Comment by DavidGoodwin** [comment]
Ah - you're using vacation.pl from 'master' ....  the above should fix it.

**Comment by marasek12345** [comment]
ok, thanks.
Now i have 
Command output: Cannot create logfile : /var/log/vacation.log at /var/spool/vacation/vacation.pl line 141.

**Comment by DavidGoodwin** [comment]
lazy approach -

```
touch /var/log/vacation.log
chown vacation /var/log/vacation.log
```

then try again.

**Comment by marasek12345** [comment]
It's work perfectly, You are my hero ;)
