### ISSUE TITLE
Postfixadmin doesn't work

### ISSUE THREAD

**Issue by raspifr** [postfixadmin/postfixadmin#549]
Hello.

Since I have migrated to the last MariaDB version (v10.3.29) my postfixadmin doesn't work anymore.

When I want to go to postfixadmin I receive an HTTP error 500. On apache logs I can see "SQLSTATE[HY000] [2002] Connection refused" but when I do a "mysql -u postfixadmin -p" with postfixadmin password I can connect to MariaDB.

I first thought that I have not the goot postfixadmin release so I tried to upgrade it with the last available release (v3.3.8). But when I do the setup I have the following issues:
Errors (MUST be fixed)
⛔Database connection string : mysql:host=DBHOST;dbname=postfixadmin;charset=UTF8
⛔Problem connecting to database, check database configuration ($CONF['database_*'] entries in config.local.php)
⛔SQLSTATE[HY000] [2002] Connection refused

I don't understand where is the issue.

If someone can help me.
Thanks.

**Comment by DavidGoodwin** [comment]
where is 'DBHOST' ? Do you need an entry in /etc/hosts ?

If you're running that mysql command OK, then you probably need to set `$CONF['database_host'] = 'localhost'; `

(I don't think this is a postifxadmin problem - i think you're problem is that mariadb is no longer listening on tcp/ip or something like that .... do you see something listening on port 3306 when you do 'netstat --tcp -lpn` ?)

**Comment by raspifr** [comment]
MariaDB is on my NAS accessible on port 3307, postfixadmin URL is accessible by my web server. So database_host must be "DBHOST".
DBHOST have an entry in /etc/hosts on my NAS and my web server.

**Comment by DavidGoodwin** [comment]
but `Database connection string : mysql:host=DBHOST;dbname=postfixadmin;charset=UTF8` ?

that doesn't look like what I'd expect if you're using a custom port.

**Comment by raspifr** [comment]
And it's strange.
When I run setup I see:
Information
✅ Database connection configured OK (using PDO mysql:host=DBSERV;dbname=postfixadmin;charset=UTF8)

AND
Errors (MUST be fixed)
⛔Database connection string : mysql:host=DBSERV;dbname=postfixadmin;charset=UTF8

**Comment by frankofno** [comment]
running in the same problem on rocky linux
with the config

<?php
$CONF['configured'] = true;
$CONF['database_type'] = 'mysqli';
$CONF['database_host'] = 'localhost';
$CONF['database_port'] = '3306';
$CONF['database_user'] = 'postfixadmin';
$CONF['database_password'] = 'mypassword';
$CONF['database_name'] = 'postfixadmin';
$CONF['setup_password'] = 'thehash'

-- ERROR
﻿    ⛔Database connection string : mysql:host=localhost;port=3306;dbname=postfixadmin;charset=UTF8
    ⛔Problem connecting to database, check database configuration ($CONF['database_*'] entries in config.local.php)
    ⛔could not find driver
