### ISSUE TITLE
MySQL PDO URL constructed incorrectly

### ISSUE THREAD

**Issue by karolyi** [postfixadmin/postfixadmin#553]
Hey,

I connect to an outside host (other than localhost) from the `config.inc.php`. When doing that, I got the following error from `setup.php`:

```php
Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /usr/local/www/postfixadmin/functions.inc.php:1741
Stack trace:
#0 /usr/local/www/postfixadmin/functions.inc.php(1741): PDO->__construct('mysql:mysql:hos...', 'mail-sql', 'hiddenpassword', Array)
#1 /usr/local/www/postfixadmin/functions.inc.php(1915): db_connect()
#2 /usr/local/www/postfixadmin/functions.inc.php(1865): db_query('SELECT * FROM `...', Array)
#3 /usr/local/www/postfixadmin/public/setup.php(406): db_query_all('SELECT * FROM `...')
#4 {main}
  thrown in /usr/local/www/postfixadmin/functions.inc.php on line 1741
```

Upon diving into the code, I noticed that the PDO string is incorrectly constructed, it starts with `mysql:mysql:` whereas it should only start with a single `mysql:`.

Either you have to replace `$dsn = '';` in line [1613](https://github.com/postfixadmin/postfixadmin/blob/d6f9694d89b643f45d597ad8b743b2e57b4c6185/functions.inc.php#L1613), or you have to remove the extra `mysql:` in line [1617](https://github.com/postfixadmin/postfixadmin/blob/d6f9694d89b643f45d597ad8b743b2e57b4c6185/functions.inc.php#L1617). One of these will solve the issue.

For now it works at my server by manually correcting it, but I'd like to have it working from the packaged version too.

**Comment by DavidGoodwin** [comment]
Thank you for reporting this!

**Comment by karolyi** [comment]
Can we have a release of this, please?

**Comment by DavidGoodwin** [comment]
You're looking for a v3.3.x release ? 

(I  think the commit that's necessary is f8c8dcf52046b93017b4fbc7039d83905b673bfa )

**Comment by karolyi** [comment]
Yes.

Looking at the releases, the latest happened in last August, before this bug got fixed. Before I let the FreeBSD maintainers know that there was a bug that has been fixed with a new release, there has to be a release that actually contains the bugfix. :)

(btw this issue was closed by a commit that fixed this)

**Comment by DavidGoodwin** [comment]
In the 3.3 branch, I added the same 'bug' in ef4ac3ce4baad0fac09ad74803d68b987db9d485 - and fixed it in 4c0983f899dfcef39dade56a5ed6022b3528a90c- but neither changeset has been in a 3.3.x release yet.

there are a few changes in the 3.3 branch which haven't yet been released - e.g. better php8 support when using crypt() ( https://github.com/postfixadmin/postfixadmin/issues/547 and #549 (database_port config) which triggered #553

**Comment by karolyi** [comment]
This is nice, thank you.

**Comment by karolyi** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=262297
