### ISSUE TITLE
PHP and page errors due to commits after d3bc1551 

### ISSUE THREAD

**Issue by heliosyne** [postfixadmin/postfixadmin#554]
Postfixadmin gives the following errors with HEAD:

`PHP message: PHP Warning:  require_once(/usr/local/www/pfa-git/vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/www/pfa-git/common.php on line 3`
`PHP message: PHP Fatal error:  require_once(): Failed opening required '/usr/local/www/pfa-git/vendor/autoload.php' (include_path='.:/usr/local/share/pear') in /usr/local/www/pfa-git/common.php on line 3`

Commit 654a19da is the last version where login.php and setup.php will even load, but I cannot login due to a regression in password hash support introduced with commit 192ef873, indicated by this error on the setup.php page:

`Password Hashing - attempted to use configured encrypt backend (php_crypt:BLOWFISH::{BLF-CRYPT}) triggered an error: Unsupported hashing scheme / algorith : PHP_CRYPT:BLOWFISH::{BLF-CRYPT}`

If I checkout 654a19da and rollback just common.php and functions.inc.php to d3bc1551, I am able to login to the app, add/edit/delete admins, domains, and aliases, but I'm not confident that is a complete fix. I'm using a PostgreSQL database, so the MySQL PDO string bug from issue #553 doesn't affect me.

To be clear, these are the commands I use to get a working application:

`git checkout 654a19da` 
`git diff 654a19da..d3bc1551 common.php functions.inc.php | git apply`

**Comment by DavidGoodwin** [comment]
Hi @heliosyne - 

https://github.com/postfixadmin/postfixadmin/blob/master/INSTALL.TXT#L60

after 3d231a54a2c021477b900ce7cbe11bf43af60312 (merging of the feature-improve-pacrypt branch) there's been a dependency on running 'composer'. There's an 'install.sh' script that I added (see https://raw.githubusercontent.com/postfixadmin/postfixadmin/master/install.sh ) 

I'll update the CHANGELOG to reflect this to make it more obvious !

**Comment by heliosyne** [comment]
I'll have to tie that into a package-management system that already creates template_c and installs necessary PHP extensions. A further requirement is the ability to install and configure the app *without* internet access.

When you say "downloads PHP libraries", what is being downloaded?

**Comment by heliosyne** [comment]
Also, if you could differentiate between build/install-time dependencies and run-time dependencies, that would also be helpful.

**Comment by DavidGoodwin** [comment]
what's downloaded -> currently https://github.com/postfixadmin/pacrypt - but it would be a good idea to also do Smarty through composer too.
