### ISSUE TITLE
site_url in config.inc.php should be commented, not set to null by default

### ISSUE THREAD

**Issue by heliosyne** [postfixadmin/postfixadmin#556]
I get the following error when loading any page:

PHP message: Config::read(): attempt to read undefined config option "site_url", returning null

I don't set site_url in config.local.php, so the value in config.inc.php takes effect. It looks like PHP doesn't like it being set to null, but the config item can just not exist. Commenting line 724 of config.inc.php instead of setting it to null makes the error go away.

**Comment by DavidGoodwin** [comment]
Hi - You've been busy testing; thank you :-) 

A better change might be to do this in functions.inc.php -
```
diff --git a/functions.inc.php b/functions.inc.php
index 5c16f068..6cf2bfb9 100644
--- a/functions.inc.php
+++ b/functions.inc.php
@@ -2392,7 +2392,7 @@ function getRemoteAddr()
  */
 function getSiteUrl(array $server = []): string
 {
-    if (Config::has('site_url')) {
+    if (is_string(Config::read('site_url'))) {
         $url = Config::read_string('site_url');
         if (!empty($url)) {
             return $url;

```

**Comment by DavidGoodwin** [comment]
the problem is/was that Config::has(...) returns true if the array key exists, regardless of value .... the code then went on to try and read a string out of a null value... and raises a PHP warning.

**Comment by heliosyne** [comment]
That fixed it. Thanks!

**Comment by heliosyne** [comment]
Nope, I spoke too soon on this. I think it's the initial Config::read() itself that just doesn't like config options returning null.

**Comment by heliosyne** [comment]
Ya that looks like it has it fixed now
