### ISSUE TITLE
Setup shows "Unsupported hashing scheme / algorith" error

### ISSUE THREAD

**Issue by heliosyne** [postfixadmin/postfixadmin#557]
I get this error after logging into setup.php:

Password Hashing - attempted to use configured encrypt backend (php_crypt:BLOWFISH::{BLF-CRYPT}) triggered an error: Unsupported hashing scheme / algorith : PHP_CRYPT:BLOWFISH::{BLF-CRYPT}

I did notice that the comments in config.inc.php say "BLOWFISH", but the pacrypt readme.md says BLF-CRYPT, but the result was the same:

Password Hashing - attempted to use configured encrypt backend (php_crypt:BLF-CRYPT::{BLF-CRYPT}) triggered an error: Unsupported hashing scheme / algorith : PHP_CRYPT:BLF-CRYPT::{BLF-CRYPT}

Digging into functions.inc.php and Crypt.php, it looks like postfixadmin passes the unaltered value of $CONF['encrypt'] to the Crypt constructor, but that function is looking for just the crypt method string (i.e., BLF-CRYPT)?

**Comment by heliosyne** [comment]
I read through the code enough to figure out I just need to set $CONF['encrypt'] = 'BLF-CRYPT', so I'm guessing this is an issue of config.inc.php needing updated comments?

**Comment by DavidGoodwin** [comment]
Thanks for pointing this out - we should continue to support PHP_CRYPT:BLOWISH .... etc - the intention was existing configuration would continue to work without change..... I'll look at fixing this soon.

**Comment by DavidGoodwin** [comment]
4bc3e1464c646c9db13614d23ce364648977e954

**Comment by DavidGoodwin** [comment]
89f3ba5387e4ea9d325f132b120524c6104309bf

**Comment by DavidGoodwin** [comment]
git
