### ISSUE TITLE
CamelCase Results in Error when using SQL-Configuration 

### ISSUE THREAD

**Issue by jwacalex** [postfixadmin/postfixadmin#559]
Good Nighttime,
when I'm using some emails with camel case e.g. ``CamelCase@ACMEinc.example``, postfixadmin should use at any place the lowercase representation of this email. right now, the SQL configuration for postfix is a strong string match.

**Comment by DavidGoodwin** [comment]
I think this is a PostfixAdmin only problem - and only when you're using PostgreSQL (I'll guess).

I don't think it's a problem for delivery of emails to the alias/mailbox (for me, Postfix seems happy doing a mailbox lookup regardless of the query case - `postmap -q foo@example.com /etc/postfix/virtual_mailbox_maps.cf` )

MySQL is case insensitive by default, and I suspect that has carried through into the codebase.

**Comment by heliosyne** [comment]
Postfix case-folds database lookup strings in all of its table-driven mechanisms, so PostfixAdmin can be safely modified to do the same.

**Comment by jwacalex** [comment]
I've tried to switch to MySQL to check if there is the same issue, when I'm try to send an email i'm getting the following issue
``<CamelCase@ACMEinc.localhost>: Sender address rejected: not owned by user camelcase@acmeinc.localhost ``

**Comment by DavidGoodwin** [comment]
@jwacalex I take you've checked there is an alias entry for the mailbox?

**Comment by jwacalex** [comment]
@DavidGoodwin there is no alias entry for this domain

**Comment by DavidGoodwin** [comment]
i thought all mailboxes needed an alias for some strange postfix related reason?

**Comment by jwacalex** [comment]
@DavidGoodwin that sounds strange, if it's mandatory those aliases should be mapped in via config

**Comment by jwacalex** [comment]
I'll close this issue since it s not CamelCase related but more about a missing ``smtpd_sender_login_maps = $virtual_alias_maps``
see also #42
