### ISSUE TITLE
Allow to specify expected common name (CN) or disable peer name verification

### ISSUE THREAD

**Issue by davidebeatrici** [postfixadmin/postfixadmin#562]
The feature would allow to connect through TLS/SSL to an SMTP server running on the same host.

Issue:

```
postfix/smtpd[65726]: connect from localhost[127.0.0.1]
postfix/smtpd[65726]: lost connection after STARTTLS from localhost[127.0.0.1]
postfix/smtpd[65726]: disconnect from localhost[127.0.0.1] starttls=1 commands=1
```

```
PHP message: PHP Warning:  stream_socket_enable_crypto(): Peer certificate CN=`<FQDN>' did not match expected CN=`localhost'
```

Workaround as of commit e0c9939f8883ccca4b8beca21ae276ba1cdc2020:

```patch
--- a/functions.inc.php
+++ b/functions.inc.php
@@ -1510,6 +1510,7 @@ function smtp_mail($to, $from, $data, $password = "", $body = "")
             smtp_get_response($fh);
 
             stream_set_blocking($fh, true);
+            stream_context_set_option($fh, 'ssl', 'verify_peer_name', false);
             stream_socket_enable_crypto($fh, true, STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT);
             stream_set_blocking($fh, true);
         }
```

Related: roundcube/roundcubemail#7514

**Comment by DavidGoodwin** [comment]
Assuming you have a server that's _m̀ail.example.com_ and it has an SSL cert installed for _m̀ail.example.com_ then does it work if you configure `$CONF['smtpd_server'] = 'mail.example.com';` ?

Turning off peer name verification is OK - but it does leave you open to some sort of man-in-the-middle attack.

**Comment by davidebeatrici** [comment]
In my case it works because I'm not behind NAT, it's indeed better than disabling peer name verification.
