### ISSUE TITLE
Vacation calendar first day of the week

### ISSUE THREAD

**Issue by tempixx** [postfixadmin/postfixadmin#564]
Is there a way to configure the first day of the week (Monday instead of Sunday) in the vacation calndar view?
Many thanks,
Tibor

**Comment by DavidGoodwin** [comment]
postfixadmin uses this - https://getdatepicker.com/4/Options/

it doesn't feel like a locale would fix this (but perhaps I'm being ignorant).

and I don't think i can see a setting within it to do what you're asking for

**Comment by tempixx** [comment]
searched in the code for "getdatepicker" and then made following changes:
 $('#datetimepicker-fActiveFrom').datetimepicker({
            locale: 'de',

  $('#datetimepicker-fActiveUntil').datetimepicker({
            locale: 'de',

also changed the format:
 format: 'YYYY-MM-DD HH:mm',   (more common in the EU)

Works perfect! Thank you
