### ISSUE TITLE
Password hashing error

### ISSUE THREAD

**Issue by mnxamoto** [postfixadmin/postfixadmin#567]
Hello. Can't login as superadmin. The setup page has the following errors.
```
Errors (MUST be fixed)
⛔Password Hashing - attempted to use configured encrypt backend (SHA512-CRYPT) triggered an error: unknown/invalid $CONF["encrypt"] setting: SHA512-CRYPT
⛔You will have problems logging into PostfixAdmin.
```
Checked dovecot hash format

```
... # cat /etc/dovecot/dovecot-sql.conf.ext
...
default_pass_scheme = SHA512-CRYPT
...
```
Updated Dovecot to 2.3.14 and PostfixAdmin to 3.3.10 but it didn't help.

**Comment by DavidGoodwin** [comment]
Hi - Thanks for testing 'master' - does 422daf6c445d51efa94fcc4c1f98c23c7c87cd3b fix it for you?

**Comment by mnxamoto** [comment]
Strange, but I don't have such a file. Gentoo OS. 

```
... # ls /var/www/xxx/htdocs/postfixadmin/model/
AdminHandler.php          CliDelete.php  CliView.php           Login.php           Shell.php
AdminpasswordHandler.php  CliEdit.php    Config.php            MailboxHandler.php  VacationHandler.php
AliasdomainHandler.php    CliHelp.php    DomainHandler.php     PFAHandler.php
AliasHandler.php          CliScheme.php  FetchmailHandler.php  PFASmarty.php
... # webapp-config --list-installs -V
* Installs for nextcloud-21.0.0
*   /var/www/xxx/htdocs/nextcloud
* Installs for phpmyadmin-5.0.3
*   /var/www/xxx/htdocs/phpmyadmin
* Installs for postfixadmin-3.3.10
*   /var/www/xxx/htdocs/postfixadmin
* Installs for roundcube-1.5.0
*   /var/www/xxx/htdocs/roundcube
```
I downloaded and installed the version from github (https://github.com/postfixadmin/postfixadmin/archive/refs/tags/postfixadmin-3.3.10.tar.gz), but the error still remains and the file is missing.

**Comment by DavidGoodwin** [comment]
Ah - sorry - I assumed you were using 'master'.

Try  `$CONF['encrypt'] = "php_crypt:SHA512";` in your config file ?

If your things need a {SHA512-CRYPT} prefix you'll need : 

`$CONF['encrypt'] = "php_crypt:SHA512::{SHA512-CRYPT}";`

**Comment by mnxamoto** [comment]
Yes, thanks, the following line helped me
`$CONF['encrypt'] = "php_crypt:SHA512";`

**Comment by LucasFN1314** [comment]
> Ah - sorry - I assumed you were using 'master'.
> 
> Try `$CONF['encrypt'] = "php_crypt:SHA512";` in your config file ?
> 
> If your things need a {SHA512-CRYPT} prefix you'll need :
> 
> `$CONF['encrypt'] = "php_crypt:SHA512::{SHA512-CRYPT}";`

Thank you so much
