### ISSUE TITLE
Edit.php mailbox table quota field

### ISSUE THREAD

**Issue by dm-msk** [postfixadmin/postfixadmin#568]
If quota for mailbox over 2097.15 Mb (for example 8192 Mb ) web-interface show 2097.15 for those mailboxes, and if i save new password user mailbox crash with lower quota.

**Comment by dm-msk** [comment]
Postfix Admin 3.3.8

**Comment by dm-msk** [comment]
Postfix Admin 3.3.10 same issue

**Comment by dm-msk** [comment]
![image](https://user-images.githubusercontent.com/42002590/144806608-f6b750db-3115-42c5-b637-e706baa754f2.png)

**Comment by DavidGoodwin** [comment]
what do you mean when you say it crashes? is there an error message or something relevant in the web server log files?

I can set a mailbox to have a quota value like : 

```update mailbox set quota = 999999999999;```

and it seems to render OK -

![image](https://user-images.githubusercontent.com/203929/144927407-658324f5-6507-48b3-ac75-c68dc9bc891f.png)

**Comment by dm-msk** [comment]
Update works fine, but Quota field in postfixadmin edit windows show wrong quota size. In database I see right quota size.
It seems select quota field from mailbox table in edit.php work not as expected.

**Comment by dm-msk** [comment]
There are no errors in /var/log/apache2/apache-postfixadmin.error.log log files

**Comment by dm-msk** [comment]
![image](https://user-images.githubusercontent.com/42002590/145166651-5868fba2-ce03-4432-837d-8a678d78f879.png)

**Comment by dm-msk** [comment]
![image](https://user-images.githubusercontent.com/42002590/145168591-caa63518-8546-476e-b0c3-feca8b929119.png)

**Comment by dm-msk** [comment]
![image](https://user-images.githubusercontent.com/42002590/145180190-852d9909-ef87-4a81-8827-a861d81644f6.png)
Created new database, same issue

**Comment by dm-msk** [comment]
The problem from x32 OS and php. There are no problems with amd64

**Comment by DavidGoodwin** [comment]
oooooooooh! that explains quite a bit. Perhaps 'gmp' can be used to work around it? https://www.php.net/manual/en/book.gmp.php etc

**Comment by dm-msk** [comment]
`protected function read_from_db_postprocess($db_result) {
        foreach ($db_result as $key => $row) {
            if (isset($row['quota']) && is_numeric($row['quota']) && $row['quota'] > -1) { # quota could be disabled in $struct
                $db_result[$key]['quotabytes'] = $row['quota'];
                $db_result[$key]['quota'] = divide_quota( **(int)** $row['quota']); # convert quota to MB
            } else {
                $db_result[$key]['quotabytes'] = -1;
                $db_result[$key]['quota'] = -1;
            }
        }
        return $db_result;`

Obviously, it is impossible to accurately reproduce the function (int) for 64-bit numbers on a 32-bit system. (int) returns int; the best you can do on a 32-bit system for 64-bit numbers is to return a string. To work with 64 bit integers you need to run 64 bit PHP

**Comment by DavidGoodwin** [comment]
I'm going to mark this as 'wontfix' as I'm going to ignorantly assume there aren't going to be many people running on 32 bit hardware.
