### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by polymeer** [postfixadmin/postfixadmin#569]
Hello Friends,

please find [in attached zip file](https://github.com/postfixadmin/postfixadmin/files/7629405/its.zip) a simple, css variable coloured dark mode theme based on the standard bootstrap.css.

SHA256: `aee3b158988665430dddffb318a5d3c4bfb030f5ad963a7858be7121638e039b`

Just add
`'$CONF['theme_css'] = 'css/its.css';`
to your 
`config.local.php`
or rename as well the css and upload to
`/path-to-your-postfixadmin/public/css/`

**Comment by DavidGoodwin** [comment]
![image](https://user-images.githubusercontent.com/203929/144227218-d6335db9-1a62-4b48-900c-c03dca9d4012.png)

Thanks for the CSS file - I'm not sure I'm a fan of grey on black, but I'll merge it in - thank you!
