### ISSUE TITLE
MIssing postfix.admin logo and mail png on opening screen

### ISSUE THREAD

**Issue by kabigears** [postfixadmin/postfixadmin#57]
When I use versions higher than 2.92 the postfix.admin logo and the large mail icon png's do not display. I can login and all seems fine, but I just cannot get these pngs to display.

Below is the interface I get with postfix admin v3.1

![image](https://user-images.githubusercontent.com/15864463/28164129-3aba9874-6811-11e7-9c6f-fa2abf9a328a.png)

**Comment by cboltz** [comment]
Can you please check your access_log or error_log to find out where PostfixAdmin expects the images?

Also, how did you install? Tarball? RPM? Deb? git clone?

**Comment by kabigears** [comment]
This is from the tar ball. No errors in errors.log, but in access.log getting 404 response. The images are in <document root>/images

-rw-rw-r--  1 apache apache  4293 Jun 26 04:02 logo-default.png
-rw-rw-r--  1 apache apache 12395 Jun 26 04:02 mail_bg.gif

192.168.1.41 - - [14/Jul/2017:11:35:31 +1000] "GET /images/logo-default.png HTTP/1.1" 404 221 "http://mailadmin.servnet.net/login.php" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0" (-)
192.168.1.41 - - [14/Jul/2017:11:35:31 +1000] "GET /css/calendar.css HTTP/1.1" 304 - "http://mailadmin.servnet.net/css/default.css" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0" (-)
192.168.1.41 - - [14/Jul/2017:11:35:31 +1000] "GET /images/mail_bg.gif HTTP/1.1" **404** 216 "http://mailadmin.servnet.net/css/default.css" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0" (-)

**Comment by cboltz** [comment]
Strange - the locations in your log lines look correct, and the tarball (checked in 3.1) also has them at the expected place.

Even more strange - 404 errors typically cause a line in the error log, so I'm surprised that you don't have any.

Wild guess - do you have an `Alias /images /some/where` (or `ProxyPass /images ...`) somewhere in your apache config that might hide PostfixAdmin's images directory? If in doubt, `grep -r images /etc/apache2` ;-)

**Comment by kabigears** [comment]
I had a very old Alias /images in mod.dav that caused the problem. Thanks for the hint.
