### ISSUE TITLE
INSTALL.TXT references 0 byte file

### ISSUE THREAD

**Issue by yajrendrag** [postfixadmin/postfixadmin#570]
In step 1 of the INSTALL.TXT instructions, the download link is attempting to download an old (I assume it's old, the text reads as 3.2.10) release and moreover, downloads a 0 byte tgz file.  

Easy enough to workaround by just downloading directly from the release page, but wondering whether anything else is outdated in the instruction file...

**Comment by DavidGoodwin** [comment]
https://github.com/postfixadmin/postfixadmin/blob/422daf6c445d51efa94fcc4c1f98c23c7c87cd3b/INSTALL.TXT#L44

**Comment by DavidGoodwin** [comment]
I've changed the version to 3.3.10. The file did say immediately above the download link "Please check ... github ... url probably stale" ... :-) 

thanks for raising the issue though
