### ISSUE TITLE
does not work after upgrading Ubuntu to 20.04

### ISSUE THREAD

**Issue by Feika1981** [postfixadmin/postfixadmin#571]
SOLVED

only one error
Failed to read password from /usr/bin/doveadm pw ... stderr: doveadm: Error: net_connect_unix(/var/run/dovecot/stats-writer) failed: Permission denied\n, password: {CRAM-MD5}XXXXXXXXXXXXXXXXXXXXXXXXXXX\n ,

**Comment by Feika1981** [comment]
Sorry I didn't notice

* read/write access to /run/dovecot/stats-writer 
   * Fixable with: `usermod -aG dovecot www-data``

**Comment by swany7** [comment]
No, don't resolve for me... Any ideas maybe?

**Comment by DavidGoodwin** [comment]
https://github.com/postfixadmin/postfixadmin/blob/7b8d03cd7933d8ca487ef7d2bd65edda00ea26c9/DOCUMENTS/DOVECOT.txt#L140
