### ISSUE TITLE
Warning: Declaration of <......>Handler::init($id): bool should be compatible with PFAHandler

### ISSUE THREAD

**Issue by Gravity-87** [postfixadmin/postfixadmin#575]
I just upgraded my postfixadmin to v3.3.8. All went fine so far. The only thing is: There are warnings, I get, when I open some of the menu topics:

- https.//...../postfixadmin/list-virtual.php ....  (Menu: Virtual list/Virtual list)
**Warning: Declaration of AliasdomainHandler::init($id): bool should be compatible with PFAHandler::init(string $id): bool in /var/www/html/postfixadmin/model/AliasdomainHandler.php on line 7**

- https://....../postfixadmin/edit.php?table=mailbox (Menu: Virtual list/Add mailbox)
**Warning: Declaration of MailboxHandler::init($id): bool should be compatible with PFAHandler::init(string $id): bool in /var/www/html/postfixadmin/model/MailboxHandler.php on line 7**

- https://....../postfixadmin/edit.php?table=mailbox (Menu: Virtual list/Add alias-domain)
**Warning: Declaration of AliasdomainHandler::init($id): bool should be compatible with PFAHandler::init(string $id): bool in /var/www/html/postfixadmin/model/AliasdomainHandler.php on line 7**

When I click the "change password"-button:
 **Warning: Declaration of AdminpasswordHandler::init($id): bool should be compatible with PFAHandler::init(string $id): bool in /var/www/html/postfixadmin/model/AdminpasswordHandler.php _on line 4_**

I googled "a little bit around", but didn't found any helpful hints. Is there an explanation for these warnings and a possible solution to get rid of them?

My system:
Debian Stretch Linux in a vserver environment with MySQL and PHP7.

**Comment by DavidGoodwin** [comment]
The lazy fix is to change PHP's error_reporting level to suppress them.

Alternatively, try applying the changeset above.

**Comment by Gravity-87** [comment]
OK, I changed the error_reporting level in my php.ini 

from: error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
to this: error_reporting = (E_ALL ^ E_WARNING);

and now the warnings are gone. Thx.
