### ISSUE TITLE
update database not working

### ISSUE THREAD

**Issue by Blisk** [postfixadmin/postfixadmin#577]
I am trying to upgrade postfixadmin and when I try to update database doesn't work and don't know how to solve this
ERROR: The PostfixAdmin database layout is outdated (you have r1843, but r1844 is expected). Please run setup.php to upgrade the database. 

Updating database:

- old version: 1843; target version: 1844
  (If the update doesn't work, run setup.php?debug=1 to see the detailed error messages and SQL queries.)

updating to version 1844 (all databases)... 

ALTER TABLE `domain_admins` ADD COLUMN id int(11) not null auto_increment primary key
SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined

**Comment by DavidGoodwin** [comment]
what's the output from running ....

`mysql --defaults-extra-file=/etc/mysql/debian.cnf postfixadmin` (assuming you're on a debian based distro)

and then : 

`show create table domain_admins`
?

**Comment by DavidGoodwin** [comment]
(update 1844 adds the 'id' primary key to the domain_admins table, if you already have this, then I'd suggest just doing an `'update config set value = 1844 where name = 'version'` )

**Comment by Blisk** [comment]
I am on centos 8 and I have already changed 1843 to 1844
but now I have a problem because I can not login into roundcube also outlook doesn't work. After transfering all to latest version
before all works.

**Comment by DavidGoodwin** [comment]
if you're using phpmyadmin, you'd be best of just looking at the screen which shows you the table structure

**Comment by DavidGoodwin** [comment]
with roundcube not working - are you seeing any error(s) in the server logs? e.g. dovecot? 

Assuming you've not changed any passwords through postfixadmin, a failure to login would be more likely to be down to dovecot not being able to authenticate the connection.
