### ISSUE TITLE
Setup doesn't display background errors

### ISSUE THREAD

**Issue by Beatsleigher** [postfixadmin/postfixadmin#579]
I've upgraded my server, and postfixadmin has said that the backend database needs to be re-initialised.
I've upgraded my setup_password in config.local.php as per the instructions, then had to create a new superadmin for some reason.

Creating a new superadmin caused a "this admin already exists" error, so I manually deleted the entry from the database and tried again.

![image](https://user-images.githubusercontent.com/3124521/148136144-668c7241-499b-4585-b973-55606974ce21.png)

As you can see, the frontend doesn't show any errors. After trying to log in (unsuccessfully), I got the following error in the Apache error log:

```
[Wed Jan 05 00:05:07.791845 2022] [php7:notice] [pid 16283] [client <snip>:53251] Failed to read password from /usr/bin/doveadm pw -r 5 ... stderr: doveconf: Fatal: Error in configuration file /etc/dovecot/conf.d/10-ssl.conf line 12: ssl_cert: Can't open file /etc/letsencrypt/live/<snip>/fullchain.pem: Permission denied\n, password:  , referer: https://<snip>/setup.php
[Wed Jan 05 00:05:07.792047 2022] [php7:error] [pid 16283] [client <snip>:53251] PHP Fatal error:  Uncaught Exception: /usr/bin/doveadm pw -r 5 failed, see error log for details in /usr/share/postfixadmin/functions.inc.php:1059\nStack trace:\n#0 /usr/share/postfixadmin/functions.inc.php(1274): _pacrypt_dovecot()\n#1 /usr/share/postfixadmin/model/PFAHandler.php(563): pacrypt()\n#2 /usr/share/postfixadmin/public/setup.php(465): PFAHandler->save()\n#3 /usr/share/postfixadmin/public/setup.php(346): create_admin()\n#4 {main}\n  thrown in /usr/share/postfixadmin/functions.inc.php on line 1059, referer: https://<snip>/setup.php
```

These errors should be thrown in the frontend, possibly with a "please check server error logs for more info".

**Comment by DavidGoodwin** [comment]
Hi - thanks for reporting this - yes we should do a better check for those sort of errors.

**Comment by DavidGoodwin** [comment]
```
  if (empty($CONF['encrypt'])) {
        $error[] = 'Password hashing - $CONF["encrypt"] is empty. Please check your config.inc.php / config.local.php file.';
    } else {
        $info[] = 'Password hashing - $CONF["encrypt"] = ' . $CONF['encrypt'];

        try {
            $output = pacrypt('foobar');
            if ($output == 'foobar') {
                $warn[] = "You appear to be using a cleartext \$CONF['encrypt'] setting. This is insecure. You have been warned. Your users deserve better";
            }
            $info[] = 'Password hashing - $CONF["encrypt"] - hash generation OK';
        } catch (\Exception $e) {
            $error[] = "Password Hashing - attempted to use configured encrypt backend ({$CONF['encrypt']}) triggered an error: " . $e->getMessage();

            if (is_writeable($error_log_file)) {
                $err = "Possibly helpful error_log messages - " . htmlspecialchars(
                        implode("",
                            array_slice(file($error_log_file), -4, 3)  // last three lines, might fail miserably if error_log is large.
                        )
                    );

                $error[] = nl2br($err);
            }

            $error[] = "You will have problems logging into PostfixAdmin.";

            if (preg_match('/^dovecot:/', $CONF['encrypt'])) {
                $error[] = "Check out our Dovecot documentation at https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/DOVECOT.txt, specifically around '3. Permissions'.";
            }
        }
    }
````


So I think tihs should behave OK on 'master' ? what version are / were you using ?

**Comment by Beatsleigher** [comment]
I've noticed the error I'm experiencing is a known issue.
Perhaps a map containing known errors and a set of hints to point in the right direction would be useful?

**Comment by Beatsleigher** [comment]
I'm using PFA 3.3.5 on Ubuntu 21.04 (upgraded from 20.04.3). This is the latest version provided by apt; can I easily upgrade the installation with a git pull? Or are there any (known) side effects?

Or would it be easier to upgrade to 21.10 and use the packages provided there?

**Comment by DavidGoodwin** [comment]
You should be able to move to 'master' easily enough. I've made some significant changes to the pacrypt algorithm support - which should fix your pacrypt problem.

(I think the underlying problem is that the www-data user doesn't have permission to load various dovecot config files - there have been a few tickets about this in the past - see https://github.com/postfixadmin/postfixadmin/blob/def280bebf7d506fe0e3cca42a6ad8da0da6f9fd/DOCUMENTS/DOVECOT.txt#L140 and https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/HASHING.md )

**Comment by Beatsleigher** [comment]
Okay, I'll try moving to the master branch.
Concerning the permissions, I gathered as much, but so far I've not been able to fix it. No matter the permissions I've set (all but 777, basically), www-data can see the files (list directories and such), but cannot open the symlinks. I'm probably still missing something.

Interestingly enough, this was a non-issue before upgrading the server.

I'll report back!

**Comment by Beatsleigher** [comment]
Well I've had time to at least fix the error in the background. Missed a single directory in the long list of them last night; permissions have been fixed. www-data can access the certificates again.

I'll see if I can update PFA later on, after work.

**Comment by Beatsleigher** [comment]
My issue has been fixed, so I'll go ahead and close this.
