### ISSUE TITLE
Password Enhancements

### ISSUE THREAD

**Issue by CyberFoundry** [postfixadmin/postfixadmin#58]
All sane password hashing schemes in postfixadmin are available only via dovecotpw binary, which is  neither practical nor desirable at times for various reasons. I have implemented a small fix to the pacrypt function to improve it.
Alas it is not possible to use hash schemes like scrypt or blowfish for interoperability with other sw (e.g. dovecot or sogo) as the standard linux crypt function does not (and will not) support them.

Anyway, here is a quickfix to support sha512.b64 password scheme without the dovecot dependency (with cryptographically secure random function and compatibility for the old MD-5 Crypt password hashing scheme included for seamless transition) :

```php
... elseif (strcmp($CONF['encrypt'],'sha512.b64') == 0)  {
        if (!function_exists('random_bytes') || !function_exists('crypt') || !defined('CRYPT_SHA512') || !function_exists('mb_substr')) {
            die("sha512.b64 not supported!");
        }
        if (!$pw_db) {
            $salt = mb_substr(rtrim(base64_encode(random_bytes(16)),'='),0,16,'8bit');
            $password = '{SHA512-CRYPT.B64}'.base64_encode(crypt($pw,'$6$'.$salt));
        } else {
            $password="#Thepasswordcannotbeverified";
            if (strncmp($pw_db,'{SHA512-CRYPT.B64}',18)==0) {
                $dcpwd = base64_decode(mb_substr($pw_db,18,NULL,'8bit'),true);
                if ($dcpwd !== false && !empty($dcpwd) && strncmp($dcpwd,'$6$',3)==0) {
                    $password = '{SHA512-CRYPT.B64}'.base64_encode(crypt($pw,$dcpwd));
                }
            }
            elseif (strncmp($pw_db,'{MD5-CRYPT}',11)==0) {
                $dcpwd = mb_substr($pw_db,11,NULL,'8bit');
                if (!empty($dcpwd) && strncmp($dcpwd,'$1$',3)==0) {
                    $password = '{MD5-CRYPT}'.crypt($pw,$dcpwd);
                }
            }
        }
    }
```

Also the login function, should verify the passwords with hash_equals function and not standard string comparison:

```php
public function login($username, $password) {
        $result = false;
        $username = escape_string($username);
        $table = table_by_key($this->db_table);
        $active = db_get_boolean(True);
        $query = "SELECT password FROM $table WHERE " . $this->id_field . "='$username' AND active='$active'";
        $result = db_query ($query);
        if ($result['rows'] == 1) {
            $row = db_array ($result['result']);
            $crypt_password = pacrypt ($password, $row['password']);
            $result = hash_equals($row['password'], $crypt_password);
        }
        return $result;
}
```

Random_bytes (PHP 7) and hash_equals (PHP 5.6) functions are relatively new additions to PHP, but they can be easily implemented with polyfills for older PHP versions to maintain compatibility.
I can supply these as well if interested.

**Comment by alexis-** [comment]
That was very helpful (and timely), thank you.
It works as expected.

**Comment by snuggeman** [comment]
Also check out:  https://github.com/postfixadmin/postfixadmin/pull/52

**Comment by CyberFoundry** [comment]
Nice one. I have added a few comments to the code.

**Comment by DavidGoodwin** [comment]
I think we should merge this, but use random_bytes() (and perhaps bundle in https://github.com/paragonie/random_compat for compatibility) instead of the random_string() function etc.

**Comment by snuggeman** [comment]
Note that random_compat does not support PHP 5.4, and ends support for PHP 5.6 at Jan 1st 2019.
This makes it impossible to run on e.g. RedHat/CentOS 7 without modification.

**Comment by DavidGoodwin** [comment]
```Although this library should function in earlier versions of PHP, we will only consider issues relevant to supported PHP versions. If you are using an unsupported version of PHP, please upgrade as soon as possible.```

**Comment by DavidGoodwin** [comment]
(testing a centos7 docker image with php5.4 shows it works fine)

**Comment by snuggeman** [comment]
Unsupported by the PHP team, supported by RedHat (they backport any security fixes made to e.g. PHP)
