### ISSUE TITLE
Add the logo in the organization

### ISSUE THREAD

**Issue by Neustradamus** [postfixadmin/postfixadmin#581]
Dear @postfixadmin team,

Can you add the logo in the organization?
- https://github.com/postfixadmin

Thanks in advance.

**Comment by neuffer** [comment]
What do you mean exactly? Can you please elaborate?
I guess you wanted to provide a different link?

**Comment by Neustradamus** [comment]
The logo "image" on https://github.com/postfixadmin near:
```
PostfixAdmin
A web ui for managing mailboxes/aliases for Postfix
http://postfixadmin.sf.net
```

**Comment by neuffer** [comment]
you mean https://postfixadmin.sourceforge.io/images/postbox.png ?

**Comment by DavidGoodwin** [comment]
![image](https://user-images.githubusercontent.com/203929/148653524-605ce8cc-2868-44a7-aa57-f123c66b58cb.png)

 happy ?

The postbox logo isn't of a very high resolution, and I don't know where it has originally come from.

**Comment by Neustradamus** [comment]
@DavidGoodwin: It is better now, thanks! :)

When you will found in HQ, it will be perfect!
