### ISSUE TITLE
Keeping existing mailboxes when switching domains

### ISSUE THREAD

**Issue by strobilomyces** [postfixadmin/postfixadmin#583]
First of all, thanks to everyone involved with this project. (I asked this on the mailing list, but I haven't seen it appear yet, so I thought I'd put it here in the interest of time).

I have a bunch of users with virtual mailboxes associated with one domain. I'm in the process of migrating to a new domain. As far as PFA is concerned, I've added the new domain. I can forward from one to the other without any problems. The only snag is that the users (of course) have mailboxes full of stuff they'd rather not lose.

I thought (naively) that I would be able to move users and their associated mailboxes by editing the mailboxes and simply selecting the new domain, but that field isn't editable after the mailbox is created.

I've tried tinkering with the records through MySQL, manually changing the domain in the mailbox and alias tables. I've also tried manually moving mailboxes under /var/vmail, etc. to match the SQL modifications, but I'm really just guessing at this point.

My question is whether it's possible (using PFA) to keep the same mailbox for a user when switching domains, whether I have to do some magic with Postfix itself to get this to work, or whether it's simply not possible at all and I'm better off exporting/importing from old mailboxes on the old domain to new ones on the new.

Thanks for your time.

**Comment by DavidGoodwin** [comment]
Yes it should be possible. 

Yes - moving the mailbox to a different part of the filesystem so /var/vmail/whatever works should be fine. Assuming you're moving the directory you shouldn't have problems with file permissions or ownership as long as it's still under /var/vmail/...

PostfixAdmin probably won't let you change the mailbox path, as it's normally generated / based on the username / domain ....

**Comment by strobilomyces** [comment]
Leaving the mailbox path alone while moving the mailbox and updating the rest of the domain-specific fields in the database worked perfectly. Not exactly easy, but better than the alternative. Thanks for your help!
