### ISSUE TITLE
Using Log4perl incorrectly?

### ISSUE THREAD

**Issue by thowe** [postfixadmin/postfixadmin#586]
Since upgrading to the 4.2 version of the vacation script, logging doesn't work, and it gives this error message in the mail log:
"(delivered via autoresp service (Log4perl: Seems like no initialization happened. Forgot to call init()?))"

There's actually some mention of this in the Log4perl FAQ that might be related:
https://metacpan.org/dist/Log-Log4perl/view/lib/Log/Log4perl/FAQ.pm#Log4perl-complains-that-no-initialization-happened-during-shutdown!

**Comment by puck** [comment]
Hey,

I've hit this problem as well. The issue appears to be that the setting for $log_to_file was changed from defaulting to enabled, to disabled in 2009 in commit 6f8b25be64b820cbf6c7a504b77fc9ebc93d72a9 .

By default neither $syslog or $log_to_file is enabled, so you'll get that error. I've set `$log_to_file=1;` in my config file, and now I both have logging, and no longer get that error message.

**Comment by DavidGoodwin** [comment]
My perl is too rusty to figure out some sort of useful oneliner which would assign `$log_to_file` to 1 if `$log_file` was writeable, else set it to 0.... and then do the reverse for `$syslog`

**Comment by puck** [comment]
Ah ha, I missed that you'd created a commit to default to syslog. I just made a PR to log to a file it syslog is disabled and vacation.pl can write to the log.

https://github.com/postfixadmin/postfixadmin/pull/755

**Comment by DavidGoodwin** [comment]
Thanks .... I was hoping some sort of one liner ternary thingy could be done in perl - e.g.

`$our_syslog = ( -w $syslog_file ) ? 1 : 0; `

but I couldn't get the syntax right .. and your patch does a similar thing (if syslog is turned off).

**Comment by puck** [comment]
Yeah, I had similar to start with, but -w will only be true if the file exists and is writable. I thought I'd test various different scenarios before I pushed the commit. :)
