### ISSUE TITLE
php8.0 fcgi error

### ISSUE THREAD

**Issue by RobinDHBW** [postfixadmin/postfixadmin#590]
Hi, 
I set up a new webserver and installed postfix and postfixadmin. Unfortunately the apache webserver won't start with php-fcgi enabled. 
The logs says: 
`[Mon Jan 24 16:19:20.311510 2022] [proxy_fcgi:error] [pid 42240] [client 37.201.5.252:46065] AH01071: Got error 'PHP message: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /usr/share/postfixadmin/functions.inc.php on line 730'`

It seems, that there is a syntactical crash with some php code. Maybe this should be fixed for future releases. 

Current workaround ist to use php7.4.

**Comment by DavidGoodwin** [comment]
Hi - thanks for the bug report - I didn't think we had any of those string access types { .. } left to remove.

What version of PostfixAdmin are you using?

**Comment by RobinDHBW** [comment]
I just installed it by apt-get package. The server is an Ubuntu 20.04 system. 
Can i find the version number somewhere in the filesystem? postfix-cli ist not working either^^

**Comment by RobinDHBW** [comment]
Good Morning, 

Within this ticket the case is documented and the workaround should do it for most usecases  👍
I only rent a little vServer for my purposes, that ships with Ubuntu 20.04 - thing is though, that postfixadmin 3.2.1-3 is the version listet in the distros package lists: 
https://packages.ubuntu.com/search?keywords=postfixadmin&searchon=names&suite=focal&section=all 
So there may be some other users run into that problem^^ 

Whatever: My system is up and running since three weeks - no worries left 😎

Greetings from Badisch-Siberia - Germany, 
Robin
