### ISSUE TITLE
integration into mailing list manager

### ISSUE THREAD

**Issue by juhoffma** [postfixadmin/postfixadmin#598]
Hi,

does postfixadmin provide mailing list management? What is the recommended solution to use as a workaround for the current version?

Thanks

**Comment by juhoffma** [comment]
nudge

**Comment by DavidGoodwin** [comment]
it provides mailing list management in so far as you could have an alias with many mailboxes attached - e.g my@list.com => a@example.com,b@example.com,foo@bar.com

But it doesn't handle e.g. unsubscribe / subscription / archives etc etc - that's what people use mailman for.

**Comment by juhoffma** [comment]
Hi @DavidGoodwin 

Thanks for answering, this sounds more of an alias feature, isn't it? Mailing List Management also takes care of the ```reply-to``` header and adds information about subscription management.

Is there a way to integrate postfix admin with mailman, that does not break future upgrades?

kind regards

**Comment by DavidGoodwin** [comment]
@juhoffma I'd assume there is, but I've never run mailman so don't really know how it's configured/integrated .... sorry I can't help any more.

(I wouldn't expect anything would need doing from Postfixadmin's side - except perhaps having a different virtual transport configured for the mailman controlled list/domain? But I'm only speculating and should STFU at this point...)
