### ISSUE TITLE
HEAD

### ISSUE THREAD

**Issue by pedromorgan** [postfixadmin/postfixadmin#6]
Is this a definitive head we can fork off.. ??

I hate raising issues, but can we please migrate from SF to here.. and can help..

**Comment by palepurple** [comment]
Hi Pete - I'll keep it in sync with sf.net, so fork away....
I'm hoping we'll move off sf.net soon.
David

**Comment by pedromorgan** [comment]
Can help with BUGS migratin..

Basically..
Grap a few and just nuke honest...

I help a few migrate and believe me its like moving an office..
leave the lode shit there.. and new shiny and faster..

Make the jump please..
SF is slow a pain in the ass et all.. now its commerciall..

**Comment by pedromorgan** [comment]
Do me a favour guys,,

If your prepared to move, then I can set up the "page" at 
postfixadmin.github.com 
in same fashion as a recent project i help with..
ts2.sf.net

Basically ripping http://postfixadmin.sourceforge.net/
and into jekyll or alike..

Also same caper at revel.github.io..

Also there is script to move issues from sf.net to github....
in the end, github.issues becomes the mailing list kinda..

But lets move on can help..
create postfix.github.com and I can do some donkey work. .all via git of course..

**Comment by pedromorgan** [comment]
Working on idea here..
And I understand where we are coming from with postfix+admin..

http://pedromorgan.github.io/postfixadmin.github.io/

Its ruff.. but moving sf.wiki nto MD is plan..

pedro want a cool soltion

**Comment by DavidGoodwin** [comment]
http://postfixadmin.github.io/postfixadmin/
