### ISSUE TITLE
    ⚠ PHP Error log (error_log) is - /var/log/php-fpm/www-error.log, but is not writeable. Postfixadmin will be unable to log error(s)

### ISSUE THREAD

**Issue by frankofno** [postfixadmin/postfixadmin#601]
just created a new mailserver with postfix/dovecot on Linux kernel 5.16

i followed along my previous working setup line by line, still i end up with an error on the postfixadmin site, telling me:

`    ⚠ PHP Error log (error_log) is - /var/log/php-fpm/www-error.log, but is not writeable. Postfixadmin will be unable to log error(s)`

Any hint/ideas how i can get rid of that?

**Comment by DavidGoodwin** [comment]
Somehow making it writeable ?

e.g. `chmod 777 /var/log/php-fpm/www-error.log `

or avoid making it writeable by anyone, making it writable by just the webserver ... (depending on your platform, the php processes may not be running under the www-data group)

`chmod 774 /var/log/php-fpm/www-error.log `
`chgrp www-data /var/log/php-fpm/www-error.log`

**Comment by DavidGoodwin** [comment]
there might be something like selinux or php's open_basedir stuff blocking access to /var/log/php-fpm/...

**Comment by frankofno** [comment]
i've comment out 1 line in /etc/php-fpm.d/www.conf

`;php_admin_value[error_log] = /var/log/php-fpm/www-error.log`

By setting the semicolon before that, the error is gone.
