### ISSUE TITLE
admin can not manage all domains

### ISSUE THREAD

**Issue by frankofno** [postfixadmin/postfixadmin#605]
Allthough I have selected both available domains for the admin, when loggin in with that admin account only 1 domain can be managed.
logged in as superadmin shows 2 domains for the admin. Is this is a bug?

Screenshot:
![Screenshot 2022-03-20 at 22 14 02](https://user-images.githubusercontent.com/35775329/159186348-ca3e854c-b584-4b2c-aef5-bc370e6c2ca1.png)

**Comment by bnchdan** [comment]
Hi,

I don't have this problem.

prt scrn from non-superadmin 
![image](https://user-images.githubusercontent.com/30780133/159215805-e8a3e1c5-a085-4336-9b77-b4c9a6f16dc1.png)

**Comment by bnchdan** [comment]
@frankofno Do you have errors in logs?

**Comment by frankofno** [comment]
> @frankofno Do you have errors in logs?

so probably related to that error?
    ⚠ PHP Error log (error_log) is - /var/log/php-fpm/www-error.log, but is not writeable. Postfixadmin will be unable to log error(s)

Since everything else is working like it should, i did ignore that error loggin problem. not sure how i can get postfixadmin write to that log. I don't really want to disable selinux.

**Comment by DavidGoodwin** [comment]
@frankofno check what's in the `domain_admins` database table.  You should find the super admin has an domain: 'ALL' entry, while your other admin has their domains listed individually.

Are you using MySQL or PostgreSQL ? 

What does your domain_admins table contain for the admin who is having problems?

**Comment by frankofno** [comment]
> 
mariadb / sql database. 
The domain2.tld (which is not available for the admin) is set as backup MX server. Allthough it is listed in the domain_admin table the admin can not manage it. Does the backup setting affect this somehow?

+---------------------+----------------+---------------------+--------+----+
| username            | domain         | created             | active | id |
+---------------------+----------------+---------------------+--------+----+
| superadmin@dom.tld  | ALL            | 2022-03-14 09:39:15 |      1 |  1 |
| admin@domain.tld    | domain1.tld    | 2022-03-20 22:48:09 |      1 |  7 |
| admin@domain.tld    | domain2.tld    | 2022-03-20 22:48:09 |      1 |  8 |
+---------------------+----------------+---------------------+--------+----+

**Comment by DavidGoodwin** [comment]
Yes, I think so. The 'backup' domain will just accept any mail for the domain, and queue it for delivery to the real primary.... so it'd possibly make sense for it to not allow you to manage users/aliases for the domain.

**Comment by frankofno** [comment]
the thing is, i wanted to create the mailboxes on this backup server so dovecot dsync can run. Guess that's only possible for the superadmin then?
