### ISSUE TITLE
Missing dependency for broadcast-message.php 

### ISSUE THREAD

**Issue by KevenImbeault** [postfixadmin/postfixadmin#612]
Hi,

I had a problem recently when sending mail to domains through the broadcast-message.php page :

`[Fri Mar 25 11:52:13.271683 2022] [php7:error] [pid 18701] [client 104.192.16.9:53236] PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /var/www/postfixadmin/public/broadcast-message.php:75\nStack trace:\n#0 {main}\n  thrown in /var/www/postfixadmin/public/broadcast-message.php on line 75, referer: https://mailadmin.digicom.ca/broadcast-message.php`

It was cause by the missing mbstring extension for PHP 7.4, and it doesn't seem to be in the composer.json file, should it be added ?

**Comment by DavidGoodwin** [comment]
i suspect there should really be a check in setup.php as well

**Comment by DavidGoodwin** [comment]
hm, should be covered by setup.php already if I'm reading the code correctly.

**Comment by KevenImbeault** [comment]
My bad, it does in fact check if it is installed during setup.
Must have missed it somehow during installation !
