### ISSUE TITLE
Incorrect path in INSTRUCTIONS.TXT

### ISSUE THREAD

**Issue by kissumisha** [postfixadmin/postfixadmin#622]
On line 153:

/postfixadmin/setup.php

Should be:

/postfixadmin/**public**/setup.php

OR

setup.php should be in the base folder.

**Comment by DavidGoodwin** [comment]
Hi @kissumisha thanks for the bug report - I don't think we have a file called 'INSTRUCTIONS.TXT'. 

Did you mean INSTALL.TXT?

If so, version 3.3 has : 

https://github.com/postfixadmin/postfixadmin/blob/58e9538e6ac4be89f66729a9c4bd89821085768b/INSTALL.TXT#L153

but that's correct..... as further up you've set an Apache alias to 'mount' /path/to/postfixadmin/public as e.g. https://yourserver/postfixadmin ...
