### ISSUE TITLE
creating domain not visible in postfixadmin

### ISSUE THREAD

**Issue by Blisk** [postfixadmin/postfixadmin#625]
I can create domain but after that is not visible in postfixadmin
but I can see it in mysql database. And can not create it again because I get error can not add domain.
When I delete it from mysql database I can add it again but can't see it in postfixadmin
what can be wrong?
I use postfixadmin 3.3.5 and nginx

**Comment by DavidGoodwin** [comment]
Hi - What does your database show in the `domain_admins` table for the user in question?

**Comment by Blisk** [comment]
I have deleted all and make new installation and now it works
