### ISSUE TITLE
error: In bool: expected config password_expiration

### ISSUE THREAD

**Issue by muh2000** [postfixadmin/postfixadmin#626]
Fatal error: In bool: expected config password_expiration to be a string, but received a NULL in /model/Config.php on line 144

newest version it throws these errors

**Comment by DavidGoodwin** [comment]
What do you have set in your config for 'password_expiration' ?

What specific version of Postfixadmin are you referring to?

**Comment by muh2000** [comment]
nothing
i guess i must have omited one config change at somepoint.

**Comment by muh2000** [comment]
i tried to apply the DB update but failed at 
>ALTER TABLE domain ADD COLUMN password_expiry int DEFAULT 0;
>ERROR 1292 (22007): Incorrect datetime value: '0000-00-00 00:00:00' for column 'created' at row 1


i added: 
>$CONF['password_expiration'] = 'YES';
but is received 
>Fatal error: In bool: expected config password_expiration to be a string, but received a NULL in ... model/Config.php on line 144

**Comment by DavidGoodwin** [comment]
The code shouldn't fail if the config is not present/set.

What version of postfixadmin are you trying to use?

**Comment by DavidGoodwin** [comment]
the latest is 3.3.11 ; I'd suggest you try that :-) it should fix the MySQL issue at least.

**Comment by muh2000** [comment]
dont know how i installed that old version.

anyway with the current version it says: 

Fatal error: require_once(): Failed opening required '...postfixadmin/vendor/autoload.php' (include_path='.:/usr/share/php') in ....postfixadmin/common.php on line 3

**Comment by DavidGoodwin** [comment]
If you're using whatever is in the master/main branch, then run the ``install.sh` shell script - it'll fix that.

**Comment by muh2000** [comment]
Fatal error: Uncaught TypeError: Argument 1 passed to Config::setAll() must be of the type array, null given, called in ....../common.php on line 57

it seems to be unable to find the config

config is there 
permissions of the file seem apt

**Comment by DavidGoodwin** [comment]
does setup.php show anything - e.g a failure to read the config file?

**Comment by muh2000** [comment]
Fatal error: Uncaught TypeError: Argument 1 passed to Config::setAll() must be of the type array, null given, called in ....../common.php on line 57

it seems to be unable to find the config

config is there 
permissions of the file seem apt

**Comment by muh2000** [comment]
no
only the same error

**Comment by muh2000** [comment]
> does setup.php show anything - e.g a failure to read the config file?

well it spawns the same error.
