### ISSUE TITLE
md5crypt Password

### ISSUE THREAD

**Issue by kleprado** [postfixadmin/postfixadmin#627]
Hi,
My old password scheme are encrypted using md5crypt.
Password all looks like : `$1$e7740121$xxxxxxxxxxxxx`
Dovecot is well configured with MD5-CRYPT

After postfixadmin upgrade (now using last version : 3.4-dev), config.local.inc has the following parameter configured : 
`$CONF['encrypt'] = 'md5crypt';`

But when I modifiy a password, database is updated with a password which look like : `$2y$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxx` (blowfish scheme)
And of course, authentication does not work.

**Comment by DavidGoodwin** [comment]
ah, you're confusing 'md5crypt' with 'MD5-CRYPT' ... i think is the problem.

Change `$CONF['encrypt'] = "MD5-CRYPT";` and things might work?

**Comment by kleprado** [comment]
After having tested, `$CONF['encrypt'] = "MD5-CRYPT";` is the solution

Thanks for your help
