### ISSUE TITLE
editing the alias (destination) address of a mailbox does not update the "last modified" date

### ISSUE THREAD

**Issue by benjyamon** [postfixadmin/postfixadmin#629]
though it does make an entry in the logs.

**Comment by DavidGoodwin** [comment]
I can't replicate this - what version of PostfixAdmin are you using, and on what database?

**Comment by benjyamon** [comment]
We are running version 3.3.11 (via the FreeBSD ports tree) backed by MySQL database.

Clicking "edit" button for a mailbox and making any change there does update the "Last modified" column.

But clicking "Alias" button for a mailbox and making any changes there does not update the "Last modified" column here. . .

**Comment by DavidGoodwin** [comment]
the modified timestamp belongs to the alias, and not the mailbox... is that the problem?

**Comment by benjyamon** [comment]
hmmm but these mailboxes don't show in the gui under the alias section. (i know in the db every mailbox also has an alias.) 

are you saying that if/when you change the destination address of a mailbox, (not an alias address) it does update the "last modified"  column shown in the gui?

**Comment by DavidGoodwin** [comment]
When you change the destination address of a mailbox, you're actually changing the alias - and it's that alias that gets updated.


```
MariaDB [postfixadmin]> select * From alias where address = 'pickle@example.com' \G
*************************** 1. row ***************************
 address: pickle@example.com
    goto: something@example.com,pickle@example.com
  domain: example.com
 created: 2021-12-15 21:14:18
modified: 2022-07-12 20:54:50
  active: 1
1 row in set (0.001 sec)
```

corresponds to this : 


![image](https://user-images.githubusercontent.com/203929/178582860-36e6888d-6811-4f09-be1f-bd2c74a4adfe.png)

**Comment by benjyamon** [comment]
yeah i get it.  it's just too bad that making these sorts of changes to a mailbox  (i know, it's actually the alias under the hood - but in the gui it's the mailbox we're working with) doesn't update the "Last modified" column shown in the gui // associated with the mailbox (just in the db, associated with the alias associated with the mailbox. . .) 

but also not the end of the world! 

and viewing logs (or looking in the database for the associated alias) one can get a sense if when a user has done something like this and the "Last modified" column for the mailbox is just misleading ;)
