### ISSUE TITLE
User session stay only one time

### ISSUE THREAD

**Issue by StanByes** [postfixadmin/postfixadmin#634]
Hello I installed Postfixadmin to configure my mail server.

SYSTEM:
NGINX, PHP8.1 Fpm

I had the issue in #630 so I commented the part of code but I have a new issue.
The session "sessid" stay only one time, so after login I saw the main page but when I tried to go in another page, the website redirected me to the login page. I use a print_r to see the content of the SESSION and only "Array ( [PFA_token] => 08a4b4916cb5d1b7328191edf2ba379b [flash] => Array ( ) [lang] => fr )" appared after I tried to move to another page

I don't know if an issue with nginx, php or PostfixAdmin.

Have a nice day, StanByes

**Comment by DavidGoodwin** [comment]
PostfixAdmin sets a new PFA_Token value each time someone logs in (or fails to login).

It then uses the PFA_Token to validate any future form requests - with the hope that no attacker could possibly know it, so it protects you from CSRF attacks.

If your $_SESSION contents are changing from one page load to another, I can only think there's a problem with your server's backend session store (look for files in e.g. /var/lib/php/session on the server?) OR your browser isn't sending/receiving a cookie, so there's nothing to link up the backend session file with your browser.

**Comment by StanByes** [comment]
Okay, I will check my server and I'll give you news about this
Thank you

**Comment by StanByes** [comment]
The session file, which is create in /var/lib/php/sessions folder, contains only the PFA_token and not the sessid at each step (after login and go to another page)

**Comment by StanByes** [comment]
bump

**Comment by DavidGoodwin** [comment]
I don't have any further suggestions - I can only suggest you use your browsers network inspector and look at the cookie values sent around.

For me, I always have a cookie called 'postfixadmin_session' and the value of it remains stable.

postfixadmin_session=51205uhk0hhb1fouooq7m3l9sp

if i look in /var/lib/php/sessions i find a file like : 

sess_51205uhk0hhb1fouooq7m3l9sp

which contains something a bit like : 


PFA_token|s:32:"a2f70dd72ebd9xxxxxxxxxxxxa3024";lang|s:2:"en";sessid|a:2:{s:5:"roles";a:2:{i:0;s:5:"admin";i:1;s:12:"global-admin";}s:8:"username";s:21:"...............



I can only assume your browser is blocking the cookie / not sending it back. 

Or something is removing the Cookie HTTP header your browser should be sending through to the server.

Or your session storage isn't working ?
