### ISSUE TITLE
PW Change Silent Failure

### ISSUE THREAD

**Issue by repetty** [postfixadmin/postfixadmin#636]
Version:  Postfix Admin 3.4-dev

Tried to change the password of a locked account. I didn't know it was locked at the time and got no feedback.

At least two valid options:
1. Display warning that PW can't be changed on locked accounts.
2. Go ahead a change the PW on locked accounts.

**Comment by DavidGoodwin** [comment]
I'm fairly sure the password would be changed on a disabled account; are you expecting there to be a "Password changed, but note the account is locked" message?
