### ISSUE TITLE
PHP 8.1 - Invalid token (session timeout; refresh the page and try again?)

### ISSUE THREAD

**Issue by zolyyy** [postfixadmin/postfixadmin#637]
I use latest Postfixadmin 3.11 with PHP 8.1.7
If i try to login, this error:

Invalid token (session timeout; refresh the page and try again?)

- Session working good on my Ubuntu 20 server

**Comment by DavidGoodwin** [comment]
seen #632 ?

**Comment by DavidGoodwin** [comment]
can you try using the version of 3.3 from github ( try here : https://github.com/postfixadmin/postfixadmin/archive/refs/heads/postfixadmin_3.3.zip ) - there were some recent fixes for PHP 8.1 which may help

**Comment by zolyyy** [comment]
Only Chrome!!! Sorry Firefox working...

**Comment by DavidGoodwin** [comment]
If one browser works, then it shouldn't be a server side issue, and I'd be inclined to think your browser is blocking cookies for some reason? If you inspect the network requests, is Chrome sending the PHP session cookie to the server?

**Comment by DavidGoodwin** [comment]
See also #634 which feels like it may be related?

**Comment by zolyyy** [comment]
> If one browser works, then it shouldn't be a server side issue, and I'd be inclined to think your browser is blocking cookies for some reason? If you inspect the network requests, is Chrome sending the PHP session cookie to the server?

I try with Portable Chrome too... not working... and yes the cookie not working too.
