### ISSUE TITLE
DOCUMENTS/Password_Expiration.md recommends too many database permissions

### ISSUE THREAD

**Issue by cboltz** [postfixadmin/postfixadmin#640]
From looking at the script in DOCUMENTS/Password_Expiration.md, it seems to use a single SQL query:

`SELECT username,password_expiry FROM mailbox WHERE password_expiry > now() + interval $LOWER DAY AND password_expiry < NOW() + interval $INTERVAL DAY`

This means it only needs _read_ access to two quite harmless fields in the mailbox table.

IMHO the documentation should recommend to create a database user that only has `SELECT` permissions on `mailbox.username` and `mailbox.password_expiry`.

(Currently there's a note saying `enter a DB user that is allowed to access (read-write) your database` which looks wrong - the script only does the SELECT shown above, and therefore doesn't need write permissions. It also doesn't need to read more critical fields like the password.)

**Comment by DavidGoodwin** [comment]
It might have been quicker to fix the docs than create a ticket ;)
