### ISSUE TITLE
Alias active flag change doesn't respect current pagination

### ISSUE THREAD

**Issue by cricalix** [postfixadmin/postfixadmin#642]
Reproduction
==
* Open Postfixadmin
* Log in as super admin
* Domain List dropdown > Domains
* Select a domain to see the aliases
* Use the pagination selector (10-am, am-ba etc) to jump to a specific section of the list
* Observe that the URL updates to be list-virtual.php?limit=n&domain=selected.domain#aAliases
* Toggle the active flag for an alias by clicking the button in the Active column

Expected behaviour
==
* The alias active flag is changed
* The page displays the confirmation in the blue box
* The URL keeps the parameters, returning the user to where they were in the list

Observed behaviour
==
* The URL changes to just list-virtual.php, all parameters are lost
* The user has to click the pagination selector again to return to where they were

My use case is that I want to disable a bunch of aliases, and a lot of them happen to be on the same page. The behaviour of going back to the first alias page introduces extra clicks to the process.

**Comment by DavidGoodwin** [comment]
does that help?

**Comment by cricalix** [comment]
That change works if the row is edited with the edit button.
It does not work if the active flag is toggled with the active button.
Looks like active flag goes via activeedit.php; the same logic change in that file seems to sort it out.
Thanks :)
