### ISSUE TITLE
update-check.php doesn't return correct values

### ISSUE THREAD

**Issue by max312** [postfixadmin/postfixadmin#644]
http://postfixadmin.sf.net/update-check.php?version=3.3.xx

The update check url is returning an old version

**Comment by DavidGoodwin** [comment]
The problem is that the update-check.php script lives on sourceforge.

I wonder if there is a github API we could use instead to check for a new release?

**Comment by drdelaney** [comment]
Could possibly parse this URL for the latest version string and compare to what is locally installed?
This should offload all checking to github and the locally installed instance.
`https://api.github.com/repos/postfixadmin/postfixadmin/releases/latest`

**Comment by DavidGoodwin** [comment]
pull request welcome :)

**Comment by DavidGoodwin** [comment]
https://api.github.com/repos/postfixadmin/postfixadmin/releases might be better? 

ideally if we were running 3.2.1, we'd want to tell someone that there was a newer minor release available (e.g. 3.2.4), as well as a newer major release (3.3.10 or whatever it currently is)?

**Comment by DavidGoodwin** [comment]
update-check.php has been updated to cope with 3.3.11.....
