### ISSUE TITLE
Change ADDITIONS/postfixadmin-mailbox-postpassword.sh for dovecot >= 2.3.19

### ISSUE THREAD

**Issue by ean365** [postfixadmin/postfixadmin#646]
Minor issue for update or notice in ADDITIONS/postfixadmin-mailbox-postpassword.sh...
Dovecot finally got around to fixing a couple of issues with the `doveadm mailbox cryptokey password` command:

The following apply to dovecot versions >= 2.3.19 <--(can run `dovecot --version` to check it)

1. They fixed the `-O` flag such that it does not expect an argument.  So, the empty quotes `""` can be removed from the end of command line in ADDITIONS/postfixadmin-mailbox-postpassword.sh.

2. They appropriately added a second password confirmation (for when people change passwords using the command line -- you don't ever want to be able to fat-finger/mistype a new password just once and have your whole mailbox (re)encrypted to an unknown).

So, for dovecot versions >= 2.3.19, the last line should become:
`printf "%s\n%s\n%s\n" "$OLD_PASSWORD" "$NEW_PASSWORD" "$NEW_PASSWORD" | doveadm mailbox cryptokey password -u "$1" -O -N`

**Comment by DavidGoodwin** [comment]
@ean365 thank you for the above :)
