### ISSUE TITLE
sha512.b64 scheme lacking support for {MD5-CRYPT} prefix

### ISSUE THREAD

**Issue by davidhrbac** [postfixadmin/postfixadmin#647]
Document https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/HASHING.md reads that sha512.b64 supports {MD5-CRYPT} prefix and links to #58.

It seems to me that the current code does not support this prefix.

What is the suggested path from MD5 passwords to a stronger one without resending te password to everyone?

**Comment by DavidGoodwin** [comment]
Hi - does the above work for you?
