### ISSUE TITLE
Adding a new admin or logging in as one throws  [unknown/invalid $CONF["encrypt"] setting: SHA256]

### ISSUE THREAD

**Issue by ren-kun** [postfixadmin/postfixadmin#649]
Hello Author,

Im currently using:
Postfixadmin 3.4.13
PHP7.4.3
PHPMailer 6
Dovecot 2.3.7.2

Goals and my issues:
I am trying to reset the admin password and also tried to create a new admin password. Im doing this because when i try and send an email outwards via PHPMailer which uses postfix's SMTP server, the apps try to talk to each other while using their default password schema and hence ( I believe one was MD5 and another ARGON2I) I get the below error (After trying to set all apps to use the same schemas) :

unknown/invalid $CONF["encrypt"] setting: SHA256 

And this error when im trying to setup the password schema:..
Invalid token! OR
can't encrypt password with dovecotpw, 

My settings for config.local.php line: 
$CONF['encrypt'] = 'dovecot:SHA256';

What I am trying to do is to sync dovecat, postfixadmin and phpmailer. Author, do you have any ideas on how i can get these apps working together? Thank you in advance!

**Comment by DavidGoodwin** [comment]
We've not yet had a release past 3.11, so your release number might be wrong there ... :-) 

If you are running the latest code from 'master' , you should just need to set `$CONF['encrypt'] = 'SHA256';`

See also https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/HASHING.md

**Comment by ren-kun** [comment]
Hello,

My mistake! postconf mail_version is for postfix

Yes i believe  the master pull for my Ubuntu 20.04 system.

I have the error "unknown/invalid $CONF["encrypt"] setting: SHA256-CRYPT"

![image](https://user-images.githubusercontent.com/1111522/184529585-5eb1a2f5-ea2c-4f80-a1ab-eb3491d55742.png)


Correct me if im wrong >_< and thank you!

**Comment by DavidGoodwin** [comment]
Hm, the unit test ( https://github.com/postfixadmin/postfixadmin/blob/master/tests/PacryptTest.php#L207 ) shows it works.

Given the age of your system, is it possible you've got multiple Postfixadmin versions installed, and what you think you are accessing at http://yourserver/postfixadmin is not the same as what you you're seeing in a terminal?

(hint: try putting something like : `<?php phpinfo(); ` in public/test.php and see if it appears when you go to http://yourserver/postfixadmin/test.php )

**Comment by ren-kun** [comment]
I can try and see if i have more than two installations..

I do however access postfix via a link like: https://postfixadmin.domain.com

Doing any logins will give me "unknown/invalid $CONF["encrypt"] setting: SHA256-CRYPT"

Could you explain a bit when you say "Seeing in a terminal" ?

**Comment by DavidGoodwin** [comment]
"seeing in a terminal" -> I just meant whatever you see when browsing/viewing your server.

In sort of other words, your server should have an Apache (?) config file for postfixadmin.domain.com somewhere in /etc/apache2 (or nginx?). Does the DocumentRoot specified by the VirtualHost configuration match up with where you think you've installed Postfixadmin 3.11 ... ?

**Comment by ren-kun** [comment]
Hey @DavidGoodwin 

Thanks for helping me once again.  Got you!

Yes Im using NGINX to setup a virtual host/block 

Yes I do see the files from the NGINX block with the relevant files. I have also confirmed it by adding a test.php to display info for that virtual subdomain.

**Comment by DavidGoodwin** [comment]
what does setup.php show you then ?

e.g. my test variant gives - 

![image](https://user-images.githubusercontent.com/203929/184533446-cf002c98-cd81-4771-810e-7de2fb94201c.png)

**Comment by DavidGoodwin** [comment]
@ren-kun any update?
