### ISSUE TITLE
Warning MailboxHandler.php after creating new mailbox

### ISSUE THREAD

**Issue by pandamasta** [postfixadmin/postfixadmin#65]
In the url /edit.php?table=mailbox after creating a new mailbox for a domain I get:

```
Warning: A non-numeric value encountered in /var/www/xx.com/model/MailboxHandler.php on line 202

Warning: Cannot modify header information - headers already sent by (output started at /var/www/xx.com/model/MailboxHandler.php:202) in /var/www/xx.com/edit.php on line 175
```

But it all is going well afterward

**Comment by DavidGoodwin** [comment]
I'll guess that you have a non-numeric quota value set for quota_multipler or something similar in your config.

**Comment by shymega** [comment]
I get this too, and `quota_multiplier` is set at the default - no non-numeric value. Using v3.2.3.

**Comment by DavidGoodwin** [comment]
it seems I didn't merge that patch from master at some point - thanks for highlighting this.

**Comment by shymega** [comment]
Cheers. I'll pull from git now for my server.
