### ISSUE TITLE
Depreciated warning in PFASmarty.php

### ISSUE THREAD

**Issue by jameslbrown** [postfixadmin/postfixadmin#650]
Running PHP 8.1.9

Everything works, but I just get lots of errors like this:

```
Deprecated: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /path/to/postfixadmin-feature-improve-pacrypt/model/PFASmarty.php on line 144

Warning: Cannot modify header information - headers already sent by (output started at /path/to/postfixadmin-feature-improve-pacrypt/model/PFASmarty.php:144) in /path/to/postfixadmin-feature-improve-pacrypt/model/PFASmarty.php on line 118
```

My PFASmarty.php goes back to 2 Oct 2021.  (latest version fails to work, get the errors but nothing else)

**Comment by DavidGoodwin** [comment]
Hi - thanks for reporting this.

Suppressing the errors will probably be the quickest fix. You probably just need to change your php.ini file to have display_errors = Off ?

I'll fix ^ (unless someone beats me to it) in the next few days ...

**Comment by DavidGoodwin** [comment]
@jameslbrown  - does the above changeset fix your problem?

**Comment by jameslbrown** [comment]
Yes, that fixed it!

Thanks heaps @DavidGoodwin
