### ISSUE TITLE
sourceforge home page has wrong IRC Link

### ISSUE THREAD

**Issue by ikonia** [postfixadmin/postfixadmin#652]
update sourceforge home page to reference libera chat instead of freenode, sending users to the wrong place / hostile network.

**Comment by DavidGoodwin** [comment]
@ikonia Thanks. Personally I don't look at sourceforge very often - so could you provide a screenshot highlighting where this link is? I can't seem to see it ... I'm probably being dumb / old / blind or some combination thereof....

**Comment by the-nic** [comment]
I think the [website](https://postfixadmin.sourceforge.io/) is meant. There, on the "Community" paragraph

**Comment by DavidGoodwin** [comment]
ah, yes, obvious with hindsight. I guess I'll have to try and remember how to edit them ...

**Comment by DavidGoodwin** [comment]
related -
 * fix the github pages site https://postfixadmin.github.io/ 
 * redirect sourceforge site to github pages page
 * improve links in README.md ( remove references to sf.net )
