### ISSUE TITLE
Postfix setup error

### ISSUE THREAD

**Issue by zerosalty** [postfixadmin/postfixadmin#653]
I new with postfixadmin, encountered following issue when i try to configure 

    ⛔Password Hashing - attempted to use configured encrypt backend (dovecot:BLF-CRYPT) triggered an error: /usr/bin/doveadm pw -r 12 failed, see error log for details
    ⛔Possibly helpful error_log messages - #4 {main}
    thrown in /var/www/postfixadmin/functions.inc.php on line 1062
    [01-Sep-2022 05:35:52 UTC] Failed to read password from /usr/bin/doveadm pw -r 12 ... stderr: Fatal: Error reading configuration: stat(/etc/dovecot/dovecot.conf) failed: Permission denied (euid=48(apache) egid=48(apache) missing +r perm: /etc/dovecot/dovecot.conf stat(/etc/dovecot/dovecot.conf) failed: Permission denied, dir owned by 0:0 mode=0755)
    ⛔You will have problems logging into PostfixAdmin.
    ⛔Check out our Dovecot documentation at https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/DOVECOT.txt, specifically around '3. Permissions'.

for the first error, i tried test this command /usr/bin/doveadm pw -r 12 , it does return a encrypted key with no problem

any help will much appreciated.

**Comment by DavidGoodwin** [comment]
Hi - Sounds like https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/DOVECOT.txt#L143

If you run the code from 'master' then you should avoid this issue. Alternatively, follow the permission instructions in the above document.

**Comment by zerosalty** [comment]
Hi, 

Thank you for your reply. My OS is RHEL9.
This is how install, thru wget command https://github.com/postfixadmin/postfixadmin/archive/postfixadmin-3.3.11.tar.gz

**Comment by zerosalty** [comment]
> Hi - Sounds like https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/DOVECOT.txt#L143
> 
> If you run the code from 'master' then you should avoid this issue. Alternatively, follow the permission instructions in the above document.

I actually stuck for quite a sometime already, i cant figure what to fix already.
is it related to apache user?

**Comment by zerosalty** [comment]
I try the method to create a ssl-keys.conf at /etc/dovecot dir

ssl_cert = </etc/letsencrypt/live/x.x.x.x/fullchain.pem
ssl_key = </etc/letsencrypt/live/x.x.x.xcat sll/privkey.pem

include the file in dovecot.conf 

after restart, postfixadmin still showing same error message.

what have I missed?

**Comment by DavidGoodwin** [comment]
```shell
su - httpd -s /bin/bash 
doveadm pw ........
```

it's that you need to fix, not really postfixadmin....

**Comment by zerosalty** [comment]
> ```shell
> su - httpd -s /bin/bash 
> doveadm pw ........
> ```
> 
> it's that you need to fix, not really postfixadmin....

 i have checked, APACHE services is run under apache username and group

su - httpd -s /bin/bash 
it returned with error, 
user httpd does not exist or the user entry does not contain all the required fields

if test with su - apache -s /bin/bash
it return encrypted password

what else can i troubleshoot?

**Comment by DavidGoodwin** [comment]
Sorry, i thought centos etc used 'httpd' as the user apache runs as ... not 'apache'.

Can you not change your dovecot.conf file to be like : 

....
!include_try ssl-keys.conf
....


where ssl-keys.conf contains :

```
ssl_cert = </etc/letsencrypt/live/x.x.x.x/fullchain.pem
ssl_key = </etc/letsencrypt/live/x.x.x.xcat sll/privkey.pem
```

**Comment by zerosalty** [comment]
I running on RHEL 9,

where before i actually already create ssl-keys.conf with ssl keys and cert and included it inside dovecot.cont 

rwxr-xr-x. 2 root root 4096 Sep  6 14:30 conf.d
-rw-r--r--. 1 root root  769 Aug 26 15:34 dh.pem
-rw-r--r--. 1 root root 4388 Sep  7 11:21 dovecot.conf
-rw-r--r--. 1 root root  392 Sep  1 10:23 dovecot-sql.conf.ext
-rw-r--r--. 1 root root  140 Sep  2 11:10 ssl-keys.conf

I did tested both, enable the ssl-keys and disabled it with both dovecot restart, but still the same

i check my apache user's group
# groups apache
apache : apache dovecot

error log from PHP-fpm

Failed to read password from /usr/bin/doveadm pw -r 12 ... stderr: Fatal: Error reading configuration: stat(/etc/dovecot/dovecot.conf) failed: Permission denied (euid=48(apache) egid=48(apache) missing +r perm: /etc/dovecot/dovecot.conf stat(/etc/dovecot/dovecot.conf) failed: Permission denied, dir owned by 0:0 mode=0755)
, password:

this is the error message i found in message.log
SELinux is preventing /usr/bin/doveadm from getattr access on the file /etc/dovecot/dovecot.conf.

**Comment by DavidGoodwin** [comment]
I can't help with SELinux, I don't have much experience with it.
