### ISSUE TITLE
Password verification failed

### ISSUE THREAD

**Issue by kartagis** [postfixadmin/postfixadmin#655]
Hi,

As instructed, I edited config.local.php to read `$CONF['setup_password'] = 'mypass';`, however when I go to mydomain/setup.php and attempt to log in, I get `Password verification failed`. How do I fix this?

Best regards,

**Comment by DavidGoodwin** [comment]
go to setup.php, and enter "mypass" twice in the text boxes there - they should look a little like -

![image](https://user-images.githubusercontent.com/203929/194073334-725cba39-b673-4b62-bce3-589e432ef79a.png)

it'll output something like : 

![image](https://user-images.githubusercontent.com/203929/194073451-a729b7eb-03e3-4bc5-83a6-2db4fbf7f5c9.png)


for e.g. 'test123'

Alternatively, you can use something like this in a shell -

```shell
php -r "echo password_hash('test123', PASSWORD_DEFAULT);"
```
which again will output something like : 

```
$2y$10$BR0pSYnP2W6L/Erva0BgP.7XTPVClGkXgGb9c7ukDgJlZbzh9XSWG
```

It's this value that needs to go into your config.local.php - so it looks like : 

```PHP
<?php
// other lines
$CONF['setup_password'] = '$2y$10$BR0pSYnP2W6L/Erva0BgP.7XTPVClGkXgGb9c7ukDgJlZbzh9XSWG';
// other lines 
```

**Comment by kartagis** [comment]
Thanks.
