### ISSUE TITLE
UPGRADE.txt needs an upgrade

### ISSUE THREAD

**Issue by bmatthewshea** [postfixadmin/postfixadmin#66]
https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/UPGRADE.txt

UPGRADE.txt : "1. Backup the Database" - small issue with syntax for mysqldump:
`mysqldump -a -u root -p > /tmp/postfixadmin-backup.sql`

"-a " or "-A"?
"-a" is not recognized on my system. Is this outdated/deprecated syntax?
"-A" is ALL databases (see `--all-databases`). Which I assume is what you wanted in document?

Ref: https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#mysqldump-syntax

"3. Change permissions"
`chown -R www-data templates_c/`
no such folder under master now (placeholder)? If fresh install from git clone the user will not have it.
Maybe: 
> sudo mkdir postfixadmin-(version)/templates_c && \
> sudo chmod 640 postfixadmin-(version)/templates_c && \
> sudo chown www-data:www-data postfixadmin-(version)/templates_c

"4. Configure":
No mention of `config.local.php` use.
This would seem appropriate since this is about upgrading.
If it does not exist the freshly installed code complains with a 'not found'..

I believe this document needs a look at anyway as its dated 2011 in master. Might be other problems with it...?

**Comment by bmatthewshea** [comment]
`chown -R www-data templates_c/`
no such folder under master now.

No mention of `config.local.php` use, either. 
This would seem appropriate since this is about upgrading.

**Comment by DavidGoodwin** [comment]
Thanks. The changes I've made might fix the above.
