### ISSUE TITLE
No Message-ID set on outgoing Password Recovery Mails

### ISSUE THREAD

**Issue by Subito** [postfixadmin/postfixadmin#667]
PFA does not seem to set a valid Message-Id Header on outgoing Password recovery Mails. This is probably related to this TODO: https://github.com/postfixadmin/postfixadmin/blob/3017ea3f3cb1e29fa02e20ec579bc745a4b6bb70/functions.inc.php#L1477 because all of the SMTP-Session gets handcrafted so something minor like the Message-Id is easily overlooked.

This might interfere with deliverability of password-recovery emails, as it might trip up some spamfilters.

**Comment by DavidGoodwin** [comment]
Hm, interestingly testing this locally, my local MTA (postfix) sets a Message-Id - e.g `Message-Id: <20221130204955.09D6BC4014C@walnut.lan>`

It is however naughty and does not necessarily specify a From address.... (at least if you've been lazy like me and not specified an 'admin_email' in your config.local.php).
