### ISSUE TITLE
Superadmin not able to see any domains without explicit linking

### ISSUE THREAD

**Issue by mmauksch** [postfixadmin/postfixadmin#668]
Affected Version: 3.3.11 master Head at 43ce9feda1f5b97be3e11b320d473baa3401fe7d
Environment:
Notebook: 

- OS: Ubutu 18.04
- PHP: 8.0
- Postgresql: 10
- PFA Version: 43ce9feda1f5b97be3e11b320d473baa3401fe7d

Server:

- OS: Debian 11
- PHP: 8.1
- Postgresql: 13
- PFA Version: 3.3.11

Given the following conditions

- Superadmin created via setup.php or cli (for example admin@randomdomain.com)
- login successful with the new superadmin
- the list for domains is completly empty
- superadmin creates a new domain otherrandomdomain.com
- newly created domain is not visible in domainlist

Expected behavior
in my understanding the superadmin exists to manage domains where he is not assigned explicitly. Only seeing an empty list of domains right after creating a new domain is very confusing

Available workaround:
it is possible to assign the domains to the admin via the "edit admin" form. This way the admin is able to manage domains

Investigation results:

- Queries pulled from the postgrelog (see Attach 1) are attached. The complex large query that seems to be responsible for filling the domain list returns no results. 

Alternative way to reproduce the error (see Attach 2)

- Add domain via cli
- add new superadmin via cli for the new domain
- adding admin to domain_admins seems to fail with foreign key constraint error

Attach 1: [postfixadmin-domainlist.pglog.txt](https://github.com/postfixadmin/postfixadmin/files/9833472/postfixadmin-domainlist.pglog.txt)
Attach 2: [postfixadmin-add-admin-for-domain.txt](https://github.com/postfixadmin/postfixadmin/files/9833493/postfixadmin-add-admin-for-domain.txt)

**Comment by DavidGoodwin** [comment]
Hm, I think the problem is that you added the domain 'example.org' but tried to associate the admin with 'example.com' (which didn't exist?)

(Thank you for the detailed bug report by the way!)

**Comment by mmauksch** [comment]
I probably switched them around while doing the bug report sorry. I was using example to not post my real domain^^ I used the same domain all around. If it helps I can probably run my ansible script against a vagrant machine end export the webroot and db if that helps

**Comment by DavidGoodwin** [comment]
```
