### ISSUE TITLE
Can I create email address in postfixadmin and use ldap authentication for each email account ?

### ISSUE THREAD

**Issue by PhilippeAccorsi** [postfixadmin/postfixadmin#669]
Hi,
I not find any information about possibility to use LDAP for user authentication (I speak about user email account, not admin user of postfixadmin interface)
We want to do:
- Postfix for smtp
- Dovecot for imap (access with thunderbird)
- Sogo for webmail access + agenda, address book, etc.
- Postfixadmin to administrate all email, domain, etc.
- LDAP to authenticate user on webmail and imap access

We don't want to have 2 list of user/password to make sure if user password change in LDAP, email can be stay accessible with this new password without admin job in PostfixAdmin.

Do you think it is possible ?

**Comment by DavidGoodwin** [comment]
This is really a Postfix question. 

From a long time ago, I know Postfix can be configured to use an LDAP backend - but I'm not sure about the other bits.

PostfixAdmin does not support an LDAP backend. If someone could create a PR for adding support for this it'd be welcome - but I suspect it'd be difficult to support/merge.
