### ISSUE TITLE
vacation.pl not work with SQLITE

### ISSUE THREAD

**Issue by fwohlfarth** [postfixadmin/postfixadmin#67]
In the postfixadmin config.inc.php i use SQLite for local database.
Now i want to activate the plugin vacation.pl but can not set up there sqlite.

**Comment by pedromorgan** [comment]
@fwohlfarth as far as I can see, vacation.pl does not support sqlite

**Comment by DavidGoodwin** [comment]
PR is welcome :)

**Comment by DavidGoodwin** [comment]
https://metacpan.org/pod/DBD::SQLite might work.

 * Requires changes to opening db connection and how unicode is specified ( https://metacpan.org/pod/DBD::SQLite#Unicode-handling )
 * Going through the various queries in the vacation.pl file and making sure they work with SQLite
