### ISSUE TITLE
Update problem database old version: 1846; target version: 1847

### ISSUE THREAD

**Issue by ZeM2008** [postfixadmin/postfixadmin#674]
Updating database:

- old version: 1846; target version: 1847

  (If the update doesn't work, run setup.php?debug=1 to see the detailed error messages and SQL queries.)
updating to version 1847 (MySQL)...

CREATE TABLE IF NOT EXISTS `dkim` ( `id` int(11) not null auto_increment primary key, `domain_name` varchar(255) NOT NULL, `description` varchar(255) DEFAULT '', `selector` varchar(63) NOT NULL DEFAULT 'default', `private_key` text, `public_key` text, `created` datetime NOT NULL default '2000-01-01 00:00:00', `modified` datetime NOT NULL default '2000-01-01 00:00:00', INDEX(domain_name, description), FOREIGN KEY (`domain_name`) REFERENCES `domain`(`domain`) ON DELETE CASCADE) CHARACTER SET latin1 COLLATE latin1_general_ci COMMENT='Postfix Admin - OpenDKIM Key Table';

SQLSTATE[HY000]: General error: 1005 Can't create table `postfixadmin`.`dkim` (errno: 150 "Foreign key constraint is incorrectly formed")

show engine innodb status

LATEST FOREIGN KEY ERROR
------------------------
2022-11-03 05:38:30 0x7ff4800de700 Error in foreign key constraint of table `postfixadmin`.`dkim`:
Create  table `postfixadmin`.`dkim` with foreign key (domain_name) constraint failed. Referenced table `postfixadmin`.`domain` not found in the data dictionary.------------

**Comment by ZeM2008** [comment]
convert MyISAM tables to InnoDB - update ok

**Comment by DavidGoodwin** [comment]
Thanks for updating / adding a fix...
