### ISSUE TITLE
admins no access to domains

### ISSUE THREAD

**Issue by eduardz** [postfixadmin/postfixadmin#68]
Hello,

I have Postfix Admin 3.1 version installed on CentOS 7
The Super admin  accounts work just fine.
The admin accounts don't see any domains even if I select domains for those accounts

As a normal admin account i get this error messages:
On the Postfixadmin Virtual List page: You don't have permissions for any domains.
On the Postfixadmin View Log: Unable to find the logs!

If I run /setup.php?debug=1 it looks fine
"""Running software:

    PHP version 5.4.16
    Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.16

    Checking for dependencies:

    Magic Quotes: Disabled - OK
    Depends on: presence config.inc.php - OK
    Checking $CONF['configured'] - OK
    Warning: config.local.php - NOT FOUND
    It's Recommended to store your own settings in config.local.php instead of editing config.inc.php
    Create the file, and edit as appropriate (e.g. select database type etc)
    Depends on: MySQL 3.23, 4.0 - OK
    Depends on: MySQL 4.1 - OK
    Depends on: SQLite - OK
    (change the database_type to 'sqlite' in config.local.php if you want to use SQLite)
    Testing database connection (using mysqli) - OK
    Depends on: session - OK
    Depends on: pcre - OK
    Depends on: multibyte string - OK
    Depends on: IMAP functions - OK

    Everything seems fine... attempting to create/update database structure

    CREATE TABLE IF NOT EXISTS config ( `id` int(11) not null auto_increment primary key, `name` VARCHAR(20) /*!40100 CHARACTER SET latin1 */ NOT NULL DEFAULT '', `value` VARCHAR(20) /*!40100 CHARACTER SET latin1 */ NOT NULL DEFAULT '', UNIQUE name ( `name` ) ) ENGINE = MYISAM COMMENT = 'PostfixAdmin settings'

    Database is up to date""""

**Comment by eduardz** [comment]
solved; domain was disabled

**Comment by VictorJosso** [comment]
Hey, 
I've got the same problem... Can you tell me how you solved it?
