### ISSUE TITLE
Fetchmail seen mails state reset after reboot

### ISSUE THREAD

**Issue by bartekczajkowski** [postfixadmin/postfixadmin#681]
Hello.
I've a problem with fetchmail subservice - i use it to sync my local postfixadmin accounts with remote mailboxes.
Some of remote mailboxes keep thousands of already downloaded mails.
After every reset those mails are redownloaded and my local mailboxes are flooded with mails.
I've done some research and there is a reason in:
https://github.com/postfixadmin/postfixadmin/blob/master/ADDITIONS/fetchmail.pl Line 151:
  _$ret=`/usr/bin/fetchmail -f $filename -i $run_dir/fetchmail.pid`;
-i option should be used for persistent file, that helds ids of already downloaded mails, by some reason its false named 'pid' in script and saved in volatile directory.
I guess it should be something like:
  _$ret=`/usr/bin/fetchmail -f $filename --pidfile $run_dir/fetchmail.pid`;
and -i should be empty (or -i should be set to some persistent file via settings).
It there any reason why it was coded like this? Is it bug or is it a feature? :)

**Comment by DavidGoodwin** [comment]
Hm, that's interesting. 
Looking at the git history - it looks like it's been like ....`-i ... pid` since 2009 ? 

https://github.com/postfixadmin/postfixadmin/commit/c4250c42b09254a03452995b0a139a120348a240

The fetchmail man page does seem to agree with you - 

```
     -i <pathname> | --idfile <pathname>
              (Keyword: idfile)
              Specify an alternate name for the .fetchids file used to save message UIDs. NOTE: since fetchmail 6.3.0, write access to the directory containing the idfile is required, as fetchmail writes a temporary file and renames it into the place of the real idfile only
              if the temporary file has been written successfully. This avoids the truncation of idfiles when running out of disk space.

       --pidfile <pathname>
              (Keyword: pidfile; since fetchmail v6.3.4)
              Override the default location of the PID file that is used as a lock file.  Default: see "ENVIRONMENT" below. Note that many places in the code and documentation, the term "lock file" is used.  This file contains the process ID of the running fetchmail on  the
              first line and potentially the daemon interval on a second line.


```

**Comment by DavidGoodwin** [comment]
I suspect one problem might be that the run dir (/var/run/fetchmail) probably always used to persist on disk back in the dark ages; now I think it's a tmpfs type thing that gets nuked on reboot?

**Comment by bartekczajkowski** [comment]
Also - i guess - you need to have specific requirements and situation to even care. It works after all (and after reboot ;) 
As long as mail from remote server are flushed, or there are not many of them - you can not even notice it.
Also - if server is stable enough no live without reboots for long - no need to care, etc ;)
