### ISSUE TITLE
Logging in setup.php for failed authentications missing

### ISSUE THREAD

**Issue by MoritzDPTV** [postfixadmin/postfixadmin#683]
Hello there,

setting up my fail2ban filters, I noticed that for the setup.php the error_log is missing when the wrong setup password is entered. This seems crucial to me when trying to protect postfixadmin from bruteforce attacks. I added it manually as follows, and it works, so seems like a quick fix. :)

    if ($pass != 'invalid') {
        if (password_verify(safepost('setup_password', 'invalid'), $configSetupPassword)) {
            $authenticated = true;
        } else {
            error_log("PostfixAdmin setup login failed (username: $fUsername, ip_address: {$_SERVER['REMOTE_ADDR']})");
            $errors['setup_login_password'] = "Password verification failed.";
        }
    }

Cheers,
Moritz

System Information
PostfixAdmin Version: 3.3.11
Server: Ubuntu 20.04.01 LTS

**Comment by DavidGoodwin** [comment]
Thanks for reporting this - happy with my changeset?
(I don't think $fUsername has any relevance here, as there's only a magic password for accessing setup).
