### ISSUE TITLE
Missing directory in 3.3.10

### ISSUE THREAD

**Issue by jim-moe** [postfixadmin/postfixadmin#684]
opensuse 15.4
postfixadmin 3.3.10

I followed all of the steps for installing postfixadmin. I am stumped by this error:

`Warning: require_once(/data01/t-drv/websites/postfix-admin/vendor/autoload.php): failed to open stream: No such file or directory in /data01/t-drv/websites/postfix-admin/common.php on line 3`
There is, indeed, no such directory "vendor/".

**Comment by jim-moe** [comment]
Oops. Somehow I got a dev version: 3.4-dev

**Comment by DavidGoodwin** [comment]
run the 'install.sh' script
