### ISSUE TITLE
Help with warnings - 3.4-dev

### ISSUE THREAD

**Issue by jim-moe** [postfixadmin/postfixadmin#685]
opensuse 15.4
php 7.4.33

Would you explain these warnings?
```
Warnings
    ⚠ Database - PostgreSQL (pdo_pgsql) extension not found
```
Why?

`    ⚠ Warning: Optional dependency 'imap' extension missing, without this you may not be able to automate creation of sub-folders for new mailboxes`
Which extension? courier-imap? imap? perl-Mail-IMAPClient?
The repo does not have a PHP imap module.
Dovecot is already installed.

```
Database Update
Everything seems fine... attempting to create/update database structure
Database is up to date: 1847/0
```

**Comment by DavidGoodwin** [comment]
* PostgreSQL -> PostfixAdmin can be configured to use PostgreSQL, SQLite or MySQL. The setup thing is just pointing out that you don't have the PostgreSQL driver installed in PHP. You probably have the MySQL driver, and you will probably use this... so don't worry (this is why it's not an error).
 * 'imap' => if you have the right config things set, when a mailbox is added, that extension is used to create some skeleton folders. If you don't have the extension installed, it won't work. Note: the imap extension is not maintained / is not always shipped by distributors nowadays

**Comment by jim-moe** [comment]
On 2022-11-21 02:04, David Goodwin wrote:

> 'imap' => if you have the right config things set, when a mailbox is added, that
> extension is used to create some skeleton folders.
>
  Is this a PHP extension? As in php-imap?

-- 
James Moe
moe dot james at sohnen-moe dot com
520.743.3936
Think.

**Comment by DavidGoodwin** [comment]
@jim-moe sorry, i missed your reply - yes it's the PHP extension called 'imap', often found in packages called 'php-imap'. It's not required, but without it you won't be able to use a configuration variable to trigger the automatic creation of folders within new mailboxes.
