### ISSUE TITLE
After upgrade, some screens do not display in UI

### ISSUE THREAD

**Issue by stone212** [postfixadmin/postfixadmin#688]
I recently upgraded a system to Ubuntu Jammy.  When I went to postfixadmin, it required me to run setup.php.  I did.  I didn't find any config.local.php file on server and I want back to the postfixadmin main page, and it worked.  I guess running setup.php was enough to upgrade the database?

I get to the login screen, I log in with my old credentials, and I see a shiny new interface.

But some of the screens do not display (fully blank page, even on View Source).  These include:

Domain List > Domain List
Domain List > New Domain
Virtual List > Virtual List

All of the other menu items seem to work.

Have I configured something wrong or is this a bug?

**Comment by DavidGoodwin** [comment]
Yes, running setup.php ought to be enough to upgrade the database.

Are there any errors logged in the PHP error log (perhaps /var/log/apache2/error.log) ?

**Comment by stone212** [comment]
Yes:

[Mon Dec 05 13:40:37.889358 2022] [proxy_fcgi:error] [pid 159086] [client x.x.x.x:54884] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key "theme_favicon" in /usr/share/postfixadmin/templates_c/63f98af09aa5bc7a4553679dd062464be3988c43_0.file.header.tpl.php on line 36'

[Mon Dec 05 13:40:44.502019 2022] [proxy_fcgi:error] [pid 159087] [client x.x.x.x:54930] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key "theme_favicon" in /usr/share/postfixadmin/templates_c/63f98af09aa5bc7a4553679dd062464be3988c43_0.file.header.tpl.php on line 36', referer: https://domain.mine/postfixadmin/login.php

[Mon Dec 05 13:40:47.679874 2022] [proxy_fcgi:error] [pid 159087] [client x.x.x.x:54930] AH01071: Got error 'PHP message: Config::read(): attempt to read undefined config option "password_expiration", returning nullPHP message: PHP Fatal error:  In bool: expected config password_expiration to be a string, but received a NULL in /usr/share/postfixadmin/model/Config.php on line 144', referer: https://domain.mine/postfixadmin/main.php

**Comment by DavidGoodwin** [comment]
@stone212 try adding : 
```PHP
$CONF['theme_favicon'] = 'images/favicon.ico';
$CONF['password_expiration'] = 'NO';
```

into your config.local.php (or config.inc.php).

**Comment by stone212** [comment]
That fixed it!

Since you mentioned `config.local.php`, `/usr/share/postfixadmin/config.local.php` is a symlink to `/etc/postfixadmin/config.local.php`, which does not exist.

So I put this directly under `<?php` in `/usr/share/postfixadmin/config.inc.php` and it's working now.  

Great!

**Comment by stone212** [comment]
That fixed it!

Since you mentioned `config.local.php`, `/usr/share/postfixadmin/config.local.php` is a symlink to `/etc/postfixadmin/config.local.php`, which does not exist.

So I put this directly under `<?php` in `/usr/share/postfixadmin/config.inc.php` and it's working now.  

Great!
