### ISSUE TITLE
Proxy url rewrite support etc

### ISSUE THREAD

**Issue by DavidGoodwin** [postfixadmin/postfixadmin#689]
See https://github.com/postfixadmin/docker/issues/51

Add configuration support for a 'base url' for PostfixAdmin - in case it's being hidden behind some sort of reverse proxy

This would rewrite any URLs in template(s) and any redirects we do.

**Comment by ariabamdad** [comment]
Hi @DavidGoodwin, 

Is there currently any workaround for placing PFA behind a proxy.  I see a few tickets open for this but no real solution.  

Thanks

**Comment by DavidGoodwin** [comment]
Hi - no one has submitted a PR yet for it ... it isn't a priority to me either. 

I assume it'd require all the templates having absolute URLs (/foo/bar) being changed to relative with a prefix (e.g. $prefix/foo/bar ) or all urls just becoming relative? (no leading slash)

**Comment by CLechleitner42** [comment]
As long as PFA keeps URLs free from a hostname there should be no need for any adaption, IMO.

Any reverse proxy should be able to map i.e. https://my-pfa/ to http://192.168.25.110:8000/my-pfa/ or the like forth and back.

In case of Apache, each ProxyPass rule needs to be accompanied by a ProxyPassReverse rule for the back part.

If we want to use relative links, then working with ../ could avoid requiring any configured (or detected) $prefix, but ../ can break if html snippets are scratched together to pages with different path depths.

In 30 years of developing web solutions we have simplified things with configurable public URLs on a regular basis, until one customer needed to serve something under totally different URLs internally and externally. In hindsight that was a good lesson ;-)

**Comment by ariabamdad** [comment]
Sorry for the delayed response.  Thank you @DavidGoodwin and @CLechleitner42 for your responses.  Yes, proxy should work.  The trouble in my case was that I had PFA running on a separate server with the application at the root of that virtual host. In other words /postfixadmin/public would be the DocumentRoot for apache.   All my proxy settings were correct as Christoph stated.  Once I moved PFA to be served from a sub directory, such as /postfixadmin, then everything worked.  Thanks again.
