### ISSUE TITLE
About install by apt-get now

### ISSUE THREAD

**Issue by qnmlgdsb** [postfixadmin/postfixadmin#69]
MySQL packages was replaced by MariaDB. PHP5 packages also be removed and  change to PHP7, any way to make those work together?

**Comment by DavidGoodwin** [comment]
Can you provide a bit more information please?

If you're using Debian Stretch, postfixadmin installs fine ... using 
```
FROM debian:stretch

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -y install apache2 libapache2-mod-php7.0 php7.0 php7.0-pdo php7.0-sqlite php7.0-json postfixadmin

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
```

**Comment by DavidGoodwin** [comment]
I've updated debian control (see 0b70b5c6864fd89f750fa650b30538f402947fa0 ) which might fix your problem(s) ?

**Comment by qnmlgdsb** [comment]
http://ip/postfixadmin/login.php
show
DEBUG INFORMATION:
MySQL 3.x / 4.0 functions not available! (php5-mysql installed?)
database_type = 'mysql' in config.inc.php, are you using a different database?

Please check the documentation and website for more information.

http://IP/postfixadmin/setup.php
show
Postfix Admin Setup Checker

Running software:

PHP version 7.0.19-1
Apache/2.4.25 (Debian)
Checking for dependencies:

Magic Quotes: Disabled - OK
Depends on: presence config.inc.php - OK
Checking $CONF['configured'] - OK
Error: Smarty template compile directory templates_c is not writable.
Please make it writable.
If you are using SELinux or AppArmor, you might need to adjust their setup to allow write access.
Depends on: MySQL 4.1 - OK 
(change the database_type to 'mysqli' in config.inc.php if you want to use MySQL)
Error: Can't connect to database
Please edit the $CONF['database_*'] parameters in config.inc.php.
DEBUG INFORMATION:
MySQL 3.x / 4.0 functions not available! (php5-mysql installed?)
database_type = 'mysql' in config.inc.php, are you using a different database?

Depends on: session - OK
Depends on: pcre - OK
Depends on: multibyte string - OK
Depends on: IMAP functions - OK
Please fix the errors listed above.


I just  run this apt-get install postfixadmin 
also use debian 9
so how to fix?

**Comment by qnmlgdsb** [comment]
Postfix Admin Setup Checker

Running software:

PHP version 7.0.19-1
Apache/2.4.25 (Debian)
Checking for dependencies:

Magic Quotes: Disabled - OK
Depends on: presence config.inc.php - OK
Checking $CONF['configured'] - OK
Depends on: presence config.local.php - OK
Depends on: MySQL 4.1 - OK
Testing database connection (using mysqli) - OK
Depends on: session - OK
Depends on: pcre - OK
Depends on: multibyte string - OK
Depends on: IMAP functions - OK
Everything seems fine... attempting to create/update database structure

CREATE TABLE IF NOT EXISTS config ( `id` int(11) not null auto_increment primary key, `name` VARCHAR(20) /*!40100 CHARACTER SET latin1 */ NOT NULL DEFAULT '', `value` VARCHAR(20) /*!40100 CHARACTER SET latin1 */ NOT NULL DEFAULT '', UNIQUE name ( `name` ) ) ENGINE = MYISAM COMMENT = 'PostfixAdmin settings'

Updating database:

- old version: 0; target version: 1835

  (If the update doesn't work, run setup.php?debug=1 to see the detailed error messages and SQL queries.)
updating to version 1 (MySQL)...

CREATE TABLE IF NOT EXISTS admin ( `username` varchar(255) NOT NULL default '', `password` varchar(255) NOT NULL default '', `created` datetime NOT NULL default '2000-01-01 00:00:00', `modified` datetime NOT NULL default '2000-01-01 00:00:00', `active` tinyint(1) NOT NULL default '1', PRIMARY KEY (`username`) ) ENGINE=MyISAM COMMENT='Postfix Admin - Virtual Admins';

DEBUG INFORMATION:
Invalid query: Specified key was too long; max key length is 1000 bytes

Check your error_log for the failed query.


now above is the new error show

**Comment by cboltz** [comment]
This is a known issue with MySQL utf8mb4 charset, and already fixed in latest git. Please grab the latest upgrade.php from github (or just do a "git clone") and try again.

**Comment by qnmlgdsb** [comment]
thanks  with the new upgrade.php now is working,but when I Create superadmin account ,change the $CONF['setup_password'] = 'long and long do not know what mean';
and then try to login show Your email address or password are not correct.
 I can very sure that password and email address is right.

**Comment by DavidGoodwin** [comment]
Check the contents of the database to confirm the username ... there's an admin table.
```
MySQL [postfixadmin]> select username,superadmin,active from admin \G
*************************** 1. row ***************************
  username: david@palepurple.co.uk
superadmin: 1
    active: 1
```

**Comment by qnmlgdsb** [comment]
all the problem above with the update of new upgrade.php and restart the server then wroks good.

**Comment by maotora** [comment]
Hello, @DavidGoodwin  I have the same problem.

When I 

    MySQL [postfixadmin]> select username,superadmin,active from admin \G

It shows `Empty set`.

I have went through all the process of creating an admin as you instructed above. And I have users using postfix on other clients (not webmail).

How can I solve this?

**Comment by DavidGoodwin** [comment]
@maotora do you have a setup password configured? (If not visit http://your.server/setup.php and create one). Once you've done this setup.php should allow you to add admin users.

**Comment by maotora** [comment]
@DavidGoodwin I have the setup password configured and then create that hash, then copy it onto the `/etc/webapps/postfixadmin/config.inc.php` and paste that hash on

    $CONF['setup_password'] = 'generated_hash';

field, when I go the https://mail.myserver.com/ and try to log in as an admin or normal user I cannot.

> Your email address or password are not correct
