### ISSUE TITLE
Version number not updated to 3.3.13 in config.

### ISSUE THREAD

**Issue by prbt2016** [postfixadmin/postfixadmin#694]
Hello,

I was in the process of manual installation of PostfixAdmin 3.3.13 (latest version) downloaded from 

https://github.com/postfixadmin/postfixadmin/archive/refs/tags/postfixadmin-3.3.13.zip  

on Centos7 with  PHP 7.0, MYSQL 5.5, Apache 2.2. 

However, I found that version number is not yet updated. It's still showing 3.3.11 :

![image](https://user-images.githubusercontent.com/17871448/206659404-8e77e110-7a36-468a-9d87-0b78bb7ce177.png)

So to check further I inspected the 'config.inc.php' file under root directory  on [Line 703](https://github.com/postfixadmin/postfixadmin/blob/postfixadmin-3.3.13/config.inc.php#L703 )

$CONF['version'] = '3.3.11'; which should be 

$CONF['version'] = '3.3.13';

Could you please update this ?.

Regards.

**Comment by DavidGoodwin** [comment]
Thanks for pointing it out .... No doubt it'll be out of date in the 3.3.14 release, if that ever happens :-)

**Comment by prbt2016** [comment]
Thanks @DavidGoodwin . :+1:

**Comment by DavidGoodwin** [comment]
It's happened many times in the past ... you'd think I'd have learnt by now! 

(One problem with doing infrequent releases)
