### ISSUE TITLE
Add Admin = "read_string: expected config min_password_length to be a string"

### ISSUE THREAD

**Issue by bmatthewshea** [postfixadmin/postfixadmin#697]
If I try to add a super admin using "Admin List/New Admin" I get this:

`PHP Fatal error:  In read_string: expected config min_password_length to be a string, but received a integer in /var/www/postfixadmin-3.3.13/model/Config.php on line 75`

If I go back into setup and try to add the same user, it seems to do nothing.

Everything was newly installed today on an AWS instance. Ubuntu 22 / MariaDB / etc. PostfixAdmin DB seems to be working fine so far other than this issue. (I can login fine, create/delete records/etc)

The only old portions of this server are the imported database and config.local.php (with minor changes for db connection-nothing really added to it). The old server the database/config came from are running new postfixadmin, but I had not added an admin to it in a long time so do not know if it's broken on it, too. This feels like a new issue, though. And as you can see, 'setup screen' checks out okay, as far as that goes.

If you need more info let me know.

![Rt4L9S8 1](https://user-images.githubusercontent.com/984097/209904026-e27d4e2c-2ca1-485c-a86e-3c242892d475.png)

**Comment by DavidGoodwin** [comment]
I think your config.local.php file has a min_password_length setting; either remove it or change it to be a string (!).

The problem is in functions.inc.php -> validate_password(...).


```PHP
    if (Config::has('min_password_length')) {
        $minlen = (int)Config::read_string('min_password_length'); # used up to 2.3.x - check it for backward compatibility
        if ($minlen > 0) {
            $val_conf['/.{' . $minlen . '}/'] = "password_too_short $minlen";
        }
    }
```

Config::read_string() tries to be strict, and calls is_string() on the value. As it's probably set to e.g. `8`or something it's failing the is_string() check. Changing your config to contain e.g. `$CONF['min_password_length'] = '8'; ` would fix it (as the 8 is now a string ... thanks to the quote marks.

**Comment by bmatthewshea** [comment]
Thanks! 
Absolutely correct. Unquoted is an integer I guess/null for string check in function.

Anyway that fixed it. Sorry I didn't catch that myself.

Was:

> `$CONF['min_password_length'] = 6;`

Now:

> `$CONF['min_password_length'] = '6';`

Now I get: "The admin me@example.com has been added!" - No errors.
Thanks again for the quick reply.
