### ISSUE TITLE
Problems upgrading from 3.3.8 to postfixadmin_3.3 branch

### ISSUE THREAD

**Issue by elyograg** [postfixadmin/postfixadmin#699]
Today I saw that my installed 3.3.8 version of postfixadmin was out of date.

I have been trying to migrate all my websites to git repositories, so I pulled this repo down and switched to the postfixadmin_3.3 branch, then went about bringing it online.

I ran into some problems when trying to run setup.php to upgrade the database.

First problem was that the created and modified dates were all zeroes in the ALL record in the domain table, so altering the table failed.  I updated those to `1970-01-01 00:00:00` and then that step worked.

Second problem was that it could not add a foreign key to the vacation_notification table.  I updated the permissions of the user to "ALL PRIVILEGES" on its database so that was allowed.

Then it failed again, trying to remove the foreign key that it had just failed to add.  Turns out that the named foreign key was not there, which I found strange because I had just fixed the access to allow creating of that foreign key.

```
Wed Jan 04 11:06:17.125124 2023] [proxy_fcgi:error] [pid 2489788:tid 139947371697920] [client 172.31.8.104:56522] AH01071: Got error 'PHP message: Invalid query: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'vacation_notification_pkey'; check that column/key exists caused by ALTER TABLE `vacation_notification` DROP FOREIGN KEY vacation_notification_pkey
```

So I manually created a foreign key with that name, and then setup.php was able to complete successfully.  Problem solved, but I think it does mean that the SQL commands in the upgrade script(s) need a look.

Then I noticed something that I haven't been able to fix.  In the footer, it still shows the version as 3.3.8.  The version in config.inc.php is 3.3.13, and I was not able to find 3.3.8 anywhere in the repo or the database.

**Comment by DavidGoodwin** [comment]
Hi @elyograg - Thanks for the feedback. I think the version is defined in the config.inc.php file - so could be overridden in your config.local.php if you want.

`$CONF['version'] = 'something here';`

**Comment by elyograg** [comment]
I don't have a config.local.php ... I should make one now that I know that's possible.  The config.inc.php file has this:

`$CONF['version'] = '3.3.13'`

But the version that is shown on the browser is 3.3.8 and I couldn't find where it's getting that data.

**Comment by elyograg** [comment]
I just noticed that config.inc.php has `<?php` at the beginning but doesn't have the closing `?>` .  This isn't causing an error.
