### ISSUE TITLE
go-mailkit

### ISSUE THREAD

**Issue by pedromorgan** [postfixadmin/postfixadmin#7]
This might not be spanner in the works guys, maybe a rachet..  sorry..

In my case I am using postfix as an "internal mailserver"..
Ie depts in a company can send things to each other on a lan..
Multi site.. but staffmail.example.com is where it is at..

I opted to use postfix, as .. the vacation.pl. .which is perl.. ohh tthe fun..

However as this is an integrated system, 
I abandonded php a decade ago
and am now replacing the python2 code 
in favour of golang..

So here's the stuff in golang, and will be trusted server on lan = minimal auth..
and depertmental maiboxes..
https://github.com/daffodil/go-mailkit

So my goals is to  All in AJAX (my GUi=Pyqt4+phonegap)

Admin Mailbox
==================
= pfa = https://github.com/daffodil/go-mailkit/tree/master/postfixadmin

1) be able to create shared "department mailbox"
2) Ability to create mailbox and accounts etc
3) be able to query mailboxes and aliases
4) set vacation times and forward to team

Read Mail
=====================
Ability to read mail 

HUge Snags.. But atmo its all plain text password and read/only/ resanoable open system.. kinda..  like a pub with an open till.. and none of this silly barcode everything in + out.. faster and more fun.. styleee

**Comment by palepurple** [comment]
Hi - Good luck! 

> However as this is an integrated system, I abandonded php a decade ago
> and am now replacing the python2 code in favour of golang.....

Well, if you wish to rewrite a vacation handling script in Go or Python or anything else, I'd be more than happy to merge it in....
