### ISSUE TITLE
DOVECOT.txt wrong ssl file (repeated twice)

### ISSUE THREAD

**Issue by RoyBellingan** [postfixadmin/postfixadmin#704]
I know can be out of the scope of this project to properly configure dovecot to use SSL.

But because mkcert.sh does not write clearly that it produces 2 files, and the current DOVECOT.txt
contain twice the same 

ssl_cert = </etc/dovecot/private/dovecot.pem
ssl_key = </etc/dovecot/private/dovecot.pem

I think is a source of confusion and should be like

ssl_cert = </etc/ssl/certs/dovecot.pem
ssl_key = </etc/ssl/private/dovecot.pem

Thank you.

**Comment by DavidGoodwin** [comment]
So, /usr/share/dovecot/mkcert.sh - at least on Debian - is what you're referring to. That looks like it produces a self signed certificate, which you'd really want to avoid, and given LetsEncrypt is so easy to setup, I'd suggest you use that.


For my personal mail server (dovecot 2.3.13, via Debian bullseye), I have ssl_key and ssl_cert set to different file(s)

But for a customer's mail server (dovecot 2.3.4, via Debian buster), I have ssl_cert and ssl_key pointing to the same file - i.e.

```
ssl_key = </etc/dovecot/ssl.pem
ssl_cert = </etc/dovecot/ssl.pem
```

and that .pem file is just made from `cat whatever.crt whatever.key > ssl.pem`

(where the crt file is that LetsEncrypt issue as the public key).

So I suspect dovecot doesn't care - and can cope with being fed a combined certificate file.

**Comment by RoyBellingan** [comment]
yes I discovered that later, maybe if you can just drop a line to prefer the usage of let's encrypt and that the file should be different, or concatenated. Please.
