### ISSUE TITLE
Domain link in the domain list is escaped incorrectly

### ISSUE THREAD

**Issue by waclaw66** [postfixadmin/postfixadmin#705]
Link to domain details is escaped incorrectly and doesn't work. Although all the buttons on the right have the domain escaped correctly and links work properly.

![obrazek](https://user-images.githubusercontent.com/15554561/218695166-c5dbeffb-6e22-4f09-b4b0-fe5e752fbea1.png)

**Comment by DavidGoodwin** [comment]
This might be linked to one of the older tickets around unicode support - #47 ?

**Comment by DavidGoodwin** [comment]
If you edit templates/list.tpl, on line 79 try changing : 

`<a href="list-virtual.php?domain={$item.target_domain|escape:"url"}">{$item.target_domain}</a> `

to

`<a href="list-virtual.php?domain={$item.target_domain|escape:"quotes"}">{$item.target_domain}</a> `


Does that fix it?


I'm not sure what the correct behaviour is here - I feel we should be using url escaping (see e.g https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.md#output-encoding-for-url-contexts )

What are the domains stored as in your database? 

Perhaps the link should be : 

`<a href="list-virtual.php?domain={$RAW_item.target_domain|escape:"url"}">{$item.target_domain}</a> `

?
