### ISSUE TITLE
Wrong checkbox icons on activate toggle buttons

### ISSUE THREAD

**Issue by waclaw66** [postfixadmin/postfixadmin#706]
There are wrong checkbox icons for domain redirection and mailbox redirection in domain overview. Mailboxes seems ok.

ANO = YES
NE = NO
![obrazek](https://user-images.githubusercontent.com/15554561/218735920-44b2b21d-db05-4ca2-933e-19cbeb2e6b1e.png)

current 3.4-dev

**Comment by DavidGoodwin** [comment]
thanks for the bug report - I had a quick look at list.tpl - but I can't (easily) figure out why this code block is presumably not working correctly - https://github.com/postfixadmin/postfixadmin/blob/0344e729d03c99f59ffcb73b5567ce2fd25c7030/templates/list.tpl#L78

**Comment by waclaw66** [comment]
it's because of 
https://github.com/postfixadmin/postfixadmin/blob/0344e729d03c99f59ffcb73b5567ce2fd25c7030/templates/list.tpl#L86
`$item._active` is localized to `ANO`

**Comment by DavidGoodwin** [comment]
Thanks - I meant I couldn't find out where $item['_active'] was being set was....


Try just changing that line (86) to 

```smarty
{if $item._active == $PALANG['YES']}
```
