### ISSUE TITLE
dovecot:CRYPT-METHOD can not be used 

### ISSUE THREAD

**Issue by Coeur2Boeuf** [postfixadmin/postfixadmin#709]
dovecot:* example CRAM-MD5, HMAC-MD5, etc,... was never used with doveadm

see my PR to fix it : https://github.com/postfixadmin/postfixadmin/pull/708

**Comment by DavidGoodwin** [comment]
Hi - 

Thanks for the bug report.

The intention to try and avoid using the `doveadm pw ...` process call

see also #430 or #171 or #528  or #379 and 

https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/HASHING.md

but I think that's the only option if you do want to do CRAM/HMAC stuff ......

**Comment by DavidGoodwin** [comment]
PR merged ... many thanks
