### ISSUE TITLE
release postfixadmin 3.3.13 version string old in downloadable archive

### ISSUE THREAD

**Issue by donvipre** [postfixadmin/postfixadmin#711]
Hi,

## actual behaviour

I recently updated from 3.3.11 to 3.3.13 and wondered some time why the updated didn't happen.
Until I found out that the archive 3.3.13 does not include the correct version string but "3.3.11".

The tag postfixadmin-3.3.13 appears do be old and not linked to the fix in #694

https://github.com/postfixadmin/postfixadmin/blob/b6eab5daed03a5c12f7d37b2ed6b6d0734878b86/config.inc.php#L703

## expected behaviour

`$CONF['version'] = '3.3.13'` behind tag postfixadmin-3.3.13 and zip archive.

**Comment by donvipre** [comment]
this most likely also affects 3.3.12

**Comment by DavidGoodwin** [comment]
Hi @donvipre - I've been "told off" before for moving/updating tags .... and trying to rewrite the past (i.e. moving the tag / force pushing etc).

So the 'version' thing will get updated whenever there is a new release (i.e. 3.3.14 ?).

I didn't see much point in having a new release (3.3.14) just to fix the version string in the footer.

**Comment by DavidGoodwin** [comment]
See also #701
