### ISSUE TITLE
postfix admin getting errors on setup page

### ISSUE THREAD

**Issue by Leonvkampen** [postfixadmin/postfixadmin#712]
I have no clue what is going wrong, postgres is working I can connect to it via command line but here in postfixadmin its failing. 

Could anyone help me further?

Hosting Environment Check
Information
✅ PHP version - 8.2.3
✅ Webserver - Apache/2.4.54 (Debian)
✅ Postfixadmin installed at - /var/www/postfixadmin/public
✅ config.local.php file found : /var/www/postfixadmin/config.local.php
✅ Database - MySQL (pdo_mysql) extension not found
✅ Password hashing - $CONF["encrypt"] = dovecot:ARGON2I
✅ Password hashing - $CONF["encrypt"] - hash generation OK
✅ Database connection configured OK (using PDO pgsql:dbname=postfixadmin;host=localhost;port=5432;options='-c client_encoding=utf8')
✅ Depends on: PHP session support - OK
✅ Depends on: PHP pcre support - OK
✅ Depends on: PHP mbstring support - OK
Warnings
⚠ Database - PostgreSQL (pdo_pgsql) extension not found
⚠ Database support - SQLite (pdo_sqlite) extension not found
⚠ Warning: Optional dependency 'imap' extension missing, without this you may not be able to automate creation of sub-folders for new mailboxes
Errors (MUST be fixed)
⛔Database connection string : pgsql:dbname=postfixadmin;host=localhost;port=5432;options='-c client_encoding=utf8'
⛔Problem connecting to database, check database configuration ($CONF['database_*'] entries in config.local.php)
⛔could not find driver
Database Update
Something went wrong while trying to connect to the database. A message should be logged - check PHP's error_log ()

\n
Could not connect to database to perform updates; check PHP error log.

**Comment by DavidGoodwin** [comment]
Hi - Is there anything printed in e.g. /var/log/apache2/error.log (or equivalent)?

**Comment by Leonvkampen** [comment]
nothign really only this

**Comment by Leonvkampen** [comment]
okay i found some more I keep getting this in the logs .

[Sat Feb 25 12:33:37.752055 2023] [php:notice] [pid 60803] [client 77.170.55.170:56394] Couldn't perform PostfixAdmin database update - failed to connect to db? could not find driver Trace: #0 /var/www/postfixadmin/functions.inc.php(1694): PDO->__construct()\n#1 /var/www/postfixadmin/public/setup.php(338): db_connect()\n#2 {main}

**Comment by Leonvkampen** [comment]
okay i fixed it, I missed the driver pdo_mysql.

To check this i used php -i | grep pdo_mysql


To install this package i ran sudo apt-get install php-mysql

**Comment by DavidGoodwin** [comment]
the `white_check_mark Database - MySQL (pdo_mysql) extension not found ` should have been shown was a warning in the setup.php output.

Your original database connection string referenced pgsql, so I'm surprised installing `pdo_mysql` would fix anything, but if you're happy ....

**Comment by Leonvkampen** [comment]
> the `white_check_mark Database - MySQL (pdo_mysql) extension not found ` should have been shown was a warning in the setup.php output.
> 
> Your original database connection string referenced pgsql, so I'm surprised installing `pdo_mysql` would fix anything, but if you're happy ....

I tried using mysql instead of postgres this didnt fix anything. than i found the fix with mysql propably would've fixed it for postgres to
