### ISSUE TITLE
Menubar icon does not use theme icon

### ISSUE THREAD

**Issue by dkatheininger** [postfixadmin/postfixadmin#718]
in templates/menu.tpl the menubar icon is hardcoded to `images/postbox.png`

It seems that the code that uses the theme icon `{$CONF.theme_logo}` was commented out for some reason. 

`{***<a class="navbar-brand" href='main.php'><img id="login_header_logo" src="{$CONF.theme_logo}" alt="Logo" /></a>***}
<a class="navbar-brand" href='main.php'><img id="login_header_logo" src="images/postbox.png"  alt="Logo"/></a>`

**Comment by DavidGoodwin** [comment]
presumably it ought to be : 

`     <a class="navbar-brand" href='main.php'><img id="login_header_logo" src="{$CONF.theme_log|default('images/postbox.png')}"
                                                             alt="Logo"/></a> `

?
