### ISSUE TITLE
Cant login into postfix admin

### ISSUE THREAD

**Issue by Brutalalex** [postfixadmin/postfixadmin#719]
Hi, I'm trying to log into Postfix admin, I always make a super admin account, but I can't log in. If I look at the database, it says there is no new super admin account generated.

This says to me in admin:

```
⛔Password Hashing - attempted to use configured encrypt backend (dovecot:ARGON2I) triggered an error: /usr/bin/doveadm pw -r 5 failed, see error log for details
⛔You will have problems logging into PostfixAdmin.
⛔Check out our Dovecot documentation at https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/DOVECOT.txt, specifically around '3. Permissions'.
```

Can someone help me?

**Comment by DavidGoodwin** [comment]
Try looking in your web server's error log ? (e.g. /var/log/apache2/error.log)

(Sorry for the delay in replying - i didn't see a notification for it)

**Comment by swany7** [comment]
Hi? i have a same problem
[Sun Jul 07 16:54:56.850875 2024] [php7:notice] [pid 20246] [client 10.2.1.1:65461] Failed to read password from /usr/bin/doveadm pw ... stderr: doveadm: Error: net_connect_unix(/run/dovecot/stats-writer) failed: Permission denied\n, password: {CRAM-MD5}63f73fd5c7d215dc...e2880a037c3\n , referer: https://mx2.

**Comment by swany7** [comment]
by now fix by chmod 666 /run/dovecot/stats-writer but may be it is not good?

**Comment by DavidGoodwin** [comment]
It's either that or you need to change e.g. the group ownership of the file.... i think you can configure this within dovecot ?

see also : https://forums.freebsd.org/threads/mail-dovecot-stats-writer-failed-permission-denied.69723/
or https://serverfault.com/questions/1118069/dovecot-postfix-ldaroot-error-net-connect-unix-run-dovecot-stats-writer

**Comment by Grokenberger** [comment]
What's about a

`gpasswd -a postfixadmin vmail (or whoever owns the stats-writer socket)`

Could it have less impact in security considerations?

**Comment by swany7** [comment]
I fix problem by dovecot.conf 0666 - link up, many thanks!
