### ISSUE TITLE
Custom fileds 'ts' type, update event

### ISSUE THREAD

**Issue by lexxai** [postfixadmin/postfixadmin#72]
I try extend custom fields by extend struct hook.
Database filed 'x_expire' is  NULL by default value and have type: datatime;
```
function x_ext_mailbox($struct) {
 $struct['x_expire'] =  pacol(1, 1, 1, 'ts','x_expire','x_expiredate',0);
}
$CONF['mailbox_struct_hook']        = 'x_ext_mailbox';
```
![pf1](https://user-images.githubusercontent.com/9219334/30037063-117002b8-91c1-11e7-8504-b7d1c1651c04.PNG)

How I can control update event, for replace entered empty or 0 value, to NULL  record to database ?
For now if db filed have NULL value, used edit form show '0' in , and if i try update user data, have error of update database;

![pf2](https://user-images.githubusercontent.com/9219334/30037064-119be838-91c1-11e7-8676-ae162c75b47f.PNG)

For search solution I added default value:
``` $struct['x_expire']['default'] = '2999-12-31';```
But it fill at all users data 2999-12-31, instead of NULL. 

![pf4](https://user-images.githubusercontent.com/9219334/30037231-8b97256c-91c1-11e7-8672-365dfe7941a0.PNG)

And need write custom script that external connect to database and replace value 2999-12-31 to NULL
```$CONF['mailbox_postedit_script'] = 'some_shell_script.sh';```

How I can update result w/o use external postedit_script?

May be I can have some methods how redefine ```beforestore()```   in config.local.php ?
```
    public function store() {
        if ($this->values_valid == false) {
            $this->errormsg[] = "one or more values are invalid!";
            return false;
        }

        if ( !$this->beforestore() ) {
            return false;
```

**Comment by DavidGoodwin** [comment]
Perhaps https://github.com/postfixadmin/postfixadmin/blob/master/model/PFAHandler.php#L550 needs some special behaviour for 'ts' columns.

**Comment by DavidGoodwin** [comment]
your code here -

```
function x_ext_mailbox($struct) {
 $struct['x_expire'] =  pacol(1, 1, 1, 'ts','x_expire','x_expiredate',0);
}
```

should probably be passing $struct in as a reference - so perhaps becomes : 

```
function x_ext_mailbox(&$struct) {
 $struct['x_expire'] =  pacol(1, 1, 1, 'ts','x_expire','x_expiredate',0);
}
```
