### ISSUE TITLE
Warning: Optional dependency 'imap' extension missing

### ISSUE THREAD

**Issue by Dmitry-I-Gornev** [postfixadmin/postfixadmin#721]
Hi

When installing the program from the PostfixAdmin 3.3.8.tar.gz file, I have the following warning:
Warning: Optional dependency 'imap' extension missing, without this you may not be able to automate creation of sub-folders for new mailboxes

The system on which I install the program has the following characteristics:

```
[root@apps ~]#  rpm -qa | grep imap
php-imap-8.0.28-1.el7.remi.x86_64

[root@apps ~]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

[root@apps ~]# php -v
PHP 8.0.28 (cli) (built: Feb 14 2023 11:05:44) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.28, Copyright (c) Zend Technologies

[root@apps ~]# cat /var/www/vhosts/postfixAdmin/pfa/config.local.php
<?php

$CONF['configured'] = true;
$CONF['emailcheck_resolve_domain'] = 'NO';
$CONF['footer_text'] = 'Return to postfixadm.local';
$CONF['footer_link'] = 'http://postfixadm.local:8081';
$CONF['default_language'] = 'ru';
$CONF['database_type'] = 'pgsql';
$CONF['database_host'] = '127.0.0.1';
$CONF['database_user'] = 'postfix';
$CONF['database_password'] = '...';
$CONF['database_name'] = 'postfix';
$CONF['setup_password'] = '$...';
$CONF['create_mailbox_subdirs'] = array();
$CONF['create_mailbox_subdirs_host']='127.0.0.1';

?>
[root@apps ~]#
```

What do I need to do to get the program to see php-imap?

Thank you.

**Comment by DavidGoodwin** [comment]
run 'php -m' - you want to see an 'imap' listed.

Depending on your Linux distribution, installation might be as simple as an `apt-get install php-imap`

**Comment by DavidGoodwin** [comment]
(you probably don't need the imap extension)

**Comment by Dmitry-I-Gornev** [comment]
> run 'php -m' - you want to see an 'imap' listed.

[root@apps ~]# php -m | grep imap
imap
`

**Comment by Dmitry-I-Gornev** [comment]
> (you probably don't need the imap extension)

maybe I won't need it. But the message itself raises a question. php-imap is installed.

**Comment by DavidGoodwin** [comment]
is 'imap' enabled within apache (or whatever web variant you're using?)

(`phpenmod -v ALL -s ALL imap` ... if you're using something debian based, off the top of my head)
