### ISSUE TITLE
Illegal mix of collations latin1_general_ci and utf8_general_ci

### ISSUE THREAD

**Issue by Ramzzes** [postfixadmin/postfixadmin#722]
This situation happens if the postfix queue receives an email address that consists of more than just ascii characters.

Log entry
`postfix/proxymap: warning: mysql:/etc/postfix/sql/mysql_virtual_alias_maps.cf: query failed: Illegal mix of collations (latin1_general_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='`

After that Postfix won't accept or send mail from any account for quite a long time, giving an error
`451 4.3.0 <xxx@yyy.com>: Temporary lookup failure;`

Since such mail could be lying in the queue for days, occasionally trying to send, the server is actually down for that time.

**System configuration**
Debian 10.13
Postfix 3.4.23
MariaDB 10.3.38
Postfixadmin 3.3.13

mysql_virtual_alias_maps.cf
```
user = postfix
password = ...
hosts = localhost
dbname = postfix
table = alias
select_field = goto
where_field = address
additional_conditions = AND active = '1'
```

table alias schema
```
CREATE TABLE `alias` (
  `address` varchar(255) NOT NULL,
  `goto` text NOT NULL,
  `domain` varchar(255) NOT NULL,
  `created` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `modified` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `active` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`address`),
  KEY `domain` (`domain`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci COMMENT='Postfix Admin - Virtual Aliases';

```

MariaDB variables
```
character_set_client	utf8
character_set_connection	utf8
character_set_database	utf8
character_set_filesystem	binary
character_set_results	utf8
character_set_server	utf8
character_set_system	utf8
collation_connection	utf8_general_ci
collation_database	utf8_general_ci
collation_server	utf8_general_ci
```

**Comment by DavidGoodwin** [comment]
seen #690 ?

**Comment by Ramzzes** [comment]
Yes, I saw that.
I had to convert the table to utf-8 to make Postfix work without errors.

**Comment by DavidGoodwin** [comment]
Ah ok - so are you using an out of date version of PostfixAdmin ? (or have we somehow messed up an upgrade that ought to have fixed it? )

(thank for the quick reply / confirmation that it's fixed)

**Comment by Ramzzes** [comment]
No, I am using the current version of PostfixAdmin 3.3.13.
It's just that the server was down for the second time in the last three days, users are complaining, I can't wait.

**Comment by charleslcso** [comment]
Hello @Ramzzes  and @DavidGoodwin I come across this when we need to use UTF8 characters in email addresses.

I'm on 3.3.5. 

So your issue is the database tables not in UTF-8?

**Comment by DavidGoodwin** [comment]
see https://github.com/postfixadmin/postfixadmin/discussions/741 and https://github.com/postfixadmin/postfixadmin/issues/327 - upgrading to 3.3.15 should update your database and fix the latin1 things.

I'm not sure about postfixadmin's utf-8 support though - I think it should be fine for the mailbox side of things, but I think the domain(s) are problematic - #47 is still open afterall.

**Comment by charleslcso** [comment]
> see #741 and #327 - upgrading to 3.3.15 should update your database and fix the latin1 things.
> 
> I'm not sure about postfixadmin's utf-8 support though - I think it should be fine for the mailbox side of things, but I think the domain(s) are problematic - #47 is still open afterall.

Sorry, I need to use utf8mb4 to get proper (?) support including emoji. Not that I would use emoji in email addresses...

Would upgrading be sufficient?

**Comment by DavidGoodwin** [comment]
``` 
CREATE TABLE `mailbox` (
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_ai_ci NOT NULL,
  `maildir` varchar(255) NOT NULL,
  `quota` bigint(20) NOT NULL DEFAULT 0,
  `local_part` varchar(255) NOT NULL,
  `domain` varchar(255) NOT NULL,
  `created` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `modified` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `phone` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `email_other` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `token` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `token_validity` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `password_expiry` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY (`username`),
  KEY `domain` (`domain`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci COMMENT='Postfix Admin - Virtual Mailboxes'
```

is the schema 3.3.15 creates.

I'm not sure why there is utf8mb3 involved ... perhaps it's a distro thing ... 

```
MariaDB [postfixadmin_test]> show variables where Value like '%utf8%'; 
+--------------------------+-------------------------------+
| Variable_name            | Value                         |
+--------------------------+-------------------------------+
| character_set_client     | utf8mb3                       |
| character_set_collations | utf8mb4=utf8mb4_uca1400_ai_ci |
| character_set_connection | utf8mb3                       |
| character_set_database   | utf8mb4                       |
| character_set_results    | utf8mb3                       |
| character_set_server     | utf8mb4                       |
| character_set_system     | utf8mb3                       |
| collation_connection     | utf8mb3_general_ci            |
| collation_database       | utf8mb4_uca1400_ai_ci         |
| collation_server         | utf8mb4_uca1400_ai_ci         |
| old_mode                 | UTF8_IS_UTF8MB3               |
+--------------------------+-------------------------------+
```

**Comment by charleslcso** [comment]
Thank you @DavidGoodwin . 

mb3... 

1. would I lose all my existing data in db? of course I'll back up first, but it is still a major hassle
2. if my Debian 12 has the same result as you, that is, mb3, then I need to change it to mb4 manually. Then why bother upgrading? I might as well keep my version, and just update the db... 

What do you think?

**Comment by DavidGoodwin** [comment]
You don't need to lose the data in the mailbox table in order to change e.g the collation.

I think the 3.3 branch is defaulting to mb3 because the schema upgrade.php script has `CHARACTER SET utf8` in it - while master has `CHARACTER SET utf8mb4` - 

 * https://github.com/postfixadmin/postfixadmin/blob/postfixadmin_3.3/public/upgrade.php#L249
 * https://github.com/postfixadmin/postfixadmin/blob/master/public/upgrade.php#L260 


Looking at the 'git blame' output, I'm inclined to think 3.3 should have the utf8mb4 change applied.
