### ISSUE TITLE
Feature Request: Account Expiration Date

### ISSUE THREAD

**Issue by michalsalamucha** [postfixadmin/postfixadmin#726]
It would be nice if the administrator had the option to set an expiration date when adding an account.  When your account expires, it would automatically go into an inactive state. Is there a possibility that this functionality will be available in future versions?

**Comment by DavidGoodwin** [comment]
There's already password expiry support, but that's slightly different from what you're asking about.

I suppose you could ...
 * Add a custom field to mailbox (E.g. expires_at) and update the SQL for dovecot/postfix to include something like `WHERE expires_at > NOW()` 
 * If you can figure out the custom field support in the PFAHandler class thing, I think you could have the field appear within postfixadmin and be configurable - see around https://github.com/postfixadmin/postfixadmin/blob/master/model/MailboxHandler.php#L60
