### ISSUE TITLE
Errors during setup on new VPS

### ISSUE THREAD

**Issue by mr-buffy** [postfixadmin/postfixadmin#728]
Hi, I am setting up Postfixadmin on a new VPS, Ubuntu 20.0.4.6

During setup phase I am getting these errors: 
    ⛔Password Hashing - attempted to use configured encrypt backend (dovecot:ARGON2I) triggered an error: /usr/bin/doveadm pw -r 5 failed, see error log for details
    ⛔Possibly helpful error_log messages -
    [02-May-2023 04:29:30 UTC] Failed to read password from /usr/bin/doveadm pw -r 5 ... stderr: doveadm(emerge3d): Error: net_connect_unix(/var/run/dovecot/stats-writer) failed: Permission denied
    , password: {ARGON2I}$argon2i$v=19$m=32768,t=5,p=1$+2Lv4keK1oL4bJoLGta0Wg$BnTDYtd7Keguoq/7aFjeetcviWNnnYd6AslugerZvdo
    ⛔You will have problems logging into PostfixAdmin.
    ⛔Check out our Dovecot documentation at https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/DOVECOT.txt, specifically around '3. Permissions'.

I am a little lost at trouble shooting, thanks

**Comment by DavidGoodwin** [comment]
Hi -

See https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/DOVECOT.txt#L152 - which should give you how to fix it (you need to change some file permissions and add the www-data user to the dovecot group).

If you can think of improvements to wording the '3. Permissions' section (linked to above) to make it more obvious/clear/friendly, I'm happy to make changes! 

Thanks,
David.
