### ISSUE TITLE
Unable to login into my emails

### ISSUE THREAD

**Issue by DeltaNicola** [postfixadmin/postfixadmin#729]
Hello everyone.

Sorry in advance if my question has already been answered elsewhere, but I'm not really skilled in troubleshooting this sort of problems.
Since this morning I was unable to login into every email I made, and this issue was not only concerning my own emails (set up with my own domain), but also other domains and their emails.

I leave here a screenshot of the `/var/log/apache2/postfixadmin_error.log`
If you guys would be so kind to lead me into what I should do in order to solve this issue, feel free to respond.
If you need anything else, like any other configuration, feel free to ask.

Thanks in advance.
![boh](https://user-images.githubusercontent.com/100431260/236289355-69ea8c64-03c4-4d31-83e5-1c1ae14e7ef1.PNG)

**Comment by DavidGoodwin** [comment]
Hi - 
What setting do you have for `$CONF['encrypt']` ?

If it's something involving dovecot, then I suspect something has been updated and you've got the same problems as e.g. #728 

See also  https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/DOVECOT.txt#L152

**Comment by DeltaNicola** [comment]
Hi! 
Thanks for the reply
This is the configuration of che config.local.php:

![image](https://user-images.githubusercontent.com/100431260/236486796-a5532b09-76ce-4c19-9b54-04cd7c354fd8.png)

**Comment by DavidGoodwin** [comment]
Your problem is almost certainly going to be due to your use of doveadm. Login as the 'www-data' or however, and try and run `doveadm pw ...` .... you'll probably find it's outputting messages to stderr etc - see the link I posted above
