### ISSUE TITLE
mysqli db connect to socket

### ISSUE THREAD

**Issue by j4Hu** [postfixadmin/postfixadmin#73]
hi, 
i have problem to connect postfixadmin to mysql-i server not listening on tcp.
with mysql driver you can specify connection to socket with config option:

**config.local.php**:
`$CONF['database_type'] = 'mysql';
$CONF['database_host'] = ':/var/run/mysqld/mysqld_sys.sock';`

with mysqli, i must modify code.

**config.local.php**:
`$CONF['database_type'] = 'mysqli';
$CONF['database_socket'] = '/var/run/mysqld/mysqld_sys.sock';`

**functions.inc.php**:1274:
`$link = @mysqli_connect ($CONF['database_host'], $CONF['database_user'], $CONF['database_password'], $CONF['database_name'], $CONF['database_port'], $CONF['dat     abase_socket']) or $error_text .= ("<p />DEBUG INFORMATION:<br />Connect: " .  mysqli_connect_error () . "$DEBUG_TEXT");`

pls add support for socket connection in mysql-i functions.
tnx

**Comment by DavidGoodwin** [comment]
thanks ... does that fix things for you?

(I think we should remove mysql_ support anyway, and add in PDO instead, but that's a different can of worms).

**Comment by j4Hu** [comment]
tnx much, for my setup works.
