### ISSUE TITLE
Custom database field

### ISSUE THREAD

**Issue by enriluis** [postfixadmin/postfixadmin#732]
In previous versions, prior to the update, I used custom fields in the database and corresponding fields in mailbox properties, such as department, age, or any other user information. I added the corresponding fields to the database, and of course, I had been using this method for many years, and upgraded and migrated the code of MailboxHandler.php, i aded the corresponding lang too and it worked. However, in this version, it is not working
`	    'x_alcance'       => pacol(   1,          1,      1,      'enum', 'mailbox_Alcance'  	    , 'Selecciona_mailbox_Alcance'      , 'Local', $src_alcance_options ),#Seleecionar el Alcance del Mensaje
	    'x_departamento'  => pacol(   1,          1,      1,      'enum', 'mailbox_departamento'        , 'Selecciona_mailbox_departamento' , 'Local', $mailbox_departamento ),
	    'x_nota'          => pacol(   1,          1,      1,      'text', 'mailbox_Nota'  		    , 'add_mailbox_Nota'		,''),
	    'x_msgsize'       => pacol(   1,          1,      1,      'enum', 'mailbox_msg_size'            , 'add_mailbox_msg_size' 		, '2048', $mb_mailbox_msg_size ),
            'quota'           => pacol(	  1,          1,      1,      'int' , 'pEdit_mailbox_quota'         , 'pEdit_mailbox_quota_text'        , '' ), # in MB
	    'x_scan_msg'      => pacol(   1,          1,      1,      'enum', 'scan_msg'             	    , 'scan_msg_desc'    		, 'yes',$scan_msg_rule), 
	    'x_allow_ext'     => pacol(   1,          1,      1,      'bool', 'x_permit_ext'                , 'x_permit_ext_desc' 		, '0'), 
`

**Comment by enriluis** [comment]
sorry, wass a code error! it work in the new version! thanks

**Comment by DavidGoodwin** [comment]
glad to hear it - I didn't think we'd made any recent changes that could have affected this.
