### ISSUE TITLE
running custom action and scripts on add, modify or delete account

### ISSUE THREAD

**Issue by enriluis** [postfixadmin/postfixadmin#733]
I need to run some tasks whenever I add, modify, or delete an account. In the past, I used the mailbox_postcreation_script , mailbox_postedit_script, and mailbox_postdeletion_script directives to run custom actions by adding my Bash code and PHP, even using sudo. Now I can't do that - I'm unable to run these custom actions like before, for some reason, my code run outside posfixadmin directly in bash with sudo by the vmail user.

I don't know why it's not working now when it used to. There must be a place to put this code so it runs, but I'm missing something. Does anyone know where I should put custom scripts to run after account creation, editing, and deletion?

**Comment by enriluis** [comment]
it run at somes commands in my code... for example i have the follow   fragment  script 
`#GENERATE RELAY RECIPIENTS FOR UPSTREAM RELAY
RELAYRCPT=/tmp/relay_recipients
TEMP_RELAY=/tmp/tmp-relay_recipients
#SELECT username,'OK' FROM mailbox WHERE x_alcance != 'Local' AND active = 1;
mysql -h $HOST -u $USER -p$PASS -D $DB \
-e "SELECT username, 'OK' 
      FROM mailbox
      WHERE x_alcance != 'Local' AND active = 1
      ORDER BY username ASC
      INTO OUTFILE '$TEMP_RELAY'      
      FIELDS TERMINATED BY '\t'  
      LINES TERMINATED BY '\n';"

mv $TEMP_RELAY $RELAYRCPT
chmod 777 $RELAYRCPT
chown root:mtagroup $RELAYRCPT
postmap $RELAYRCPT
ssh $RELAYRCPT root@myrelay:/remote/dir
`
it give me the /tmp/tmp-relay_recipients file right, but not found this file to execute the rest of the code... in apache i see:
'chmod: cannot access '/tmp/tmp-restricciones': No such file or directory
mv: cannot stat '/tmp/tmp-restricciones': No such file or directory
chown: changing ownership of '/tmp/restricciones': Operation not permitted
mv: cannot stat '/tmp/tmp-relay_recipients': No such file or directory
chown: changing ownership of '/tmp/relay_recipients': Operation not permitted
chown: changing ownership of '/tmp/max.message.size.rules': Operation not permitted
'

**Comment by DavidGoodwin** [comment]
I'm not quite sure what you're doing there, but the problem is probably due to systemd - apache's view of /tmp will be different from roots. 

If this is the case, as root, look in /tmp and you'll see entries like e.g. systemd-private-07c4de3somelongid84615-apache2.service-...  

So when PHP (running in Apache) attempts to look in /tmp, it's actually looking in /tmp/systemd-private...../tmp/

If this is the case, I think you can change the systemd service file to stop it using the the "private" tmp directory...

**Comment by enriluis** [comment]
wow yes this is the case! tmp is inside /tmp/systemd-private.....apache2..../tmp/ and my all resulting files are on it too. 
i disable it on  in /lib/systemd/system/apache2.service  setting PrivateTmp=false systemctl daemon-reload them restarting service   and voila! thanks for point me to right direction!

**Comment by DavidGoodwin** [comment]
Thanks for confirming the problem is fixed :)
