### ISSUE TITLE
ERROR 1819 (HY000): Your password does not satisfy the current policy requirements

### ISSUE THREAD

**Issue by EvilGaming69** [postfixadmin/postfixadmin#735]
Hello, so im trying to install postfixadmin on 22.04 ubuntu and after i create a password it tells me that
![image](https://github.com/postfixadmin/postfixadmin/assets/68130362/3fdb5f07-d9da-47d0-a596-094139399df6)
I have set the password requirements to 0, tried using really complexed passwords, tried using easy passwords etc.
Nothing really works and i cant seem to find a solution for this problem, if anybody knows how to, please help me, i have to finish this work less than in a week or im getting expelled from my college :(

**Comment by DavidGoodwin** [comment]
Hi -

The error message makes me think it's an error being raised by MySQL/MariaDB... is it just asking you to choose a password for your 'root' mysql user?

If so, I'd suggest just using a more complex password (e.g. get one from https://xkpasswd.net/s/ - just avoid choosing a password with quote marks, as that might make things annoying when you go to use it within e.g. PostfixAdmin )


Perhaps try installing default-mysql-server first, deal with whatever questions it asks, and then try the postfixadmin package? 

David.
