### ISSUE TITLE
many issues after upgrading from debian 11 to 12

### ISSUE THREAD

**Issue by damnms** [postfixadmin/postfixadmin#737]
hi, i just upgraded my debian server and now postfixadmin is broken.
first i had to add $CONF['theme_favicon'] = 'images/favicon.ico'; into my config, now it fails with

`AH01071: Got error 'PHP message: Failed to read password from /usr/bin/doveadm pw ... stderr: Error: net_connect_unix(/run/dovecot/stats-writer) failed: Permission denied\nFatal: Missing {scheme} prefix from hash\n, password:  ; PHP message: Error trying to call pacrypt(); PHP message: Exception: /usr/bin/doveadm pw failed, see error log for details in /usr/share/postfixadmin/functions.inc.php:1066\nStack trace:\n#0 /usr/share/postfixadmin/functions.inc.php(1281): _pacrypt_dovecot()\n#1 /usr/share/postfixadmin/model/Login.php(49): pacrypt()\n#2 /usr/share/postfixadmin/public/login.php(63): Login->login()\n#3 {main}; PHP message: PostfixAdmin admin login failed`

the database was not upgraded - i had to purge postfixadmin and reinstall it, no sure what happened there. 
so i *assume* that i might have an old database. i was using 3.2.x and now installed 3.3.13

**Comment by DavidGoodwin** [comment]
@damnms the doveadm is a known issue - see https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/DOVECOT.txt#L152

**Comment by damnms** [comment]
thanks, i changed it to
#$CONF['encrypt'] = 'dovecot:SHA512-CRYPT';
$CONF['encrypt'] = 'php_crypt:SHA512::{SHA512-CRYPT}';
now i get invalid token!, i read that also here, i'll see how far i come ;)
