### ISSUE TITLE
nginx alias Doc root : Please update your webserver config so that the DocumentRoot or Alias points to the directory "public".

### ISSUE THREAD

**Issue by supersophie** [postfixadmin/postfixadmin#739]
HI,

I upgraded to the latest and got this on my nginx server

```
Please update your webserver config so that the DocumentRoot or Alias points to the directory "public".
```

My layout is: 

/var/www/mx.e.org  ( for postfixadmin )
/var/www/cat.org/
/var/www/www.client1.com
/var/www/www.client2.com
/var/www/roundcube.client2.com
and so on.

My point is that my postfixadmin installation is untared into /var/www/mx.e.org/  and I still want to have the URLs as https://mx.e.org

I'm not sure how to do this in nginx:

```
 location / {
      alias /var/www/mx.e.org/public;
      try_files $uri $uri/ /index.php?$args;
    }
```

My existing config is:

```
server {
  listen 80;
  #listen [::]:80 ipv6only=off;
  server_name mx.e.org;
  return 301 https://$server_name$request_uri;
  access_log off;
}
server {
   listen 443 ssl http2 default deferred;
   #listen [::]:443 ipv6only=off ssl;
   server_name     mx.e.org;
   root            /var/www/mx.e.org;
   index           index.php;
   charset         utf-8;
	access_log /var/log/nginx/access.log combined_ssl;
	error_log /var/log/nginx/error.log warn;
   ssl_certificate		/etc/letsencrypt/live/mx.e.org/fullchain.pem ;
   ssl_certificate_key		/etc/letsencrypt/live/mx.e.org/privkey.pem ;
   ssl_prefer_server_ciphers On;
   ssl_protocols TLSv1.2 TLSv1.3;
   #ssl_protocols TLSv1.1 TLSv1.2;
   #ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
   ssl_session_timeout       8m;
   ssl_ecdh_curve            secp384r1;
   #ssl_ecdh_curve            secp521r1;
   ssl_stapling on;
   ssl_stapling_verify on;
   ssl_trusted_certificate /etc/letsencrypt/live/mx.e.org/chain.pem;
   resolver 127.0.0.1 8.8.8.8 valid=200s;
   resolver_timeout 2s;
   add_header X-Content-Type-Options nosniff;
   add_header X-Frame-Options SAMEORIGIN;
   add_header X-Content-Type-Options nosniff;
   add_header X-XSS-Protection "1; mode=block";
   add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
   add_header Referrer-Policy "no-referrer";
   location ~* .(jpg|jpeg|png|gif|ico|css|js)$ {
   expires 365d;
   }
 
   location = / {
      allow 1.2.3.4;
      deny all;
   }
   location ~* \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include       fastcgi_params;
        fastcgi_pass  unix:/run/php/php8.2-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
    fastcgi_hide_header X-Powered-By;
    fastcgi_hide_header Server;
    fastcgi_hide_header X-AspNetMvc-Version;
    fastcgi_hide_header X-AspNet-Version;
   }
	location ~ \.cgi$ {
	root /var/www/cgi-bin;
	include fastcgi_params;
	#include /etc/nginx/fastcgi_params;
	fastcgi_pass fcgiwrap;
	}
	location ~ /\. {
	deny all;
	}
}
```

**Comment by supersophie** [comment]
I tried this:

```
 root            /var/www/mx.e.org;
```

to 

```
 root            /var/www/mx.e.org/public;
```

But got a sick server:

```
2023/06/29 18:08:00 [error] 247848#247848: *16170 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/var/www/mx.e.org/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/mx.e.org/common.php on line 3; PHP message: PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/mx.e.org/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/mx.e.org/common.php:3
Stack trace:
#0 /var/www/mx.e.org/public/common.php(3): require_once()
#1 /var/www/mx.e.org/public/login.php(30): require_once('...')
#2 {main}
  thrown in /var/www/mx.e.org/common.php on line 3" while reading response header from upstream, client: 212.224.239.122, server: mx.e.org, request: "GET /login.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "mx.e.org"
```

**Comment by supersophie** [comment]
This new requirement to put everything under Docroot/public is likely going to break my configuration. 

I've got a better idea. Downgrade to the earlier version I was on, because it worked before. 

I have got a tarball of the earlier postfixadmin installation and a backup of the sqlite dBs.  Am I correct to think that I can just put these back into place and have it workin again?

**Comment by drdelaney** [comment]
> I'm not sure how to do this in nginx:
> 
> ```

I assume you changed or added this. you probably do not need this as the proper change should be below...

>  location / {
>       alias /var/www/mx.e.org/public;
>       try_files $uri $uri/ /index.php?$args;
>     }
> ```
> 
> My existing config is:
> 
> ```
> server {
>   listen 80;
>   #listen [::]:80 ipv6only=off;
>   server_name mx.e.org;
>   return 301 https://$server_name$request_uri;
>   access_log off;
> }
> server {
>    listen 443 ssl http2 default deferred;
>    #listen [::]:443 ipv6only=off ssl;
>    server_name     mx.e.org;
>    root            /var/www/mx.e.org;

change this root line to /var/www/mx.e.org/public.

This will most likely fix your nginx configuration to work with the new versions path changes.

**Comment by drdelaney** [comment]
> /var/www/mx.e.org/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/mx.e.org/common.php on line 3

Did you make sure this file physically exists on the filesystem and your webserver user has correct read permissions to it?
Depending on how you extracted the file it may have overwrote or used generic permissions.

**Comment by drdelaney** [comment]
> This new requirement to put everything under Docroot/public is likely going to break my configuration.

This will probably impact a lot of people.  But it is a common thing to do when using a system like bootstrap, code igniter or similar applications.

> I've got a better idea. Downgrade to the earlier version I was on, because it worked before.

Good idea if you do not mind keeping it behind and not getting feature updates.  I think it would be prudent to take a step back, deploy this on a development directory or server and play around with the files and take your time with this.

> 
> I have got a tarball of the earlier postfixadmin installation and a backup of the sqlite dBs. Am I correct to think that I can just put these back into place and have it working again on the earlier version? It's a choice between a working postfixadmin and a broken one.

Probably.  But you really should have a development environment to play around with staged upgrades. This way you are not crap-posting issues because you broke your production environment and making 3 simultaneous comments that could have been one continuous one.
</goes back to the depths of which i came>

**Comment by DavidGoodwin** [comment]
> I tried this:
> 
> ```
>  root            /var/www/mx.e.org;
> ```
> 
> to
> 
> ```
>  root            /var/www/mx.e.org/public;
> ```
> 
> But got a sick server:
> 
> ```
> 2023/06/29 14:22:00 [error] 247848#247848: *16170 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/var/www/mx.e.org/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/mx.e.org/common.php on line 3; PHP message: PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/mx.e.org/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/mx.e.org/common.php:3
> Stack trace:
> #0 /var/www/mx.e.org/public/common.php(3): require_once()
> #1 /var/www/mx.e.org/public/login.php(30): require_once('...')
> #2 {main}
>   thrown in /var/www/mx.e.org/common.php on line 3" while reading response header from upstream, client: 1.2.3.55, server: mx.e.org, request: "GET /login.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "mx.e.org"
> ```

That's a different issue. I think you've installed what's in 'master' to be getting that error, and you need to run the `install.sh` script (or manually download composer, and do a `composer install -n`).

To clarify 
 * your nginx config just needs '/public' adding onto the 'root'.
 * as you're running 'master', you need to install some PHP libraries through `composer` (See getcomposer.org). If you're "lazy" there's a 'install.sh` script which should download composer and do it all for you.

**Comment by DavidGoodwin** [comment]
Hi - the composer bit is fine -  as you're running things as root, composer issues a warning (but it has still tried to do stuff - it's just not able to as you don't have the mysqli PHP extension installed which it thinks it needs).

(hint: àpt-get install php8.2-mysqli`) 

(Yes, it's possible you have a PostgreSQL database configured and composer is incorrectly flagging this ... you can tell it to ignore extension requirements (`php composer.phar update --ignore-platform-reqs` I think ) ) 


If you want a more stable release, try https://github.com/postfixadmin/postfixadmin/releases 


(If you need a .deb or .rpm to install, there's a chance your local distribution will offer one. If you want to use docker instead, there's a postfixadmin official image).

**Comment by supersophie** [comment]
Mine is a small sqlite file. There are only 25 domains.

**Comment by supersophie** [comment]
Hi,

I have had a while to play around with this a little.  I rolled back to my old version of postfixadmin, and it had the same error.   

This makes me wonder if this is related to the version of PHP I am using which is from Debian 12  php-fpm 2:8.2+93

The nginx error log gives:

`2023/07/02 18:52:15 [error] 287043#287043: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/abc.org/functions.inc.php on line 697" while reading response header from upstream, client: 2.4.4.9, server: abc.org, request: "GET /login.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "abc.org"`


The access log is : 

`2.4.4.1 - - [02/Jul/2023:18:52:15 +0000] TLSv1.3/TLS_AES_256_GCM_SHA384 "GET /login.php HTTP/2.0" 500 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15"`

**Comment by DavidGoodwin** [comment]
@supersophie yes, the problem is viewable because you've upgraded your PHP runtime from something (probably quite old) to something fairly new (8.2.x), and the postfixadmin source code has not been updated to match.

You shouldn't see these error(s) if you are using a recent version of Postfixadmin.

**Comment by supersophie** [comment]
I installed postfixadmin 3.3.13.

**Comment by supersophie** [comment]
Nothing there.  Time to try to start from scratch with my dB..
I've got an sqlite database and I have my old config.local.php.  
 I could do a fresh install, but get it to use my existing database. 
Could I install postfix 3.3.13 in an empty dir., and copy my old config.local.php into the ./config dir, and take it from there?


I've used postfixadmin since 2009, and admittably I have never successfully upgraded it. I have had to re-install each time.

**Comment by supersophie** [comment]
Update: 

Did as I wrote above ( freshly installed into dir /var/www/mx.a.org, nginx root=/var/www/mx.a.org/public, and copied config.local/php over)
 Got instructed to run setup.php because dB was out of date.

Got this:

`Configure and Setup Postfixadmin
This page helps you setup PostfixAdmin. For further help see [the documentation](https://github.com/postfixadmin/postfixadmin/tree/master/DOCUMENTS).

TODO You need to have a setup_pasword hash configured in a config.local.php file
TODO You need to authenticate using the setup_password before you can perform some environment and hosting checks.
One you have logged in with the setup_password, this page will ...

run some simple hosting/environment checks which may help identify problems with your environment
create/update your database of choice,
allow you to list / add super user accounts
For a new installation, you must generate a 'setup_password' to go into your config.local.php file.

You can use the form below, or run something like the following in a shell - php -r 'echo password_hash("password", PASSWORD_DEFAULT);'
Your setup_password is in an obsolete format. As of PostfixAdmin 3.3 it needs regenerating.

Generate setup_password
Setup password
Setup password (again)
Hosting Environment Check
Hosting Environment warnings found. Login to see details.
Database Update
Everything seems fine... attempting to create/update database structure

Updating database:
- old version: 1836; target version: 1847

  (If the update doesn't work, run setup.php?debug=1 to see the detailed error messages and SQL queries.)
updating to version 1837 (all databases)...   done
updating to version 1837 (SQLite)...   done
updating to version 1839 (all databases)...   done
updating to version 1841 (SQLite)...   done
updating to version 1842 (all databases)...   done
updating to version 1843 (all databases)...   done
updating to version 1844 (all databases)...   done
updating to version 1845 (all databases)...   done`

Note that I did not enter a password into the **Generate_set_password** field.

**Comment by supersophie** [comment]
I see a new field when I set up domains:  

`Date when password will expire = 365`



Now, this is a nasty trip up. 

Can I add this anwhere into my config.local.php?
`$CONF['password_expiration'] = 'NO';`

**Comment by DavidGoodwin** [comment]
@supersophie the database updates will indeed run before you have authenticated yourself on the setup.php page; that's intentional ...

**Comment by DavidGoodwin** [comment]
Am i right in thinking everything is fixed and this ticket can be closed?

**Comment by supersophie** [comment]
Yes, everything looks good to me.
Thank-you so much for your help David.
