### ISSUE TITLE
Error in viewlog.php

### ISSUE THREAD

**Issue by quicktrick** [postfixadmin/postfixadmin#74]
From Nginx error log:

> 2017/09/05 20:26:05 [error] 24177#24177: *6898 FastCGI sent in stderr: "PHP message: PHP Notice:  Use of undefined constant page_size - assumed 'page_size' in /var/www/postfixadmin/viewlog.php on line 63" while reading response header from upstream, client: 192.168.1.1, server: zzz.no-ip.org, request: "GET /postfixadmin/viewlog.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "zzz.no-ip.org", referrer: "https://zzz.no-ip.org/postfixadmin/list-virtual.php?domain=zzz.no-ip.org"

Line 63 of viewlog.php:

    $query = "SELECT timestamp,username,domain,action,data FROM $table_log WHERE domain='$fDomain' ORDER BY timestamp DESC LIMIT " . intval($CONF[page_size]);

Please, correct  `intval($CONF[page_size])`, it must be  `intval($CONF['page_size'])`

**Comment by quicktrick** [comment]
Current state of master branch -- error in viewlog.php again.

From Nginx error log:

> 2017/09/13 10:03:11 [error] 3398#3398: *218 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ')' in /srv/www/zzz.zzz/postfixadmin/viewlog.php on line 65" while reading response header from upstream, client: 95.28.10.194, server: webmail.artinvestment.ru, request: "GET /postfixadmin/viewlog.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "zzz.zzz", referrer: "https://zzz.zzz/postfixadmin/edit.php?table=adminpassword"

Line 65:

    $query = "SELECT timestamp,username,domain,action,data FROM $table_log WHERE domain='$fDomain' ORDER BY timestamp DESC LIMIT $page_size");

Please, remove the trailing `)`

**Comment by cboltz** [comment]
Fixed, thanks for the report!
