### ISSUE TITLE
Error handling with single quote in a password

### ISSUE THREAD

**Issue by b90g** [postfixadmin/postfixadmin#742]
If i enter a password for a new user with a single quote `'` and  submit my form i get only a white page.

I expected feedback that i might have entered a forbiddem sign, but i get `500 Internal Server Error`

let me know of you need more info (server version etc).

**Comment by DavidGoodwin** [comment]
Hi @b90g - are there any error message(s) logged in the webserver's error log (e.g. /var/log/apache2/error.log) that give a bit more information?

**Comment by b90g** [comment]
sorry for wasting your time, turns out we had a password blocklist feature installed which didnt santize the input before querying... (:
