### ISSUE TITLE
"GB" for Mailbox/Domain Quota?

### ISSUE THREAD

**Issue by ozgurkazancci** [postfixadmin/postfixadmin#746]
Greetings.

We have already passed the era of gigabytes when it comes to data. Do you plan supporting "GB" directive for the "Mailbox Quota (MB)" and "Domain Quota (MB)" values? E.g.; '1GB' as value.

Best,
Özgür Konstantin.

**Comment by DavidGoodwin** [comment]
Yes, this is probably overdue, I can't think many people allocate mailbox quota below 0.5GB....

**Comment by neuffer** [comment]
Don't be so sure.
I have a customer where employees still get a 100MB mailbox on Exchange per default and they do not extend it beyond 1GB.... 
When they outsourced the service >20 years ago and why should the management change something that has been working for so long (and then pay more money). Of course it is also forbidden to use external mailboxes in the home directory and of course everybody has them, but who cares......
