### ISSUE TITLE
Upgrade passwords from md5crypt to php_crypt

### ISSUE THREAD

**Issue by ztjuh** [postfixadmin/postfixadmin#751]
God bless you! 🌟

I just upgraded my really old installation but the passwords in the database are still `md5crypt`. I would like to upgrade them to `ARGON2ID`. 

Any help?

**Comment by DavidGoodwin** [comment]
What version of Postfixadmin are/were you using?

**Comment by ztjuh** [comment]
Postfix Admin 3.3.13 and then I did a composer update but I think that downgraded the package instead of updated it...

**Comment by ztjuh** [comment]
Yes I used the master documentation.
