### ISSUE TITLE
Suppressing date.timezone warnings

### ISSUE THREAD

**Issue by zsdsys** [postfixadmin/postfixadmin#757]
in vacation.pl there is line 74 with 

`date_default_timezone_set(@date_default_timezone_get()); # Suppress date.timezone warnings`

This has prevented me from realizing I forgot to set the timezone on my new server install

users have been complaining their autoreplies are not working and by the time I test them they are working fine.  Took me a while to figure out the vacation entry in the database had the incorrect timezone and was using UTC so they were not "active yet" by the select query looking for NOW() (in local TZ) when inserted time was in UTC

this really is the reason for that date.timezone warning...  

probably better as config option than set without warning, I could do up the pull if you want

**Comment by DavidGoodwin** [comment]
Hi - Yes - PRs are always welcome :)
