### ISSUE TITLE
Database Update Problem during release update 

### ISSUE THREAD

**Issue by angelo68000** [postfixadmin/postfixadmin#759]
**Hi all when update release the setup.php page report this problem.**

Updating database:

- old version: 1847; target version: 1848

updating to version 1848 (MySQL)...

CREATE TABLE IF NOT EXISTS `dkim` ( `id` int(11) not null auto_increment primary key, `domain_name` varchar(255) NOT NULL, `description` varchar(255) DEFAULT '', `selector` varchar(63) NOT NULL DEFAULT 'default', `private_key` text, `public_key` text, `created` datetime NOT NULL default '2000-01-01 00:00:00', `modified` datetime NOT NULL default '2000-01-01 00:00:00', INDEX(domain_name, description), FOREIGN KEY (`domain_name`) REFERENCES `domain`(`domain`) ON DELETE CASCADE) CHARACTER SET latin1 COLLATE latin1_general_ci COMMENT='Postfix Admin - OpenDKIM Key Table';

SQLSTATE[HY000]: General error: 1824 Failed to open the referenced table 'domain'

**this is description of "domain"  table.**

mysql> desc domain;
+-----------------+--------------+------+-----+---------------------+-------+
| Field           | Type         | Null | Key | Default             | Extra |
+-----------------+--------------+------+-----+---------------------+-------+
| domain          | varchar(255) | NO   | PRI | NULL                |       |
| description     | varchar(255) | NO   |     | NULL                |       |
| aliases         | int          | NO   |     | 0                   |       |
| mailboxes       | int          | NO   |     | 0                   |       |
| maxquota        | bigint       | NO   |     | 0                   |       |
| quota           | bigint       | NO   |     | 0                   |       |
| transport       | varchar(255) | NO   |     | NULL                |       |
| backupmx        | tinyint(1)   | NO   |     | 0                   |       |
| created         | datetime     | NO   |     | 2000-01-01 00:00:00 |       |
| modified        | datetime     | NO   |     | 2000-01-01 00:00:00 |       |
| active          | tinyint(1)   | NO   |     | 1                   |       |
| password_expiry | int          | YES  |     | 0                   |       |
+-----------------+--------------+------+-----+---------------------+-------+
12 rows in set (0.01 sec)

HOW TO SOLVE THIS PROBLEM?

thank you

**Comment by DavidGoodwin** [comment]
What version of MySQL are you using?

**Comment by DavidGoodwin** [comment]
I don't know, try running the query manually? is anything useful output? 

The table presumably does exist, and 'domain' is not a reserved word for MySQL as far as I can see.

Is the domain table marked as crashed?

Is it a character set problem (try : "show create table domain")

**Comment by angelo68000** [comment]
Run query manually report the same problem...   Failed to open the referenced table 'domain'
check table domain not report table marched as crashed.

mysql> check table domain;

+-------------+-------+----------+----------+
| Table       | Op    | Msg_type | Msg_text |
+-------------+-------+----------+----------+
| mail.domain | check | status   | OK       |
+-------------+-------+----------+----------+

thw output of "show create table domain " is : 

| domain | CREATE TABLE `domain` (
  `domain` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `description` varchar(255) CHARACTER SET utf8mb3 NOT NULL,
  `aliases` int NOT NULL DEFAULT '0',
  `mailboxes` int NOT NULL DEFAULT '0',
  `maxquota` bigint NOT NULL DEFAULT '0',
  `quota` bigint NOT NULL DEFAULT '0',
  `transport` varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `backupmx` tinyint(1) NOT NULL DEFAULT '0',
  `created` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `modified` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `password_expiry` int DEFAULT '0',
  PRIMARY KEY (`domain`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci COMMENT='Postfix Admin - Virtual Domains' |

**Comment by angelo68000** [comment]
PROBLEMA SOLVED
adding  "ENGINE=MyISAM"  to the query  

THANK YOU
