### ISSUE TITLE
Password Hashing - attempted to use configured encrypt backend (dovecot:ARGON2I) triggered an error: /usr/bin/doveadm pw -r 5 failed,

### ISSUE THREAD

**Issue by Leonvkampen** [postfixadmin/postfixadmin#770]
So I haven't been on my mail server for a very long time because everything was running fine. 

Now I want to add a new domain but I can't get into the postfixadmin backend. 

This is the problem I am getting :

<img width="910" alt="image" src="https://github.com/postfixadmin/postfixadmin/assets/14541956/a366b7a4-f0db-4f3d-9fca-7582c781cd32">

I have taken a look at the error logs but I have no idea how to fix these issues and what could be the problem as to why I can't log in into the backend. 

Since the email itself on roundcube is working perfectly. 

root@mail:/var/log/apache2# cat postfixadmin_error.log
[Tue Oct 10 02:58:16.913192 2023] [php:error] [pid 2364501] [client :58257] script '/var/www/postfixadmin/public/wp-login.php' not found or unable to stat, referer: http://postfixadmin.domain.nl/wp-login.php
[Tue Oct 10 16:44:50.995513 2023] [php:notice] [pid 2364502] [client :24630] Failed to read password from /usr/bin/doveadm pw -r 5 ... stderr: doveconf: Fatal: Error in configuration file /etc/dovecot/ssl-keys.conf line 1: ssl_cert: Can't open file /etc/letsencrypt/live/mail.domain.nl/fullchain.pem: Permission denied\n, password:  , referer: https://postfixadmin.domain.nl/login.php?a5sun7upyovr3qyuyvegst6wom=czdhlzlxnilutqlovnrmsm5jpe
[Tue Oct 10 16:44:50.995688 2023] [php:notice] [pid 2364502] [client :24630] Error while trying to call pacrypt(), referer: https://postfixadmin.domain.nl/login.php?a5sun7upyovr3qyuyvegst6wom=czdhlzlxnilutqlovnrmsm5jpe
[Tue Oct 10 16:44:50.995731 2023] [php:notice] [pid 2364502] [client :24630] Exception: /usr/bin/doveadm pw -r 5 failed, see error log for details in /var/www/postfixadmin/functions.inc.php:1066\nStack trace:\n#0 /var/www/postfixadmin/functions.inc.php(1281): _pacrypt_dovecot()\n#1 /var/www/postfixadmin/model/Login.php(36): pacrypt()\n#2 /var/www/postfixadmin/public/login.php(63): Login->login()\n#3 {main}, referer: https://postfixadmin.domain.nl/login.php?a5sun7upyovr3qyuyvegst6wom=czdhlzlxnilutqlovnrmsm5jpe
[Tue Oct 10 16:44:50.995791 2023] [php:notice] [pid 2364502] [client :24630] PostfixAdmin admin login failed (username: leon@domain.nl, ip_address: ), referer: https://postfixadmin.domain.nl/login.php?a5sun7upyovr3qyuyvegst6wom=czdhlzlxnilutqlovnrmsm5jpe
[Tue Oct 10 16:45:03.866818 2023] [php:notice] [pid 2370646] [client :24634] Failed to read password from /usr/bin/doveadm pw -r 5 ... stderr: doveconf: Fatal: Error in configuration file /etc/dovecot/ssl-keys.conf line 1: ssl_cert: Can't open file /etc/letsencrypt/live/mail.domain.nl/fullchain.pem: Permission denied\n, password:
[Tue Oct 10 16:45:15.390196 2023] [php:notice] [pid 2362250] [client :24636] Failed to read password from /usr/bin/doveadm pw -r 5 ... stderr: doveconf: Fatal: Error in configuration file /etc/dovecot/ssl-keys.conf line 1: ssl_cert: Can't open file /etc/letsencrypt/live/mail.domain.nl/fullchain.pem: Permission denied\n, password:  , referer: https://postfixadmin.domain.nl/setup.php
[Tue Oct 10 16:49:17.752563 2023] [php:notice] [pid 2365558] [client :24646] Failed to read password from /usr/bin/doveadm pw -r 5 ... stderr: doveconf: Fatal: Error in configuration file /etc/dovecot/ssl-keys.conf line 1: ssl_cert: Can't open file /etc/letsencrypt/live/mail.domain.nl/fullchain.pem: Permission denied\n, password:
[Tue Oct 10 16:49:39.568858 2023] [php:notice] [pid 2362250] [client :24648] Failed to read password from /usr/bin/doveadm pw -r 5 ... stderr: doveconf: Fatal: Error in configuration file /etc/dovecot/ssl-keys.conf line 1: ssl_cert: Can't open file /etc/letsencrypt/live/mail.domain.nl/fullchain.pem: Permission denied\n, password:  , referer: https://postfixadmin.domain.nl/login.php
[Tue Oct 10 16:49:39.568994 2023] [php:notice] [pid 2362250] [client :24648] Error while trying to call pacrypt(), referer: https://postfixadmin.domain.nl/login.php
[Tue Oct 10 16:49:39.569041 2023] [php:notice] [pid 2362250] [client :24648] Exception: /usr/bin/doveadm pw -r 5 failed, see error log for details in /var/www/postfixadmin/functions.inc.php:1066\nStack trace:\n#0 /var/www/postfixadmin/functions.inc.php(1281): _pacrypt_dovecot()\n#1 /var/www/postfixadmin/model/Login.php(36): pacrypt()\n#2 /var/www/postfixadmin/public/login.php(63): Login->login()\n#3 {main}, referer: https://postfixadmin.domain.nl/login.php
[Tue Oct 10 16:49:39.569110 2023] [php:notice] [pid 2362250] [client :24648] PostfixAdmin admin login failed (username: leon@domain.nl, ip_address: ), referer: https://postfixadmin.domain.nl/login.php

[Edit]
Okay I think that this is the issue:
Failed to read password from /usr/bin/doveadm pw -r 5 ... stderr: doveconf: Fatal: Error in configuration file /etc/dovecot/ssl-keys.conf line 1: ssl_cert: Can't open file /etc/letsencrypt/live/mail.domain.nl/fullchain.pem: Permission denied\n, password:

**Comment by Leonvkampen** [comment]
Okay i commented out this line in dovecot.conf and this fixed my issues very weird this was even here. 
#!include_try ssl-keys.conf

But as i stated i havent been on this server for years so maybe it was somthing i was trying. Doesn't look like commenting out this line breaks the ssl certificate

**Comment by DavidGoodwin** [comment]
Hello - see all the various tickets related to #379 - e.g. https://github.com/postfixadmin/postfixadmin/issues?q=is%3Aissue+379+is%3Aclosed

The problem is actually dovecot - and the fact that when you run 'doveadm' from postfixadmin you're doing it as the www-data user (most likely) and doveadm moans that it can't read some dovecot or other referenced files.

If you've not interacted much with postfixadmin recently (no new users, no logins, no password change etc) then you could easily not have noticed.

There is a magic dovecot fix - see e.g. https://github.com/postfixadmin/postfixadmin/issues/398#issuecomment-843124406 - i think you'd need to change your dovecot config a little so the !include_try bit in your main dovecot config loads a file which the www-data user doesn't have access to, and that references your letsencrypt keys?

**Comment by Leonvkampen** [comment]
this magic dovecot fix worked all I had to do was sudo chmod 600 ssl-keys.conf. 

I still don't fully understand what cause this problem, but if it works it works I gues.

Thanks alot for helping me !!!
