### ISSUE TITLE
Problem with css and graphic

### ISSUE THREAD

**Issue by mami5454** [postfixadmin/postfixadmin#772]
Hi
I use postfixadmin-3.3.11. My connections is after NAT and use ngnix

like:
server {
   listen 8845;
   server_name mail-test.domain.ltd

   root /var/www/postfixadmin/public/;
   index index.php index.html;

   access_log /var/log/nginx/postfixadmin_access.log;
   error_log /var/log/nginx/postfixadmin_error.log;

   location / {
       try_files $uri $uri/ /index.php;
   }

   location ~ ^/(.+\.php)$ {
        try_files $uri =404;
        fastcgi_pass 127.0.0.1:9999;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include /etc/nginx/fastcgi_params;
   }

All works fine but postfixadmin not use css. Any idea ?

**Comment by DavidGoodwin** [comment]
What does your browser say are the URLs it's trying to request (when you use the dev tools -> network inspector thingymbob?)

This link might help - https://help.fullstory.com/hc/en-us/articles/360020623654-How-do-I-use-the-Network-view-in-Dev-Tools-
