### ISSUE TITLE
Backend: count support for Dovecot quota?

### ISSUE THREAD

**Issue by ozgurkazancci** [postfixadmin/postfixadmin#773]
Greetings,

I think PostfixAdmin uses "dict backend" of Dovecot, to store and show the used quotas.

However, nowadays, Dovecot recommends using the "count" quota backend, together with Quota Clone Plugin.

Here: https://doc.dovecot.org/configuration_manual/quota/quota_count/#quota-backend-count

And thus, I replaced my quota backend from "dict" to "count" (with all related settings set).

The current quota information for mailbox users shows up&works fine under Roundcube, however PostfixAdmin doesn't show the currently used quota anymore.

![here](https://i.ibb.co/grFFpKs/quota.png)

Is there any workaround/fix for this, or any plan to support the count backend?

Many thanks,
Best.

**Comment by DavidGoodwin** [comment]
Hi - thanks for the bug report ...

PostfixAdmin already supports this backend - it's just using a table called 'quota2' -

```SQL
```SQL
CREATE TABLE quota (
  username varchar(100) not null,
  bytes bigint not null default 0,
  messages integer not null default 0,
  primary key (username)
);
```

which is the same schema as dovecot ask for ... so i think you just need to configure PostfixAdmin to use that quota backend.

The DOCUMENTS/DOVECOT.txt file looks relevant ....

**Comment by ozgurkazancci** [comment]
Hi, I mean this backend;

https://doc.dovecot.org/configuration_manual/quota/quota_count/#quota-backend-count

Are we sure PostfixAdmin supports that above? If so, how to try?

Many thanks.

**Comment by DavidGoodwin** [comment]
I'd agree, it looks like `new_quota_table` is YES by default ... personally I don't use quota, so I can't help any further
