### ISSUE TITLE
"Invalid parameter" bug, right after deleting a domain?

### ISSUE THREAD

**Issue by ozgurkazancci** [postfixadmin/postfixadmin#774]
Hello,

I've encountered an issue, just wanted to report it here;

Go to: "Domain List" at the top menu. Then, delete a domain with the red "del" button.
Afterwards, when you got the "_domain.tld deleted._" message, click to "Virtual List" drop-down menu, and select "Virtual List" there. You will get: "**Invalid parameter!**"

Anyone to replicate that?

PostfixAdmin version: 3.3.13

**Comment by DavidGoodwin** [comment]
I can't replicate that on 'master' or with '3.3.13'. 

Poor man's screen recording attached.....

![postfixadmin-774](https://github.com/postfixadmin/postfixadmin/assets/203929/d6cd9b0b-4a5e-46b3-9574-ba4ee03311e3)
