### ISSUE TITLE
In PostfixAdmin 3.3.13 version not changed

### ISSUE THREAD

**Issue by cppmm** [postfixadmin/postfixadmin#778]
It's not a bug, small fix.
In release 3.3.13 in config.inc.php variable is still `$CONF['version'] = '3.3.11';`

**Comment by computersalat** [comment]
ACK! same here, too
But in branch postfixadmin_3.3 it is fixed already.
Is the tarball not up-to-date ?

**Comment by DavidGoodwin** [comment]
I suspect no one (?me?) has made a new release ... that's all.
