### ISSUE TITLE
How to debug the error "Creating the mailbox admin@graphitecore.pro failed!" 

### ISSUE THREAD

**Issue by RoyBellingan** [postfixadmin/postfixadmin#780]
I tried to look at log, but there is not much just the create_alias command...

(in the past I already created a few domain and email account on other domain)

**Comment by DavidGoodwin** [comment]
hm, I think that'll be from a problem inserting into, or updating, the database. The obvious thing would be e.g. a duplicate primary key ....

Depending on your version of PostfixAdmin, you could probably find out which by editing model/PFAHandler.php and look for the 'save()' function - perhaps around line 548 .... towards the bottom of this function, there's :

```PHP
        try {
            if ($this->new) {
                $result = db_insert($this->db_table, $db_values,  array('created', 'modified'),true);
            } else {
                $result = db_update($this->db_table, $this->id_field, $this->id, $db_values, array('modified'), true);
            }
        } catch (PDOException $e) {
            error_log(__FILE__ . ' - failed to save mailbox; message: ' . $e->getMessage()); // ADD THIS LINE
            $this->errormsg[] = Config::lang_f($this->msg['store_error'], $this->label);
            return false;
        }

```

Hopefully that will then log something useful to your web server's error log file (e.g. /var/log/apache2/error.log)
