### ISSUE TITLE
Rouncube give a white screen

### ISSUE THREAD

**Issue by sovkutsan** [postfixadmin/postfixadmin#781]
hi everyone, I recently discovered that my mail server is on Ubuntu22.04
Operates on 143,537 ports.

I fixed it to 993.465 (SSL/TLS) mail domain to https:// all is well.

But the problem is that Roundcube has stopped showing the login window...

https://mail.example.kg/webmail/

And that's it - a white screen.

I spent the whole evening and night setting up Roundcube..

But error.php, which I created for convenience, always complains about the same inscription...
At line in which the option is the authorization method...

Two questions?

1) Thunderbird works great with the authentication method - a simple password.

2) How can the authentication method affect the white screen?

In the Roundcube config above this line it says “Leave this value empty.” The server itself will select the one you need.
I leave it empty - null;  don't work, again php tell my those string.

Still no pictures, 
I will be glad for any help

**Comment by DavidGoodwin** [comment]
Firstly, this isn't a generic help forum for roundcube or running postfix; PostfixAdmin is a web UI for managing mailboxes/aliases.

Having said the above, I suspect roundcube is erroring for some reason (e.g it's config says to connect on port X and it can't, or some other dependency has changed). I'd expect there to be error logged somewhere - perhaps in `/var/log/apache2/error.log` (or similar). If not, try turning PHP's error reporting on (see `/etc/php/<version>/<web server>/php.ini `and set `log_errors = On`, restart Apache and then try again - perhaps it'll log something. 

Good luck

**Comment by sovkutsan** [comment]
Good afternoon. If I'm writing to the wrong forum, tell me where to write.

Regarding PostfixAdmin, I know what it is and what it is for, I have configured it many times. On different systems. He's fine now. It opens and works

/var/log/apache2/error.log - empty, Apache has been disabled for many days and everything works through Nginx.

Rundcube worked for reception while I had ports 143,537
When I noticed that mail was running on the wrong ports, I reconfigured everything to 993.465 ssl

Mail works (via Thunderbird), postfixadmin works. There are no questions here.

But rouncube complains about an authorization error:
I can only see errors in php.log
[13-Nov-2023 08:20:37 Asia/Bishkek] PHP Parse error: syntax error, unexpected variable "$config" in /var/www/html/webmail/config/config.inc.php on line 307

Here is line 307 and the comment above it from the file /var/www/html/webmail/config.inc.php

// IMAP authentication method (DIGEST-MD5, CRAM-MD5, LOGIN, PLAIN or null).
// Use 'IMAP' to authenticate with IMAP LOGIN command.
// By default the most secure method (from supported) will be selected.
$config['imap_auth_type'] = null;

**Comment by sovkutsan** [comment]
Вот так я собрал основные настройки роундкуб, вместе, аккуратно

///////////////////////////////////////////////// Config for наша фирма //////////////////////////////////////////////////////////
//IMAP

$config['product_name'] = 'Roundcube Webmail';
$config['imap_vendor'] = 'Наша фирма';
$config['default_port'] = 993;
$config['imap_host'] = 'localhost:993'
$config['imap_auth_type'] = null;

//SMTP
$config['smtp_server'] = 'ssl://mail.kan.kg';
$config['default_host'] = 'ssl://mail.kan.kg';
$config['smtp_host'] = 'localhost:465';
$config['smtp_port'] = 465;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';

**Comment by sovkutsan** [comment]
This is how I put the basic roundcube settings together, neatly

/////////////////////////////////////////////// Config for our company ////////////////////////////////////////////// ///////////
//IMAP

$config['product_name'] = 'Roundcube Webmail';
$config['imap_vendor'] = 'Our company';
$config['default_port'] = 993;
$config['imap_host'] = 'localhost:993'
$config['imap_auth_type'] = null;

//SMTP
$config['smtp_server'] = 'ssl://mail.kan.kg';
$config['default_host'] = 'ssl://mail.kan.kg';
$config['smtp_host'] = 'localhost:465';
$config['smtp_port'] = 465;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';

**Comment by sovkutsan** [comment]
I just have to try different authorization options, since now the mail works using encrypted protocols, maybe I need to install CRAM-MD5

in php.ini - log_errors = On

**Comment by DavidGoodwin** [comment]
I can't tell if you still have a problem.

I suspect your problem with config.inc.php is some sort of quoting issue - e.g a ` instead of a ' or something like that, before line 307 in the file.

**Comment by sovkutsan** [comment]
I did Rouncube.  5 days ago, It works perfect.
I found problem myself.
