### ISSUE TITLE
Fetchmail authentication fails when special characters in password

### ISSUE THREAD

**Issue by johnfawcett** [postfixadmin/postfixadmin#782]
I found a case of an imap password containing a slash character \. When running fetchmail.pl authentication was failing. The issue is that the imap server expects slash and double quote characters in passwords to be escaped. 

An easy fix is to update the fetchmail.pl script adding a function to escape these characters, for example:
```
sub escape_password
{
        $output = "";
        for $i (0..length($_[0])-1){
        $char = substr($_[0], $i, 1);
                if ($char eq "\\" or $char eq "\"")
                {
                        $output = $output . "\\";
                }
                $output = $output . $char;
        }
        return $output;
}
```
And then to update where the password is used to

```
       $cmd="user '${src_user}' there with password '".escape_password(decode_base64($src_password))."'";
```

**Comment by DavidGoodwin** [comment]
Thank you for contributing. I don't use fetchmail, so hopefully my copy+pasting will "just work" !
