### ISSUE TITLE
Next release plan?

### ISSUE THREAD

**Issue by ramank775** [postfixadmin/postfixadmin#783]
Hi, what's the plan for next release, any anticipated timeline?

Particularly i am looking for the DKIM setup feature, as that's the only thing for which i need to login into server to add new domain.

**Comment by DavidGoodwin** [comment]
unfortunately there's no real plan !

3.3.0 was from e6e040b2430861d98b69e12ce7ddbf0cce22579e (back in Jan 2021, so it'll soon be 2 years since then, which perhaps makes a nice anniversary?)

I suppose some people might want the TOTP stuff included in a new release ? ( #753 )

**Comment by ozgurkazancci** [comment]
Perhaps a christmas release? :) 🎄

**Comment by DavidGoodwin** [comment]
@progsmile So if there was a 3.3.14 - i think it'd basically be this - https://github.com/postfixadmin/postfixadmin/compare/postfixadmin-3.3.13...postfixadmin_3.3 ?

**Comment by progsmile** [comment]
I'm not full aware of releasing strategy for this repository, just could assume. We have:
branch: `master` with new commits in comparison to `postfixadmin_3.3`
branch: `postfixadmin_3.3` with prev commits from master
tag: `postfixadmin_3.3.13` that has older commits

So this may fit:
- Update `postfixadmin_3.3` with commits from `master`
- Create tag `postfixadmin_3.3.14` from `postfixadmin_3.3.13...postfixadmin_3.3`

**Comment by DavidGoodwin** [comment]
er, I don't follow that ... 

'master' is basically where the development takes place, it may be broken or incomplete. It may also have new shiny things.

every so often we've had a 'major' release, e.g. postfixadmin X.Y, at which point we create a postfixadmin_X.Y branch off master. 

while we support X.Y, we cherry-pick/apply updates to that branch and master (if applicable). Every so often we create a new tag on the branch for a new minor release (X.Y.Z - e.g. 3.3.10).

If we were to create a new 3.3.x release, then the new stuff would be what's shown in my link above - https://github.com/postfixadmin/postfixadmin/compare/postfixadmin-3.3.13...postfixadmin_3.3

Does that make sense?

**Comment by progsmile** [comment]
Ok!
