### ISSUE TITLE
fetchmail.pl $src_port implementation incomplete

### ISSUE THREAD

**Issue by tempixx** [postfixadmin/postfixadmin#784]
Dear all,
we have just started using the fetchmail port entry of the GUI 
(managing two different pop3 servers via stunnel proxy - TCP/110 and TCP/111).
The GUI and DB implementations are fine, but the fetchmail.pl script is incomplete (**bold** entries are missing):
SELECT id,mailbox,src_server,src_auth,src_user,src_password,src_folder,fetchall,keep,protocol,mda,extra_options,usessl,sslcertck,sslcertpath,sslfingerprint,**src_port**
my ($id,$mailbox,$src_server,$src_auth,$src_user,$src_password,$src_folder,$fetchall,$keep,$protocol,$mda,$extra_options,$usessl,$sslcertck,$sslcertpath,$sslfingerprint,**$src_port**)=@$_;
---> tested and works!
BR, Tibi

**Comment by DavidGoodwin** [comment]
Thank you!
