### ISSUE TITLE
Hello everyone, a unique case with basic auth. it does not turn on, at all

### ISSUE THREAD

**Issue by sovkutsan** [postfixadmin/postfixadmin#785]
I want to ask right away, dear Mr. Goodwin.
is this a Linux forum? or am I writing somewhere else? in the wrong section maybe? I'm confused. I don’t know English well, I write and read using Google translate

In general, as always, I’m “lucky”...)) it works for millions of people, it’s very simple
basic_autn "alert text";
basic_auth file/etc/nginx/auth.basis/.htaccess
and that's all
it can even be simpler /etc/nginx/.htaccess
I’m already writing from memory, I didn’t copy it now, the server is not nearly...
What could be simpler?
you insert these two lines into sites-available/default and that’s it.

but it doesn’t turn on)) the authentication window doesn’t appear....))
I sat up the night, from 7 pm to 9 am, I tried everything... absolutely everything...
except installing the ngx_http_auth_basic_module
because my head just fell on the bed, I spent all my strength.....
 I'm sure it's 99% sure it's installed.

I'm sure I'm making some small mistake, I'm missing something important but obvious, but I don't know what.

The only thing I managed to achieve was enabling basic_auth in the main configuration file nginx.conf
then the authorization window is there, but it is impossible to edit directories.
I need to leave one directory open...
but for some reason you can enable basic_auth in the nginx.conf file, but you can’t even use the word “directory”...
nginx -t immediately gives a syntax error

and if I set basic_auth off for the directory I need, then this has no effect... after all, the authorization window is either launched through nginx.conf - which is wrong. Because if I set the value of the directory I need to off in sites-available, nothing happens.
Nothing is enabled via sites-available, no authorization whatsoever...
Maybe because I'm running as root
But it’s unlikely that I own the entire server and always do everything as root... it’s convenient.
The module is definitely installed, I don’t even see the point of checking....

Please tell the fool what I missed? What am I missing? It was even embarrassing to create this topic. It works for everyone in the world, but not for me.

I would be glad for any hint, thanks for your attention...

**Comment by DavidGoodwin** [comment]
Hi there - I don't know - sorry - my knowledge of nginx is minimal, as I've always stuck with Apache.

This isn't a general Linux forum. You should probably try asking somewhere else - like StackOverflow ?
