### ISSUE TITLE
Issue with connection to database with postfixadmin 3.4

### ISSUE THREAD

**Issue by zilon84** [postfixadmin/postfixadmin#793]
Hello,

I am not able to use postfixdmin 3.4 since there is an isue when it tries to connect to the database. Postfixadmin 3.3 is working fine on the same machine.

My machine is running FreeBSD 13.2 with latest patch level. PHP vesion is 8.1. Database is MariaDB 10.6 running in a jail with a different IP.

Output from setp.php:

Database connection string : mysql:mysql:host=LOCALSERVERIP:3306;dbname=db_mailserver;charset=UTF8

It seems that the "mysql:" at the beginning of the conncetion tring is twice there. Might this be the reason for the conncetion issue?

**Comment by DavidGoodwin** [comment]
there isn't an officially released 3.4 version of PostfixAdmin, 

With what's in the 'master' branch at the moment, i see something like this on setup.php

![image](https://github.com/postfixadmin/postfixadmin/assets/203929/39920ed1-b122-4710-a4a9-8bd747df51fc)

(Note I'm also using MySQL).

There was this bug https://github.com/postfixadmin/postfixadmin/issues/553 some time ago - which looks like what you're hitting. So I suspect you need to update at least to https://github.com/postfixadmin/postfixadmin/commit/5a8f334b4536013fdde44cf5ee3aee02ea91540e ?
