### ISSUE TITLE
Domain admins disapeared

### ISSUE THREAD

**Issue by kwitkow** [postfixadmin/postfixadmin#795]
Hello,

After upgrade from 3.2.x to 3.4-dev (master) I can't see Domain admins
There is no Admin list in UI like this https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/screenshots/admin-list.png
Is this something that should be enabled in config.inc or config.local?

**Comment by DavidGoodwin** [comment]
well spotted ... 

![image](https://github.com/postfixadmin/postfixadmin/assets/203929/7a6e5463-66a2-48a3-aab9-68d72f4f5f12)

there is/was a bug in login.php where init_session() was being called and that was wiping out the global-admin role that is/was added there.

See 0632d39d0c5891d1372762f36a242accc475ba30
