### ISSUE TITLE
Future + Thoughts 

### ISSUE THREAD

**Issue by pedromorgan** [postfixadmin/postfixadmin#8]
Maybe we can do awaya with the RPC call on focus on the root purpose..
Aad to do its postfix style.. in php..

Now I know in my heart  that php is what I grew up on.. (smarty+dev)
And php5 was cool then..
python..

So I Want to work with postfixadmin.. and make the same DB work another way..

In my case golang, and stuff python, but the onlt cool things we can do in golang is play and have a lot of fun in ajax..

Now its up to the "designer" to go and dream up her system with the ladies..

But if we can have a "clean ajax" api.. then were in..

And the only way to do that is with a "clean slate".. sometimes...............

**Comment by cboltz** [comment]
Creating an ajax interface (even including on-the-fly verification before hitting the "submit" button) is quite easy. We just need someone to do the work ;-)

If you want to work on adding ajax support, please speak up on the postfixadmin-devel mailinglist or on IRC (#postfixadmin on freenode). I'll happily help you to get started.
