### ISSUE TITLE
Enforce code style ?

### ISSUE THREAD

**Issue by PowerKiKi** [postfixadmin/postfixadmin#80]
Would you accept a PR that use [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) and Travis CI to enforce a consistent code style throughout the entire PHP code base ?

I believe this would make it easier to contribute, by avoiding a lots of annoying useless diff (such as trailing whitespaces) and by automating some feedback on incoming PR.

If you agree on the principle, I could suggest PHP-CS-Fixer rules, or you choose them yourself and let me implement the rest via composer and Travis.

**Comment by DavidGoodwin** [comment]
Sounds good to me. Please submit a pull request when you are able to.
