### ISSUE TITLE
Not Create All Table Rows on First  Set Up

### ISSUE THREAD

**Issue by july8six** [postfixadmin/postfixadmin#81]
Operating System:  Centos 7 
PostfixAdmin: latest stable
Postfix:  2.10.1
SQLite:  3.7.17
Apache:  2.4.6
php:  5.4.16

The script is not creating all table rows on the first set up.

I get the error message:
Invalid query: no such column: phone
Invalid query: no such column: email_other

caused by query:  SELECT username,password,password as password2,phone,email_other,CASE superadmin WHEN '1' THEN '1'    WHEN '0' THEN '0'   END as superadmin,CASE superadmin WHEN '1' THEN 'YES' WHEN '0' THEN 'NO' END as _superadmin,coalesce(domains,'') as domains,coalesce(__domain_count,0) as domain_count,CASE active WHEN '1' THEN '1'    WHEN '0' THEN '0'   END as active,CASE active WHEN '1' THEN 'YES' WHEN '0' THEN 'NO' END as _active,strftime(modified, '%Y-%m-%d') AS modified, modified AS _modified,1 as _can_edit,1 as _can_delete  FROM admin  LEFT JOIN (  SELECT count(*) AS __domain_count, group_concat(domain) AS domains, username AS __domain_username  FROM domain_admins WHERE domain != 'ALL' GROUP BY username  ) AS __domain on username = __domain_username
  WHERE 1=1    AND    ( username='admin@example.com' )  ORDER BY username

The solution is to go to the SQLite table and add the missing fields.

**Comment by evaryont** [comment]
Getting the same error when trying to create a superadmin from setup.php. Using PHP 7 and SQLite 3.
