### ISSUE TITLE
vacation.pl - replace_string() is produced parsing errors

### ISSUE THREAD

**Issue by ntavares** [postfixadmin/postfixadmin#818]
The replace_string introduced in commit be5dad4d0411c475c72375aed7e088bea57c2823 contains an hardcoded strptime() format string to parse activefrom and activeuntil dates. However, I'm using Postgresql, and my schema is laid out as:
```
 activefrom    | timestamp with time zone | default '2000-01-01 00:00:00+01'::timestamp with time zone
 activeuntil   | timestamp with time zone | default '2000-01-01 00:00:00+01'::timestamp with time zone
```

Which means that the results of the query will be:
```
postfix=# SELECT activefrom,activeuntil FROM vacation WHERE email='....';
       activefrom       |      activeuntil       
------------------------+------------------------
 2024-04-10 11:14:00+02 | 2024-04-13 13:14:00+02
(1 row)
```

Therefore the script will produce complaints:
```
 (garbage at end of string in strptime:  00:00:00+02 at /usr/lib64/perl5/Time/Piece.pm line 481, <STDI)
```

According to [perl_date_time.htm](https://www.tutorialspoint.com/perl/perl_date_time.htm) there's no way to catch the "+02" relative to the UTC offset.

Therefore I propose casting the field directly in the query, which solves the problem. I've validated the syntax with MySQL as well.

**Comment by DavidGoodwin** [comment]
Thank you @ntavares
