### ISSUE TITLE
Have installed 3.3.13  install and setup ok but cant login

### ISSUE THREAD

**Issue by hobbycharken** [postfixadmin/postfixadmin#820]
I have installed postfixadmin on my vps

Ubuntu 22.04
Php8.1
Mariadb

Installation an setup went ok but when I want to login to admin I get a 500 error

I cant see anything specail in the logs so I have no clue where to begin to look

I followed this tutorial, all parts

https://www.linuxbabe.com/mail-server/postfixadmin-ubuntu

Regards

Anders Yuran

**Comment by DavidGoodwin** [comment]
Is there anything relevant in the apache or php error log file(s) (perhaps: /var/log/apache2/error.log ?)
