### ISSUE TITLE
Vacation.pl script will not send messages if $no_vacation_pattern is null string

### ISSUE THREAD

**Issue by ariabamdad** [postfixadmin/postfixadmin#826]
The vacation.pl script has this configuration option and comments:

```
# By default vacation email addresses will be sent for all recipients.
# default = ''
# preventing vacation notifications for recipient info@example.org would look like this:
# our $no_vacation_pattern = 'info\@example\.org';
our $no_vacation_pattern = 'info\@example\.org';
```

However, if as explained in the comments, you set the $no_vacation_pattern = ''   (null string), then the relevant statement later in the script:

```
if ($to =~ /^.*($no_vacation_pattern).*/i) {
   $logger->debug("Will not send vacation reply for messages to $to");
   exit(0);
}
```

will match for every to address and therefore not send a reply message to ANY address.  To circumvent, I have set `$no_vacation_pattern = '\@\@'; ` to get around the problem.  Another option is to set the string to one or more blank spaces.

Thanks

**Comment by DavidGoodwin** [comment]
Oh nice catch; see 6c84ceeb9472dab3fac88a2bc0fbd15f7a536908 which should do the same as your @@ pattern.

Thanks!
