### ISSUE TITLE
Invalid session - Chrome only - Firefox works

### ISSUE THREAD

**Issue by Wilburunion** [postfixadmin/postfixadmin#830]
I use latest Postfixadmin 3.13 (lux) with PHP 8.2.19 (remi)

If I try to login via Chrome, this error occurs:

Invalid token (session timeout; refresh the page and try again?)

Works in Firefox; however the table list and virtual list of domain fails blank - while all else works

( postfixadmin/list.php?table=domain ) and ( postfixadmin/list-virtual.php )

This is an in place hot upgrade from Centos7 to AlmaLinux 9.4  and I had to fix permissions - what are the correct permissions ??

**Comment by DavidGoodwin** [comment]
Hello - 

Permissions - PHP requires the files are readable by the webserver, and the templates_c directory needs to be writeable.

If you're having token problems, my guess is it's actually a cookie problem as PostfixAdmin is just using the underlying PHP session functionality, which in turn depends on cookies. So - perhaps chrome isn't persisting the same cookie across requests (perhaps it's blocking cookies?) ?

**Comment by Wilburunion** [comment]
I had changed permissions - I was womdering thecorrect permissions

still ...

Works in Firefox; however the table list and virtual list of domain fails blank - while all else works

( postfixadmin/list.php?table=domain ) and ( postfixadmin/list-virtual.php )

worked in centos 7 - on php 8.2 - but not in almalinux php 8.2

**Comment by DavidGoodwin** [comment]
Is anything showing in the webserver log files ? e.g. /var/log/apache2/error.log ?

Are there actually entries within the underlying alias and domain tables?

**Comment by Wilburunion** [comment]
yes, and yes.  Worked fine in Centos7  (uses httpd)

In Chrome the ssl_access shows the get for login.php

In Firefox it logs in and throws a 500 error on attempting access the domain or virtual  list 

"GET /postfixadmin/list.php?table=domain HTTP/2.0" 500
"GET /postfixadmin/list-virtual.php HTTP/2.0" 500 

actually i am using postfixadmin 3.3.13-1.el9.lux 

if I try to send an email the form comes up but on send throws a 500 error also

"GET /postfixadmin/sendmail.php HTTP/2.0" 200 7257
"POST /postfixadmin/sendmail.php HTTP/2.0" 500 -

It appears this is an owner user permissions issue which is why I asked for owner permissions setup

I am using  php-fpm, but it is NOT setup like here => https://bbs.archlinux.org/viewtopic.php?id=245780     - never needed it before like that    If that way is correct I will try that next

I note that thread is not showing as actually solved but it is similar to my php-fpm setup

**Comment by Wilburunion** [comment]
I setup php-fpm as  https://bbs.archlinux.org/viewtopic.php?id=245780 shows and it now launches in both Chrome and Firefox, but I still get 500 errors on domain and virtual list

"GET /postfixadmin/list.php?table=domain HTTP/2.0" 500
"GET /postfixadmin/list-virtual.php HTTP/2.0" 500

**Comment by DavidGoodwin** [comment]
I'd expect PHP to log an error somewhere if there's a http 500 response. Once you find ....

**Comment by Wilburunion** [comment]
No PHP log of errors in php-fpm - I will try to ini set to throw them to the screen

I re-ran setup and it reported everything fine -I installed imap and pdo-mysql but now change 

I get 

 Undefined array key "theme_favicon" in /var/cache/postfixadmin/templates_c/63f98af09aa5bc7a4553679dd062464be3988c43_0.file.header.tpl.php on line 36', referer: https://. . ./postfixadmin/main.php

I added the variable 

$CONF['password_expiration'] = 'NO';

since it was looking for that  ( https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/Password_Expiration.md )

Could this array key issue be the problem ??

**Comment by Wilburunion** [comment]
My postfixadmin.conf in httpd.conf.d now reads as I modified from the  setup php-fpm as https://bbs.archlinux.org/viewtopic.php?id=245780 showed

Alias /postfixadmin "/usr/share/postfixadmin/public"
<Directory "/usr/share/postfixadmin/public">
    DirectoryIndex index.html index.php
    <FilesMatch \.php$>
        SetHandler "proxy:unix:/run/php-fpm/postfixadmin.sock|fcgi://localhost/"
    </FilesMatch>
    AllowOverride All
    Options FollowSymlinks
    Require all granted
    SetEnv PHP_ADMIN_VALUE "open_basedir = /tmp/:/usr/share/postfixadmin:/etc/postfixadmin/:/var/cache/postfixadmin:/usr/bin/doveadm/:/var/cache/postfixadmin/templates_c"
    SetEnv PHP_ADMIN_FLAG "allow_url_include off"
    SetEnv PHP_ADMIN_FLAG "allow_url_fopen off"
</Directory>

<Directory /usr/share/postfixadmin/public>
    <IfModule mod_authz_core.c>
        require all granted
    </IfModule>
    <IfModule !mod_authz_core.c>
        order allow,deny
        allow from all
    </IfModule>
</Directory>

Restarted php-fpm and httpd after those changes above and it now came up working upon a launch in a new browser window.  I have a suspicion it was the " $CONF['password_expiration'] = 'NO'; " that did it

**Comment by Wilburunion** [comment]
The pastes above deleted the close directory commands  " </Directory> "  and  " </FilesMatch> "  for some reason

**Comment by DavidGoodwin** [comment]
Hi - Glad to hear you've fixed it

An undefined variable might trigger PHP to output to the browser, which might happen before it's sent http headers (necessary for cookies etc)?
