### ISSUE TITLE
Vacation auto response form too narrow using new bootstrap css

### ISSUE THREAD

**Issue by ariabamdad** [postfixadmin/postfixadmin#834]
Hello again!

It seems that the default css is usable for most functions but not for when the vacation auto reply message needs to be edited by user or admin.  The same set of parameters for a form are applied here but these are too narrow and thus the fields, particularly the subject and message body fields are so narrow that they inhibit the user from composing a visually acceptable message.  

One option is to relocate the move all the field names (ex. Subject:, Message:, Choice of reply:, etc.), to be above the field, rather to the left,  so to allow more room on each side of the field.  This will widen the field more.  Or, preferably do both this as well as widen the field more than the current 600px as is stated by the following: 

`<div class="container" style="min-width: 600px; width: min-content" role="main"><!-- flash_error.tpl -->`

I have reviewed suggestions in #462 and #533 but am unable to make this happen by providing a $CONF['theme_custom_css'] file that will address the problem.  As it is now, the vacation auto responder screen is not usable with the formatting template provided.  Would you be able to provide a temporary fix that widens the auto reply screen via a custom css statement?

Also, I noticed there is an extra `</div>` tag at the bottom of the form definition of tile ./templates/vacation.tpl.

Thank you in advance.

**Comment by DavidGoodwin** [comment]
Hi -
I assume you're referring to PostfixAdmin 3.3.x which looks like : 

![image](https://github.com/postfixadmin/postfixadmin/assets/203929/186b1dd0-dc06-437f-ba18-d3285447e3bd)


rather than the 'master' version which looks like : 

![image](https://github.com/postfixadmin/postfixadmin/assets/203929/f8e1a2b3-e978-4ef6-a48e-d746fb02c3ce)

if it's postfixadmin 3.3 then one solution might just be to change the div wrappers around the form elements to give the input elements more space - e.g.

![image](https://github.com/postfixadmin/postfixadmin/assets/203929/ede721f2-d839-4b6f-8151-26a6a168c10a)

**Comment by ariabamdad** [comment]
Hi @DavidGoodwin ,
Thank you again for your quick suggestion.  Yes, I am working with 3.3.10 version.  I tried your solution and it is better now.  I like the screen shot for the master version.  Would it make sense to use the vacation.tpl from the current master release on my 3.3.10 installation?  I like the even wider look there more.

Thanks.

**Comment by DavidGoodwin** [comment]
Hi -

I think the 'master' codebase is usable on the whole, but I'm fairly sure there are a lot of other changes that have taken place in master, and I don't think you can get away with just using the vacation.tpl file from it in 3.3.x.

I assume your idea of making the container div wider would also work / have a similar result - and you could do that as well if you want even more room. I was just changing the proportion of the existing space given to the padding/labels/fields and not wanting to change the theme's overall appearance.
