### ISSUE TITLE
Login with email verification code.

### ISSUE THREAD

**Issue by winicius87** [postfixadmin/postfixadmin#839]
It would be nice for there to be a login verification code.

The code would be sent to an email. This will prevent unwanted login attempts.

**Comment by DavidGoodwin** [comment]
Hi -

We're happy to receive a PR this ... :-) 

In the mean time, I think your main alternatives are :

  * http auth with your webserver
  * fail2ban can monitor the PHP error log and block an IP that fails to login too many times within a time period
