### ISSUE TITLE
Installation on separate mysql host

### ISSUE THREAD

**Issue by laidback01** [postfixadmin/postfixadmin#840]
I don't know if this is fixed in a new version or not, but the dsn string is constructed wrong in function db_connection_string()

Originally:
```
$dsn = 'mysql:';
        if ($socket) {
            $dsn .= "unix_socket={$socket}";
        } else {
            $dsn .= "mysql:host={$CONF['database_host']}";
        } 
```
should be
```
$dsn = 'mysql:';
        if ($socket) {
            $dsn .= "unix_socket={$socket}";
        } else {
            $dsn .= "host={$CONF['database_host']}";
        } 
```

This allows it to install as expected on a remote mariadb/mysql server.

**Comment by DavidGoodwin** [comment]
Hello - Yes ... this was fixed about 3 years ago ... https://github.com/postfixadmin/postfixadmin/commit/5a8f334b4536013fdde44cf5ee3aee02ea91540e
