### ISSUE TITLE
Vacation period may not take into account timezones?

### ISSUE THREAD

**Issue by michaelkrieger** [postfixadmin/postfixadmin#842]
If I have a vacation set currently, it seems to show that there is no active vacation.  If I set it back a day, it seems to work.  Does vacation.pl not take into account the timezone adjustment?

> select activefrom, activeuntil from vacation;
```
+---------------------+---------------------+
| activefrom          | activeuntil         |
+---------------------+---------------------+
| 2024-07-12 11:29:55 | 2024-07-29 11:26:00 |
+---------------------+---------------------+
```
vacation.pl
`2024/07/12 11:32:52 DEBUG> /etc/postfixadmin/vacation.pl:682 main:: - SMTP recipient ... which resolves to  does not have an active vacation (rv: 0, email: )`

But if I set it back a day
```
 select activefrom, activeuntil from vacation;
[+---------------------+---------------------+
| activefrom          | activeuntil         |
+---------------------+---------------------+
| 2024-07-11 11:26:00 | 2024-07-29 11:26:00 |
+---------------------+---------------------+
```
then I get
`2024/07/12 11:34:55 DEBUG> /etc/postfixadmin/vacation.pl:346 main::find_real_address - Found '...' has vacation active`

**Comment by DavidGoodwin** [comment]
Hi - probably not - I suspect we're not correctly requesting a date with a timezone from the browser; or making sure that we convert from the browser's timezoned date to something comparable within the database.

If everything is in the same timezone, I suspect it'd work fine !
