### ISSUE TITLE
password crypt

### ISSUE THREAD

**Issue by mrglobule** [postfixadmin/postfixadmin#843]
Hello,
Thanks for the great job.
I use postfixadmin to manage my mail domain/server
![VersionPostfixAdmin](https://github.com/user-attachments/assets/d01a163c-5409-4789-982f-f42eaa1c9532)
I have an mistake with the change password fonctionnality.
I have this parameter in the /etc/dovecot/dovecot-sql.conf.ext
`default_pass_scheme = MD5-CRYPT`
So i have password beginning by `$1$`
but if i put in the /var/www/postfixadmin/config.local.php
`$CONF['encrypt'] = 'md5crypt';`
the password don't begin with `$1$` and i cant connect to my mails accounts...
Would you mind to help me on this feature/config?
Regards,

**Comment by DavidGoodwin** [comment]
er, i think dovecot likes (but doesn't require '{MD5-CRYPT}' infront of it - so ...

 '{MD5-CRYPT}$1$AIjpWveQ$2s3eEAbZiqkJhMYUIVR240' is equivalent to `$1$AIjpWveQ$2s3eEAbZiqkJhMYUIVR240`

(at least from dovecot's point of view).

Can you try and set `$CONF['encrypt'] = 'MD5-CRYPT';` and see if that works?

**Comment by mrglobule** [comment]
Thanks for replying,
but if i change the `$CONF['encrypt'] = 'MD5-CRYPT';` value, i cannot be able to connect to postfixadmin?
Postfixadmin said me the password is not correct ?

**Comment by DavidGoodwin** [comment]
Oh, sorry, I think I might have misread your original question. 

Are you really sure that pacrypt(..) is using the $CONF['encrypt'] setting you think it is? Is there a `config.local.php` file that is specifying a different setting, or is it possible you have multiple Postfixadmin config.inc.php files and confusion over which one is in use ?

I'd suggest you stick a `die($CONF['encrypt']);` towards the top of e.g. the login.php page and make sure it's set to MD5-CRYPT.?

**Comment by mrglobule** [comment]
Thanks for replying,
sorry for my poor english ;-)
Effectively i have two conf file and if i suppress one i have an 500 error????
I have the same  `$CONF['encrypt'] = 'MD5-CRYPT';` in each files the config.inc.php and the config.local.php.
When i put this setting i have: 
![error](https://github.com/user-attachments/assets/bcad7f72-864f-45cc-8afa-ff841a5ed753)
if i let the `$CONF['encrypt'] = 'md5crypt';` i can connect to my account but the password if i changeit is like this:
![cryptBDD](https://github.com/user-attachments/assets/bcf6ed96-e76f-46d9-b3ab-c71abd487add)
if i try to browse the setup.php i see my config.local.php:
![setuppage](https://github.com/user-attachments/assets/d294a124-9ba3-4f6c-a90e-07393089a6f4)
I don't understand at all...
Regards

**Comment by DavidGoodwin** [comment]
er, $2$ is a blowfish like password ( think), and looks like something I'd expect for the setup.php page?

The password 'setup.php' uses (`$CONF['setup_password']`) is NOT linked to the password format mailboxes have. It's ONLY for the setup.php page. 

All passwords in the 'admin' or 'mailbox' table should take the format as specified by `$CONF['encrypt']`.

**Comment by mrglobule** [comment]
ok, thanks,
but in the Database the mailboxes password begun with `$1$` and when i chnage the password with the postfixadmin user page, the password begun with `$2$` so i can't connect to my mail server i had to re enter in the database the old password begun with `$1$`
regards

**Comment by mrglobule** [comment]
I read about this: [](https://www.php.net/manual/fr/function.password-hash.php) maybe a food of thought?

**Comment by DavidGoodwin** [comment]
Yeah - PostfixAdmin uses that for the setup password hash ... but doesn't use it for others.

I can't help but feel there's something weird going on with your configuration. I can only suggest you do the equivalent of 

```PHP
var_dump($CONF);
die('check the above');
```

either in functions.inc.php or the edit page that's used for mailbox editing to try and figure out what's going on.

**Comment by nunix2** [comment]
Hi,

I had the same issue.
To correct please read:
https://security.stackexchange.com/questions/150687/is-it-safe-to-use-the-encrypt-function-in-mysql-to-hash-passwords

I had to change a line in functions.inc.php:
#old
//$res= db_query_one("SELECT ENCRYPT(:pw, CONCAT('$6$', '$salt')) as result", ['pw' => $pw]);
#new
$res= db_query_one("SELECT ENCRYPT(:pw) as result", ['pw' => $pw]);

Hope it helps

**Comment by DavidGoodwin** [comment]
@nunix2 I'm curious what version of MySQL you're using ...

**Comment by nunix2** [comment]
mysql  Ver 15.1 Distrib 10.11.8-MariaDB, for Linux (x86_64) using  EditLine wrapper

**Comment by nunix2** [comment]
it works fine using Salt $1$ passwds with pam_mysql-0.8.1
but if you upgrade to pam_mysql-1.0.0 it stops working. You need to change those lines in functions.inc.php to auth works again. (of course, you also need to re-type the passwords in that new mode.)
