### ISSUE TITLE
The version has not been updated in the 3.3.13 (and 3.3.12) release

### ISSUE THREAD

**Issue by TigerP** [postfixadmin/postfixadmin#845]
In the 3.3.13 branch version 3.3.11 is still in the config file.

https://github.com/postfixadmin/postfixadmin/blob/b6eab5daed03a5c12f7d37b2ed6b6d0734878b86/config.inc.php#L703

This means that the version showed on the webpage is wrong. I would expect the version on the webpage to be the same as the release I downloaded.
I noticed that in the main branch the version has been changed.

**Comment by DavidGoodwin** [comment]
Hi @TigerP 

Thanks for reporting this. Yes, some idiot (me) forgot to update a version number .... 

For what it's worth, there is no 3.3.13 branch, there is however a Postfixadmin 3.3 branch - and that has been updated - https://github.com/postfixadmin/postfixadmin/blob/postfixadmin_3.3/config.inc.php#L703 

See also #778 and #740 and #694 

Thanks
David
