### ISSUE TITLE
Missing config on doc about mysql-login_maps_dovecot.cf

### ISSUE THREAD

**Issue by Zatalyz** [postfixadmin/postfixadmin#846]
I read https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/POSTFIX_CONF.txt and see this to add on main.cf :

`smtpd_sender_login_maps = proxy:mysql:/etc/postfix/mysql-login_maps_dovecot.cf`

But in the document, if content of other files are described ("mysql_virtual_alias_maps.cf" and other), there are not "mysql-login_maps_dovecot.cf". I'm not sure what is expected in the query...

**Comment by DavidGoodwin** [comment]
I don't use smtpd_sender_login_maps - but perhaps this article will give you an idea of what it might / should / could be ? https://serverfault.com/questions/948362/postfix-multiple-smtpd-sender-login-maps
