### ISSUE TITLE
caching_sha2_password cannot be loaded

### ISSUE THREAD

**Issue by fleming42** [postfixadmin/postfixadmin#847]
Updated from MySQL 8.0 to 8.4 LTS, and it broke postfixadmin.

MySQL 8.4 uses caching_sha2_password as default auth mechanism. I had to manually reenable mysql_native_password for postfixadmin to work again.

In MySQL 9, mysql_native_password is removed. So I think postfixadmin won't work in MySQL 9 at all.

Any fixes on the horizon for postfixadmin to support caching_sha2_password? Thanks.

**Comment by fleming42** [comment]
caching_sha2_password.so is no longer available as a separate download. It is built in to MySQL 8.4 statically.

**Comment by DavidGoodwin** [comment]
if dovecot can't connect, that implies it's really a dovecot<->mysql problem?

I'd only expect this to be a Postfixadmin problem if you're trying to use `mysql_encrypt` for password hashing?

**Comment by fleming42** [comment]
Thank you David for your quick response. I'm sure I'm confused a bit as to the source of the issue. I am not using mysql_encrypt, sot that is out. At first I thought it was dovecot, then noticed postfixadmin as the database, so I experimented with changing the postfixadmin db user plugin back and forth between mysql_native_password and caching_sha2_password. In that process, I realized only the native would work. But I think I understand now what you're saying: that dovecot is trying to connect to MySQL in a way that sort of supports caching_sha2_password, but only if it has a .so library file to load. So I will look into dovecot some more. Thanks again David.

**Comment by DavidGoodwin** [comment]
Hi @fleming42 - no problem... we've all been there ... too many new things floating around and we've not yet got a solid mental model of how everything fits together ...

Yes, I think your problem is dovecot <-> mysql ....  somewhere. :)
