### ISSUE TITLE
Why does vacation.pl send mails on its own?

### ISSUE THREAD

**Issue by mauline** [postfixadmin/postfixadmin#848]
When updating postfixadmin from an older version, I run into several problems with the vacation service.

Looking into the vacation.pl script, I noticed that the script tries to contact the remote mail servers by itself instead of just using the local mail server to deliver the vacation mails.

Two problems I had with this approach:

1. starttls didn't work. Looks like perl is missing the certificate database. I'm not sure if a required perl module is missing so I disabled it which is a poor solution but works.
2. Delivering mails to local users is complex in my case, because the mail server is behind NAT and the MX points to the outside address. So the script connects to the outside address which must be routed back to the internal mail server running on the same host on which the vacation script is running. I had to reconfigure the firewall for NAT reflection and add some more rules to make this work.

Both problems would go away when using the local mail server for delivery, so I'm really curious as to why the current solution was chosen.

**Comment by DavidGoodwin** [comment]
Unless you can get anything useful from 'git log vacation.pl', I suspect it's just historic baggage and that's always been the way..... I thought it could deliver to a local smtp server though?
