### ISSUE TITLE
What permissions should we set for the "postfixadmin" and recorsive files/folders to be the most secure.

### ISSUE THREAD

**Issue by Danrancan** [postfixadmin/postfixadmin#849]
My postfixadmin folder is installed in `/var/www/postfixadmin`. Everything seems to be working, but that was only from a brief glance. I noticed that all of my pfadmin files and folders are owned by `user:user`. Since my installation is in root directories, I'm assuming I should do a `chown -R root: /var/www/postfixadmin` or a `sudo chown -R www-data: postfixadmin` .  But I'm not really sure what the difference is or if ownership even matters. I also want to know how I should set file and folder permissions for the postfixadmin folder. I can't seem to find anything about securing the /var/www/postfixadmin folder with chmod that would make my installation more secure. 

Could you please tell me what the default ownership and permissions for all folders/files recursively in /var/www/postfixadmin, and then could you also tell em what secure ownsership and permissions might be for all files/folders recursively in /var/www/postfixadmin would be? Thanks for any help! I appreciate it!

**Comment by DavidGoodwin** [comment]
Hi - the ownership of the files by user:user shouldn't really matter....

Ideally you don't want the user PHP runs as to be able to write / modify any files, especially if this is on some sort of shared server where other code being executed (which could allow a vulnerability to spread to your PostfixAdmin instance).

However, the template library (smarty) that postfixadmin uses, needs to be able to write to the 'templates_c' directory. You should find this is already set to be writeable by the webserver (often 'www-data' user).

If you want you can change the ownership of everything in /var/www/postfixadmin to be 'root:root' - but you might annoy smarty (if templates_c is no longer writeable). 

In other words, all .php files in /var/www/postfixadmin should NOT be writeable by the user executing the postfixadmin code. Often this is 'www-data'.
