### ISSUE TITLE
PHP Security.  Disabled PHP functions causing postfixadmin to have blank white screen. What php functions are required by postfixadmin?

### ISSUE THREAD

**Issue by Danrancan** [postfixadmin/postfixadmin#850]
I am running an Ubuntu LEMP server with php8.1. I have several PHP Functions disabled in my php.ini for better security. When I keep these php functions disabled, Postfixadmin points to a completely white blank web page after login.

Below are my disabled php functions:

cat /etc/php/8.1/fpm/conf.d/99-custom.ini
```
; DEFAULT
disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,pcntl_unshare,exec,passthru,shell_exec,system,proc_open,popen,parse_ini_file,show_source;

allow_url_fopen=Off
allow_url_include=Off

```
When I comment out "disable_functions" and don't disable anything, my postfixadmin web page works flawlessly, however when I uncomment it again, then postfixadmin becomes a white blank page.

I would like to keep the above functions disabled (by uncommenting them) without disabling the specific functions that blocks Postfixadmin web page from working.

What function/functions that I have listed are causing Postfixadmin to break with a white screen? Which ones must I exclude from the "disable_functions" list?

Please help!

**Comment by Danrancan** [comment]
I figured out through process of elimination, that the disabled function which was causing the blank white screen on postfixadmin.example.com was `proc_open`. Removing `proc_open` from the `disable_functions =` option allows my postfixadmin page to work after login.

Now, my question is, allowing proc_open is another attack vector that I would like to remove in PHP. So is there a way to disable proc_open in php without it botching my postfixadmin web interface? Any way around this?

Thanks

**Comment by DavidGoodwin** [comment]
Hi - I think the only time proc_open will be used i when PostfixAdmin is trying to hash a password (and you've chosen to use one of the dovecot: based mechanisms).

**Comment by Danrancan** [comment]
> Hi - I think the only time proc_open will be used i when PostfixAdmin is trying to hash a password (and you've chosen to use one of the dovecot: based mechanisms).

I don't understand. What is the dovecot based mechanisms? Also, I am using Basic Auth on postfixadmin for extra security. Then after successful basic auth login, I use my postfix username and password on the main postfix admin web interface.

Does that tell you anything? Does this get me closer to understanding about hashed passwords and dovecot?

Thanks for any answers.

**Comment by damnms** [comment]
i have it running with 
disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,pcntl_unshare,system, exec, shell_exec, passthru, show_source, highlight_file, popen, proc_open, fopen_with_path, dbmopen, dbase_open, putenv, move_uploaded_file, chdir,   filepro, filepro_rowcount, filepro_retrieve, posix_mkfifo

**Comment by ozgurkazancci** [comment]
> i have it running with disable_functions = pcntl_alarm,pcntl_fork...

Does Roundcube fully work with them as well if you happen to have it too?

**Comment by damnms** [comment]
I did not test it tbh, but i have no white screens. I also have only 5 or 6 users that probably never use postfixadmin. Maybe some functions do not work.

**Comment by Danrancan** [comment]
> dovecot based means you use the dovecot binary to get a password (the hash), which should really not be used. i would set default to the php library. set $CONF['encrypt'] to something like 'php_crypt:SHA512::{SHA512-CRYPT}'

I'm not sure what this means either. Where do I find $CONF['encrypt'] and how do I set it to php_crypt:SHA512::{SHA512-CRYPT}' ? Is this a file I need to access? Or a command? Please let me know as I want my server to be configured as tightly secure and efficient as possible.

I built my server using a [15 step Linuxbabe tutorial](https://www.linuxbabe.com/mail-server/setup-basic-postfix-mail-sever-ubuntu) so i don't remember everything I did. I was more or less just following instructions directly from the tutorial and don't remember all the steps I took. If you look over that tutorial, maybe that will help you figure out if I am using the dovecot binary to get a password hash? Otherwise, how can I find out if I am using dovecot for that?

Thanks for any reply and help.

**Comment by DavidGoodwin** [comment]
> > dovecot based means you use the dovecot binary to get a password (the hash), which should really not be used. i would set default to the php library. set $CONF['encrypt'] to something like 'php_crypt:SHA512::{SHA512-CRYPT}'
> 
> I'm not sure what this means either. Where do I find $CONF['encrypt'] and how do I set it to php_crypt:SHA512::{SHA512-CRYPT}' ? Is this a file I need to access? Or a command? Please let me know as I want my server to be configured as tightly secure and efficient as possible.
> 


PostfixAdmin is responsible for creating mailbox passwords. It needs to be configured to store passwords in the same format that Dovecot (the thing that does the pop3/imap part) uses. The passwords are stored in the `mailbox` database table.

PostfixAdmin knows what password format to use by looking in its configuration - somewhere on your server (perhaps /etc/postfixadmin) there will be a file called `config.inc.php` and a `config.local.inc.php`. 

`config.local.inc.php` should contain your local customisations to PostfixAdmin's default settings. Settings put in this file should override what is in `config.inc.php`. 

(In other words - you should **not** be editing config.inc.php, but if you are naughty you will have).

So ... to find where your config is, a lazy approach would be : 

`find / -name config.local.inc.php -type f -print` 


Then view that file and look for a line that looks like : 

`$CONF['encrypt'] = 'php_crypt:SHA512::{SHA512-CRYPT}';`

(at least it should start with `$CONF['encrypt'] = `;

**Comment by Danrancan** [comment]
> > > dovecot based means you use the dovecot binary to get a password (the hash), which should really not be used. i would set default to the php library. set $CONF['encrypt'] to something like 'php_crypt:SHA512::{SHA512-CRYPT}'
> > 
> > 
> > I'm not sure what this means either. Where do I find $CONF['encrypt'] and how do I set it to php_crypt:SHA512::{SHA512-CRYPT}' ? Is this a file I need to access? Or a command? Please let me know as I want my server to be configured as tightly secure and efficient as possible.
> 
> PostfixAdmin is responsible for creating mailbox passwords. It needs to be configured to store passwords in the same format that Dovecot (the thing that does the pop3/imap part) uses. The passwords are stored in the `mailbox` database table.
> 
> PostfixAdmin knows what password format to use by looking in its configuration - somewhere on your server (perhaps /etc/postfixadmin) there will be a file called `config.inc.php` and a `config.local.inc.php`.
> 
> `config.local.inc.php` should contain your local customisations to PostfixAdmin's default settings. Settings put in this file should override what is in `config.inc.php`.
> 
> (In other words - you should **not** be editing config.inc.php, but if you are naughty you will have).
> 
> So ... to find where your config is, a lazy approach would be :
> 
> `find / -name config.local.inc.php -type f -print`
> 
> Then view that file and look for a line that looks like :
> 
> `$CONF['encrypt'] = 'php_crypt:SHA512::{SHA512-CRYPT}';`
> 
> (at least it should start with `$CONF['encrypt'] = `;

Thank you for this explanation. However, this leads me to a series of more questions.

1) I noticed that I seem to have an extra postfixadmin folder in /etc/postfixadmin, which looks like this:
```
/etc/postfixadmin$ ls -la
total 24
drwxr-xr-x   2 root root  4096 Jan 30  2023 .
drwxr-xr-x 173 root root 12288 Aug 15 06:51 ..
lrwxrwxrwx   1 root root    40 Apr 29  2021 config.local.php -> /usr/share/postfixadmin/config.local.php
-rw-r--r--   1 root root   662 Jun 24  2022 config.local.php.orig
-rw-r-----   1 root root   552 Apr 29  2021 dbconfig.inc.php.orig
```
I also noticed that I have a postfixadmin.old folder in /usr/share/postfixadmin.old, which looks like this:
```
/usr/share/postfixadmin.old$ ls -la
total 132
drwxr-xr-x  11 root root  4096 Jan 30  2023 .
drwxr-xr-x 212 root root  4096 Aug 15 06:27 ..
-rw-r--r--   1 root root  3014 Jan 12  2019 common.php
lrwxrwxrwx   1 root root    32 Feb 10  2020 config.inc.php -> /etc/postfixadmin/config.inc.php
-rw-r--r--   1 root root   440 Apr 29  2021 config.local.php
-rw-r--r--   1 root root   440 Jun  3  2021 config.local.php.orig
drwxr-xr-x   2 root root  4096 Jun  1  2021 configs
-rw-r--r--   1 root root 71719 Feb 10  2020 functions.inc.php
-rw-r--r--   1 root root   248 Jan 12  2019 index.php
drwxr-xr-x   2 root root  4096 Jun  1  2021 languages
drwxr-xr-x   3 root root  4096 Jun  1  2021 lib
drwxr-xr-x   2 root root  4096 Jun  1  2021 model
drwxrwxr-x  16 root root  4096 Jan 30  2023 postfixadmin
drwxr-xr-x   5 root root  4096 Jun  1  2021 public
drwxr-xr-x   3 root root  4096 Jun  1  2021 scripts
drwxr-xr-x   2 root root  4096 Jun  1  2021 templates
drwxrwxr-x   2 root root  4096 Dec  9  2021 templates_c
```
I must have renamed it with the .old extension before uninstalling postfixadmin from apt (i think). I believe that once upon a time, I installed postfixadmin from the Ubuntu Apt package manager, and these files are remnants of that. My current postfixadmin folder was downloaded as a `.tar` file and extracted to` /var/www/postfixadmin`. Is it possible that when running my current postfixadmin, ubuntu also put the aformentioned files into the `/etc/postfixadmin` and `/usr/share/postfixadmin` directories? Can you confirm if my theory is true or false, about if these files came from the Ubuntu Apt installation of postfixadmin? I would like to get any remnants of postfixadmin off of my Ubuntu Server before I continue to install the official postfixadmin from the `.tar` file. Is it okay to delete `/usr/share/postfixadmin` and `/etc/postfixadmin` directories? and just work off of the current postfixadmin in `/var/www/postfixadmin`? Any suggestions?

2) I installed postfixadmin by following [these linuxbabe instructions](https://www.linuxbabe.com/mail-server/postfixadmin-ubuntu), and in there, he doesn't have us create a `config.local.inc.php` file, but instead we create a `config.local.php` file, and put our user custom settings there. Is it okay to be using `config.local.php` instead of `config.local.inc.php` for the custom user file? Or should I rename `config.local.php` to `config.local.inc.php`?

3) Again, I installed postfixadmin by following [these linuxbabe instructions](https://www.linuxbabe.com/mail-server/postfixadmin-ubuntu), and I noticed in his postfixadmin/config.local.php file he has the following:
```
<?php
$CONF['configured'] = true;
$CONF['database_type'] = 'mysqli';
$CONF['database_host'] = 'localhost';
$CONF['database_port'] = '3306';
$CONF['database_user'] = 'postfixadmin';
$CONF['database_password'] = 'postfixadmin_password';
$CONF['database_name'] = 'postfixadmin';
$CONF['encrypt'] = 'dovecot:ARGON2I';
$CONF['dovecotpw'] = "/usr/bin/doveadm pw -r 5";
if(@file_exists('/usr/bin/doveadm')) { // @ to silence openbase_dir stuff; see https://github.com/postfixadmin/postfixadmin/issues/171
    $CONF['dovecotpw'] = "/usr/bin/doveadm pw -r 5"; # debian
}
```
so it seems he has `$CONF['encrypt'] = 'dovecot:ARGON2I';` instead of what you recommend (`$CONF['encrypt'] = 'php_crypt:SHA512::{SHA512-CRYPT}';`).

My question is, why does[ Linuxbabe](linuxbabe.com) use the `$CONF['encrypt'] = 'dovecot:ARGON2I';` instead of your line, and what are the ramifications of my system if I change `$CONF['encrypt'] = 'dovecot:ARGON2I';` to what you suggest `$CONF['encrypt'] = 'php_crypt:SHA512::{SHA512-CRYPT}';`? I don't want to make any changes to postfix/dovecot until I know they wont obstruct and functionality, and that they are safe and secure changes to make.

Please let me know what you think about all of this! Any and all explanations are sincerely appreciated!

Thank you!

**Comment by damnms** [comment]
eMail is a rather complex topic. There are some systems that must work together. You have a database which stores the passwords. To know, if someone is allowed to login, you need to verify that with what is stored in the database. If you store it in the Argon2 format, it will be incompatible if you change it now to SHA512. 
First, i would get rid of all old files/postfixadmin-installs that are on your system. Then continue.

To check that, see your apache/nginx config what is really in use (which folder). Then go into that folder and check whats in your ./conf folder

**Comment by DavidGoodwin** [comment]
@Danrancan - sorry, I'm being useless - I don't know why I typed config.local.inc.php. The file you want is called **config.local.php**.

**Comment by DavidGoodwin** [comment]
I'd suggest you edit the various config files you've found and put e.g `die(__FILE__); ` with them,  if they're being executed, then you should see output in the web browser the file path for whichever has been used ... you should be able to then figure out which one(s) are (or aren't) being used.

At a guess, I suspect you want to do a `dpkg --purge postfixadmin` (this should remove most/all of /etc/postfixadmin, but perhaps not any config.local.php file).

**Comment by DavidGoodwin** [comment]
Hi - There are different ways of "encrypting" (hashing) a password so it's stored in a secure way in the database. You could store all passwords as plain text, but if your server was compromised your users wouldn't thank you.

Which hash format you chose is probably down to you. I'm not a cryptographic expert, but as far as I'm aware any of e.g. SHA-512, ARGON2I, SHA256 or BLF (blowfish) would all be fine. You just need to make sure whichever you chose is supported by the various pieces of the puzzle (dovecot or courier and postfixadmin).



So - this : 

`$CONF['encrypt'] = 'dovecot:ARGON2I';`

Is telling PostfixAdmin to use the `doveadm pw` command to generate the hash (see: "man doveadm-pw"). For example, `doveadm pw -s ARGON2I `

If that user attempted to log into the postfixadmin web interface, postfixadmin would also be using 'doveadm pw' to validate their password.

You can generate a password hash using doveadm yourself from the command line like : 

```sh
$ doveadm pw -s ARGON2I
Enter new password: 
Retype new password: 
{ARGON2I}$argon2i$v=19$m=32768,t=4,p=1$6GJfobDW33U6L2Upf8/3Yw$YpTvHsV8b05kaVlJLe/ruP2ER1UuekaXWogT462Er5w
```

The problem with using the 'dovecot:' variants is that postfixadmin has to call the `doveadm` binary, and then parse the response. There have been changes to dovecot, which result in permissions errors if the webserver user tries to run `doveadm pw ...`. It's also not particularly portable (requiring you have dovecot installed on the webserver) etc. There have been plenty of issues raised here where people have problems with permissions - see e.g. #379 


For some time postfixadmin didn't have 'native' support for e.g. Argon2I, so if you wanted to use that for your password format, you had to. A few years ago I added #491 which tried to move to use the PHP `crypt` function for more hash formats - so the project wasn't as reliant on running the `doveadm` binary.

**Comment by damnms** [comment]
When using any SHA, you absolutely should use -CRYPT, e.g. SHA512-CRYPT. Recommended today is argon2id.
