### ISSUE TITLE
How to get the currently installed version of postfixadmin?

### ISSUE THREAD

**Issue by Danrancan** [postfixadmin/postfixadmin#852]
I installed postfixadmin on Ubuntu from the github release file. However, that was long ago and i dont know what version of postfixadmin I'm running.

How can I get the current version number of postfixadmin? I need to know if I should be upgrading or not. 

Thanks for the help.

**Comment by ozgurkazancci** [comment]
Look for "**$CONF['version']**" in config.inc.php file of your postfixadmin installation. Example;
$CONF['version'] = '3.3.11';

**Comment by Danrancan** [comment]
doesn't `git status` imply that my  installation of postfixadmin is from a git cloned repository? I didn't know that was the reccommended install method. Is it? Should I be doing that as well as git updates?

**Comment by Danrancan** [comment]
> Look for the line **$CONF['version']** in config.inc.php file of your postfixadmin installation. Example; $CONF['version'] = '3.3.11';

Here is why I am getting confused...
In [postfixadmin-3.3.11](https://github.com/postfixadmin/postfixadmin/releases/tag/postfixadmin-3.3.11)`/config.inc.php`, the $CONF['version'] = '`3.3.11`';

This seems correct.

and in [postfixadmin-3.3.13](https://github.com/postfixadmin/postfixadmin/releases/tag/postfixadmin-3.3.13)`/config.inc.php` the $CONF['version'] **ALSO** = '`3.3.11`';

This does not seem correct. Shouldn't it be $CONF['version'] ALSO = '`3.3.13`'; ?

**Comment by DavidGoodwin** [comment]
@Danrancan - I'm not sure there's any specific 'recommended' install way - personally I do a git clone, but doing an install from a github release .zip/whatever is also fine ... as would installing through e.g. debian's postfixadmin package - it just depends who you trust more / whether there's some shiny feature you really need etc etc.
