### ISSUE TITLE
 Undefined array key "quota"

### ISSUE THREAD

**Issue by qcybb** [postfixadmin/postfixadmin#853]
I'm using Postfixadmin 3.3.1.1 and this just appeared in my error logs :

`PHP Warning:  Undefined array key "quota" in /usr/local/www/postfixadmin/model/MailboxHandler.php on line 231`

**Comment by DavidGoodwin** [comment]
possibly fixes with #823  ?

**Comment by DavidGoodwin** [comment]
Hi @qcybb - thanks for the bug report - this should be fixed on the postfixadmin 3.3 branch

**Comment by qcybb** [comment]
Ok, thank you.
