### ISSUE TITLE
Update 3 year old screenshot?

### ISSUE THREAD

**Issue by melroy89** [postfixadmin/postfixadmin#857]
Just an idea, but maybe a good idea to update the screenshots at: 
https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/screenshots/README.md ?

That would also help marketing the product better. I was looking at the screenshots, to better understand how it looks and feels like. So up to date images would help a lot.

Regards,
Melroy van den Berg

**Comment by DavidGoodwin** [comment]
Hi @melroy89 - thanks for the feedback. 

I suspect it'd make sense to record new screenshots and also do some sort of installation video or guide. Finding the time for it is another matter ;)

**Comment by melroy89** [comment]
I understand, I purely ask for refreshed screenshots mainly. Videos are nice, but most likely cost more time.

**Comment by melroy89** [comment]
https://github.com/postfixadmin/postfixadmin/commit/3cb22ed23c9335b1bf4c80cf73241e19542375c7 is really awesome. Great! Love it.
