### ISSUE TITLE
Suggested Dovecot config may have unwanted side-effects

### ISSUE THREAD

**Issue by niallor** [postfixadmin/postfixadmin#86]
In DOCUMENTS/DOVECOT.txt, a configuration is suggested for allowing Postfix to use Dovecot's authentication service, specifically:

    # Uncomment this if you want Postfix to be able to do smtpd auth through dovecot
    # At a minimum Postfix probably needs : smtpd_sasl_type = dovecot 
    # And additionally: smtpd_sasl_path = private/auth
    #service auth {
    #    unix_listener /var/spool/postfix/private/auth {
    #        mode = 0660
    #        user = postfix
    #        group = postfix
    #    }
    #    user = postfix
    #    group = postfix
    #}

IIUC, the last two lines before the outer closing brace have the entire __auth__ service as their scope. This seems

- un-necessary since these values will not be inherited by the __unix_listener__ process defined for use by Postfix  (which has process-specific settings for these properties) and 

- undesirable since these values will be used as defaults for other processes belonging to the __auth__ service, and so may expose these processes to undesired access.

Unless I've misunderstood, it seems appropriate simply to remove those two lines from the suggested configuration.

**Comment by DavidGoodwin** [comment]
Hi - removing the definition doesn't seem to break anything to me, so i'll merge the change. 

Thanks for reporting it!
