### ISSUE TITLE
 Issues with PostfixAdmin Authentication Using Remote Dovecot and ARGON2I Encryption

### ISSUE THREAD

**Issue by sidboy55555** [postfixadmin/postfixadmin#862]
Hi,

I am experiencing issues running PostfixAdmin on a remote server, away from both the Postfix/Dovecot mail server and the MySQL database. The setup consists of using `dovecot:ARGON2I` as the encryption method, with SSH used to remotely execute the `/usr/bin/doveadm pw` command for password management.

With this setup:
- Creating a PostfixAdmin admin account works as expected.
- However, logging into the admin account fails.
- When I log in with a plaintext password and then switch back to `dovecot:ARGON2I`, changing the password from an inbox and logging in via IMAP/SMTP works correctly. So, the issue seems to only affect PostfixAdmin's login after the admin account is created.

To hash the password while Dovecot is on a remote server, I am using the following settings in `config.local.php`:

```php
$CONF['encrypt'] = 'dovecot:ARGON2I';
$CONF['dovecotpw'] = "ssh mail_server '/usr/bin/doveadm pw'";
```

As mentioned earlier, this setup works for creating and logging into mailboxes, and it successfully creates admin accounts in PostfixAdmin. However, it does not work for logging into PostfixAdmin itself.

One issue I’ve noticed is that when running the command `ssh mail_server '/usr/bin/doveadm pw'` manually, even when running this command twice providing the same password, two different password hashes are generated. I suspect this could be the source of the problem, as PostfixAdmin might be unable to validate the login due to the mismatch between the stored hash and the one generated during login attempts.

Additionally, there is very little documentation regarding the use of PostfixAdmin with a remote Dovecot server. The only mention is in [DOCUMENTS/DOVECOT.txt](https://github.com/postfixadmin/postfixadmin/blob/master/DOCUMENTS/DOVECOT.txt), which states: "Please note, PostfixAdmin does not need to run on the same server as the Dovecot server."

Any guidance or suggestions for troubleshooting this issue would be greatly appreciated.

**Comment by gianlucagiacometti** [comment]
I think that you should use

`'/usr/bin/doveadm pw -s ARGON2ID'`

as stated here:

[](https://doc.dovecot.org/2.3/configuration_manual/authentication/password_schemes/) https://doc.dovecot.org/2.3/configuration_manual/authentication/password_schemes/

**Comment by DavidGoodwin** [comment]
@sidboy55555 It wouldn't surprise me that the hashes produced on two consecutive invocations are different - the 'more advanced' (newer) hash formats (e.g argon, bcrypt etc) have a dynamic salt built into them .... so unlike sha1/md5/sha256 etc you can't get the same hash out multiple times.

They should still verify correctly though! 

So for example : 

```
php > echo password_hash('test', PASSWORD_DEFAULT);
$2y$10$.wRXAd03Me.S9KBA3.Vc7uw/dYypnDBNtelwHFvWkqJd35hy2Cql.
php > echo password_hash('test', PASSWORD_DEFAULT);
$2y$10$heT6qIEYUS7038snVtVy/ucOZDovY9sPDWR9QI3ggmDFA6cxCbgRq
php > var_dump(password_verify('test', '$2y$10$heT6qIEYUS7038snVtVy/ucOZDovY9sPDWR9QI3ggmDFA6cxCbgRq'));
bool(true)
php > var_dump(password_verify('test', '$2y$10$.wRXAd03Me.S9KBA3.Vc7uw/dYypnDBNtelwHFvWkqJd35hy2Cql.'));
bool(true)

```

**Comment by sidboy55555** [comment]
> I think that you should use
> 
> `'/usr/bin/doveadm pw -s ARGON2ID'`
> 
> as stated here:
> 
> https://doc.dovecot.org/2.3/configuration_manual/authentication/password_schemes/

The default settings in PostfixAdmin use `/usr/bin/doveadm pw`, as shown in the config.inc.php file. However, since I run Dovecot on a remote server, I use `ssh mail_server '/usr/bin/doveadm pw'`. Nonetheless, I followed your advice and modified my code for testing to` ssh mail_server '/usr/bin/doveadm pw -s ARGON2ID'`, but this did not resolve the issue.


> @sidboy55555 It wouldn't surprise me that the hashes produced on two consecutive invocations are different - the 'more advanced' (newer) hash formats (e.g argon, bcrypt etc) have a dynamic salt built into them .... so unlike sha1/md5/sha256 etc you can't get the same hash out multiple times.
> 
> They should still verify correctly though!
> 
> So for example :
> 
> ```
> php > echo password_hash('test', PASSWORD_DEFAULT);
> $2y$10$.wRXAd03Me.S9KBA3.Vc7uw/dYypnDBNtelwHFvWkqJd35hy2Cql.
> php > echo password_hash('test', PASSWORD_DEFAULT);
> $2y$10$heT6qIEYUS7038snVtVy/ucOZDovY9sPDWR9QI3ggmDFA6cxCbgRq
> php > var_dump(password_verify('test', '$2y$10$heT6qIEYUS7038snVtVy/ucOZDovY9sPDWR9QI3ggmDFA6cxCbgRq'));
> bool(true)
> php > var_dump(password_verify('test', '$2y$10$.wRXAd03Me.S9KBA3.Vc7uw/dYypnDBNtelwHFvWkqJd35hy2Cql.'));
> bool(true)
> ```

That explains why I’m not getting the same hashing results—I didn’t realize they added salting by default. However, it seems like password validation isn’t working with my setup. When I enter the hash with `doveadm pw -t myhash` and then input the password, I get Fatal: reverse password verification check failed: Password mismatch. This happens both when I run the command directly on the mail server and when I run it over SSH from the web server.

Interestingly, when I create a password with doveadm pw directly on the mail server and then attempt to verify it immediately, it still fails. This suggests that the issue may lie with Dovecot rather than PostfixAdmin? Strangely enough, changing the mailbox passwords does work correctly.
```
root@mail:~# doveadm pw -s ARGON2ID
Enter new password:
Retype new password:
{ARGON2ID}$argon2id$v=19$m=65536,t=3,p=1$fyumI23YIbwVmhZGCgI5dg$RdQ5LTF5RIVpvKAGH4f3Rx4xzd/wCHTr6MCFRXvCADE
root@mail:~# doveadm pw -t {ARGON2ID}$argon2id$v=19$m=65536,t=3,p=1$fyumI23YIbwVmhZGCgI5dg$RdQ5LTF5RIVpvKAGH4f3Rx4xzd/wCHTr6MCFRXvCADE
Enter password to verify:
Fatal: reverse password verification check failed: Password mismatch
```
And yes, I entered the password correctly, or rather, copied it in accurately! ;)

**Comment by sidboy55555** [comment]
> I think you're going to have problems with dollar signs / variable expansion from the shell there ...
> 
> ```shell
>  $ echo "{ARGON2ID}$argon2id$v=19$m=65536,t=3,p=1$fyumI23YIbwVmhZGCgI5dg$RdQ5LTF5RIVpvKAGH4f3Rx4xzd/wCHTr6MCFRXvCADE"
> {ARGON2ID}=19=65536,t=3,p=1/wCHTr6MCFRXvCADE
>  $ echo '{ARGON2ID}$argon2id$v=19$m=65536,t=3,p=1$fyumI23YIbwVmhZGCgI5dg$RdQ5LTF5RIVpvKAGH4f3Rx4xzd/wCHTr6MCFRXvCADE'
> {ARGON2ID}$argon2id$v=19$m=65536,t=3,p=1$fyumI23YIbwVmhZGCgI5dg$RdQ5LTF5RIVpvKAGH4f3Rx4xzd/wCHTr6MCFRXvCADE
> ```

I see, when I put the hashed data in quotes, it verifies as expected. However, for some reason, PostfixAdmin still doesn’t validate it correctly. I haven’t found a debug log in PostfixAdmin, like Dovecot’s, that shows password feedback, which would be really useful at this point. Do you have any suggestions for debugging this?

I’d also be open to using a different encryption method for PostfixAdmin admin/users, like `php_crypt`, as PostfixAdmin is running on the same server which runs php. However, I assume this would require modifying code within PostfixAdmin. If no general solution for this problem exists, I may explore this approach, as it seems easier to implement.

**Comment by DavidGoodwin** [comment]
I think, there's one level of shell quoting when postfixadmin opens proc_open and executes the ssh command, and then another when you run something on the other side.

You might be able to run `escapeshellarg` twice on the password command, that there's a chance that would work. 

I think you'll have an easier life however if you try some of these in your config file : 

 * `$CONF['encrypt'] = 'php_crypt:SHA512::{SHA512-CRYPT}';` or
 * `$CONF['encrypt'] = 'php_crypt:BLOWFISH';` or
 * `$CONF['encrypt'] = 'php_crypt:sha512.b64';`

**Comment by cboltz** [comment]
For debugging, please create the following script as `/tmp/echoperms` on your mail server:

```
#!/bin/bash

{
echo "self: $0"
echo "1: $1"
echo "2: $2"
echo "3: $3"
echo "4: $4"
echo "5: $5"
echo "6: $6"
echo "7: $7"
echo "8: $8"
echo "9: $9"

echo "== begin stdin =="
cat /dev/stdin
echo "== end stdin =="
echo
} > /tmp/echoparms.log
```

chmod +x it, and then (temporarily) set `$CONF['dovecotpw'] = "ssh mail_server '/tmp/echoperms pw'";`

Then try to login, using "test123" as password. This will of course fail, but it will create `/tmp/echoparms.log`, which shows the parameters used and the values submitted on stdin. Please show the content of echoparms.log. (If you redact the password hash, please only replace characters in the `[a-zA-Z0-9]` range, and leave special characters intact.)

**Comment by sidboy55555** [comment]
> I think, there's one level of shell quoting when postfixadmin opens proc_open and executes the ssh command, and then another when you run something on the other side.
> 
> You might be able to run `escapeshellarg` twice on the password command, that there's a chance that would work.
> 
> I think you'll have an easier life however if you try some of these in your config file :
> 
> * `$CONF['encrypt'] = 'php_crypt:SHA512::{SHA512-CRYPT}';` or
> * `$CONF['encrypt'] = 'php_crypt:BLOWFISH';` or
> * `$CONF['encrypt'] = 'php_crypt:sha512.b64';`

I think you're right, I’ve switched my setup to one of these. They work well with their Dovecot counterparts, which is great! :)


> For debugging, please create the following script as `/tmp/echoperms` on your mail server:
> 
> ```
> #!/bin/bash
> 
> {
> echo "self: $0"
> echo "1: $1"
> echo "2: $2"
> echo "3: $3"
> echo "4: $4"
> echo "5: $5"
> echo "6: $6"
> echo "7: $7"
> echo "8: $8"
> echo "9: $9"
> 
> echo "== begin stdin =="
> cat /dev/stdin
> echo "== end stdin =="
> echo
> } > /tmp/echoparms.log
> ```
> 
> chmod +x it, and then (temporarily) set `$CONF['dovecotpw'] = "ssh mail_server '/tmp/echoperms pw'";`
> 
> Then try to login, using "test123" as password. This will of course fail, but it will create `/tmp/echoparms.log`, which shows the parameters used and the values submitted on stdin. Please show the content of echoparms.log. (If you redact the password hash, please only replace characters in the `[a-zA-Z0-9]` range, and leave special characters intact.)

Since I've switched to another hash, I won't be able to debug this further. Hopefully, someone else experiencing this issue can share their findings here! I'm not sure whether to close this issue, as it hasn't been resolved, just changed to another hash.

**Comment by emcomit** [comment]
Hello,
I followed this interesting discussion.
I have a symilar @sidboy55555 configuration, with webserver (postfixadmin) on another server i the same private network of dovecot server.
In my case, ssh authentication is via keys and I have a lot of issues trying to read the ssh private key by apache server.
Thereis another way to connect postfixadmin to an dovecot external server?
Any suggestions would be greatly appreciated.

**Comment by DavidGoodwin** [comment]
> Hello, I followed this interesting discussion. I have a symilar @sidboy55555 configuration, with webserver (postfixadmin) on another server i the same private network of dovecot server. In my case, ssh authentication is via keys and I have a lot of issues trying to read the ssh private key by apache server. Thereis another way to connect postfixadmin to an dovecot external server? Any suggestions would be greatly appreciated.

I'd suggest either ...

 1. Use a different password hash format (see above - https://github.com/postfixadmin/postfixadmin/issues/862#issuecomment-2466630618 )
 2. Install the dovecot cli on the webserver - dovecot doesn't need to run as a service on the webserver, postfixadmin just needs to be able to call the 'doveadm pw' stuff

**Comment by emcomit** [comment]
Hi @DavidGoodwin ,
your configuration 1. work fine for me...and now postfixadmin is connected to the mail server. I'm also able to join in the postfixadmin web interface after user creation (I verified that it is correctly created in the mysql db).
But If I try to send an test email, I see this error now:

`[Mon Nov 18 21:54:24.867619 2024] [php:notice] [pid 2359005] [client <ip-address>:43321] fsockopen failed - errno: 111 - errstr: Connection refused, referer: https://postfixadmin.emcom.cloud/sendmail.php`

...in the error log and

<ip-address> - - [18/Nov/2024:21:58:12 +0000] "POST /sendmail.php HTTP/1.1" 200 2977 "https://postfixadmin.emcom.cloud/sendmail.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0"
<ip-address> - - [18/Nov/2024:21:58:12 +0000] "GET /images/favicon.ico HTTP/1.1" 200 15432 "https://postfixadmin.emcom.cloud/sendmail.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0"

in the request logs.
Where is the problem now? I'm able to send mails from the mail server using the command:

`echo "test email" | sendmail f.andrisani@emcom.it` for example.

**Comment by DavidGoodwin** [comment]
Hi @emcomit - I suspect there's a difference between sending through a socket (which is probably what the sendmail command is doing) vs trying to open a tcp connection to localhost:25 (which is what the code is trying to do)

Check your configuration settings for 'smtp_server' and 'smtp_port' and look at the output from 'netstat --tcp -lpn' and see if postfix is listening on localhost / 127.0.0.1 port 25 or not?

**Comment by emcomit** [comment]
> Hi @emcomit - I suspect there's a difference between sending through a socket (which is probably what the sendmail command is doing) vs trying to open a tcp connection to localhost:25 (which is what the code is trying to do)
> 
> Check your configuration settings for 'smtp_server' and 'smtp_port' and look at the output from 'netstat --tcp -lpn' and see if postfix is listening on localhost / 127.0.0.1 port 25 or not?
 Hi @DavidGoodwin,
I checked. postfix is listening on the entire network. Below the command output:

```
root@mail:~# netstat --tcp -lpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:993             0.0.0.0:*               LISTEN      113179/dovecot
tcp        0      0 0.0.0.0:995             0.0.0.0:*               LISTEN      113179/dovecot
tcp        0      0 0.0.0.0:143             0.0.0.0:*               LISTEN      113179/dovecot
tcp        0      0 0.0.0.0:110             0.0.0.0:*               LISTEN      113179/dovecot
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      113500/master
tcp        0      0 0.0.0.0:465             0.0.0.0:*               LISTEN      113500/master
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      588/systemd-resolve
tcp        0      0 127.0.0.54:53           0.0.0.0:*               LISTEN      588/systemd-resolve
tcp6       0      0 :::993                  :::*                    LISTEN      113179/dovecot
tcp6       0      0 :::995                  :::*                    LISTEN      113179/dovecot
tcp6       0      0 :::143                  :::*                    LISTEN      113179/dovecot
tcp6       0      0 :::110                  :::*                    LISTEN      113179/dovecot
tcp6       0      0 :::22                   :::*                    LISTEN      1/init
```
About the configuration setting, you mean the postfixadmin conf?

I tried also to open a remote connection on the mail server on port25 and it work. Could be a postfixadmin misconfiguration?

**Comment by DavidGoodwin** [comment]
Er.... well the error message you had was that PHP couldn't open a tcp connection to whatever you had configured.

```
[Mon Nov 18 21:54:24.867619 2024] [php:notice] [pid 2359005] [client <ip-address>:43321] fsockopen failed - errno: 111 - errstr: Connection refused, referer: https://postfixadmin.emcom.cloud/sendmail.php
```

Do you have SELinux enabled? 

If you become the webserver user, can you telnet to 127.0.0.1 port 25  or whatever you had configured?

**Comment by emcomit** [comment]
> Er.... well the error message you had was that PHP couldn't open a tcp connection to whatever you had configured.
> 
> ```
> [Mon Nov 18 21:54:24.867619 2024] [php:notice] [pid 2359005] [client <ip-address>:43321] fsockopen failed - errno: 111 - errstr: Connection refused, referer: https://postfixadmin.emcom.cloud/sendmail.php
> ```
> 
> Do you have SELinux enabled?
> 
> If you become the webserver user, can you telnet to 127.0.0.1 port 25 or whatever you had configured?

I solved it changinf the config.inc.php as well. The problem now is that I have an error postfix side (see my previous message).
I tried to chage the conf file main.cf and i verified the sql files. All seem be ok, but every time that i try to send test email from postfix the above error occur.

**Comment by DavidGoodwin** [comment]
postfix wise - telling it to allow relaying from your local host would fix it? 

e.g. `mynetworks = 127.0.0.0/8, .... `
