### ISSUE TITLE
pagebrowser broken with sqlite

### ISSUE THREAD

**Issue by cboltz** [postfixadmin/postfixadmin#87]
The SQL query to create the pagebrowser ("a-h | j-o | p-z") errors out with a syntax error when using sqlite.

Originally reported at https://sourceforge.net/p/postfixadmin/discussion/676076/thread/ac0ae9ce/ - check there for the details.

Workaround: increase `$CONF['page_size`]` to avoid the need for a page browser.

**Comment by pedromorgan** [comment]
Is this a bug ? 
or is is some docs required to increaze page size to 500+ . hey were 2018++ almost

**Comment by DavidGoodwin** [comment]
it's a bug - the SQL PostfixAdmin generates doesn't work with SQLite properly.
