### ISSUE TITLE
Undefined array key "quota" in MailboxHandler.php

### ISSUE THREAD

**Issue by ozgurkazancci** [postfixadmin/postfixadmin#870]
Hello, I'm getting the following PHP warning;

`FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "quota" in /var/www/postfixadmin/model/MailboxHandler.php on line 231" while reading response header from upstream, request: "GET /postadmin/editactive.php?table=mailbox&id=myuser%40mysite.com&active=0&token=404ee3b82ab8f38f88de7b94524e009c HTTP/2.0", upstream: "fastcgi://unix:/var/www/run/php-fpm.sock:"`

PHP: 8.1.30
Postfixadmin version: 3.3.13

FYI,
Regards.

**Comment by DavidGoodwin** [comment]
You're probably missing 49c254a4e607a86b46c10ea186fd4b3a04bed2d7 - which is in the yet-to-be-released 3.3.14 version

**Comment by DavidGoodwin** [comment]
(3.3.14 should be released ... )
