### ISSUE TITLE
PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]

### ISSUE THREAD

**Issue by v0vas** [postfixadmin/postfixadmin#871]
Hi! Looks similar error with this [issue](https://github.com/postfixadmin/postfixadmin/issues/553). Try to open postfixadmin/public/login.php page

I have Postfoxadmin 3.4 version and PHP 8.4.0RC4

```
# pkg info | grep pdo
php84-pdo-8.4.0.r4             The pdo shared extension for php
php84-pdo_mysql-8.4.0.r4       The pdo_mysql shared extension for php
```
Error log:

```
2024/11/18 11:27:14 [error] 16966#100878: *39958 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /usr/local/www/postfixadmin/functions.inc.php:1740
Stack trace:
#0 /usr/local/www/postfixadmin/functions.inc.php(1740): PDO->__construct()
#1 /usr/local/www/postfixadmin/functions.inc.php(1914): db_connect()
#2 /usr/local/www/postfixadmin/functions.inc.php(1875): db_query()
#3 /usr/local/www/postfixadmin/functions.inc.php(2222): db_query_one()
#4 /usr/local/www/postfixadmin/public/login.php(40): check_db_version()
#5 {main}
```
How to fix it?

**Comment by DavidGoodwin** [comment]
Check your database configuration - e.g edit functions.inc.php and add something like : 

See : 

https://github.com/postfixadmin/postfixadmin/blob/24b3b12581ee83ba200ccf1e8c148712afd54fed/functions.inc.php#L1795

and add e.g. ``` var_dump($dsn, $options); die('stop here'); ```

I assume you have a typo in your hostname/connection details and that's causing the problem.

**Comment by v0vas** [comment]
Have this. Try to change localhost to 127.0.0.1 and same output:
`string(51) "mysql:mysql:host=127.0.0.1;dbname=exim;charset=UTF8" array(2) { [3]=> int(2) [2]=> int(5) } stop here`

**Comment by DavidGoodwin** [comment]
You've got an extra 'mysql:' in the DSN. 

https://github.com/postfixadmin/postfixadmin/blob/24b3b12581ee83ba200ccf1e8c148712afd54fed/functions.inc.php#L1676

**Comment by v0vas** [comment]
> You've got an extra 'mysql:' in the DSN.
Remove it?

**Comment by DavidGoodwin** [comment]
Yes - this was an error sometime ago - just updating your postfixadmin installation might fix it? Presumably the code in db_connection_string() that you have doesn't match what's visible from the link above.

**Comment by v0vas** [comment]
Thanks! It's works now
