### ISSUE TITLE
Using unregistered function "htmlentities" in a template is deprecated 

### ISSUE THREAD

**Issue by qcybb** [postfixadmin/postfixadmin#872]
After updating to the latest version, I received this notice in my error logs this morning.

`PHP Deprecated:  Using unregistered function "htmlentities" in a template is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier. in /www/postfixadmin/lib/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 663`

**Comment by DavidGoodwin** [comment]
Thanks! I suspect there might need to be a 3.3.15 soon, else there will be a continual stream of issues raised for this.

**Comment by DavidGoodwin** [comment]
release https://github.com/postfixadmin/postfixadmin/releases/tag/postfixadmin-3.3.15 should resolve this.

**Comment by qcybb** [comment]
Thank you, however I won't be able to test this update until tomorrow. I'll report back if I see anything.

**Comment by qcybb** [comment]
It looks like the update fixed it, thank you.
