### ISSUE TITLE
ERROR: the templates_c directory doesn't exist or isn't writeable for the webserver

### ISSUE THREAD

**Issue by Kasherpete** [postfixadmin/postfixadmin#873]
Hey guys I'm getting the error `ERROR: the templates_c directory doesn't exist or isn't writeable for the webserver`. I did make sure to create the `templates_c` folder, both in the `postfixadmin` folder as well as the `public` directory inside of `postfixadmin` just to make sure. I ran `chmod 777` on everything too, but nothing helps. Any advice? Is more info needed?

I'm running this on Apache2 if that helps. I had to disable the Wordpress site on the main domain in order to get this to show up (separate issue related to Wordpress and Apache) since it kept redirecting the `mail` subdomain to the main domain.

**Comment by DavidGoodwin** [comment]
Hi @Kasherpete

 - you don't need/want public/templates_c. 
 - the permissions shouldn't need changing to 777. Doing a 'chgrp www-data' (or whatever the webserver uses) on templates_c should suffice.

It's probably the case you have multiple postfixadmin installations (e.g one is a debian/rpm package, and the other is from a .tar.gz) and there is confusion over which one is in use.

You could put a `die(__FILE__); ` line into PHP source code (whether that's config.inc.php or public/index.php or somewhere else) and that may help you rule out specific installation directories.

**Comment by Kasherpete** [comment]
> It's probably the case you have multiple postfixadmin installations (e.g one is a debian/rpm package, and the other is from a .tar.gz) and there is confusion over which one is in use.

Okay, there did seem to be multiple installations. One at `/var/www/html/postfixadmin` and another at `/apps/postfixadmin`.

> You could put a `die(__FILE__); ` line into PHP source code (whether that's config.inc.php or public/index.php or somewhere else) and that may help you rule out specific installation directories.

I did this to the main installation at `/var/www/html/postfixadmin` and login.php in the browser just output the path of the installation, nothing more. I renamed the second installation at `/apps/postfixadmin` and made sure there wasn't any references to it, deleted the `die(__FILE__)` line from the config, and proceeded with the setup.php in the browser. It said it finished successfully, but I go back to login.php and it still has the templates_c error, even after I updated the folder permissions.

**Comment by Kasherpete** [comment]
Alright I ran `chmod 777` on the folder one last time and it seems to have worked. Looks like it was the permissions, thanks for your help! I'll mess around with chmod a bit so I'm not granting full access for everything on the server. Thanks again!
