### ISSUE TITLE
import_users_from_csv.py: not python3 compatible

### ISSUE THREAD

**Issue by delgh1** [postfixadmin/postfixadmin#875]
Hi,

So the `import_users_from_csv.py` script under `ADDITIONS` fails to run on python3.12:

```
  File "./postfixadmin/ADDITIONS/import_users_from_csv.py", line 32
    except ImportError ,e:
           ^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
```

Do you have a plan to fix the script?

**Comment by DavidGoodwin** [comment]
hm, well, I've had a go, but I've not actually tested it properly yet - so dffc938bf7ad3fc151fdd82c10e4b8f9b5290a12 could be a pile of rubbish
