### ISSUE TITLE
[Question] How to upgrade manully installed PostfixAdmin

### ISSUE THREAD

**Issue by CJYKK** [postfixadmin/postfixadmin#881]
I followed [INSTALL.txt](https://github.com/postfixadmin/postfixadmin/blob/master/INSTALL.TXT), used `master` branch and installed commit [`704bad6`](https://github.com/postfixadmin/postfixadmin/commit/704bad6d63e8e6617920658de002c46ce3848c9c) of PostfixAdmin on my server because there hasn't been a release for a long time. But now there is. How can I upgrade to the latest release or catch up with `master`?

Server infomation:
- Debian trixie/testing
- PHP 8.2.27
- Nginx 1.26.2
- MariaDB 11.4.3

PostfixAdmin infomation:
- Version 3.4-dev (commit [`704bad6`](https://github.com/postfixadmin/postfixadmin/commit/704bad6d63e8e6617920658de002c46ce3848c9c), `master` branch)
- Installation dir /var/www/postfixadmin/

Nginx reverse proxy configuration file:
<details><summary>Details</summary>
<p>

```
server {
    server_name <my server address>;

    root /var/www/postfixadmin/public/;
    index index.php index.html;

    access_log /var/log/nginx/postfixadmin_access.log;
    error_log /var/log/nginx/postfixadmin_error.log;

    location / {
        try_files $uri $uri/ /index.php;
    }

    location ~ ^/(.+\.php)$ {
        try_files $uri =404;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include /etc/nginx/fastcgi_params;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/<my server address>/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/<my server address>/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    ssl_trusted_certificate /etc/letsencrypt/live/<my server address>/chain.pem; # managed by Certbot
    ssl_stapling on; # managed by Certbot
    ssl_stapling_verify on; # managed by Certbot
}

server {
    if ($host = <my server address>) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name <my server address>;
    return 404; # managed by Certbot
}
```

</p>
</details>

**Comment by DavidGoodwin** [comment]
Hi -

 1. Run `install.sh` 
 2. Point your browser to setup.php and i think it'll apply any outstanding database updates without you needing to enter the setup password.


Beyond that, there isn't anything you'd need to - the CRUD like functionality around mailboxes/aliases will just work.

**Comment by CJYKK** [comment]
> Hi -
> 
> 1. Run `install.sh`
> 2. Point your browser to setup.php and i think it'll apply any outstanding database updates without you needing to enter the setup password.
> 
> Beyond that, there isn't anything you'd need to - the CRUD like functionality around mailboxes/aliases will just work.

So... I need to do `git checkout master` in installation dir or any action else?

**Comment by DavidGoodwin** [comment]
Yeah, I guess?

**Comment by CJYKK** [comment]
> Yeah, I guess?

I updated and everything is working fine, thanks for patient response!
P.S. I can't use the `git checkout master` command because I forgot to use the `git pull` command. 💀

**Comment by DavidGoodwin** [comment]
p.p.s. .... I was taught to not use 'git pull' and instead use 'git fetch' and then 'git rebase origin/whatever' 

... see also https://stackoverflow.com/questions/292357/what-is-the-difference-between-git-pull-and-git-fetch

(there's nothing really wrong with using pull, i think my behaviour is hard coded from years of doing it that way when git probably had less friendly behaviour)
