### ISSUE TITLE
Support MySQL over SSL

### ISSUE THREAD

**Issue by leeclemens** [postfixadmin/postfixadmin#91]
postfixadmin should allow the ability to configure backend MySQL connections over an SSL connection, using the standard functionality provided by mysql client and php

**Comment by DavidGoodwin** [comment]
I think this would be best supported by supporting PDO.....

**Comment by leeclemens** [comment]
The PR is based on the pre-existing use of mysqli and merely extends it to accept SSL related flags.
Are you suggesting all of the MySQL functionality be replaced in favor of PDO? (I do not claim to be a PHP expert, so forgive me if I am misunderstanding something.)

**Comment by DavidGoodwin** [comment]
Oh - sorry - I was being blind - I didn't spot the PR for some reason.

I've never used MySQL with SSL, so I can't say much about your code ..... it /looks/ alright !

**Comment by leeclemens** [comment]
Ahh, no worries!  I emailed a patch about a year ago similar to this PR and had been using it prior to writing this PR. Using this specific code now without issue for a few days.

I suppose if this works as-is with non-SSL MySQL connections and fails when `database_use_ssl` is set to `true` without SSL configured with MySQL it could be considered fairly reliable?

It really just passes arguments to `mysqli_real_connect`, and I admit I have not tested all combinations - but those are handled by PHP and MySQL once passed in.

**Comment by DavidGoodwin** [comment]
Hi - I'll merge this - but really postfixadmin should move to use PDO - and things like SSL flags etc would then be handled through whatever the PDO connection string / options are.
