### ISSUE TITLE
setup.php doesn't update the database

### ISSUE THREAD

**Issue by quicktrick** [postfixadmin/postfixadmin#93]
Recently I've been using the git version of Postfix Admin from Sep 13.  Today I cloned the current git version. The `setup.php` ran Ok (I tried it a few times).  But when I tried to add a new mailbox I got the following error (from Nginx log):

> 2017/11/16 16:13:23 [error] 4125#4125: *446 FastCGI sent in stderr: "PHP message: Invalid query: Unknown column 'token' in 'field list' PHP message: caused by query: INSERT INTO mailbox (username,local_part,domain,maildir,password,name,quota,active,phone,email_other,token,token_validity,created,modified) VALUES ('test@mydomain.tld','test','mydomain.tld','mydomain.tld/test/','{BLF-CRYPT}$2a$12$lxz.....','test account','2097152000','1','','','','',now(),now())" while reading
response header from upstream, client: xxx.xxx.xxx.xxx, server: mail.mydomain.tld, request: "POST /postfixadmin/edit.php?table=mailbox&domain=mydomain.tld HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "mail.mydomain.tld", referrer: "https://mail.mydomain.tld/postfixadmin/edit.php?table=mailbox&domain=mydomain.tld"

My current `mailbox` table contains the following fields:

    SELECT `COLUMN_NAME`
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = 'mailserver' AND TABLE_NAME ='mailbox'
    
    COLUMN_NAME	
    username	
    password	
    name	
    maildir	
    quota	
    local_part	
    domain	
    created	
    modified	
    active	
    phone	
    email_other	

It obviously wasn't updated by `setup.php`.  Meanwhile, I reverted to my previous Postfix Admin version.

**Comment by DavidGoodwin** [comment]
I think I saw that briefly on my development version - I worked around it by running the running the last upgrade function in upgrade.php manually.

**Comment by cboltz** [comment]
That sounds like the function number in setup.php is too low.

quicktrick and David, can you please run the following SQL query and show the result?

    select * from config;

**Comment by DavidGoodwin** [comment]
I can't now. 

As I said - I updated config to have n-1 as it's version number and re-ran upgrade.php to fix it.

I assumed it was just a result of me trying various branches and sometimes breaking things ....

**Comment by quicktrick** [comment]
Hi!  My previous version was 1837.  I changed it to 1836 and re-ran upgrade.php from version 1838.  After that I got the following error when trying to add a mailbox:

> 2017/11/20 14:12:46 [error] 23954#23954: *3207 FastCGI sent in stderr: "PHP message: Invalid query: Incorrect datetime value: '' for column 'token_validity' at row 1 PHP message: caused by query: INSERT INTO mailbox (username,local_part,domain,maildir,password,name,quota,active,phone,email_other,token,token_validity,created,modified) VALUES ('test@mydomain.tld','test','mydomain.tld','mydomain.tld/test/','$1$7f1a71fb$rhVlZYR1usF2PZg3mSJNj/','test','2097152000','1','','','','',now(),now())" while reading response header from upstream, client: 192.168.1.1, server: mydomain.tld, request: "POST /postfixadmin/edit.php?table=mailbox&domain=mydomain.tld HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "mydomain.tld", referrer: "https://mydomain.tld/postfixadmin/edit.php?table=mailbox&domain=mydomain.tld"

I can see the empty value going to be inserted in the `token_validity` field, that gives the error.

**Comment by DavidGoodwin** [comment]
i think that's the issue found in https://github.com/postfixadmin/postfixadmin/pull/85

**Comment by quicktrick** [comment]
David, please, have a look at the last paragraph I added to my previous post, starting with "Edit: ...".

**Comment by DavidGoodwin** [comment]
I merged a patch from #85 again; can you confirm if this fixes the problem for you?

**Comment by quicktrick** [comment]
I'm so sorry David, but just yesterday I reverted to Release 3.1 because of all these issues and configured the server properly for production.  I don't have any test server at hands right now.  Thanks anyway for your kind attention!

By the way, is it possible to add a feature to display used domain quotas in the domain list as mentioned in #96? I think the best format is "used/max_summary/limit".
