### ISSUE TITLE
postfixadmin.github.io

### ISSUE THREAD

**Issue by pedromorgan** [postfixadmin/postfixadmin#95]
So can I help, cos here i am again having to read docs etc..

New install, so can u create repos =  postfixadmin.github.io,
and move to jekyll, so documentation is easier, and the new www..

Am familiar with this stuff...

ie migrate this http://postfixadmin.sourceforge.net/

Mainly cos every push recompiles "the site" ;-))))

**Comment by pedromorgan** [comment]
Snag is "things are" everywhere
- http://postfixadmin.sourceforge.net/
- https://github.com/postfixadmin/postfixadmin/blob/master/INSTALL.TXT
- https://sourceforge.net/p/postfixadmin/wiki/Home/
- https://github.com/postfixadmin/postfixadmin/tree/master/DOCUMENTS
- https://github.com/postfixadmin/postfixadmin/tree/master/VIRTUAL_VACATION

So I understand the challenge

**Comment by pedromorgan** [comment]
Realise I kinda been here before..

https://github.com/pedromorgan/postfixadmin.github.io

**Comment by DavidGoodwin** [comment]
How do we view what is in your repo above? I'm not seeing anything with Postfixadmin stuff in it...

**Comment by DavidGoodwin** [comment]
there is http://postfixadmin.github.io/postfixadmin/ ...

**Comment by pedromorgan** [comment]
Ok so am moving forward with the postfix.admin site..

I go thge site almost working,,
and using a tried and tested and using faorula.. (formika) lol
- http://ts2.github.io/
- http://revel.github.io/

So the mode I want @DavidGoodwin to do, is to 
- create the postfixadmin.github.ipo repos..
- namrge this http://pedromorgan.github.io/postfixadmin.github.io/

If it gets official,
then i have no problemwith seting up the whole capres,
and a new stuff, alll in mardown etc..

**Comment by pedromorgan** [comment]
updated to give more of an idea

http://pedromorgan.github.io/postfixadmin.github.io/

**Comment by DavidGoodwin** [comment]
There's https://github.com/postfixadmin/postfixadmin.github.io - for the 'record' @pedromorgan should have commit access.

**Comment by pedromorgan** [comment]
am still hacking away.. ready soon... (time as usual)
