### ISSUE TITLE
How can I display domain used space in WebUI ?

### ISSUE THREAD

**Issue by quicktrick** [postfixadmin/postfixadmin#96]
I've configured Dovecot to use two-level quotas: `user` and `domain`. Both are stored in `quota2` table.  And I can see both of them in Roundcube (limit/used for the user and the domain).  In the Postfix Admin WebUI I can see the user quota (used/limit).  But for the domain quota It shows the summary of all the mailbox quotas, but it doesn't show the domain used space.  How can I add the `used` column for the domain quota on the Domain List page?

**Comment by xm74** [comment]
Here are more details about 2-levels quotas with Dovecot (sorry, only in russian but configs and output are clear) - configuration and found issue with Postfixadmin when deleting mailbox.
https://kostikov.co/dvuhurovnevoe-kvotirovanie-v-dovecot-2
https://kostikov.co/problemy-uchyota-domennoj-kvoty-v-dovecot-2

**Comment by lelutin** [comment]
The domain quota usage information is visible in the domain list either as a super-admin or a normal admin, at least in 3.1. It's shown as a ratio in the bar that gets drawn under the Domain Quota column in the form "allocated / max". The bar also currently gets colored according to current percentage used as an added visual queue.

It would be interesting to also see this information in the "virtual" list to make it easier to have this information in mind when managing mailboxes.

**Comment by lelutin** [comment]
@quicktrick just to make sure that all details are covered, the Domain Quota column is not shown until you set "$CONF['quota'] = 'YES'" in config.local.php to enable storage quotas.

**Comment by quicktrick** [comment]
@lelutin , please, read carefully what I ask about.  I want to see the domain used space, not only the domain quota as the summary of all the mailbox' quotas.
