### ISSUE TITLE
Issues with mysql 8

### ISSUE THREAD

**Issue by er1cs** [postfixadmin/postfixadmin#97]
Errors while setup on FreeBSD 11.1 Apache/2.4.29 (FreeBSD) PHP/7.1.11 Mysql 8 

Something like [https://sourceforge.net/p/postfixadmin/discussion/676076/thread/616c1d25/](url)

I found that Mysql 8 don't like table names without `` in requests. So i make changes in function table_by_key in functions.inc.php and in upgrade.php . Now it works. Changed files attached. 
[for_postfixadmin_3_1_mysql8.zip](https://github.com/postfixadmin/postfixadmin/files/1502679/for_postfixadmin_3_1_mysql8.zip)

**Comment by DavidGoodwin** [comment]
Is the only change required : 

```    return $CONF['database_prefix']."`".$table."`"; ```  in table_by_key(...) ?

**Comment by er1cs** [comment]
For table_by_key(...) i think yes. For upgrade.php - several changes with `` removing, and around line 940 changes in CREATE TABLE request. I make diff and upgrade.php without my #.
[diff.zip](https://github.com/postfixadmin/postfixadmin/files/1502932/diff.zip)
[upgrade.zip](https://github.com/postfixadmin/postfixadmin/files/1502934/upgrade.zip)

**Comment by DavidGoodwin** [comment]
can you please change the above into a pull request?
