### ISSUE TITLE
Setup fails with php syntax error

### ISSUE THREAD

**Issue by ebarrosa** [postfixadmin/postfixadmin#99]
Hello,

Tried to upgrade PF Admin from 2.93 to 3.1 but setup.php fails with error:

PHP Parse error:  syntax error, unexpected '[' in /usr/share/postfixadmin-3.1/setup.php on line 61

Envronment:
Postifixadmin 3.1
Using PHP 5.3.3
Mysql 5.1.73

Any suggestion?

Eduardo

**Comment by ebarrosa** [comment]
Typo made.

Envronment:
Postifixadmin 2.93
Using PHP 5.3.3
Mysql 5.1.73

**Comment by DavidGoodwin** [comment]
I suspect there's short array syntax there; try looking at line 61 and replace ```$errormsg = []``` with ```$errormsg = array(); ```

See also changeset:cf72bf1dcc9c3473fdc58e7dec8e4ec3648bd2fa

But you should really upgrade that version of PHP; it's pretty old.
